### ISSUE TITLE
gRPC Client - Setting up the Number of request to be queued

### ISSUE THREAD

**Issue by banandh** [grpc/grpc-java#10164]
We are doing some performance testing and below are the Observations with the test results and Need feedback on this

1.Even if the upstream gRPC service is up and running, client gets "Unreachable error" at times - what is the exact reason. We have configured retries to resolve the issue. But would like to understand what is happening behind it.

2. We configured , Semaphore to throttle request in client side even with Semaphore count of 10 , still seeing retries so would like to know the client side connection queueing feature where we can limit the connections on the channel instead of using a separate variables

**Comment by ejona86** [comment]
You would need to provide the full error message, including any 'caused by' exceptions, for us to tell you what is happening. We need to see the error to have any hope of telling you the cause.

The channel manages connections. Your semaphore is unlikely to change the number of connections used. It sounds like you want to limit the number of concurrent RPCs because it causes your server load problems. I don't think we have any intention of handling that on client-side as it is best done closer to the application, like you are already doing, because the policy can vary heavily and the application frequency needs to be aware of it to limit memory usage.

You may find community interceptors, like https://github.com/Netflix/concurrency-limits , to be useful. `GrpcClientLimiterBuilder` may be what you need.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
