### ISSUE TITLE
class file for io.grpc.InternalNotifyOnServerBuild not found

### ISSUE THREAD

**Issue by crazyjat** [grpc/grpc-java#10324]
I have a block of code:

```
Server server = ServerBuilder.forPort(12000)
    .addService(ProtoReflectionService.newInstance())
```
That produces the following error with my gradle build:

```
error: cannot access InternalNotifyOnServerBuild
                .addService(ProtoReflectionService.newInstance())
                                                  ^
  class file for io.grpc.InternalNotifyOnServerBuild not found
```

I am using io.grpc version 1.26.0

I have found no information to help me understand this error or where this class exists in the `io.grpc` package. Please help.

**Comment by sanjaypujare** [comment]
> I am using io.grpc version 1.26.0

1.26 is at least 3 years old. Can you move to a newer version?

**Comment by ejona86** [comment]
Why are you using such an old version of grpc for new code? Filing issues for such old versions is pretty useless, as the answer is essentially always "upgrade" because you are ignoring years of fixes.

You are using grpc-api version >= 1.30.0 with grpc-services < 1.30.0. Upgrade grpc-services to 1.30.0 or later. If you are using Maven, consider using grpc-bom [as in our example](https://github.com/grpc/grpc-java/blob/v1.56.0/examples/pom.xml).

**Comment by ejona86** [comment]
Seems like this should resolved. If not, comment, and it can be reopened.
