### ISSUE TITLE
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 1.999884080s. [closed=[], open=[[buffered_nanos=2001703685, waiting_for_connection]]] at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)

### ISSUE THREAD

**Issue by zzq0341** [grpc/grpc-java#10365]
I encountered some problems with grpc-java, please help, thank you very much.
My version number is 1.45.4.
My code is as follows:
```
originChannel is an instance variable
ManagedChannel originChannel=NettyChannelBuilder.forAddress(XXXX, XXXX)
               .idleTimeout(2, TimeUnit.MINUTES)
               .usePlaintext()
               .build();
```
grpc remote call code is
```
XXService. newBlockingStub(originChannel)
               .withInterceptors(new ClientInterceptor[]{MetadataUtils.newAttachHeadersInterceptor(meta)})
               .withDeadlineAfter(2, TimeUnit. SECONDS)
               .xx(Empty.newBuilder().build());
```
I get some error messages and after 20 seconds it's fine again
```
o.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 1.999884080s. [closed=[], open=[[buffered_nanos=2001703685, waiting_for_connection]]]
```

**Comment by larry-safran** [comment]
The first time you use the channel, gRPC will connect to the server which may take some time.  Since you are giving a deadline of 2 seconds, if the combination of connecting, transporting over the network both ways and server side processing exceeds 2 seconds you will get a timeout as you describe.

Since you specified an idle timeout of 2 minutes, at the 20 second point the connection would still be active so the next invocation wouldn't have the overhead of setting up the connection.  Increasing the timeout on the method call to 10 seconds will probably eliminate the problem.

**Comment by zzq0341** [comment]
> 第一次使用该通道时，gRPC 将连接到服务器，这可能需要一些时间。由于您给出的截止时间为 2 秒，因此如果连接、网络双向传输和服务器端处理的组合超过 2 秒，您将遇到您所描述的超时。
> 
> 由于您指定了 2 分钟的空闲超时，因此在 20 秒时连接仍将处于活动状态，因此下一次调用不会产生设置连接的开销。将方法调用的超时时间增加到 10 秒可能会消除该问题。

Thank you very much, but this happened during the running of the program, and there was still traffic in the last second, and then a 20-second timeout exception occurred, and then it returned to normal by itself. Is it caused by network jitter to re-establish the tcp link?

**Comment by zzq0341** [comment]
> The first time you use the channel, gRPC will connect to the server which may take some time. Since you are giving a deadline of 2 seconds, if the combination of connecting, transporting over the network both ways and server side processing exceeds 2 seconds you will get a timeout as you describe.
> 
> Since you specified an idle timeout of 2 minutes, at the 20 second point the connection would still be active so the next invocation wouldn't have the overhead of setting up the connection. Increasing the timeout on the method call to 10 seconds will probably eliminate the problem.

Thank you very much, but this happened during the running of the program, and there was still traffic in the last second, and then a 20-second timeout exception occurred, and then it returned to normal by itself. Is it caused by network jitter to re-establish the tcp link?

**Comment by larry-safran** [comment]
If you use the current version of gRPC do you still see the delay?

**Comment by ejona86** [comment]
20 second timeout sounds like connect() timed out, although it would have been better to paste the exact error text. There may have been a bad address or the network was busted for a while. Either way the delay seems caused by the network.

You might end up benefiting from Happy Eyeballs, as if one address is slow it allows continuing on to the next without waiting the full 20 seconds. You could follow along on progress of https://github.com/grpc/proposal/pull/356 , which looks to add Happy Eyeballs. And also https://github.com/grpc/grpc-java/pull/10486
