### ISSUE TITLE
Channel in TRANSIENT_FAILURE state moves to IDLE state

### ISSUE THREAD

**Issue by ranavivek04** [grpc/grpc-java#10380]
Is it correct behavior that a Channel in TRANSIENT_FAILURE state moves to IDLE state?
Ideally channel in TRANSIENT_FAILURE state should retry and if retry attempts are exhausted and it still fails to connect, either it should be moved to  TRANSIENT_FAILURE or SHUTDOWN state.

**Comment by sanjaypujare** [comment]
Where do you see that happening? According to this doc https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md a Channel will from TRANSIENT_FAILURE to CONNECTING (or SHUTDOWN triggered by application but not on its own).

**Comment by sanjaypujare** [comment]
If there are no active/pending RPCs then it makes sense that the channel goes to IDLE. Why would the channel try to initiate a connection when there are no RPCs to send?

**Comment by ranavivek04** [comment]
But the channel is useless since it won't be able to resolve the host no matter how many rpc are made.
Won't it make sense to move this channel into transient_failure state permanently after retry attempts are exhausted?

**Comment by sanjaypujare** [comment]
> ...it won't be able to resolve the host no matter how many RPCs are made

So you are saying the channel should somehow determine that "unable to resolve host" is a permanent error so the channel should be shut down? One can argue that this is not a permanent error because of temporary network issues (such as DNS server not being reachable or the DNS server dynamic updates) and for majority of cases not shutting down the channel because of host resolution issues might be the right thing to do.

**Comment by temawi** [comment]
It seems like this question might be resolved? I'll close it, but feel free to re-open.
