### ISSUE TITLE
How to configure https scheme for proxy ?

### ISSUE THREAD

**Issue by deveshpujari** [grpc/grpc-java#10453]
I saw this issue : https://github.com/grpc/grpc-java/issues/9057
My follow up question on this . How the scheme of proxy is chosen ? 
I want to use ProxySelector class to specify either https or http scheme for the proxy. Proxyselector class only provides method to return the List<proxy> select(uri) , Which is nothing but socket address. 

Also which trust store is used to verify the proxy certificate ? I know I can set the javax.net.ssl.trustStore  property but is there any other way ?  

Thanks!!

**Comment by ejona86** [comment]
HTTPS_PROXY vs HTTP_PROXY is different than "TLS to the proxy." The environment variables talk about the protocol used to communicate with the proxy, not whether TLS is used. HTTPS_PROXY uses the HTTP CONNECT verb to form a TCP tunnel through the proxy, which is then used to communicate with the end-server using TLS. HTTP_PROXY is the old "proxy-in-the-middle-of-every request" proxy protocol in HTTP/1 that powered on-premise caching squid servers way back in the day.

HTTP/2 is incompatible with the HTTP_PROXY style of communication. gRPC always uses HTTP CONNECT to the proxy, even if using plain-text to the end-server. That's why gRPC observers `-Dhttps.proxyHost` instead of the http form.

**Comment by deveshpujari** [comment]
@ejona86 
Hi Eric, sorry .. still not clear to me. 
So if fwd-proxy is configured as TLS and gRPC client set the -Dhttps.proxyHost , will this work ? 

Plain HTTP proxy without TLS works. I tested, if the proxy is NOT Configured for TLS , and I used proxy detector class to provide proxy socketAddress. This works. gRPC client does the HTTP Connect and tunnel is created and Client runs the TLS on that tunnel. 

Now if the , proxy is configured for TLS . Does HTTP connect will be sent on the TLS connection to proxy ? This is needed to encrypt the basic auth sent in HTTP connect method.

Thanks !!

**Comment by ejona86** [comment]
> So if fwd-proxy is configured as TLS

Then gRPC will not work with it. That is not supported.

> This is needed to encrypt the basic auth sent in HTTP connect method.

Yeah, the basic auth is otherwise in plaintext. But it is also very wasteful to encrypt the entire connection for the sake of just the handshake. I think I've generally seen the basic auth as an observability "feature," where it lets you track down which system is doing what. But it's not expected to stand up against malicious actors that can see the network traffic.

**Comment by temawi** [comment]
It seems like the question has been answered - I'll close the issue. Feel free to re-open if further discussion is needed.
