### ISSUE TITLE
Okio CVE-2023-3635

### ISSUE THREAD

**Issue by skjolber** [grpc/grpc-java#10456]
Okio seems to be flagged by [CVE-2023-3635](https://nvd.nist.gov/vuln/detail/CVE-2023-3635) and current the [proposed fix](https://github.com/square/okio/pull/1280) is to upgrade to >= 3.4. As far as I can see this project uses version 2.10.0. 

Is the project already compatible with Okio 3.x, and/or any chance of moving to Okio 3.x in the near future?

**Comment by ejona86** [comment]
To my knowledge we are already compatible with okio 3. So if you just depend on the newer version things are expected to work. I know of regular testing using okio version 3.1.0, but it also compiles against 3.1.0. So the only possible issue would be an ABI issue, which would error loudly.

Our last last release was on the last okio 1.x release. Our 1.58 release in a month should upgrade to 2.10. We tried to upgrade further, but need to spend more time fighting our build (https://github.com/grpc/grpc-java/pull/10359#issuecomment-1632853307) due to okio's published Gradle Module Metadata.

We were sitting on okio 1.x to avoid the Kotlin dependency and because we were compatible with newer versions so we wouldn't be holding anyone else back. But yeah, that CVE was cause to move forward.

**Comment by temawi** [comment]
I think the question has been answered so I'll close the issue. Feel free to re-open if needed.
