### ISSUE TITLE
grpc modules not found in java 9+ modules

### ISSUE THREAD

**Issue by kpagratis** [grpc/grpc-java#10529]
### What version of gRPC-Java are you using?
1.57.2

### What is your environment?

Mac OS
```
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)

Gradle 8.3
```

### What did you expect to see?
I would expect to be able to use GRPC in a modular java proejct with a `module-info.java` like so:
```
module my.awesome.server {
  requires grpc.services;
  requires jakarta.inject;
}
```
Intellij is happy and can find and index `grpc.services`

### What did you see instead?
When attempting to build with gradle, I get 
```
error: module not found: grpc.services
  requires grpc.services;
               ^
1 error
```

**Comment by sanjaypujare** [comment]
Since gRPC does not yet have module descriptors you have to rely on automatic module names and the [`ModuleFinder`](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/lang/module/ModuleFinder.html#of-java.nio.file.Path...-)

Also have you defined the module-path in your builds? (see https://openjdk.org/projects/jigsaw/quick-start)

If you are still having issues can you share a small reproducible test-case?

**Comment by ejona86** [comment]
I think this is related to https://github.com/gradle/gradle/issues/17609 . It seems once we release 1.58 (this week), which will have automatic module names defined, then Gradle will start treating it as a module.

**Comment by kpagratis** [comment]
fantastic! I'll keep an eye out

**Comment by liangyuanpeng** [comment]
1.58.0 is out. :)

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
