### ISSUE TITLE
WriteQueue should stop flushing when the channel is not active

### ISSUE THREAD

**Issue by slandelle** [grpc/grpc-java#10527]
Otherwise, when there's a `SslHandler` in the pipeline, `SslHandler#flush` is going to add an empty ByteBuf in its pending writes buffer, then unwrap it, and will ultimately generate an Exception as the `SSLEngine` is already closed.

**Comment by slandelle** [comment]
`io.grpc.netty.WriteQueue`

**Comment by slandelle** [comment]
The underlying issue is that netty's `SslHandler#flush` (and hence also `close`) generates every time an Exception when it's already been closed.

**Comment by ejona86** [comment]
The related netty issue: https://github.com/netty/netty/issues/13569

**Comment by sanjaypujare** [comment]
@slandelle would you like to contribute a PR?

**Comment by ejona86** [comment]
I don't think WriteQueue is the best place for this. It is just an optimization compared to `writeAndFlush()` from Netty. If we did stop flushing, there is some risk of ByteBufs being leaked, so we'd need to be careful with the change.

**Comment by ejona86** [comment]
Yeah, we go through great pains to avoid connection creation, because it is expensive, especially TLS. Note that you should be wary of TLS session caching/tickets, as that would definitely change results. Connection close in general is commonly an error-ish condition given it can happen abruptly and not all tasks may complete.

For your use-case, you might find using `channel.enterIdle()` to be slightly faster than fully shutting down the channel. That will stop using the Name Resolver/Load Balancer/Connections, but the next RPC will re-create them all. The Channel itself doesn't have _that_ much state, but there is some synchronization to manage thread pools and the like.

**Comment by larry-safran** [comment]
@slandelle do you have any updates or did you get enough assistance to close the issue?

**Comment by slandelle** [comment]
@larry-safran Sorry for the late reply.

This ticket was originally triggered by an allocation bug in Netty, that's been fixed since then.

Then, as someone who's not familiar with the grpc-java codebase, it seemed to me that the current behavior triggers useless work. But indeed, this is only for a very special use case (simplifying, no keep-alive connections).
And then as @ejona86 pointed out, I don't have the full picture and modifying the existing behavior might break things I'm not familiar with.

So let's close this ticket.

Thanks a lot for your help, much appreciated.
