### ISSUE TITLE
Change in behaviour from 1.47.1 to 1.48.0 around stream request, single response services

### ISSUE THREAD

**Issue by Thrillpool** [grpc/grpc-java#10562]
Hello, I have a service like so
```
rpc ClientStreamingEcho(stream EchoRequest) returns (EchoResponse) {}
```
And I send an EchoRequest, get an EchoResponse sent to me and then send an EchoRequest

The client prints both what it is sending and what it receives.

In 1.47.1 I get output like

```
Sending an echo request for: some
Received an echo: cheers
Sending an echo request for: thing
```

While in 1.48.0 I get output like

```
Sending an echo request for: some
Sending an echo request for: thing
Received an echo: cheers
```

and in fact the onNext of the client is not being invoked until all the requests are sent.

If I change my service to 

```
rpc ClientStreamingEcho(stream EchoRequest) returns (stream EchoResponse) {}
```

Then I return to the old behaviour (which is the one I want).

What is this about? This commit here https://github.com/grpc/grpc-java/pull/9273/files looks like the reason for the change in behaviour. Was I relying on some undefined behaviour previously, the release notes don't detail the change in behaviour.

https://github.com/Thrillpool/grpc-repro/tree/master is a reproduction

https://github.com/Thrillpool/grpc-repro/blob/master/src/main/java/io/grpc/examples/multiplex/EchoService.java#L64 is where I respond to the first client message with a response of my own.

Can change https://github.com/Thrillpool/grpc-repro/blob/master/build.gradle#L26 between 1.47.1 and 1.48.0 to see it change behaviour. The new behaviour is present in 1.58.0.

**Comment by ejona86** [comment]
Is it important to your server to receive and process that second message? If so, streaming is probably what you want. If the server doesn't care about the second message, than just closing the RPC earlier would send the response sooner.

For unary responses, there's three things that get sent by the server: response headers, response message, and trailers+status. For streaming, those may need to be sent in separate packets. For unary, gRPC would ideally combine them together and send only one packet. That improves throughput and commonly reduces latency. This sort of optimization was already done on client-side for unary request (probably since before 1.0) where the client sends headers, request message, half-close. I think the optimization in #9273 got us further to the goal, but response headers are still separate from response message and trailers.

I feel pretty confident C core has this optimization on server-side, so the behavior you were relying on is not cross-language. But I also agree that it is subtle and not well documented.

If you can easily swap to using a streaming response, that's what I suggest. If that would take some effort, we can add a temporary knob to help give you more time to migrate while still allowing you to upgrade to newer gRPC versions. If that would take a lot of effort, we can give you a recipe to let you opt-in to the old behavior. It'd just fiddle with the MethodDescriptor on server-side to tell gRPC this is a bidi call instead of client-streaming.

**Comment by Thrillpool** [comment]
Yep it is important, the design of the thing in question is basically one where the client asks for some work to do, the server responds with some work and the client finally sends back the result of the work.

I can easily swap to using a streaming response, and from what you describe it sounds like this is the correct thing to do.

Thank you very much! This was the last remaining issue in upgrading the grpc version in our code base.
