### ISSUE TITLE
gRPC taking more time compared to normal REST.

### ISSUE THREAD

**Issue by vishalyadav9600** [grpc/grpc-java#10603]
Hi, 
I am implemented gRPC service and for comparision to check how fast gRPC is over REST I have done performance testing using JMeter. 

But I am getting more delay in gRPC service over REST
this is gRPC jmeter performance testing for 1000 calls.
![1000requestreport](https://github.com/grpc/grpc-java/assets/64917567/342c581e-33d9-4caf-ac4b-3aa849221231)

gRPC almost took 29 seconds to complete 1000 requests.

this is normal REST jmeter testing for 1000 calls.

![1000requesthttp](https://github.com/grpc/grpc-java/assets/64917567/bfa532ea-c9ef-4da1-b708-1e6eed8d52ab)
whereas normal REST take 1 second to complete 1000 requests.

**Comment by vishalyadav9600** [comment]
@ejona86 please help

**Comment by sanjaypujare** [comment]
This has been discussed previously in this repo:

https://github.com/grpc/grpc-java/issues/10126
https://github.com/grpc/grpc-java/issues/9895

BTW There is also an issue regarding Netty vs okhttp  https://github.com/grpc/grpc-java/issues/6696 

Would you be able to do your tests for gRPC using okhttp instead of Netty?

**Comment by vishalyadav9600** [comment]
I am using okhttp

**Comment by sanjaypujare** [comment]
This sounds unusual and has not been reported (other than the 2 issues I reported above). Couple of thoughts/questions:

- is there any kind of a proxy between the client and server in either case?
- for the HTTP REST case, are you using GET or POST calls? Note that gRPC *always* uses POST 
- I was thinking of some kind of a caching layer short-circuiting REST calls (if they are GET and server includes cache control headers in the response)

**Comment by ejona86** [comment]
I don't see gRPC taking more time per request. It looks like 32/65/995 (min, avg, max) is ms latency, and gRPC's compares similarly to REST's 35/73/179. The main difference is Throughput, which probably just means there was a different number of concurrent requests. gRPC looks to have 2 workers (1000/65 = 15 req/sec, with 35 req/sec being seen) where HTTP looks to have a lot more (60-70). I suggest checking the test configuration.

Even 32 ms and 35 qps is "very slow" for the how fast gRPC can go ([our dashboard](https://grpc.io/docs/guides/benchmarking/) has grpc-java median latency near 140 µs and qps near 150 kqps on an 8 core VM), so unless you were doing this test over the internet, I'd expect the results to mostly be testing the performance of your application.

**Comment by vishalyadav9600** [comment]
Let me explain my architecture to you, I have a normal request with few details like name, mobNo, etc. This is used to check the performance of gRPC. I have created a protobuf with these details and created a rpc service where I am taking this request and then sending the same in response. I have two modules in my service one for creating protobuf and another for service to take request and generate response simply in normal java/ kotlin code with returning in responseObserver. This is my flow and I am used postman to normally hit request as it uses gRPC and while performing performance testing I am using JMeter to test for 1000 request for which I have uploaded a screenshots. The issue was when I hit Http for 1000 request it took only 1 second to complete while when I used gRPC it took almost 29 seconds to complete 1000 request. I am not sure was it because I tested this whole thing in my local machine. Should I deploy this in a virtual machine and then try? I am unsure to use gRPC in payment services to serialize and deserialize.

**Comment by vishalyadav9600** [comment]
@ejona86 please tell and let me know if you need any more details. I am stuck in this issue from 15 days.

**Comment by ejona86** [comment]
The request latency showed there was little difference between REST and gRPC timing. The "time taken to complete 1000 requests" is simply a function of the number of concurrent requests. This sounds like a jmeter configuration issue. I was suggesting increasing the number of workers/concurrent requests in jmeter, to configure gRPC with a similar number as REST.

**Comment by vishalyadav9600** [comment]
i run 1000 request in 0 seconds.

**Comment by vishalyadav9600** [comment]
[](url)
![image](https://github.com/grpc/grpc-java/assets/64917567/e91aa141-0862-448e-b751-b7ab5452b2f2)

**Comment by ejona86** [comment]
I last used JMeter at least a decade and a half ago. I don't think we can really help you configuring it. But _just_ by looking at its output, it is clear JMeter is behaving differently between gRPC and REST.

I don't know the purpose of the ramp-up period, but it might be related. Ramping up over 1 second seems far too slow a ramp if you are expecting it to complete within 1 second.

Java is very slow to start. You should do 30-60 seconds of traffic to the server _and then_ run the benchmark. I expect that's what the "loop count" can help with, as you can discard the early runs. Without a warmup, if you run the REST and gRPC benchmarks against the same server, you may also notice the _second_ benchmark is faster, independent of whether the second one is gRPC or REST. That's simply because the first one partly warmed up the JVM to allow the second one to go faster.
