### ISSUE TITLE
Pass MethodDescriptor to ClientStreamTracer

### ISSUE THREAD

**Issue by anti-social** [grpc/grpc-java#10619]
### Is your feature request related to a problem?

I need an information about method that a client calls, to expose it in metrics. But at the moment I did not find a way to do that.

### Describe the solution you'd like

I want to propose either to add another `streamCreated` method:

```java
public void streamCreated(ClientCallInfo<?, ?> callInfo) {
  streamCreated(callInfo.transportAttrs, callInfo.headers)
}
```
In this way it will be backward compatible with old tracers. The drawback is that now someone will be able to override both methods.

Or to pass a `method` argument to the `ClientStreamTracer.Factory.newClientStreamTracer` method. As I can see all the sites where client tracers are constructed have a possibility to do that.

### Additional context

For instance `ServerStreamTracer.serverCallStarted` has a `callInfo` argument which in its turn has a `methodDescriptor` field. Also a `ServerStreamTracer.Factory.newServerStreamTracer` has a `fullMethodName` argument.

It looks like a really strange mismatch between client and server tracing API.

**Comment by ejona86** [comment]
We normally solve this by saving the MethodDescriptor within the interceptor that calls `callOptions.withStreamTracerFactory()`. Basically, grab the object before creating the tracer.

> Also a ServerStreamTracer.Factory.newServerStreamTracer has a fullMethodName argument.

This is because on server-side we receive the name from the client and we have to separately look up the MethodDescriptor. So the MethodDescriptor doesn't exist when the stream is created.

**Comment by anti-social** [comment]
> We normally solve this by saving the MethodDescriptor within the interceptor that calls callOptions.withStreamTracerFactory(). Basically, grab the object before creating the tracer.

After filling the issue I found an example how it was done in a PR:
https://github.com/grpc/grpc-java/pull/10593/files#diff-b12ba2e9141ff322f12a2b5c01ad85d9ee371fc77561978c9c141ecbf8a2ce99R454

But I would not say it is a convenient way. You also need to add an interceptor to a server (or instead of a tracer - it is not clear for me at the moment). 

> This is because on server-side we receive the name from the client and we have to separately look up the MethodDescriptor. So the MethodDescriptor doesn't exist when the stream is created.

I searched the code and what I've found is that `ClientStreamTracer.streamCreated` is called inside the `StatsTraceContext.newClientContext` method, which in its turn is called inside the `ConnectionClientTransport.newStream`, where a `MethodDescriptor` exists:
- https://github.com/grpc/grpc-java/blob/v1.59.0/core/src/main/java/io/grpc/internal/StatsTraceContext.java#L53
- https://github.com/grpc/grpc-java/blob/v1.59.0/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L183

So it seems to me that it is possible to pass `MethodDescriptor` to the `ClientStreamTracer.streamCreated` method.

**Comment by ejona86** [comment]
> But I would not say it is a convenient way. You also need to add an interceptor to a server (or instead of a tracer - it is not clear for me at the moment).

"server"? Why are you talking about server? I thought this was for client. For client-side, there should already be an interceptor in-use to install the tracer.

> ... which in its turn is called inside the ConnectionClientTransport.newStream, where a MethodDescriptor instance exists:

The interceptor had access to the MethodDescriptor already, before the tracer is even created. How are you using ClientStreamTracer if not from an interceptor?

**Comment by anti-social** [comment]
> "server"? Why are you talking about server?

Oh, it is a typo of course.

> The interceptor had access to the MethodDescriptor already, before the tracer is even created. How are you using ClientStreamTracer if not from an interceptor?

Oh, I didn't pay attention that there is no an analogue API for a client that server has: `ServerBuilder.addStreamTracerFactory`. We have an API for server metrics in our library, but not for a client. So I decided to fix that and I didn't expect that client tracer usage differs from a server. Possibly it is worth to have `ManagedChannelBuilder.addStreamTracerFactory` to be on a par with server version. Are there some blockers that prevent building such API?

**Comment by ejona86** [comment]
> Possibly it is worth to have ManagedChannelBuilder.addStreamTracerFactory to be on a par with server version.

Probably not. Clients and servers are opposite each other. On servers, the network (stream) is the beginning of the RPC and it is much simpler. On clients, the application (stub/interceptors) is the beginning of the RPC. There's also complications like retries (a single RPC can have multiple streams) and delays from DNS, connection establishment, oauth token retrieval, etc. It is very possible for an RPC to fail without any stream being created.

So for our own tracers on client-side, we create a new factory per-RPC. And the API is easy to use the same factory for each RPC. For your use-case, you will need to consider whether an interceptor or a tracer is a better fit (or normally, both), because the two are more different on client-side.

We actually wish we could hide the server tracers behind an interceptor (or similar) on server-side. Tracers are useful, but we want them to be more of an implementation detail. We don't really want to expose a "OTel tracer" but instead a "OTel interceptor," if users would be explicitly installing them in a ServerBuilder. That isn't really practical.
