### ISSUE TITLE
Load Balancing on OpenSHIFT (NameResolver not work) 

### ISSUE THREAD

**Issue by torquato** [grpc/grpc-java#10708]
Guys,

I am using the GRPC to communicate among micro services made in Java with Springboot, they all stay in an OpenSHIFT environment. My problem is that I am doing the load balancing with the strategy of "round_robin" and at the initial moment works perfectly, but if I climb another service, the GRPC does not identify it and keeps sending the messages just to the ones you have already sent.

Example:

**1x** service A <-------> **3x** service B = works by sending to the 3
**1x** service A <-------> **4x** service B = only sends to 3
**1x** service A <-------> **5x** service B = only sends to 3

Only starts to all, if I restart service A.

I'm sending as follows:

`setChannel(ManagedChannelBuilder
	.forTarget(dns:host_xpto:8090)
	.defaultLoadBalancingPolicy("round_robin")
	.usePlaintext().build());`

Version:
`<grpc.version>1.57.1</grpc.version>`
  ```
    <properties>
        <grpc.version>1.57.1</grpc.version>
        <protobuf.maven.plugin.version>0.6.1</protobuf.maven.plugin.version>
        <os.maven.plugin.version>1.7.1</os.maven.plugin.version>
        <protoc.version>3.21.7</protoc.version>
        <protoc-gen-grpc-java.version>1.57.1</protoc-gen-grpc-java.version>
    </properties>
    ...
    <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>${protobuf.maven.plugin.version}</version>
        <configuration>
            <protocArtifact>com.google.protobuf:protoc:${protoc.version}:exe:${os.detected.classifier}</protocArtifact>
            <pluginId>grpc-java</pluginId>
            <pluginArtifact>io.grpc:protoc-gen-grpc-java:${protoc-gen-grpc-java.version}:exe:${os.detected.classifier}</pluginArtifact>
        </configuration>
        <executions>
            <execution>
                <goals>
                    <goal>compile</goal>
                    <goal>compile-custom</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
    ...
   <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty-shaded</artifactId>
      <version>${grpc.version}</version>
      <scope>runtime</scope>
  </dependency>
  <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf</artifactId>
      <version>${grpc.version}</version>
  </dependency>
  <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-stub</artifactId>
      <version>${grpc.version}</version>
  </dependency>
```

What would be the best way to make a load balancing on OpenSHIFT with GRPC?

Thanks

**Comment by temawi** [comment]
Looks like you are depending on your DNS server to tell service A what addresses to use for service B. The DNS lookup happens when service A starts up and initiates a connection to service B. The addresses in the DNS response are used to round robin over the service B backends. There is nothing that would trigger a refresh in the gRPC client when you add a new service B instance.

Usually this is solved by utilizing a control plane server that is aware of all the nodes in the mesh and can send push updates when new instances come or go. gRPC supports the xDS protocol defined by the Envoy project and can be configured to use an xDS name resolver instead of a DNS one. This would trigger the gRPC client to listen to real-time updates from the control plane and to add any new service B instances you might add.

I am not at all familiar with OpenSHIFT, but if it supports the xDS protocol I presume there would be some resource out there that explains how OpenSHIFT would be used with a gRPC mesh.

**Comment by ejona86** [comment]
The client will refresh DNS when it is disconnected from a server. So the approach for this setup is to configure [`ServerBuilder.maxConnectionAge()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#maxConnectionAge(long,java.util.concurrent.TimeUnit)). If you set max age of 15 minutes, then after 7.5 minutes half of the clients are likely sending traffic to any new backend. After 15 minutes, they all are.

**Comment by juliojgd** [comment]
@ejona86 Does it make sense to force to close a connection at a fixed number of seconds if such connection is perfectly healthy? I guess that if a connection is healthy we want to keep it open and working for the maximum possible time; closing it at a fixed time after opening (needlessly) would be a counter-performant measure because opening connections is costly.

Wouldn't it be better to have a refreshing mechanism like a scheduled thread that refreshes DNS resolution every N seconds? Without the need to close any healthy and working connection.

**Comment by ejona86** [comment]
You might be able to get a watch-based resolver without too much trouble (replacing DNS). Looks like this one supports watches; dunno if there are others:
https://github.com/saturnism/grpc-by-example-java/blob/master/kubernetes-lb-example/echo-client-lb-api/src/main/java/com/example/grpc/client/KubernetesNameResolver.java

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
