### ISSUE TITLE
[Question] How can i  compilation successful for protoc-gen-grpc-java without android env?

### ISSUE THREAD

**Issue by yrzs** [grpc/grpc-java#10741]
```bash
$ cd $GRPC_JAVA_ROOT/compiler
$  ../gradlew java_pluginExecutable
```
A problem occurred evaluating project ':grpc-cronet'.
SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/home/xxx/grpc-java/local.properties'.

**Comment by ejona86** [comment]
You generally don't need to compile protoc-gen-grpc-java because pre-built binaries are [available on Maven Central](https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.60.0/).

But if you do try to compile it, look at COMPILING.md which suggests using `skipAndroid=true`. For one-off usage, that looks like:
```
../gradlew java_pluginExecutable -PskipAndroid=true
```

**Comment by yrzs** [comment]
> You generally don't need to compile protoc-gen-grpc-java because pre-built binaries are [available on Maven Central](https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.60.0/).
> 
> But if you do try to compile it, look at COMPILING.md which suggests using `skipAndroid=true`. For one-off usage, that looks like:
> 
> ```
> ../gradlew java_pluginExecutable -PskipAndroid=true
> ```

Thanks for your quick response

**Comment by sergiitk** [comment]
We're happy to help!
