### ISSUE TITLE
Handling certificate revocation with mTLS `ChannelCredentials`

### ISSUE THREAD

**Issue by jon-signal** [grpc/grpc-java#10779]
Hello!

We're considering building a service where consumer clients connect directly to a gRPC server that uses mTLS `ChannelCredentials`. At account creation time, clients would be issued a uniquely-identifying certificate for use with the service. In this scenario, certificates would expire or be revoked relatively frequently because user accounts get deleted or rotate their credentials.

Our thought is to do a (relatively expensive) credential check once when the channel opens, then close the channel if we have reason to believe the underlying credentials have been revoked, thereby forcing subsequent calls to go through a fresh credential check. As an example, if we had a single server, and that server received a "delete my account" request, the server would look for any open channels belonging to the deleted account and close them. The remote client would then have to reconnect and establish a new mTLS session before making any more calls (which the server would not permit because the credentials had been revoked).

From other discussions (like #8770 and [at least one StackOverflow thread](https://stackoverflow.com/questions/63749113/grpc-call-channel-connection-and-http-2-lifecycle)), I understand that this is not really A Thing and gRPC-Java doesn't really expose a way to operate on channels as a whole. Is my understanding correct? If so, what's the recommended best practice for dealing with credential revocation when using channel credentials? Is this just a bad use case for channel credentials in general?

Thanks!

**Comment by jon-signal** [comment]
Digging more, https://github.com/grpc/grpc-java/issues/779#issuecomment-340499638 is perhaps the most direct/relevant statement I've found that closing channels is not A Thing. I guess the more direct framing of this question, then is:

1. Has anything changed since 2017 (when that comment happened)?
2. If not, what's the recommended approach for dealing with certificate revocation in the context of `ChannelCredentials`?

**Comment by YifeiZhuang** [comment]
I am not an expert on the topic. I feel certificate rotation can be handled automatically nowadays through grpc api, does this work for you
> [AdvancedTlsX509KeyManager](https://grpc.github.io/grpc-java/javadoc/io/grpc/util/AdvancedTlsX509KeyManager.html) passed to [TlsChannelCredentials](https://grpc.github.io/grpc-java/javadoc/io/grpc/TlsChannelCredentials.Builder.html#keyManager(javax.net.ssl.KeyManager...)).

from comment: https://github.com/grpc/grpc-java/issues/10737#issuecomment-1850409811

**Comment by ejona86** [comment]
Closing channels is not A Thing. We aren't completely against the option of having it, but we've mainly just considered it for load shedding when behind a L4 LB. But even there, you have to be careful. Plenty of people have asked for it to authenticate a connection with the first request, but those approaches are fundamentally broken in gRPC; your case with client certs might not be.

Is there an account DB, or are the certs used solely (the cert includes the account information needed)? Said another way: what would naturally happen in your application if a client deleted an account, but then continued using the connection?

**Comment by ejona86** [comment]
> Today, we actually have a mix of two approaches:

From an authz standpoint, both of those approaches are roughly available in gRPC. The websocket approach is similar to using a bidi stream. The REST approach is per-RPC checking. But using a bidi stream is indeed a bit different for how the client behaves when the account is deleted.

> can we safely make blocking/long-running async calls from a KeyManager in the context of TlsChannelCredentials

KeyManager is a blocking API, so async isn't available. I know for xds we use blocking. But it is a bit more subtle whether all code paths are blocking-safe. If `executorPool != null` here, then you are safe: https://github.com/grpc/grpc-java/blob/4e163361d4a84f10afcfc4cf738e8f857c642004/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L364C32-L364C32

This looks to be the only path that would be a problem:
https://github.com/grpc/grpc-java/blob/4e163361d4a84f10afcfc4cf738e8f857c642004/netty/src/main/java/io/grpc/netty/ProtocolNegotiators.java#L398

I _think_ for a while TlsChannelCredentials was safe but maybe not Netty's SslContext. But maybe now there is no path that uses `null` there. I could look into this more later.

> then pull user information from the cert after the initial authentication/verification

I was asking about the DB because there's really two different parts involved here: authn and authz. Even with a "stale" authn (client cert) check, an account deletion could/should maybe trigger an authz failure. It sounds like you aren't storing the authz information in the certificate, which means a separate authz check per-RPC may be fine.

> what I'm picking up from this conversation is that the "normal" way to check for certificate revocation would be to check for revocation on each call; is that right?

Not really. The normal approach is to trust the TLS handshake for the life of the connection. This is the most common deployment strategy for server-side certs, after all. If a client connects one second before the server's cert expires, but it was valid when the client connected, then the client considers the server authenticated for the life of that connection.

CRL updates are pretty slow. So checking every RPC is excessive. For those using CRLs and client-certs, I think a more common approach is to limit the lifetime of the connection with `maxConnectionAge()`. CRLs might be refreshed every few hours, and the max connection age could be 30 minutes. With those combined you have a limit on how long a revoked certificate could be used. Even with OCSP there's a noticeable delay, so limiting the connection age still works well.

> also part of the effort as we move to gRPC, and we will likely need to contend with load-shedding

Disconnecting specific clients for load shedding is pretty hard to get right. For example, if all your backends are overloaded, that behavior could increase total load. It gets ugly as well when a single connection can cause overload. We were entertaining it for larger proxy cases (or control plane cases), where you have to load balance your load balancer using L4. At scale it can make sense for the proxy or control plane to invest the needed engineering, which requires care and coordination between servers. For virtually everyone else, it is better to KISS and use max connection age with L4, or use L7 (be it client-side, server-side, or lookaside load balancing).

**Comment by ejona86** [comment]
> I think for a while TlsChannelCredentials was safe but maybe not Netty's SslContext. But maybe now there is no path that uses null there. I could look into this more later.

It looks like only xds.internal.security.SecurityProtocolNegotiators is using the non-executor code path. So I think you can block, since you aren't using that xds code path.

**Comment by jon-signal** [comment]
> The websocket approach is similar to using a bidi stream. The REST approach is per-RPC checking. But using a bidi stream is indeed a bit different for how the client behaves when the account is deleted.

This is a very reasonable interpretation of what I actually wrote, but it turns out that it's not what I actually meant. My bad there!

Our use case is unusual in that we expose _the same API endpoints_ via both REST and the WebSocket. In other words, the WebSocket is acting more like an HTTP/2 connection for gRPC than a streaming gRPC call (although there IS some bonus streaming stuff that can only happen over WebSockets; it's messy!).

> I was asking about the DB because there's really two different parts involved here: authn and authz. Even with a "stale" authn (client cert) check, an account deletion could/should maybe trigger an authz failure. It sounds like you aren't storing the authz information in the certificate, which means a separate authz check per-RPC may be fine.

Right—point(s) taken. We haven't decided how this would work if we used TLS channel credentials yet, but I get where you're going!

> It looks like only xds.internal.security.SecurityProtocolNegotiators is using the non-executor code path. So I think you can block, since you aren't using that xds code path.

Quoting this specifically, but addressing the wider range of discussion on the topic: thank you! I really appreciate the safety check on blocking calls in this pathway!

Taking a step back: I think we have a clear picture of the space as it exists today, and we're still in enough of design phase that it's too early for me to argue for a new feature or behavior change with any kind of confidence. I thiiiiink that means it's probably time to close this issue. @ejona86 is there anything else you think we should resolve before we do so?

**Comment by ejona86** [comment]
Yeah, sounds like we can close this. If y'all get through your design before the bot auto-locks this issue, comment and we can reopen/continue the conversation here. Otherwise you can make a new issue. Good luck!

**Comment by jon-signal** [comment]
Thanks again!
