### ISSUE TITLE
When generating Java code, is it possible to have compatibility with both Jakarta and javax?

### ISSUE THREAD

**Issue by glsong7** [grpc/grpc-java#10793]

**Comment by ejona86** [comment]
Without you saying more, I have to assume this is a duplicate of #9179, and not actually a Jakarta compatibility issue. To date, I've not heard of any _problem_ caused by gRPC using javax.annotation.Generated, other than the need for a compile-only dependency.

If that's not what's happening here, comment and we can reopen.
