### ISSUE TITLE
Investigate if Application protocols should be required

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1081]
FYI: This is more of a collection of thoughts that an actual issue.  The existing behavior might actually be correct.

When doing HTTP2 over TLS, the spec says that the next protocol "h2" can be used when negotiating using ALPN/NPN.  Currently today, the netty server accepts any next protocol, as long as there is one.  Specifically, sending a next protocol of "gibberish" does not cause the server to fail the connection.  This is controlled by SelectedListenerFailureBehavior.ACCEPT in our GrpcSslContexts class.  

Intuitively, it seems like if the wrong protocol is specified by a client, the connection should fail.  If no protocol is specified, it seems like the server should entertain the possibility that the client wants to speak HTTP2, and not fail the connection.

The spec indicates a limited set of TLS requirements, of which application protocol negotiation doesn't appear to be on the list.

**Comment by nmittler** [comment]
FYI, sounds like this is the culprit: https://github.com/grpc/grpc-java/blob/aefefb50c4fd5cb15828470694c73d7ba42a79e0/netty/src/main/java/io/grpc/netty/GrpcSslContexts.java#L64.  We had to boil this down to using `ACCEPT` due to the limited modes for OpenSSL. I think the right fix is to just fail if the returned application protocol isn't `h2`.

**Comment by carl-mastrangelo** [comment]
That sounds like something worth documenting in the code.

**Comment by nmittler** [comment]
@carl-mastrangelo Yeah probably a good idea ... want to add it to #1082?

**Comment by carl-mastrangelo** [comment]
I believe this is done.
