### ISSUE TITLE
can withWaitForReady print some error

### ISSUE THREAD

**Issue by twogoods** [grpc/grpc-java#10860]
if server is not ready，client use withWaitForReady will block without error msg print, sometimes will make me confused

if use withoutWaitForReady onError will show msg，onError  will restart grpc stream and send request like this:
```
onError(Throwable throwable) {
    requestObserver = this.stub.stream(new ResponseObserver()); //will connection refused error
	requestObserver.onNext(request); //will connection refused error
}
```
server not ready，this onError will get two connection refused error, 2 error execute onError will get 4 error, 4 to 8 ...

so onError only restart stream，cannot send request
```
onError(Throwable throwable) {
    requestObserver = this.stub.stream(new ResponseObserver()); 
}
```
but how to know connection ready and can send request?

**Comment by ejona86** [comment]
We agree that today you have to choose between seeing an error message and using wait-for-ready. You shouldn't make a tight error loop like that, as errors will happen rapidly when the channel is in TRANSIENT_FAILURE and because the errors could be from the server. You don't want to hammer RPCs. Using non-wait-for-ready with exponential backoff is the only available approach today.

We are still discussing ways this could be addressed. We could maybe allow the channel state API (`managedChannel.getState()`) to return an error message, but that has some complexities and would need cross-language agreement.

**Comment by temawi** [comment]
I think the question has been addressed so I'll go ahead and close it. If there are further questions we can reopen it.
