### ISSUE TITLE
binder: ServerAuthInterceptor might use an Executor that BinderServer has already returned to the pool

### ISSUE THREAD

**Issue by mateusazis** [grpc/grpc-java#10897]
This is a follow-up to #10566.

*(note: I'm describing the issue as I recollect it; Chat ate the discussion thread. @markb74 please correct me if I'm wrong)*

#10633 introduced the `PendingAuthListener` class and the logic to handle `AsyncSecurityPolicy` without blocking any threads. This required an `Executor` to be passed to `BinderTransportSecurity` [here](https://github.com/mateusazis/grpc-java/blob/6f6cde9b1372c480bd730c470e615ec73a0b82da/binder/src/main/java/io/grpc/binder/BinderServerBuilder.java#L184). In the same PR, we added a shutdown listener to return that executor to the object pool during server shutdown ([here](https://github.com/mateusazis/grpc-java/blob/6f6cde9b1372c480bd730c470e615ec73a0b82da/binder/src/main/java/io/grpc/binder/BinderServerBuilder.java#L185)).

@markb74 commented that this was sub-optimal, and we could instead return the executor during termination. One suggestion was to pass an `Executor` to `BinderServer.start` and reuse it throught that server's lifetime. I prototyped it in https://github.com/mateusazis/grpc-java/commit/3f262ca61dab1bbdcca1e664331727803e03e7b3, but ended up with a chicken-and-egg issue in `BinderServerBuilder.build`:

- `BinderTransportSecurity.installAuthInterceptor` wants an Executor, but it will only be available on `BinderServer` after it is instantiated and started
- `BinderServer` is only instantiated after the authorization interceptor gets installed

Any help here is welcome!

**Comment by jdcormie** [comment]
I think I finally understand the problem Mark was pointing out.

Today `BinderServer` returns this Executor to the pool in `InternalServer#shutdown()`. But shutdown() merely "*Initiates* an orderly shutdown of the server. Existing transports continue ....". So we have a bug where `ServerAuthInterceptor` may continue to use this executor after it has been released. The upshot could be `RejectedExecutionException`s, since the resource pool may call shutdown on a returned Executor.

It seems to me that we can't safely release this executor until the last `BinderServerTransport` created by this `BinderServer` has called `ServerTransportListener#transportTerminated()`

**Comment by mateusazis** [comment]
Ah, that does ring a bell w.r.t. to the chat I had with him. #11240 is an attempt to address it. PTAL when you have a chance.
