### ISSUE TITLE
Support user control of the timing of send "goaway".

### ISSUE THREAD

**Issue by leizhiyuan** [grpc/grpc-java#10929]
### Describe the solution you'd like

Currently, if you want to close the gRPC long connection from the server side to achieve load balancing, it can only be done by setting the parameter maxConnectionAgeGraceInNanos. After enabling this, it will periodically close, but the control is not strong.

### Describe alternatives you've considered

https://github.com/golang/net/commit/97aa3a539ec716117a9d15a4659a911f50d13c3c http2 implement
https://github.com/kubernetes/apiserver/commit/e5c6ec44deca37a04183eaf295de5413ae83154c GoawayChance

Can we refer to this implementation? Users can set the "connection close" in the sendHeaders method of SimpleForwardingServerCall according to their own conditions. After that, when grpc recognizes it, it will trigger the corresponding goaway.

**Comment by ejona86** [comment]
What are you trying to accomplish? You mention load balancing, but what sort of load balancing is going on?

We aren't against allowing a server to trigger goaway for a client, but you have to be exceedingly careful about it. We haven't heard of anyone needing this that is willing to put forth the effort on their side to avoid the negatives. Essentially, your servers need to coordinate in order to determine when to trigger the goaway, which is a lot of work. Simple approaches seem to be universally exposed to cascading failures. (I know I've mentioned this before, and I thought I did recently, but I can't find it.)

**Comment by leizhiyuan** [comment]
Thank you for your reply.

The client connects to backend grpc servers, such as s1 and s2, through an L4 load balancer.

When there are few clients, due to the existence of long connections, the client actually only maintains connections with either s1 or s2, resulting in an imbalance in the number of connections between s1 and s2.

To solve this, maxConnectionAgeGraceInNanos can be set to periodically disconnect s1 and s2, allowing the client to establish new connections. This can gradually achieve load balancing.

However, this feature remains active and after running for a period of time, if the connection count is balanced, it seems unnecessary to continue executing goaway. Therefore, I would like to refer to the implementation in Go.

This should be executed during a certain period of time t after startup. After t has passed, the application layer will no longer trigger goaway. When s1 or s2 restarts, this scenario can also trigger the application layer to take action.

**Comment by ejona86** [comment]
@ayanamist, your request sounds separate from this issue. We could provide a "send GOAWAY after X requests on the connection," similar to nginx, for that case. You don't need fine-level control. Please create a separate issue.

> it seems unnecessary to continue executing goaway

The question is not whether it is "unnecessary" but whether it causes a problem. For 95% of users, I have trouble believing it would be costly. It does have occasional increases of latency, but that's in the long tail, and there are alternative solutions to that problem. With HTTP/1 libraries were creating connections _constantly_. Here we are amortizing a connection over many minutes. Yes, the connection lasting longer is even better, but it has diminishing returns.

> if the connection count is balanced

The problem is, "how do you know if it is balanced?"

> After t has passed, the application layer will no longer trigger goaway

That sounds like it will cause imbalance. Let's say S1 has been running for 1 h, so `t` has passed. Let's say S2 is restarted. Then any connections that are sent to it will be "rebalanced," meaning they have a 50% chance of going to S1. But if they choose S1, they are "stuck" to S1 and don't change again. This creates a large bias, with many more connections on S1 than S2.

Unless you were meaning S1 and S2 would coordinate with each other and both would go into "rebalancing mode." Is there enough value in coordinating that though? Can you measure a problem caused by the reconnecting? What sort of `t` are you considering, and how would you select connections trigger goaway? It would seem you'd have trouble supporting high and low qps clients simultaneously.

**Comment by leizhiyuan** [comment]
Controlling this timing is quite difficult. In my opinion, it is more about providing users with the ability to control the timing of "goaway" based on different scenarios.

**Comment by ejona86** [comment]
> Controlling this timing is quite difficult. In my opinion, it is more about providing users with the ability to control the timing of "goaway" based on different scenarios.

I don't disagree, but it is almost guaranteed to shoot yourself in the foot. As in "everyone before you that has asked for this, planned to use it in a way that would _cause_ load imbalance or cascading failure." Or put another way, "the solution was worse than the problem." Before adding such a feature we want to make sure _at least one project_ will benefit from it.

So, the important questions are "Are you actually experiencing a problem?" (vs "it feels icky") and "Are you going to coordinate between your servers?"

**Comment by leizhiyuan** [comment]
> So, the important questions are "Are you actually experiencing a problem?" (vs "it feels icky") and "Are you going to coordinate between your servers?"

Currently, I have indeed forked and modified the grpc code to support this feature. Then my s1 and s2 will coordinate through an intermediate node to determine how many connections should be closed using goaway.

I admit that this feature is quite complex. Apart from kubernetes/apiserver@e5c6ec4 GoawayChance k8s, there are currently no other products with a similar feature.

If there is more information or scenarios in the future, we can discuss them. Thank you for your reply and explanation.

**Comment by ejona86** [comment]
Okay, with coordination you can do a reasonable job. I would still like to know what problem you are solving, as there might be alternatives. But assuming you have a good reason there's the question of the API and such. I do expect this would become a cross-language discussion, but we can get an idea of "what do we want" before we bring in other languages.

I don't think we want a per-request API. If you are actively managing connections, you might want to close some that are idle to free memory, for example. Today, the only API that is 1:1 with connections is the [`ServerTransportFilter`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#addTransportFilter(io.grpc.ServerTransportFilter)). That doesn't allow killing connections, though. I wonder if it would be best to extend it to pass an object that could be called to close the connection. The Filter would then be free to copy that object (or one of its own creation) to RPCs on that connection by including it in the `Attributes`.

Unfortunately, that is a grpc-java-centric API. Go might be able to do something similar with their Dialer. I don't know for C++.

**Comment by sergiitk** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
