### ISSUE TITLE
What is the difference between grpc-netty and grpc-netty-shaded?

### ISSUE THREAD

**Issue by zxyao145** [grpc/grpc-java#10931]
Hi, although there are some reasons for recommending the use of grpc-netty-shaded in SECURITY.md, is there a document that can provide a detailed explanation of the differences between the two?

And we are still using Java 8. Is there any recommendations for Java 8?

**Comment by panchenko** [comment]
@zxyao145 You can find that online, e.g. https://stackoverflow.com/q/49810578

**Comment by zxyao145** [comment]
> @zxyao145 You can find that online, e.g. https://stackoverflow.com/q/49810578 您可以在网上找到它，例如https://stackoverflow.com/q/49810578

@panchenko Hi, Thank you for your reply. But I am confused as to why they have different APIs, for example, `NettyChannelBuilder`. When I use grpc-netty-shaded, I cannot find this class.

**Comment by panchenko** [comment]
@zxyao145 The idea is that most of the code does not depend on the those classes directly, whatever is available during runtime is loaded automatically by `ServerBuilder.forPort(port)` or `ManagedChannelBuilder.forAddress(host, port)`

**Comment by ejona86** [comment]
`grpc-netty-shaded` is grpc-netty + netty + netty-tcnative all built into one jar. It prefixes all package names with `io.grpc.netty.shaded.` so they don't collide with the normal versions. `grpc-netty` uses some unstable APIs of Netty, and Netty has a weaker API stability policy than gRPC expects, so `grpc-netty-shaded` allows using a compatible version of Netty without worrying about if Netty is a transitive dependency somewhere else in your app (since Netty is a pretty common dependency). It also is a benefit for vulnerabilities, as upgrading Netty can sometimes be difficult, but with grpc-netty-shaded you can upgrade for gRPC easily.

**Comment by zxyao145** [comment]
@ejona86 Thank you very much, this is the answer I am looking for!
