### ISSUE TITLE
implement timeout_on_sleeping_server interop test

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-java#1099]
https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md

**Comment by madongfly** [comment]
We've already had such (test)[https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java#L614] with a different name.

But the implementation is different than the SPEC, we are asking the server to sleep for a while, instead of set deadline to a super short value, I think our implementation is correct for a `timeout_on_sleeping_server` test, do you know whether other languages' test servers respect the ResponseParameters.interval_us? should we change the test SPEC to use it?

**Comment by ejona86** [comment]
@madongfly, our test predates the one in the test specification. We should update our test or create a new one to match the spec.

There's no need to use interval_us for this test since it uses a full duplex call. Currently "Observe ResponseParameters.interval_us" is defined for server-side, but no cross-language interop test requires it.

**Comment by ejona86** [comment]
Also, the test should be made available via the command line with the interop test tool.

**Comment by madongfly** [comment]
Hmm, the test is actually already in the AbstractTransportTest, I'll add it to interop test client.
