### ISSUE TITLE
Close AutoCloseables after async send?

### ISSUE THREAD

**Issue by gen-user1** [grpc/grpc-java#11006]
Hello, is there any mechanism, where grpc sending thread can close Autocloseable message after it has left the queue (was sent/was cancelled and so on) after asynchronous send through https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/StreamObserver.html#onNext(V) ?

**Comment by temawi** [comment]
Sorry, that mechanism does not exist. What are you trying accomplish? There might be other approaches you can take.

**Comment by gen-user1** [comment]
Thank you for prompt response, @temawi ! 
In my setup messages, that are sent through GRPC, contain references to resources, that need to be closed manually after the message was sent (hence they are Autocloseable). Currently the setup is trying to catch them on GC and then close, since API is async, but maybe there is a better way to handle this?

**Comment by ejona86** [comment]
For your messages to contain references, are you using Protobuf? Are you doing zero-copy tricks with ByteString, or do you have a custom marshaller format?

There's been conversation about this in https://github.com/grpc/grpc-java/issues/1054 . You can do zero-copy in the receive path thees days, but the send path hasn't been solved. Interceptors generally won't participate in the lifetime handling.

That issue has a bunch of conversation. See my response in #9704 where I gave a hint of where a good place to start reading is. I don't think there's been any progress on the sending side since that 2022 comment of mine in #9704.

**Comment by gen-user1** [comment]
Hello @ejona86, you are right, it is related to zero-copy , but I can't dive into details. That is unfortunate that the progress is not yet there, I am looking forward for this option to be provided. Thanks for the info!

**Comment by ejona86** [comment]
We're tracking zero-copy for sending in #9704. Closing this one.
