### ISSUE TITLE
How to monitor the number of bytes transmitted, such as the total number of bytes received and sent

### ISSUE THREAD

**Issue by jaceding** [grpc/grpc-java#11127]
I use the GRPC library as the RPC implementation of the system. After optimizing the core algorithm of the system, the number of RPCs in the system will be reduced. However, I am also very concerned about whether the data transmission size has been reduced, but I do not know how to record the data transmission size, such as the total number of bytes sent and received.

Looking forward to your answer very much !!!

**Comment by larry-safran** [comment]
There are several ways of handling this.  

The simplest might be to use call tracing.  

Another approach is to override the marshaller on the `MethodDescriptor` to do the counting and then delegate to the regular marshaller.  We have a [preserialized example](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/preserialized) that could be useful to you for this approach.  You could do it either on the client or the server.

Another approach would be to use either `ClientInterceptor` or `ServerInterceptor`.  
  For `ClientInterceptor` you would implement `interceptCall` which will give you direct access to the outgoing request and in that method wrap the listener so that you could track the response.
