### ISSUE TITLE
grpc-netty-shaded latest version (1.63.0) still affected by CVE-2023-44487 in our scan report

### ISSUE THREAD

**Issue by Akshobhya123** [grpc/grpc-java#11135]
grpc-netty-shaded latest version (1.63.0) still shows it is affected by CVE-2023-44487 in our scan report based on the bellow discussion https://github.com/grpc/grpc-java/issues/10614 we have updated **netty-codec-http2**  jar version to latest **4.1.109.Final** but no luck. Can someone let us know what is the solution?

**Comment by ejona86** [comment]
+1 to @panchenko's reply.

I'll further note that grpc-netty-shaded typically doesn't show up in scanners for Netty issues because it doesn't depend on Netty in the pom and [we remove the Maven version identifiers](https://github.com/grpc/grpc-java/commit/1882c47eb916fa516a4342a3dab32a5bdf7b3230) from within the jar itself.

So I'd be suspicious of the tool you used and where it got its data. There's a lot of bad data/tools out there. I don't see any CPEs in [the CVE](https://nvd.nist.gov/vuln/detail/CVE-2023-44487) that match against grpc-java 1.63.0.

Another option is you are using Maven and accidentally _aren't_ using the version of gRPC or Netty you think you are using. You can use `maven dependency:tree` to see the the computed version numbers. Maven users should always enable Maven Enforcer's requireUpperBoundDeps, like we do in our examples, because Maven's version selection is so bad.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
