### ISSUE TITLE
Retry does not work with grpc-servlet in Tomcat

### ISSUE THREAD

**Issue by panchenko** [grpc/grpc-java#11244]
**gRPC version 1.64.0 / Tomcat 9.0.89**

As retry is configured from the client side - I would expect it to work, no matter which technology is used by server.
However, something is different if using Tomcat.

I would like to understand if that's a known situation and probably possible directions on how it can be fixed.

I have used `RetryingHelloWorldClient` from the examples, retry works with `RetryingHelloWorldServer`, but does not work if starting gRPC inside Tomcat.

My code is like the following, with `ForceTrailersServerInterceptor` from #10125

```java
public class TomcatServer {
    public static void main(String[] args) throws IOException, LifecycleException {
        Path tempDir = Files.createTempDirectory("test");
        try {
            Tomcat tomcatServer = new Tomcat();
            tomcatServer.setPort(50051);
            tomcatServer.setBaseDir(createDirectory(tempDir.resolve("root")).toString());
            Context ctx = tomcatServer.addContext("", createDirectory(tempDir.resolve("context")).toString());
            GrpcServlet grpcServlet = new ServletServerBuilder()
                    .addService(new RetryingHelloWorldServer.GreeterImpl())
                    .intercept(new ForceTrailersServerInterceptor())
                    .buildServlet();
            Tomcat.addServlet(ctx, "TomcatTest", grpcServlet).setAsyncSupported(true);
            ctx.addServletMappingDecoded("/*", "TomcatTest");
            tomcatServer.getConnector().addUpgradeProtocol(new Http2Protocol());
            tomcatServer.start();

            Uninterruptibles.sleepUninterruptibly(10, TimeUnit.MINUTES);
        } finally {
            delete(tempDir);
        }
    }
```

**Comment by kannanjgithub** [comment]
From the provided information it doesn't look like the issue is specific to the service logic (retrying Hello world server).
For a GrpcServlet wrapping a Grpc Service, the contextRoot/urlPattern must match the gRPC services' path, which is /full-service-name/short-method-name as mentioned in this [code comment](https://github.com/grpc/grpc-java/blob/master/servlet/src/main/java/io/grpc/servlet/GrpcServlet.java#L29).  Can you confirm if this is the case?

**Comment by panchenko** [comment]
The service methods are called, so I think patterns/paths are correct. This code snippet is based on the corresponding [tests](https://github.com/grpc/grpc-java/blob/df8cfe9ddc541b9548ff3a62c6d1e802c5251b14/servlet/src/tomcatTest/java/io/grpc/servlet/TomcatTransportTest.java#L87), obviously in a real application it would be different.

**Comment by ejona86** [comment]
Given "Tomcat does not support trailers only" in https://github.com/grpc/grpc-java/issues/10124 , this is exactly the behavior we'd expect. Retries uses trailers only.

https://github.com/grpc/proposal/blob/master/A6-client-retries.md

> If the application code closes the stream with an error before sending headers or any response messages, gRPC servers should send the error in Trailers-Only.

This is caused by trailers being detected by END_STREAM. https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

> For responses end-of-stream is indicated by the presence of the END_STREAM flag on the last received HEADERS frame that carries Trailers.

Either Tomcat would need to change (their behavior isn't wrong, but not what we are desiring), to use a different servlet container, or for gRPC clients to change to allow trailers without END_STREAM.

Trailers without END_STREAM would probably be implemented as the client detecting `grpc-status` in the headers, and then delaying delivering anything up to the application until it receives a zero-length DATA with END_STREAM. If it receives anything else it fails the RPC as incompatible (and doesn't use the grpc-status). But that'd need a change to gRPC's spec and updates to all clients.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
