### ISSUE TITLE
Add close method with Throwable parameter to ServerCall

### ISSUE THREAD

**Issue by minwoox** [grpc/grpc-java#11321]
I wanted to inquire if it would be feasible to consider adding a `close` method to `ServerCall` that accepts a `Throwable`, similar to the following proposal:

```
public abstract class ServerCall<ReqT, RespT> {
  ...
  public void close(Throwable t) {
    Metadata metadata = Status.trailersFromThrowable(t);
    if (metadata == null) {
      metadata = new Metadata();
    }
    call.close(Status.fromThrowable(t), metadata);
  }

  public abstract void close(Status status, Metadata trailers);
  ...
}
```

The reason for this request is that our gRPC framework supports converting exceptions into specific statuses that are preferred by our users. Most occurrences handle this conversion appropriately, except for one specific case, which can be found at:

https://github.com/grpc/grpc-java/blob/5770114d08dcd352f2288ef52d17e1833530323c/stub/src/main/java/io/grpc/stub/ServerCalls.java#L389

Introducing `call.close(t);` at that location would resolve the issue we're encountering.

Please let me know if further details are needed. 🙏

**Comment by ejona86** [comment]
> Most occurrences handle this conversion appropriately, except for one specific case

"one specific case" that _everyone_ uses, and is the only case exposed in the stub. I can't say I entirely follow. "Most occurrences handle this conversion appropriately," but this is the path that all statuses come through...

Adding a method to `ServerCall` is probably not worth it, because it causes complications for all interceptors. The problem you are having is part of the stub; the fix should be part of the stub.

Even with some way to change the behavior, I do have some concern about semantics; if you change the behavior of one of gRPC's APIs, then the API loses its semantics/predictable behavior. ("If I call close() with X, what will the client see?" changes depending on the situation.) Without understanding what things your framework is doing, it is hard for me to give much guidance.

**Comment by minwoox** [comment]
Thanks a lot for the answer.
> Without understanding what things your framework is doing,

Our framework provides a way to customize converting an exception into a gRPC `Status`.
However, because the exception is already converted into a `Status` before `close` is called,
we cannot unify the converting logic into one place without breaking the current API.

We have decided to introduce a breaking change, so please don't worry about it. Thanks a lot for your help. 😄
