### ISSUE TITLE
Optional keepalive requests parameter on the client

### ISSUE THREAD

**Issue by nyukhalov** [grpc/grpc-java#11728]
### Is your feature request related to a problem?

We are using grpc-java for both clients and servers deployed in EKS. Our servers are exposed to the clients via AWS ALBs.
The AWS ALB has a [hard limit of 10,000 requests per connection](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#response-code-000) and sends a GOAWAY frame when the limit is exceeded.
When a high throughput client breaches the limit, several inflight requests fail. At scale this significantly impacts the service SLOs.

### Describe the solution you'd like

When we used Finagle, we solved this issue by introducing a configurable client-side limit that forced the client to reconnect after exceeding the limit: https://github.com/twitter/finagle/commit/610a21cac42b086170600097c94f0963511382ae. The benefit of this mechanism is that the client proactively reconnects before sending a bunch of requests. We would like a similar functionality to be added to the gRPC client.

### Describe alternatives you've considered

We don't have any other alternative solutions: there is not much we can do as long as there is an ALB in the middle.

### Additional context

I have seen an old [statement](https://github.com/grpc/grpc-java/issues/10533#issuecomment-1718294338) from @ejona86 about a similar request

> No, we don't have anything like that, and we wouldn't want it because this should be in the server's control. Adding it to the client prevents the server from managing it; the server can't reduce the value as then clients start seeing errors and increasing the value has no effect as clients close early.

but I wonder if you could reconsider this given the real life use-cases where a load balancer enforces such limitations.

**Comment by ejona86** [comment]
Having a client-side configuration that has to match the server is not really a solution. ALB is allowed to change their setting and then you'd suffer the failures again. Request limits (instead of time) is a very nginx thing to do; I wonder if ALB is using nginx.

Note that this is not an HTTP/2 problem, as it [allows a fully-graceful connection closure](https://httpwg.org/specs/rfc9113.html#GOAWAY):
> A server that is attempting to gracefully shut down a connection SHOULD send an initial GOAWAY frame with the last stream identifier set to 231-1 and a NO_ERROR code. This signals to the client that a shutdown is imminent and that initiating further requests is prohibited. After allowing time for any in-flight stream creation (at least one round-trip time), the server MAY send another GOAWAY frame with an updated last stream identifier. This ensures that a connection can be cleanly shut down without losing requests.

If ALB is not using nginx, then they should implement that double-GOAWAY shutdown. [nginx does not do double-GOAWAY](https://trac.nginx.org/nginx/ticket/2224).

Note that gRPC's transparent retries should hide some level of these failures. There is https://github.com/grpc/grpc-java/issues/10533 where it was claimed the transparent retries weren't happening with nginx, but it has not been reproduced or the bug identified.

**Comment by nyukhalov** [comment]
Thank you for the answer @ejona86.

> Having a client-side configuration that has to match the server is not really a solution.
Would you mind elaborating on this just for my understanding, please? Is this based on some gRPC design principles?

> double-GOAWAY
This does sound like a reasonable solution, I will check with AWS, thank you.
To confirm, do gRPC clients and servers support double GOAWAY?
Just wondering if direct client -> server connectivity will actually solve this problem given that only the server can control the collection lifetime.

**Comment by ejona86** [comment]
> To confirm, do gRPC clients and servers support double GOAWAY?

All HTTP/2 clients should support receiving double-GOAWAY. The gRPC-Java server sends double-GOAWAY for regular shutdown. Most other gRPC server implementations do as well.

> Just wondering if direct client -> server connectivity will actually solve this problem given that only the server can control the collection lifetime.

I'm not quite sure what you mean by that.

I'll remind you that we do have a back-up solution which is transparent retries. Double-GOAWAY is great because it prevents errors entirely, but without it gRPC should be able to handle some level of abrupt shut down. If we're seeing more errors than expected, maybe the specific way the server is shutting down is preventing transparent retries from working. The first step to diagnose that would be to know what error message you see on the client. (You can compare to those seen in [the other issue](https://github.com/grpc/grpc-java/issues/10533#issuecomment-1718344120).)

**Comment by nyukhalov** [comment]
> The gRPC-Java server sends double-GOAWAY for regular shutdown.

To clarify, does this include a connection shutdown during normal server operation (e.g. when a connection's max age is reached)?

> The first step to diagnose that would be to know what error message you see on the client.

The error that I linked with the 10,000 ALB limit was `Abrupt GOAWAY closed sent stream. HTTP/2 error code: NO_ERROR`.

**Comment by nyukhalov** [comment]
> I'm not quite sure what you mean by that.

I would like to understand the client behaviour in a scenario when a connection with several inflight requests is terminated by the server, for example, due to exceeding the `maxConnectionAge` threshold. 

Do I understand correctly, that unless the client's retry policy is configured to retry on `UNAVAILABLE`, the transparent retries mechanism is _the only_ solution that helps recovering from such failures by retrying each eligible request once?

**Comment by ejona86** [comment]
Seems like this is resolved (as much as is expected). If not, comment, and it can be reopened.

If it seems transparent retries aren't working when it seems they should, I don't really mind assuming nginx is involved and that this is related to #10533. Independent of whether nginx is involved, the next steps would be essentially the same as https://github.com/grpc/grpc-java/issues/10533#issuecomment-2557455705

If it seems this is separate, comment, and we can reopen it.

**Comment by nyukhalov** [comment]
Hi @ejona86 , just a quick update: after testing the transparent retries mechanism in our lab environment, I confirmed that it (the mechanism) is correctly handling most of the GOAWAY responses as you mention above. Also, as you mentioned, the only scenario where it does not seem to help is when the targets consecutively respond with GOAWAY. After additional testing, I confirmed that the scenarios where more than one GOAWAY response is received per an RPC is not related to exceeding the 10,000 requests per connection limit. Therefore, the requested feature would not help in that case either.
Thank you again for the quick and detailed responses.
