### ISSUE TITLE
Consider allowing clients to provide cancellation details

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1221]
When designing `Context` we decided that `cancel(Throwable)` could be useful for debugging where a cancellation came from. In general, I'm not a fan of using that information for changing behavior, but it is very helpful for debugging.

Currently `ClientCall.cancel()` does not accept any arguments, because there is no way for the client to inform the server of any reasoning (and aren't too interested in that scenario, because servers can't really trust clients too much). When reviewing #1203, I saw that `Context` auto-propagation can make it quite opaque why a call was cancelled. We could have `ClientCall.cancel(String desc, Throwable t)` which will end up notifying the application `onClose()` with a `Status.CANCELLED.withDescription(desc).withCause(t)`.

That would allow us to propagate a `Context`'s failure exception as well.

**Comment by carl-mastrangelo** [comment]
We could make cancel(StatusException), just extract the status and associated metadata (assuming we pin metadata to status somehow)

**Comment by ejona86** [comment]
We would want to enforce that the status code is `CANCELLED`.

**Comment by ejona86** [comment]
Cancel without debug information is becoming a bigger problem. We need to do this.

**Comment by zhangkun83** [comment]
I wonder if we need to record any stacktrace other than the one for where `cancel()` is called. If the answer is no, `cancel(String)` would suffice because `cancel()` is now already generating a stacktrace. It's also a simpler interface.

**Comment by ejona86** [comment]
We should allow someone to provide their own exception, because that can have additional cause information.

**Comment by zhangkun83** [comment]
OK. I will do `cancel(String, Throwable)`. I would avoid passing Status or StatusException and asserting it's `CANCELLED` in the implementation, because if the user does pass a non-CANCELLED Status, he may not notice it until the application runs into the situation where `cancel()` is called.

**Comment by zhangkun83** [comment]
Had discussions with @ejona86, @louiscryan and @carl-mastrangelo. Here are the options we have considered:
 1. `cancel(Status)`: can be either confusing (if allowing non-CANCELLED status) or repetitive (if restricted to CANCELLED status).
 2. `cancel()` always generates stack trace: convenient but the cost of generating stack traces every time is concerning.
 3. `cancel()` generates stack trace if log level is `FINE` or a system property is set: less useful if not on by default.
 4. `cancel(String)`: generally useful with little performance impact, though not as useful as Throwable. We could later add stack trace generation that is controlled by log level for cases where a string message is not enough.

@louiscryan, @carl-mastrangelo and I think `cancel(String)` is the best choice. We also agree on deprecating `cancel()` and eventually delete it. The deprecation should go into 0.14.0 so that the actual deletion can happen in 1.0.

**Comment by zhangkun83** [comment]
Talked with @ejona86 and @louiscryan, we agreed upon having `cancel(String message, Throwable cause)`. Both of them are nullable, but we will discourage people from calling `cancel(null, null)` by log a warning (info before `cancel()` is deleted) with a stack trace. The Throwable is always wrapped as the cause of the resulting CANCELLED status.
