### ISSUE TITLE
Custom Serialization [question]

### ISSUE THREAD

**Issue by bobymicroby** [grpc/grpc-java#1240]
Hello guys,

Do you think that it is feasible using the current codebase, to avoid using protocol buffers and switch to another serialization mechanism? If so, can you point me to the places where one should do it ? 

Regards, B.

**Comment by buchgr** [comment]
Yes, the grpc protocol does not require protobuf. However, for non protobuf serialization formats you won't have the comfort of code generation. You want to have a look at [MethodDescriptor](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/MethodDescriptor.java), [MethodDescriptor.Marshaller](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/MethodDescriptor.java#L116) and [Channel](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/Channel.java#L60).

What you need to do is implement a `Marshaller` for your serialization format. Then for each method you create a `MethodDescriptor` and pass your own `Marshaller` to it. In order to call a method one simply passes his `MethodDescriptor` object to `Channel.newCall(methodDescriptor, CallOptions)`. You create the `Channel` just as you would when using protobuf. 

In order to understand this better, I would recommend you to play around with one of our examples. There have a look at one of the generated stubs - they are really just a simple wrapper around the concepts I mentioned before. The [helloworld](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/helloworld) example seems like a good place to start.

**Comment by bobymicroby** [comment]
Thanks a lot for the quick answer. I will have a look.

**Comment by buchgr** [comment]
@bobymicroby The recent discussion in https://github.com/grpc/grpc-java/issues/1196 might also be of interest for you. 

Also the `hello world` example stub can be found in ./examples/src/generated/main/grpc/io/grpc/examples/helloworld/GreeterGrpc.java once generated.

I ll close this issue for now. Feel free to open a new one if you encounter any problems along the way.
