### ISSUE TITLE
Exception when configuring SSL: "Jetty ALPN/NPN has not been properly configured." (and possible solution)

### ISSUE THREAD

**Issue by gubby** [grpc/grpc-java#1311]
I am unable to configure an SSL gRPC.

```
SslContextBuilder sslBuilder = GrpcSslContexts.forServer(new File("a"), new File("b"))
sslBuilder.build();
```

Causes this exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
        at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:143)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:120)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:109)
        at io.grpc.netty.GrpcSslContexts.forServer(GrpcSslContexts.java:90)
```

I think the root cause is here:
```
/**
   * Indicates whether or not the Jetty ALPN jar is installed in the boot classloader.
   */
  static boolean isJettyAlpnConfigured() {
    try {
      Class.forName("org.eclipse.jetty.alpn.ALPN", true, null);
      return true;
    } catch (ClassNotFoundException e) {
      return false;
    }
  }
```

This method is restricting the search to the *boot* classloader, which I don't think is correct. i.e. in the following code, the first line executes fine, but the second line throws CNFE (despite the class being loaded), causing `isJettyAlpnConfigured()` to return false:

```
System.out.println("Class loaded? " + org.eclipse.jetty.alpn.ALPN.class);
System.out.println("Maybe not: " + Class.forName("org.eclipse.jetty.alpn.ALPN", true, null));
```

I suspect the `Class.forName(String)` variant should be used instead (which doesn't throw CNFE), but maybe there was some good rationale for restricting to the boot classpath?

FWIW I am using alpn-api-1.1.2.v20150522.jar with the following other deps:
grpc-all-0.9.0.jar
hpack-0.10.1.jar
netty-all-4.1.0.Beta6.jar
okhttp-2.4.0.jar
okio-1.6.0.jar
protobuf-java-3.0.0-beta-1.jar

**Comment by nmittler** [comment]
@gubby did you set up the boot classpath? https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-jdk-jetty-alpnnpn

**Comment by ejona86** [comment]
@gubby wrote:
> This method is restricting the search to the boot classloader, which I don't think is correct.

Actually, it is correct. Jetty ALPN _replaces_ certain SSL classes in the JDK, and it has to be in the bootclasspath to do that. Yeah, that's a bit icky, but it can get the job done.

Note that since grpc-java v0.9 we are encouraging using netty-tcnative instead of Jetty ALPN. netty-tcnative uses OpenSSL via JNI. See the SECURITY.md file that nmittler linked to for details.

**Comment by gubby** [comment]
Hmm, I didn't see the security page, but that makes more sense.

But this seems like a shame, unless I misunderstood, it seems like to use gRPC with SSL one needs to either:

1. Configure the boot classpath on the JVM of every user of the RPC client library being built, or
2. Install a package onto the operating system on every host the client/server are deployed.

This means it's nearly impossible to just ship a client library JAR built on gRPC, and incorporate it into another project, since that project would need to modify their JVM args or install OS packages.

I'll upvote the OpenJDK bug, but is there no workaround that one can do to make a client library built on gRPC more distributable?

**Comment by ejona86** [comment]
Yes, it is a shame. ALPN is the bane of HTTP/2 development at present. We've already increased the ease _dramatically_, but yes, it still isn't as easy as native Java. Application authors are reasonably served, but things aren't seemless for Java libraries. Some important Google libraries are to use gRPC, so there is pressure from multiple directions to make the process easy.

There is general work on some improvements: static linking of OpenSSL or BoringSSL, which solves point 2; and a tcnative [Jumbo JAR](https://github.com/netty/netty-tcnative/issues/24) that contains binaries for common OSes. The Jumbo JAR work stalled, but gRPC-java is actively pushing forward static-linking.

**Comment by ejona86** [comment]
The page I was referencing was [SECURITY.md](https://github.com/grpc/grpc-java/blob/master/SECURITY.md).

**Comment by gubby** [comment]
Agreed, this was me not reading the SECURITY.md page properly.

Is there a way I can contribute to make this easier for end users? You mentioned a Jumbo JAR, presumably (depending on licensing) one implement a native library hack whereby on startup something spits out an openssl .so/.dll (etc) to /tmp and then loadLibrary() from there?

**Comment by ejona86** [comment]
@gubby, the hack you mention is already in place with tcnative. The Jumbo JAR idea is to include multiple .so/.dll so that on startup tcnative could choose the one that is appropriate for the platform. If that interests you might take a look at [the issue for it](https://github.com/netty/netty-tcnative/issues/24).

Combined with static linking it would greatly improve deployment ease, at some expense for binary size.

**Comment by aditya2007** [comment]
I have tried, for longtime with so many solutions and finally, the final solutions works for me.

Solutions:

=========

1.       As suggested by google, use jetty container instead of tomcat, this solution works, but in our production, applications deployed on tomcat container. – No from team

2.       On debugging the gRPC code, found that guava version causing the issue, updated the guava version 18.0, (where in some classes missed in previous versions) , solved the problem , but failed while deploying in CF

3.       Customized emebed-tomcat-core, and it works fine consistently – but team say no to custom tomcat container.

4.       Java –jar apm-asset-xxxx.jar – works fine locally, but need to provide a custom command to CF start, didn’t have luxury to change the CF start process.

5.       Finally, trick, the class loader to use tcnative-boring-ssl, library instead of tomcat-core library at runtime, by providing the following dependency in pom.xml. From past 3 days, this solution is working CF.

 

  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.hibernate</groupId>
            <artifactId>*</artifactId>
        </exclusion>
        <exclusion>

            <groupId>org.apache.tomcat.embed</groupId>

            <artifactId>tomcat-embed-core</artifactId>

        </exclusion>

    </exclusions>

 </dependency>

<dependency>

    <groupId>org.apache.tomcat.embed</groupId>

    <artifactId>tomcat-embed-core</artifactId>

    <scope>provided</scope>

</dependency>

**Comment by qiang-dai** [comment]
This is my way:
1. Edit catalina.sh
2. At line 103, add the following
`CATALINA_OPTS="-javaagent:/Library/Tomcat/lib/jetty-alpn-agent-2.0.6.jar"`
3. Restart tomcat
`../bin/shutdown.sh
../bin/startup.sh`

**Comment by prayagupd** [comment]
For non-tomcat app, I [could make it work](https://github.com/upd-machine/nlu-pipeline/issues/1) with `-javaagent` on CentOS. For some reason does not require `jetty-alpn` on MacOS.

```bash
wget http://central.maven.org/maven2/org/mortbay/jetty/alpn/jetty-alpn-agent/2.0.7/jetty-alpn-agent-2.0.7.jar

/home/prayagupd/jdk1.8.0_161/bin/java -jar 
-Djavax.net.ssl.keyStore=/home/prayagupd/keystore/keystore.jks 
-Djavax.net.ssl.keyStorePassword=password 
-Djavax.net.ssl.trustStore=/home/prayagupd/keystore/truststore.jks 
-Djavax.net.ssl.trustStorePassword=password 
-javaagent:jetty-alpn-agent-2.0.7.jar nlu-intent-toolkit.jar test-agent "music venues near me?" credentials.json
```
