### ISSUE TITLE
Error in java grpc files generated by compiler

### ISSUE THREAD

**Issue by JoostvDoorn** [grpc/grpc-java#1333]
I am generating protocol buffer code with the following command:
```
protoc --plugin=protoc-gen-grpc-java=/path/to/grpc-java/compiler/build/binaries/java_pluginExecutable/protoc-gen-grpc-java --grpc-java_out=/path/to/testproject/src/ --java_out=/path/to/testproject/src/ --proto_path=/path/to/testproject/protoc/ /path/to/testproject/protoc/Protofile.proto
```
I get the following error in Intellij.
```
Error:(29, 66) java: cannot find symbol
  symbol:   method parser()
  location: class Test.Protofile.B
Error:(30, 66) java: cannot find symbol
  symbol:   method parser()
  location: class Test.Protofile.C
Error:(84, 37) java: callOptions has private access in io.grpc.stub.AbstractStub
Error:(84, 11) java: channel has private access in io.grpc.stub.AbstractStub
Error:(108, 37) java: callOptions has private access in io.grpc.stub.AbstractStub
Error:(108, 11) java: channel has private access in io.grpc.stub.AbstractStub
Error:(133, 37) java: callOptions has private access in io.grpc.stub.AbstractStub
Error:(133, 11) java: channel has private access in io.grpc.stub.AbstractStub
```
Protofile:
```
syntax = "proto2";
package Test;

service A {
  rpc A (B) returns (C) {}
}
message B {
  repeated double field_a = 1;
  repeated double field_b = 2;
}
message C {
  repeated double field_a = 1;
  repeated double field_b = 2;
}
```
The dependencies I use are:
grpc-all-0.9.0, guava-18.0, protobuf-java.3.0.0-beta-2 (I also tried guava-19 and beta 1)

Also see the generated files:
https://gist.github.com/JoostvDoorn/c69f14a485144276545b

```
uname -a
Linux joost-EX58-UD5 3.11.0-19-generic #33-Ubuntu SMP Tue Mar 11 18:48:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```

**Comment by alugowski** [comment]
Just a guess:

> syntax = "proto2";

proto2 and proto3 are incompatible. GRPC uses proto3.

**Comment by JoostvDoorn** [comment]
From the documentation:
> In general, while you can use proto2 (the current default protocol buffers version), we recommend that you use proto3 with gRPC as it lets you use the full range of gRPC-supported languages, as well as avoiding compatibility issues with proto2 clients talking to proto3 servers and vice versa.

**Comment by ejona86** [comment]
@JoostvDoorn, hmm... I see parser() in both protobuf 3.0.0-beta-1 and beta-2, both proto2 and proto3 syntax. However, looking at the gRPC-generated code, it looks like you are using an older `protoc-gen-grpc-java` (pre-v0.9.0). [Update it to v0.9.0](http://search.maven.org/#artifactdetails%7Cio.grpc%7Cprotoc-gen-grpc-java%7C0.9.0%7CN%2FA) and the "has private access" errors will definitely go away. Could you report back if that fixes the "cannot find symbol" issue too?

@alugowski, proto2 syntax is definitely supported by grpc-java. proto3 protobufs are compatible with proto2. The opposite is also true, but at reduced fidelity because proto3 will provide less information after parsing, like field presence, and doesn't permit specifying default values, etc.

**Comment by JoostvDoorn** [comment]
@ejona86 Thanks, this seems to fix all the issues I have with the example. I did notice another thing that having the same name for the proto file as the package name does generate problems.
