### ISSUE TITLE
can put the service instances on different ports?

### ISSUE THREAD

**Issue by zhongql** [grpc/grpc-java#1344]
i want to  create  gRPC server in python with client in java , and start up multiple service instances on different ports, can  it work ? and the client how to support  different ports ?

**Comment by ejona86** [comment]
Generally we would expect you to run multiple services on the same port, as long as they are in the same process. But yes, there is an issue with python: grpc/grpc#4418.

For dealing with multiple ports in Java, instead of doing:
```java
ManagedChannelBuilder.forTarget("somehost")
```

Just do:
```java
ManagedChannelBuilder.forTarget("somehost:1234")
```

Where 1234 is the appropriate port number you want to connect to.

**Comment by zhongql** [comment]
Oh, so great , but the  ManagedChannelBuilder.forTarget is a ExperimentalApi, temporarily can't use ?

**Comment by ejona86** [comment]
Oh, you're right, it is still experimental. Honestly, that particular API is unlike to change much. But there is also 'ManagedChannelBuilder.forAddress(String name, int port)' which is stable.

**Comment by zhongql** [comment]
ok, thank you very much
