### ISSUE TITLE
../gradlew java_pluginExecutable fatal error

### ISSUE THREAD

**Issue by ouyangkongtong** [grpc/grpc-java#1346]
hi，
environment：
java version "1.7.0_79"
Mac OS X 10.10.5
Gradle 2.10
protobuf version 3.0

I have configured  'export CXXFLAGS="-I/usr/local/protobuf-3.0.0-beta-2/include" LDFLAGS="-L/usr/local/protobuf-3.0.0-beta-2/lib"'  in the ~/.bash_profile file：
![image](https://cloud.githubusercontent.com/assets/2417403/12542025/e1651226-c358-11e5-8e2e-1b47abb5f1e9.png)

fatal error info：
![image](https://cloud.githubusercontent.com/assets/2417403/12542009/a3147426-c358-11e5-824b-372b87881a66.png)

**Comment by ejona86** [comment]
Just in case you aren't aware, building the plugin is generally not necessary since we have releases of the plugin binary on Maven Central and you can build gRPC itself with -PskipCodegen=true (see the first section of [COMPILING](https://github.com/grpc/grpc-java/blob/master/COMPILING.md)).

I'm not sure why it can't find the header. Can you verify that the file `/usr/local/protobuf-3.0.0-beta-2/include/google/protobuf/io/zero_copy_stream.h` exists? If not, you may need to re-try the `make install` of protobuf.

Also, later, if you have trouble with actually running the protoc binary, depending on how you compiled you may need `LD_LIBRARY_PATH=/usr/local/protobuf-3.0.0-beta-2/lib`

**Comment by ouyangkongtong** [comment]
1、It has been based on [COMPILING](https://github.com/grpc/grpc-java/blob/master/COMPILING.md) setting
2、I verify that the file `/usr/local/protobuf-3.0.0-beta-2/include/google/protobuf/io/zero_copy_stream.h ` exists
![aa8bb8bf-24de-421f-b10a-463654e24af6](https://cloud.githubusercontent.com/assets/2417403/12585263/2a830124-c486-11e5-95c6-3fd336371c5d.png)

3、i add setting `LD_LIBRARY_PATH=/usr/local/protobuf-3.0.0-beta-2/lib` ，run ` ../gradlew java_pluginExecutable` is error

![image](https://cloud.githubusercontent.com/assets/2417403/12585599/b855394e-c487-11e5-9f69-1b1506c1de68.png)


4、setting `skipCodegen=true` in gradle.properties file - 
run ` ../gradlew java_pluginExecutable`  ，error info:
![image](https://cloud.githubusercontent.com/assets/2417403/12585289/5b959948-c486-11e5-81aa-6707147df5f0.png)

no setting `skipCodegen=true` in gradle.properties file 
run ` ../gradlew java_pluginExecutable`  ，error info
![error info](https://cloud.githubusercontent.com/assets/2417403/12542009/a3147426-c358-11e5-824b-372b87881a66.png)

**Comment by ejona86** [comment]
The point of `skipCodegen=true` is to _avoid_ building `java_pluginExecutable`. When using `skipCodegen=true` you would just try to build grpc as a whole with `./gradlew build`.

I think I see the problem though. In the most recent screenshot of your `.bash_profile` I see two lines at the end:
```sh
export CXXFLAGS="-I/usr/local/protobuf-3.0.0-beta-2/include" LDFLAGS="-L/usr/local/protobuf-3.0.0-beta-2/lib"
export CXXFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"
```

That last line will overwrite variables set on the protobuf line. Instead, you need something like:
```sh
export CXXFLAGS="$CXXFLAGS -I/usr/local/include" LDFLAGS="$LDFLAGS -L/usr/local/lib"
```

**Comment by ouyangkongtong** [comment]
That is the question，setting `CXXFLAGS `、`LDFLAGS ` question.
thanks @ejona86 ~~~
