### ISSUE TITLE
Access unparsed data in interceptor?

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#1403]
I'd like to make a caching interceptor that uses the raw binary of the message as a key, and the raw binary of a response as the value so that I can avoid any ser/der costs on the server.  Is it possible to get access to the InputStream that goes through the Listener before it calls "call.method.parse(inputStream)" ?

Maybe there's a different/better way to do this and avoid serialization costs?  I suppose I could use a header approach and have a server interceptor look for a "CacheKey" header and use that for lookup.  It requires a bit more cooperation from the client though which I'd like to avoid if possible.

Thanks for any pointers!

**Comment by carl-mastrangelo** [comment]
Not ideal, but could you put the caching logic in the MethodDescriptor?  I believe you can hook the InputStream -> ReqT conversion logic there.  Would that work?

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/MethodDescriptor.java#L55

**Comment by jhspaybar** [comment]
I had considered that, but it seems that the ServerCallImpl gets instantiated with a MethodDescriptor I can't modify to swap out the marshaller.  I suspect I'd either need to change code-gen to plug in my marshaller very early, or use reflection in an interceptor to change the private field holding the MethodDescriptor in the ServerCallImpl.  Maybe as an aside, it's possible for an interceptor to rewrite the call object you pass down stream, but it doesn't have access to the ServerStream that gets passed into the ServerCallImpl.  Is there maybe an API/abstraction here to provide a ServerCallFactory to the ServerBuilder, or potentially expand the interface of a "ServerCall" to provide access to the underlying stream objects?  I'd be happy to discuss more if this is something that should potentially exist.

**Comment by carl-mastrangelo** [comment]
@ejona86 have any ideas on how this could be accomplished?

**Comment by ejona86** [comment]
I think you are forced to ditch normal server interceptors and instead modify the `ServerServiceDefinition` directly. `ServerInterceptors` does modify the definition when calling `intercept()`, but it isn't powerful enough to let you modify the `MethodDescriptor`. You don't need to do any hacks luckily. Instead, you just process the returned definition from `YourServiceGrpc.bindService()` before it is passed to `ServerBuilder.addService()`. As an example, you can take a look at `ServerInterceptors` itself.

Your modified definition would use a `byte[]`- or `InputStream`-based `MethodDescriptor` (so you'd write a fairly trivial `Marshaller`) which would provide the bytes to a handler you make. If the bytes are a cache hit, the handler will process the entire call. If the bytes aren't, then you can use the original `MethodDescriptor` to deserialize the bytes into an object and pass that object to the real handler. You shouldn't need to do any casting or fake the generics (although it may require generics tricks like creating additional methods just to convert `?`s to some `T`, as is done with `ServerInterceptors.wrapAndAddMethod()`).

I hope you're able to follow that. If not, I can make a more concrete code sample.

**Comment by jhspaybar** [comment]
That does actually make sense!  Thanks for the detailed explanation.  I'd been looking at ServerInterceptors quite a bit already and saw it was modifying stuff...and just didn't put it together, so thanks for hitting me over the head with what should have been obvious. :)

**Comment by jhspaybar** [comment]
I should also ask, if I end up making something like a `MethodDescriptorInterceptors` that operates sort of like a `ServerInterceptor` but allows for an earlier interception(like possibly to allow for a different serialization format like flatbuffers, or grpc-json) is it something I should at least open a PR for to get a discussion going?

**Comment by ejona86** [comment]
@jhspaybar, possibly. I'm not quite sure how useful the feature is in general. I would mainly hope that the API is relatively small and that we figure out other use-cases. If it is primarily just this one use-case, I think I'd prefer a utility that just tries to help with caching. If it's easy to open a PR though, we can take a look at the code and try to figure out where to go from there.

I'm not as wild about using it for alternative serialization formats. I'd like to have a better understanding of a complete design for alternative formats first, really. I also think that we should have better support than using a super-interceptor. I don't think there isn't enough information available to implement alternative formats at runtime. That may change once we have server reflection support, though.

**Comment by ejona86** [comment]
@jhspaybar, I think I know the rough API I'm leaning toward, if you want to send a PR. In ServerInterceptors, a `byteIntercept(ServerServiceDefinition, ServerInterceptor... interceptors)` method (and I guess a `List<? extends ServerInterceptor>` counterpart). The docs would mention that the type of both requests and responses passed through the interceptors would be `InputStream`, but the interceptors themselves would have to cast to `InputStream`.

We could have a separate interface for these types of interceptors that we know will be passed a `Call<InputStream, InputStream>` instead of `<ReqT, RespT>`, but I'm not sure if it beneficial to do so (I'm on the fence about it).

This API would be specific to accessing the raw bytes of messages, but it makes doing so fairly straight-forward and I've not really been able to think of very many use-cases for a more advanced API.

If there is a need for reduced overhead, a future enhancement could add support for `mark()` on the `InputStream` so that your interceptor could calculate the hash and then just reset the `InputStream` if there is a cache miss.

**Comment by jhspaybar** [comment]
@ejona86 Sure, I'll take a poke at something like what you've described and try to get something put together within a couple days.  

Another thing to keep in mind here, since I think we're getting very close to it is that serialization could happen in interceptors as well.  The API goes downhill from a type safety perspective, but if the input/output was just passed as an Object and started as a raw InputStream and relied on an interceptor to then convert it to a real type before passing it down the chain and eventually to a server method invocation, it would be possible to accomplish what I'm after(raw byte access) as well as allow for other serialization formats.  A different serialization format would be just an interceptor at the end of the chain, and you could even support multiple serialization formats through a content/accepts style header where the interceptor just doesn't do anything but forward if the message was sent as a different content type.  You'd want to code-gen these interceptors, and it's potentially 1 extra installation step when starting the server as well.

Maybe that's a bit too far since it would modify existing interfaces, but it would at least unify all this behind the same abstraction of an interceptor.

**Comment by ejona86** [comment]
My main problem with using it for other formats is that the Server implementation will be expecting Protobufs. Yes, you could convert JSON bytes -> Protobuf objects (which could be quite natural if using JSON-encoded Protobuf), but for something like flatbuffers that sort of defeats the point.

For the JSON protobuf case, yes, that could work and be quite helpful. However, it also feels like a bit of a hack. I'd prefer seeing something like a more-powerful Marshaller that is provided some additional content-type information for it to know to decode JSON instead of binary Proto. But maybe that doesn't work out. Meh.

I feel like we should just design alternative format support. If it this super-interceptor is used for it, so be it. But I'd rather not add the super-interceptor speculating that it could be used for alternative formats.

**Comment by ejona86** [comment]
Fixed by #1422
