### ISSUE TITLE
Name resolution failures can cause the call to hang.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1407]
If an exception is thrown from NameResolver.Listener.onUpdate(), the call hangs indefinitely and is never closed.  This is a problem if the actual name resolution succeeds, but is not successfully set.

**Comment by zhangkun83** [comment]
The only known case so far (#1657) is because channel didn't expect empty address lists from NameResolver. This is actually a hole in the NameResolver interface, where handling for _empty list_ is not defined.

I am going to fix the hole in the interface, by documenting and enforcing that giving out an empty list will be treated as an error. After that, I won't expect `onUpdate()` to throw. Throwing from `onUpdate()` will be a bug. I slightly prefer such bug to be annoying enough so that users are motivated to report, other than catching the exception and possibly recover later.
