### ISSUE TITLE
different grpc components depends on the same dependencies but of different versions

### ISSUE THREAD

**Issue by saturnism** [grpc/grpc-java#1421]
This looks quite unsafe.
```
Dependency convergence error for com.google.code.findbugs:jsr305:3.0.0 paths to dependency are:
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-core:0.12.0
      +-com.google.code.findbugs:jsr305:3.0.0
and
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-auth:0.12.0
      +-com.google.auth:google-auth-library-oauth2-http:0.3.0
        +-com.google.http-client:google-http-client:1.19.0
          +-com.google.code.findbugs:jsr305:1.3.9

[WARNING] 
Dependency convergence error for com.twitter:hpack:v1.0.1 paths to dependency are:
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-netty:0.12.0
      +-io.netty:netty-codec-http2:4.1.0.Beta8
        +-com.twitter:hpack:v1.0.1
and
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-netty:0.12.0
      +-com.twitter:hpack:0.10.1

[WARNING] Rule 1: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for com.google.code.findbugs:jsr305:3.0.0 paths to dependency are:
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-core:0.12.0
      +-com.google.code.findbugs:jsr305:3.0.0
and
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-auth:0.12.0
      +-com.google.auth:google-auth-library-oauth2-http:0.3.0
        +-com.google.http-client:google-http-client:1.19.0
          +-com.google.code.findbugs:jsr305:1.3.9
, 
Dependency convergence error for com.twitter:hpack:v1.0.1 paths to dependency are:
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-netty:0.12.0
      +-io.netty:netty-codec-http2:4.1.0.Beta8
        +-com.twitter:hpack:v1.0.1
and
  +-io.grpc:grpc-all:0.12.0
    +-io.grpc:grpc-netty:0.12.0
      +-com.twitter:hpack:0.10.1
```

**Comment by ejona86** [comment]
I expect the hpack conflict to not cause any problems today. In addition, Netty in CR1 (the current version we are using) has forked hpack internally, and I've noticed we no longer directly use hpack in gRPC so I'm removing the dependency (in #1430).

The jsr305 dependency is for annotations. google-http-client should probably be updated to a newer version; I just tried compiling the library with the newer version without trouble.

In general, different libraries depending on different versions will happen, and except for io.netty, that shouldn't cause trouble.

**Comment by ejona86** [comment]
I filed google/google-http-java-client#320 for the jsr dependency.

**Comment by saturnism** [comment]
Thanks. I understand that usually this type of dependency conflicts aren't an issue, but it also can cause havoc. Some projects, like Spring, enforces dependency convergence. gRPC dependency will fail in that case.

In addition to have the dependent library to be brought up to speed for the jsr dependency, I highly recommend gRPC pom.xml exclude the old version from its dependency tree and keep the new version only.

**Comment by saturnism** [comment]
and for the comment above, i suggest reopen this :) and exclude jsr305 from google-http-client so that it only uses the jsr305 dependency from grpc-core .

**Comment by ejona86** [comment]
Excluding the dependency seems counter-productive. We want whatever the latest version is, which is the default behavior of Maven. If google-http-client _requires_ a newer version, then I don't want to accidentally leave in the exclusion and break it.

Keeping all the versions _identical_ seems a non-goal and not worthwhile. If Spring wants to enforce that, they can go for it, but it doesn't seem like a generally appropriate approach. Is there some blog or documentation that could convince me otherwise?

Based on a skimming of [Maven's docs](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html), it seems using exclude for jsr305 isn't the intended purpose of exclude.

**Comment by saturnism** [comment]
https://dzone.com/articles/dependency-convergence-maven

**Comment by ejona86** [comment]
I remain unconvinced. However, I did learn that Maven uses "nearest" for choosing the version of a dependency, which is unsettling. Maven is the only package manager I know of that doesn't use "greatest version". That leads me to find the enforcer's requireUpperBoundDeps _quite_ useful, and I would gladly try to address any issues it finds because it would be detecting actual problems. And from what I can tell, the problem discussed in the blog post should either be solved by jersey using [version] syntax between its components or would be detected by requireUpperBoundDeps (it's a little unclear what was actually the problem). In light of that, I've created #1459 in order to version-pin grpc-core to prevent accidental mixing of versions.

I still don't find much value in DependencyConvergence because it seems buggy to maintain and like a fool's errand in most applications. I fully expect any overrides we add will be forgotten and not re-verified as we update the versions of our dependencies, so it could fix bugs in the short-term but cause them in the long-term. Most applications I would expect to have a very long list of failures that would be a pain to manage, and the blog post lets on a bit of the trouble: 
> if the output from the DependencyConvergence rule looks anything like mine does presently, it might take you a while before you get around to getting your maven build to pass and conform to other rules.

I simply don't expect most applications have much to gain by using DependencyConvergence. I feel most problems would be found using requireUpperBoundDeps. Although DependencyConvergence could be useful when debugging a problem.

**Comment by saturnism** [comment]
+1 to version pin. you mentioned version pin grpc-core, can we also version pin netty?

DependencyConvergence is not a fool's errand. It is fully utilized in Spring and it does avoid unexpected issues.

A component library, like gRPC, is responsible to understand the exact dependency version requirements. Leaving this to chance and/or other dependent libraries is more error prone.

No Spring Boot applications have long list of failures, because it's already strictly enforced. Again, it's up to the component library themselves to be a good citizen to make sure it includes the right versions it depends on.

**Comment by ejona86** [comment]
Added a comment to pin netty version to #1459.

> A component library, like gRPC, is responsible to understand the exact dependency version requirements.

The problem is that Maven does not provide a way to do that. The version range would be a solution to that, except that we can no longer suggest a version to use, the actual version used will be re-chosen every day, and in general we will need an open upper-bound. That means in practice we can no longer suggest a version that is known to work well and when a new version comes out of a dependency our users have the version they use change out from underneath them.

> Leaving this to chance and/or other dependent libraries is more error prone.

We already provide the version we recommend. Anything other than that one version is unknown. And it should be unknown since our dependencies will release new versions after we release our version. Most of the time updating to the new version is fine, but there could be problems. And if there are problems we can only fix it by doing a new release, even if the "fix" is to specify a more precise version range.

Maven and Gradle also do not provide aid to avoid leaving it up to chance. I'm thinking along the lines of: compile and test with the oldest and newest of each library within a specified range. Because the tooling is not there and the dearth of projects using version ranges, it seems almost every time you include multiple libraries that share dependencies DependencyConvergence would break. And on each update of said libraries it would break. And if you had overridden a version of one library and it now required a newer version but you had already overridden it so Maven doesn't given you an error, it would break. DependencyConvergence seems worse than the problem, especially since requireUpperBoundDeps doesn't seem broken in the same way.

**Comment by saturnism** [comment]
agreed on version range. if versions follow the semver practice, we can assume at least major.minor, and and not worry about revisions. :)
