### ISSUE TITLE
Create a grpc-api artifact

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1447]
After #1446 we could make a grpc-api artifact that does not include `io.grpc.internal`. From the other issue:

> It would be useful to be able to depend on the API but not the implementation to not pull in unnecessary dependencies and provide cleaner builds that don't accidentally depend on the implementation. For instance, a library could have optional gRPC support, but depend on grpc-api even when grpc was not selected.

**Comment by carl-mastrangelo** [comment]
Unscheduling, since there hasn't been demand to it.

**Comment by adriancole** [comment]
I would ask for this to change. Notably now the armeria project supports gRPC directly, and I'm told others do as well. For reasons including not knocking around gson or other versions, plus the <1.0 telemetry apis.. seems a valid time to reconsider extracting this before more deps are added.

**Comment by anuraaga** [comment]
This is cool and would definitely simplify implementation of the grpc wire format in armeria :)

Just want to add a note based on what I experienced while working on this, is that both grpc and armeria do seem to tie wire-format handling to the threading model of the server. I felt this while working on https://github.com/line/armeria/pull/1600 I was surprised to see how much more complex wire-format handling became in grpc-java to support thread models since the first time I examined it, but somewhat unhappily implemented similar in armeria too. I think this issue doesn't exist in other languages like Go and Javascript which only have a single threading model.

Just food for thought and to keep it on record - a generic wire format library for Java would be really awesome but will probably not be trivial.

**Comment by ejona86** [comment]
@anuraaga, if you require users to run on the event loop then things could be a lot easier :). But experience has shown us that most users can't be trusted to run on the event loop, and they can't even be trusted to debug the issues they cause when they block the event loop.

Part of the trouble is there is no standard thread/work model in Java. Some things are blocking, some things spawn a new thread each request, some things are async via futures, some things are async via Rx. That's not a problem in Go and Javascript because they have a strong language convention already: Go uses new goroutines per RPC and Javascript uses callbacks on a single thread. I will say that Go requires some work to get good performance, and in Javascript you are basically accepting you don't care about performance.

I'm okay with others re-implementing the wire format. The format itself is fairly easy (although I would agree streaming compression requires a lot of work in Java); most of the complexity comes from threading and flow control, at which point things become more opinionated.

**Comment by anuraaga** [comment]
Yeah it sounds like we're saying the same thing :) 

I probably misinterpreted the intent of this issue since we're talking about extracting utilities related to the wire format itself in the other issues. If it's only to split off an artifact for the `internal` package here, it might not help with the transitive dependency issue @adriancole is worrying about (AFAICT the original post seems to be more concerned with the bytes of the grpc-core jar than transitive deps).

**Comment by adriancole** [comment]
definitely interested in transitive deps problem and any core dep on <1.0
lib as we know that causes problems. I probably spend more time on guava
compat issues than needed. best way to not break people for silly things
like checkArgument is to not depend on something that could. also if a tool
is optional in maven it should be set to optional to not drag in things
that are more byte concerns. the api jar can solve some of this.

anyway I am also interested in the conversation you are having.
