### ISSUE TITLE
Losing messages in 0.13.0

### ISSUE THREAD

**Issue by trask** [grpc/grpc-java#1455]
I've posted a repro to https://github.com/trask/grpc-lost-msgs-repro.  Just clone and run `mvn test`.

The repro sends 1000 messages to the server, but the server only ever sees around 30 of them (I'm running locally on windows, though I also see this issue on travis-ci linux).

I don't see this issue in 0.12.0.

**Comment by ejona86** [comment]
I think I may have fixed this on Friday. Could you try with the v0.13.x branch that has 103d3d17? I've published v0.13.1-SNAPSHOT you can use if you add [our snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/) or you can use `./gradlew install -PskipCodegen` to build a snapshot directly on your machine. Note that master is still broken.

I was planning on making a new release on Monday and at the very least sending out a notification to the list.

I'm quite disappointed by this bug because we were notified of it but didn't piece it together that we were impacted. We were unable to update to netty CR2 before the release due to #1398. On Friday netty CR3 was released, which is what master will be fixed with on Monday.

**Comment by trask** [comment]
I'm not seeing the issue anymore with the snapshot. Thanks.

**Comment by ejona86** [comment]
@trask, thanks for testing and thanks for your exceptional bug reports. I'm sorry to have caused you the trouble in reproducing the bug. I spent a reasonable amount of time tracking down the issue myself, so I know it can be quite time and thought-intensive.

**Comment by trask** [comment]
No problem, thanks for getting to the bottom of it.
