### ISSUE TITLE
*Interceptor interceptForward methods?

### ISSUE THREAD

**Issue by jhspaybar** [grpc/grpc-java#1470]
Would you be open to a pull request which allows users to pass in interceptors in forward order?  Meaning, if I pass in ServerInterceptors.interceptForward(svc, new A(), new B(), new C()) that I'll end up with interceptors being called in the order A -> B -> C rather than C -> B -> A?

**Comment by ejona86** [comment]
Maybe. We used to do that order because it seemed most intuitive initially, but changed it because it was confusing when mixing separate calls (#570). Having a method named differently that does it in the opposite order seems like it could work, though.

@nmittler @zhangkun83 @louiscryan, thoughts, since y'all were part of the earlier discussion?

**Comment by nmittler** [comment]
Hmm ... maybe a more builder-style interface would help to clear up the ambiguity?

**Comment by ejona86** [comment]
After some discussion, we're still a bit on the fence. Having an additional method that does the opposite order is easy, but we also question if it improves the situation since it has its own gotchas. Maybe it would have been better to have not swapped the order, but it was all getting pretty confusing at the time.

Would you also want an `interceptForward()` in `ManagedChannelBuilder`?

We do think we could maybe improve the situation with some more documentation, but it does seem it will be a source of confusion.

**Comment by ejona86** [comment]
After some offline discussion, I'm on-board and nobody seems to be strongly against it. Let's add it.

`interceptForward()` works really well when you only have one call to it for the channel. I'm in favor of that over piece-meal installing of interceptors, and having them in the forward direction does ease the comprehensibility of that sort of code.

**Comment by jhspaybar** [comment]
Alright, I'll send a pull request later today.
