### ISSUE TITLE
why DEFAULT_FLOW_CONTROL_WINDOW in NettyServerBuilder set to 1048576?

### ISSUE THREAD

**Issue by makeyang** [grpc/grpc-java#1485]
in http2 doc, the max value of flow control window would be 2^31-1

**Comment by ejona86** [comment]
I'm not sure why you bring up the maximum of 2^31-1. The default in the http/2 standard is 2^16-1. For the connection it is discussed in section 6.9.2. For streams is discussed near `SETTINGS_INITIAL_WINDOW_SIZE` 

We are using 1 MiB instead of 64 KiB because the Netty transport is used in many places where the bandwidth-delay product is on the order of 1 MiB. My eventual hope is to auto-tune the window based on the network. Although we are playing with designs to do that, no implementation has started.
