### ISSUE TITLE
Doc Fixit: Java is missing from website Auth doc

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-java#1528]
Java is missing from this doc: http://www.grpc.io/docs/guides/auth.html

**Comment by ejona86** [comment]
We have some information at (SECURITY.md)[https://github.com/grpc/grpc-java/blob/master/SECURITY.md#enabling-tls-on-a-server]. That could be used as a basis for the auth.html docs

**Comment by hsaliak** [comment]
For java, I'd recommend we point to security.md from the website until we are clear that SECURITY.md would be stable for the foreseeable future. @ejona86 do we expect updates to SECURITY.md in the next 1-2 releases, especially around the recommended approach?

**Comment by ejona86** [comment]
@hsaliak, as of now, things particular things are stable; I have little concern with copying them.

**Comment by hsaliak** [comment]
Thanks! 
@LisaFC  would you be able to give this a shot?

**Comment by LisaFC** [comment]
Sure, will do that today and you and @ejona86 can review the PR for truthiness.

**Comment by LisaFC** [comment]
Couple of questions:

- Many of the other languages have scopeless credentials as the default approach for authenticating with Google, with using an OAuth2 token as a legacy approach, does Java just use scoped credentials for authenticating with Google?
- The existing doc has lots of information about all the stuff you need to install to use SSL/TLS but there's no example code (other than enabling TLS on the server side), do we have any? Would be good to show a snippet of client code making an authenticated call, corresponding to the other SSL/TLS examples.  I think I might leave the "what to install" stuff in the SECURITY.md, as we've generally been leaving installation details in the repo.

Also the structure of this doc is getting pretty unwieldy but a reorg is one of our objectives for GA docs...

**Comment by LisaFC** [comment]
Aaaaaanyone?

**Comment by ejona86** [comment]
> Many of the other languages have scopeless credentials as the default approach for authenticating with Google, with using an OAuth2 token as a legacy approach, does Java just use scoped credentials for authenticating with Google?

Using scoped credentials isn't required, but I don't know the times it works and doesn't work. It's not clear to me what the various other language examples do oauth-wise, especially since many just call `IsCreateScopedRequired` for the scoped case.

I think there may be some need to [convert to JWT](https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/AbstractTransportTest.java#L863), which could be automatic, but isn't. I don't know how that would mix with calls to like `IsCreateScopedRequired`.

> The existing doc has lots of information about all the stuff you need to install to use SSL/TLS but there's no example code

What sort of example code are you talking about? The equivalent of what sections in the grpc.io docs? I would have expected [the section I pointed to earlier](https://github.com/grpc/grpc-java/blob/master/SECURITY.md#enabling-tls-on-a-server) that shows server-side code would be what you would be looking for.

**Comment by LisaFC** [comment]
> Using scoped credentials isn't required, but I don't know the times it works and doesn't work.

Ok, we can leave the scoped example "as is".

> What sort of example code are you talking about? The equivalent of what sections in the grpc.io docs? I would have expected the section I pointed to earlier that shows server-side code would be what you would be looking for.

All the other examples in the auth doc have client-side code examples for SSL/TLS, showing providing credentials when creating a channel: http://www.grpc.io/docs/guides/auth.html#examples

Is there an appropriate equivalent in Java? (and, now that I think of it, I should check is there anything server developers need to do on the server side in the other languages...)

**Comment by ejona86** [comment]
> All the other examples in the auth doc have client-side code examples for SSL/TLS, showing providing credentials when creating a channel

Ah, no, unless you need to provide your own root CAs.

```java
// Base case - No encryption
ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 50051)
    .usePlaintext(true)
    .build();
GreeterGrpc.GreeterStub stub = GreeterGrpc.newStub(channel);

// With server authentication SSL/TLS
ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 50051)
    .build();
GreeterGrpc.GreeterStub stub = GreeterGrpc.newStub(channel);

// With server authentication SSL/TLS; custom CA root certificates; not on Android
ManagedChannel channel = NettyChannelBuilder.forAddress("localhost", 50051)
    .sslContext(GrpcSslContexts.forClient().trustManager(new File("roots.pem")).build())
    .build();
GreeterGrpc.GreeterStub stub = GreeterGrpc.newStub(channel);
```

The equivalent of the last example for OkHttp is a bit painful, and generally only helpful during testing on mobile. We do have [`TestUtils.newSslSocketFactoryForCa()`](https://github.com/grpc/grpc-java/blob/42d787288e17952ad6880479f57aeb8694ebc494/testing/src/main/java/io/grpc/testing/TestUtils.java#L238) that does the hard part, but I'm thinking we may just not mention OkHttp.

As a side note, we do support the "localhost:50051" syntax used by the other languages via `forTarget()` instead of `forAddress()`. However, when using host:port, I'd recommend using `forAddress()` since it handles some edge cases for you.

**Comment by LisaFC** [comment]
Thanks, that's very helpful! Will have PR with updated doc shortly....

**Comment by stanley-cheung** [comment]
Anything else for this issue?
