### ISSUE TITLE
Example of LoadBalancer implementation? 

### ISSUE THREAD

**Issue by thefallentree** [grpc/grpc-java#1551]
Hi,

Is there a example we can see how to createa and use an  LoadBalancer  ? It should be able to deal with usual error and some health checking/retry etc.

Thanks.

**Comment by ejona86** [comment]
The only "examples" are [SimpleLoadBalancerFactory](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/SimpleLoadBalancerFactory.java) and the half-finished [GrpclbLoadBalancer](https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/java/io/grpc/grpclb/GrpclbLoadBalancer.java). Client-side load balancing is pretty far along, but it isn't complete yet.

We have no support for retry at present. I expect we would try hard to make retry a feature of the core and not a feature of the LoadBalancer.

We are using the term "health checking" to be service monitoring, which we aren't going to implement in any of our client-side load balancers since it can cause a DDoS. We will be doing centralized health checking, but won't be open sourcing the server-side implementation.

There is keep-alive/ping which can monitor a TCP connection that we are discussing support for, and it would be built-in to the transports. We are still trying to mitigate the DDoS risk.

**Comment by doubler** [comment]
I have the same checking/retry problem when implementing a LoadBalancer.
I use an `List<EquivalentAddressGroup> addressGroups `with each EquivalentAddressGroup has different SocketAddress at position 0. And in pickTransport, `return tm.getTransport(addressGroups.get(counter.getAndIncrement() % addressGroups.size()));`

If all the servers are available, it acts like Round-Robin. While if any remote server service restart, it won't  be available unless all other servers can not connect.
I think if the `tm.updateRetainedTransports(addressGroups);` is implemented, the problem can be solved.

**Comment by ejona86** [comment]
Retry shouldn't be part of the LoadBalancer. For now, implement it as an interceptor or in the code calling the stub.

I don't understand the need for `updateRetainedTransports()`; that should only be necessary when routes change permanently, like when the name resolver returns an updated address. It's meant to remove address groups from tracking.

**Comment by doubler** [comment]
I think I miss understood with the `updateRetainedTransports()`
Looking forward to the "health checking" service.

**Comment by thefallentree** [comment]
What I mean "Retry" is really the transporting layer retry. We are seeing some pretty strange issue which I guess is the due to stream abrutply closed,  We need a reliable example on how to Close and Reopen Channel in a sane manner. 

Just like a conneciton pool

**Comment by ejona86** [comment]
You should have no need to close and reopen a channel, and we aren't very interested in making that easy. The Channel internals should be handling that without any LoadBalancer interaction.

**Comment by ejona86** [comment]
Closing this because I don't think we'll end up having an example, other than the other implementations LBs we have.
