### ISSUE TITLE
Can I get Request MetaData From Context in 0.13.2

### ISSUE THREAD

**Issue by Thinkfly** [grpc/grpc-java#1567]
How Can I get Request MetaData From Context in 0.13.2,Please Help me,Thank you.

**Comment by buchgr** [comment]
Hey @Thinkfly ! Check out the examples in https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/header . There, it's illustrated how to access metadata when using the stub api. 

For future questions, it's best to ask them on stackoverflow.com using the java and grpc tags, so that other developers with the same questions can also benefit.

Thanks!
