### ISSUE TITLE
Round-robin LB should be aware of and skip bad servers

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#1600]
The round-robin logic in `GrpclbLoadBalancer` should listen to transport life-cycle events (`handleTransportReady()` and `handleTransportShutdown()`) to learn what servers are not usable, so that it can skip them. The round-robin logic will also be shared with the simple round-robin `LoadBalancer` (which is yet to be implemented).

**Comment by zhangkun83** [comment]
Since TransportSet today reconnects only if there is request. The round-robin LB should be able to request for active reconnect, otherwise a once disconnected address wouldn't have a chance to be used again. This was supposed to be done by `TransportManager.updateRetainedTransports()`, which requires TransportSet to be able to actively reconnect by itself. 

@ejona86 comes up with a better approach -- do not explicitly call out "retained transports", instead let LoadBalancer listen to the "channel state" of TransportSets, and make TransportSet to reconnect as desired when it's disconnected. With this approach, TransportSet can keep the lazy connection behavior, and the LoadBalancer API would be simpler.

**Comment by zhangkun83** [comment]
@ejona86 and I brainstormed a few options. We found the following issues keep coming up:

#### Channel state callback leakage

Rejected solution: TransportManager has a `getChannel(EAG)` that returns a stateful subchannel which is not bound to a TransportSet. The advantage is those subchannels are shims and don't need lifecycle management. However, channel state callbacks may be held by ManagedChannelImpl and may never be cleared if a TransportSet for that EAG never gets created.

#### TransportSet leakage

This issue is particularly a problem in GRPCLB affinity case, where the local LoadBalancer doesn't know all the servers, thus can't give TransportManager the list of servers to be kept.

Rejected solution: we thought about relying on ChannelImpl's idle mode and TransportSet shutting down itself when going idle, to clear up unused TransportSets
 1. ChannelImpl may never go idle while harnessing unused TransportSets, thus the leaking.
 2. Shutting down TransportSet when it's idle has its own problem (see the next issue).

### Reconnect back-off state being cleared

Rejected solution: we always shutdown the TransportSet when it becomes idle. It solves the problem of TransportSet leakage, but shutting down the TransportSet would clear the back-off state, making it possible to hammer a server.

**Comment by zhangkun83** [comment]
The solution we finally landed with:

1. TransportSet implements Channel State API. A discrepancy with the state semantics needs to be fixed: at the end of back-off, go to CONNECTING state instead of going to idle. This is equivalent to infinite IDLE_TIMEOUT.
1. Never shutdown TransportSet when it goes IDLE.
1. TransportManager: replace `getTransport(EAG)` with `createSubChannel(EAG)`, which means two changes: 
 1. For an EAG, LoadBalancer will get a **SubChannel** that extends ManagedChannel, which will have Channel state API on it, instead of a transport. SubChannel is in fact a facade of TransportSet.
 2. LoadBalancer is responsible for the life-cycle of the returned subchannels. `createSubChannel()` always creates a new subchannel, unlike `getTransport()` which will re-use existing TransportSets for the same EAG.

### How this addresses the issues
#### Channel state callback leakage
The callback is owned by TransportSet and will not leak as long as TransportSet doesn't leak.

#### TransportSet leakage
It becomes LoadBalancer's responsibility to shutdown a SubChannel (thus TransportSet) that is no longer used.

#### Reconnect back-off state being cleared
Because we never shutdown TransportSet when idle, back-off state will be kept (unless LoadBalancer maliciously shuts down and re-create a SubChannel frequently, which is not our concern).

#### A once-bad server never gets used again by round-robin
Once the channel state semantics discrepancy in TransportSet is fixed, TRANSIENT_ERROR will always transition to CONNECTING, thus TransportSet will always try to reconnect if connection failed.

Question: if a server sends go-away (a READY->IDLE transition), round-robin LB will receive a channel state update, it can request for reconnect through the channel state API. But should it?

**Comment by zhangkun83** [comment]
> TransportManager: replace getTransport(EAG) with createSubChannel(EAG), which means two changes:
>  1. For an EAG, LoadBalancer will get a SubChannel that extends ManagedChannel, which will have Channel state API on it, instead of a transport. SubChannel is in fact a facade of TransportSet.
>  1. LoadBalancer is responsible for the life-cycle of the returned subchannels. createSubChannel() always creates a new subchannel, unlike getTransport() which will re-use existing TransportSets for the same EAG.

@lukaszx0 @jhump This API change may impact your work in a non-trivial way. I'd like to hear your opinions.

**Comment by jhump** [comment]
Thanks for the heads up @zhangkun83.

I think this will actually be a better API for us. @lukaszx0 has done a lot of work integrating our name service with gRPC. But one last step is implementing heartbeats and better load balancing. The existing API is problematic -- particularly that `TransportManager` takes an `EquivalentAddressGroup' instead of a `ResolvedServerInfoGroup`.

We have cases where some traffic must transit through a virtual IP, for security reasons. Virtual IPs in our network generally map to hardware load balancers. This means that a client may only have a single address (e.g. host and port) but actually have multiple backends. With the previous API (only being able to target by actual address), there wasn't a clear way to distinguish multiple backends that transit through the same virtual IP address (for purposes of sending heartbeats and also for load balancing since we must distribute traffic across multiple connections that all go through the same address from the client's point of view).

So we would likely have had to write the same connection management logic in our load balancer anyway, and potentially be unable to use `TransportManager`. I think this change will actually help.

We have this stuff implemented in Go, but their API for picking a connection accepts an address object which includes metadata from the name service (so much more like `ResolvedServerInfoGroup` than `EquivalentAddressGroup`).

**Comment by lukaszx0** [comment]
@zhangkun83 thanks for heads up, as Josh said, I think this might be a better API, however I must admit that I still need to spend some more time reading internals to fully understand current design and its abstractions to be able to better judge and/or propose some alternative solutions.

**Comment by zhangkun83** [comment]
@jhump happy to hear that! Would that be OK if I just change the API in-place, instead of deprecating and deleting the old methods in two releases?  Keeping the old API is kind of painful.

**Comment by zhangkun83** [comment]
RE: detecting bad server, we have to [live with the current channel-state API design](https://github.com/grpc/grpc-java/issues/28#issuecomment-248162532), which doesn't provide reliable signal of TRANSIENT_FAILURE. As a workaround, we will mark an address as bad if it has not been ready for some timeout.

**Comment by lukaszx0** [comment]
> Would that be OK if I just change the API in-place, instead of deprecating and deleting the old methods in two releases? Keeping the old API is kind of painful.

Yes. We're quite flexible and this shouldn't be a problem for us.

**Comment by lukaszx0** [comment]
For the record, while I don't much about [kubernetes it looks like people using it are also _"affected"_](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/grpc-io/2DTu1hZwklI/rr5JCiG_AwAJ) by this and the use case @jhump described - the situation when there's a L4 load balancer in play

**Comment by zhangkun83** [comment]
@lukaszx0 it looks like the new API will help with their case by allowing creating multiple sub-Channels for the same EAG.

**Comment by ejona86** [comment]
All FYI (nothing really impacting discussion):

There is a grpc-wide L4 LB issue at grpc/grpc#7957.

The specific case of having multiple transports to the same host was intended to be supported, but we had multiple ways of obtaining it. For instance, we could easily have an extra id on `EquivalentAddressGroup` that serves no purpose but to allow making instances not equal.

The C core auto-reuses transports across channels, so they have the same problem (but at an even higher level). They use a similar hack where they add useless configuration that avoids sharing but otherwise has no effect.

**Comment by zhangkun83** [comment]
There is another issue that will result from LoadBalancer actively shutting down TransportSets -- a race between shutting down the transport (when RR addresses change) and calling `newStream()` on the transport. If not handled, this race could cause spurious errors.

**Comment by zhangkun83** [comment]
Design doc for the new API and the related Channel impl refactor:
https://docs.google.com/document/d/1exE0_QNwbHJesD-Opl2D6qX1wujADkUm5OpFykks3C8/

**Comment by jhspaybar** [comment]
The doc appears private. I requested access.

**Comment by zhangkun83** [comment]
@jhspaybar: Due to policy restrictions, the doc cannot be published and I have to grant access to individuals upon request.

**Comment by lukaszx0** [comment]
@zhangkun83 LBv2 has landed in master, I think we can close it?

**Comment by zhangkun83** [comment]
Resolved by #2707
