### ISSUE TITLE
Remove AbstractStub.StubConfigBuilder

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#168]
Forked from #150

Now we are doing this to reconfigure a stub:
```
stub = stub.configureNewStub().setDeadline(...).addInterceptor(...).build();
```
Why not just:
```
stub = stub.withDeadline(...).withInterceptor(...);
```

This could make per-call configuration more concise. Instead of:
```
response = stub.configureNewStub().setDeadline(...).build().foo(request);
```
we could have:
```
response = stub.withDeadline(...).foo(request);
```

**Comment by ejona86** [comment]
I don't think anyone was against the with* method version. I think people were debating between what we have and the with* methods.

There were two arguments for configureNewStub():
 1. Is only one method, and so will be less likely to collide with a user-defined service method. This seems like a strong argument, although users prefixing a method with "with" seems unlikely.
 2. Uncertainty about whether there will ever be a need to set two things at once. With a builder you can verify during build() that things are set correctly, whereas with with* each method call must be able to stand alone and produce a valid Stub. I don't recall any concrete examples proposed.

I've always preferred the with* methods (because it is so concise and feels inexpensive to a user), so you have my vote, but bullet 1 does need to be considered.

**Comment by zhangkun83** [comment]
Collision with a user-defined service method is almost impossible, because even if the names collide, the arguments will be different.

Because of using absolute deadlines, setting the deadline on stub becomes a per-call thing, and it's really annoying with the builder pattern. So I would really love to get rid of it.

@louiscryan @nmittler don't have problem with this proposal either. I will proceed if Java libraries team don't object.
