### ISSUE TITLE
Consider removing ServerServiceDefinition, per the comment

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1713]
This class is experimental, and needs to be checked if it should be part of the stable API

**Comment by zhangkun83** [comment]
The comment is:
"Since the handler map uses fully qualified names as keys, we should consider removing ServerServiceDefinition and let the registry to have a big map of handlers."

There wasn't a strong motivation for removing it in the first place. Over time this class has been used in various places internally, including in generated code (not from gRPC codegen). Now while the motivation hasn't got stronger, the effort needed has become larger.

On the other hand, keeping the service an additional layer on top of method is potentially useful, because it aligns with the structure of the IDL. If we ever add more per-service information, having this class will be handy.

We should probably keep it. @ejona86 WDYT?

**Comment by ejona86** [comment]
I don't think the comment is saying we should remove the class itself. Instead, I think it is saying to remove it from [registry](https://github.com/grpc/grpc-java/blob/28d51c5/core/src/main/java/io/grpc/MutableHandlerRegistryImpl.java#L49). See also the [original location of the comment](https://github.com/grpc/grpc-java/commit/a6621daca26ee28238eede8c1124b5334bb49a26#diff-6958b7d39728dfc8769f70234c8a3f7f).

I don't see how we can delete the `ServerServiceDefinition` class, but we may be able to remove some usages of it or reduce its importance.
