### ISSUE TITLE
Tracking Issue for affinity being Experimental.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1766]
Specific usages:
- `CallOptions.getAffinity`
- `Calloptions.withAffinity`
- `LoadBalancer.pickTransport`

**Comment by odiszapc** [comment]
Let's say I have Consul name resolving policy. For example, name "consul:rpc" is resoled ot [1.1.1.1, 2.2.2.2] but it's dynamic, new ips can arrive.

And each time new service appears, i.e 3.3.3.3 my Discovery service wants to add new connection to this host to grpc connection pool.

I guess it should be done with NameResolver, but it resolves name only once.
Then I guess the LoadBalancer can do that, but it receives only the IPs provided by NameResolver.
I need the way I can pass "consul:rpc" to LoadBalancer. Is afinity good to do that?

Thanks!

**Comment by ejona86** [comment]
@odiszapc, this issue is for affinity being marked experimental, which is unrelated to your question. The answer to your question is to use a `NameResolver`, and just call `onUpdate` any time the list changes. If you can listen for updates, the `NameResolver` should do that, otherwise it will need to poll. At certain points gRPC may notice things look a bit broken and will call `NameResolver.refresh()`. The `NameResolver` can then asynchronously re-resolve the addresses and call `onUpdate`, but that `onUpdate` callback isn't special in any way; the resolver can choose to call it any time it's aware of updated information.
