### ISSUE TITLE
Tracking Issue for Idempotence being Experimental.

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#1775]
Specific usages:
- `MethodDescriptor.isIdempotent`
- `MethodDescriptor.withIdempotent`

**Comment by jhspaybar** [comment]
How do I get code gen to set this field to true?  We have a custom Retry interceptor that we'd like to check this field to determine when to trigger it.  It looks like there isn't a proto option, or at least I haven't been able to dig one up.

**Comment by ejona86** [comment]
The protoc changes haven't landed yet. grpc/grpc#7945 with Proposed Method Annotations discusses it some, but I don't think I've seen the protoc changes land for any language.

**Comment by noel-yap** [comment]
I'm thinking `withSafe(boolean safe)` should also set `idempotent` to the value of `safe`.

**Comment by rmichela** [comment]
@ejona86 Are we are still waiting for protoc to emit cache-control compliant grpc stubs? Any idea on an ETA?

**Comment by ejona86** [comment]
@makdharma, is there anything to share about the current state of POST support (plumbing, how hard we're pushing)?

**Comment by makdharma** [comment]
The support for GET (POST was always supported :) has landed in Java and C
stacks. Nobody is working on the protoc change for plumbing the idempotent
option all the way through to code gen. For now you'll have to manually add
the flag.

**Comment by ejona86** [comment]
> POST was always supported

Oops. I meant PUT.

> The support for GET has landed in Java and C stacks.

That needs to be clarified: GET on client-side. Java does not support GET nor PUT on server-side.

It should also be clarified that the current GET protocol has known future breaking changes planned.

**Comment by rmichela** [comment]
The ultimate purpose of these changes is to implement native request cache support in gRPC. 

Is native request cache support a near-term, long-term, or "eventually" feature? Should we pursue other application-tier or `ClientInterceptor`-based caching strategies in the interim?

**Comment by makdharma** [comment]
If you are using Java or C++ client and C++ server and you have a HTTP/2
caching proxy then it should work currently. Any other combination is a
"eventually" feature. The HTTP/2 proxy (that speaks H2 on both client and
backend) could be a problem, as the nginx changes are still in the process.

**Comment by ejona86** [comment]
The PUT and GET work has stalled. The drive to work on this from within Google has stopped. We'd have engaged with the community more for GET, but we're not currently aware of a popular caching proxy that supports HTTP/2 to the backend. Similarly, PUT was helpful for QUIC, but QUIC is hard to deploy in servers. We're fairly happy wire protocol (GET support in Java was an earlier version of the protocol), but don't see much value to drive the work to completion if nobody could end up using it.

I recognize that some people would like to just have the idemponent/safe detail about a method, without PUT and GET support. However, I don't feel comfortable enabling idemponent/safe method details until there is a working deployment strategy for PUT and GET, as otherwise adding PUT/GET support could cause breakages. I'd suggest those users to create their own idemponent/safe protobuf option for the time being.

I've created #12038 and #12039 for discussion and tracking of progress. If this work would benefit you, please champion the work in those issues. We have some implementations already in place, but we'd need to implement the support universally and may need to consider rollout in more detail.

**Comment by ejona86** [comment]
Sooo, apparently protobuf did get support for the idempotency bit. You can see it in the schema at:
https://github.com/google/protobuf/blob/9e745f7/src/google/protobuf/descriptor.proto#L630

Example:
```proto
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {
    option idempotency_level = IDEMPOTENT;
  }
}
```

**Comment by leventov** [comment]
IMO the term "safe" is confusing. Should be "sideEffectFree": withSideEffectFree(), setSideEffectFree().

**Comment by carl-mastrangelo** [comment]
@leventov We use the existing parlance from the HTTP RFCs:  https://tools.ietf.org/html/rfc7231#section-4.2.1  

You can see existing usage here: https://tools.ietf.org/html/rfc7237#section-3

**Comment by z-kovacs** [comment]
Hi,

Is there any update on this?
Seems in grpc 1.19.0 I still get `false` for `method.isIdempotent()` even if I add `option idempotency_level = IDEMPOTENT;` to the rpc call. (Compiles without issue though.)

**Comment by ejona86** [comment]
@z-kovacs, yes. gRPC is not currently using the idempotent flag, so it is not fully plumbed. If you want to use the value yourself, you can cast `method.getSchemaDescriptor()` to `ProtoMethodDescriptorSupplier` and look for the option.

**Comment by ejona86** [comment]
API review:
 * Okay to stabilize. "No heartburn."
