### ISSUE TITLE
Vendorize our usages of OkHttp internal classes

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#182]
Using the normal OkHttp API didn't quite seem to work for us. The blocking style made it seem like we would need a thread per stream, flow control wasn't exposed enough (although this may no longer be an issue due to how we are now using flow control, other than blocking), RST_STREAM, and other similar advanced HTTP/2 features didn't have quite as much support as we needed. Oh, and trailers...

So that led us to use internals of OkHttp that we shouldn't be, because it will be brittle. Instead, we should propose/upstream an API that supports advanced usage and can be stable.

**Comment by louiscryan** [comment]
From @swankjesse 

https://github.com/square/okhttp/issues/32#issuecomment-88887281

We need to consider the maintainability of forking a bunch of OkHttp code here. Other viable options are to JNI-wrap the C runtime on Android or to use the Chrome networking library

Jesse - Got any strong opinions about those alternatives, particularly given that we already have a pure Java impl in Netty that would facilitate local development and testing. In particular do any environment issues come to mind that should motivate us to continue to maintain a pure Java Android solution?

**Comment by swankjesse** [comment]
JNI complicates development & deployment. You'll need a nontrivial amount of code to manage sharing buffers between native code and Java. How big are the buffers? Are they dynamically resized? When are they released? So that approach would be a nonstarter for me.

I haven't used the Netty. I would be reluctant to adopt it for my Android apps due to its code size, but I'm probably more sensitive to this than most developers. My back-of-napkin estimate is that Netty contributes ~1.6 MiB worth of .jar files and ~10,000 methods to an Android application. Okio+OkHttp are ~350 KiB and ~2,500 methods.

If I were to set out to build a GRPC implementation, I'd just fork the code in this package and strip out SPDY/3:
https://github.com/square/okhttp/tree/master/okhttp/src/main/java/com/squareup/okhttp/internal/spdy

**Comment by ejona86** [comment]
At the very least we should vendorize the http/2 code that we use.

Although I feel less urgent about it, we should also vendorize our usages in OkHttpTlsUpgrader and OkHttpProtocolNegotiator, although there may be significant savings by only bringing in the methods that we use.

**Comment by madongfly** [comment]
Fixed by b121c46b42e58fedb8694a9ce1ad9c5c117e8f6a
