### ISSUE TITLE
gRPC server does not exit on OutOfMemoryError

### ISSUE THREAD

**Issue by rsmilyanov** [grpc/grpc-java#1946]
Hello,

I did a simple test as throwing java.lang.OutOfMemoryError in my service code. It seems that the error is caught in ```io.grpc.internal.ServerImpl.JumpToApplicationThreadServerStreamListener.halfClosed() ``` and its not re-thrown. 

```
@Override
    public void halfClosed() {
      callExecutor.execute(new ContextRunnable(context) {
        @Override
        public void runInContext() {
          try {
            getListener().halfClosed();
          } catch (RuntimeException e) {
            internalClose(Status.fromThrowable(e), new Metadata());
            throw e;
          } catch (Throwable t) {
            internalClose(Status.fromThrowable(t), new Metadata());
            throw new RuntimeException(t);
          }
        }
      });
    }
```

Therefore the server will continue running.

The version of the gRPC is 0.15.0-SNAPSHOT

Is this expected behavior or it is a bug in the code?

Thanks,
Rado

**Comment by carl-mastrangelo** [comment]
@rsmilyanov Won't that be caught by the `Throwable`  catch?

**Comment by rsmilyanov** [comment]
@carl-mastrangelo, yes its caught by the ``Trowable``. That's why I opened this issue.
I expected that fatal errors like ``java.lang.OutOfMemoryError`` will not be caught and I expected that the server process should have exited in case of fatal errors. Are my expectations wrong?

**Comment by carl-mastrangelo** [comment]
No, I had the same expectations too.  For convention though it seems our code handles throwable in a lot of places, so I guess this does too.  Exception propagation happens strangely when you don't really have callstack, which is the case in our code.  You can handle the exception in the listener's `closed(Status)` method, and get the exception out of that.

**Comment by rsmilyanov** [comment]
@carl-mastrangelo I can handle errors that occur into my code. Can you please give me some advice how can I handle in a proper way fatal errors thrown in gRPC server code?

**Comment by carl-mastrangelo** [comment]
@rsmilyanov There are two error classes that I would care about: Fatal errors whose root cause is application code and fatal errors from the RPC code.  If the cause is from Application code (such as in a callback you provided to us), then we try to get that Throwable back to you.  In case it is caused by our runtime library, then there is really no telling what the best way to proceed is.  We can try to propagate the error back, but it may never make it (maybe our error propagation code has a bug).

In any case, we might have differing ideas of how bad an error is.  Is Fatal so bad as to be worth calling System.exit() ?  Is it bad enough to try and gracefully shutdown?

**Comment by vleushin** [comment]
@carl-mastrangelo I had memory leak. I got out of memory exception. I expected server to crash and to be restarted by system (server is is docker container, if it exists with code != 0 than it gets restarted by CoreOS). Instead it hanged, was not responding and GC was eating CPU. It was not able to gracefully shutdown.

**Comment by carl-mastrangelo** [comment]
OOM is going to have a bad outcome anyway, we just don't know what bad outcome we want.  Fail all RPCs?  That isn't particularly graceful.  Spin and do GC continuously?  That's bad too.  

A better solution would be to not ever get into that circumstance to begin with.  The flow control semantics let you limit how much much you are using, and how fast you get data in.  

Another alternative is to use ulimit and cap memory at close to the Xms and Xmx.  That would get the process to die with an exit code like you want.

**Comment by vleushin** [comment]
"Fail all RPCs? That isn't particularly graceful." I do not have any reasonable choice. Instead of failing and letting others know "I'm dead" (load balancer will stop forwarding requests to me), I take requests and hang on them, hoping that they will eventually time out on client.

http://docs.oracle.com/javase/8/docs/api/java/lang/Error.html
"An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions." We are talking about abnormal situation here.

**Comment by carl-mastrangelo** [comment]
@vleushin Right, and we defer to you on what to do in such cases.  You can definitely catch OOME and end your process.  I think we all agree something bad has happened on such an error, but not what should be done in every single case.  

Error is definitely something bad, but killing the whole process is not always what you want.  Unit tests often use AssertionError.  If we killed the whole process instead of propagating it back, it would be difficult to debug failing tests.  (and interfere with other tests).

**Comment by ejona86** [comment]
So that everyone is clear, normal multi-threaded Java applications do not exit after `OutOfMemoryError`. Instead, the OOME propagates up to `Thread`, which uses `Thread.UncaughtExceptionHandler` to process the exception, which by default does `t.printStackTrace(System.err)`. Most thread pools will then later create a new Thread.

Instead of wrapping the `Throwable` in `RuntimeException`, it is a good idea to try to throw it directly. However, that would not have changed much of the behavior you saw.

**Comment by vleushin** [comment]
OK, I got your points. One possible solution I see now is to use some external service -- like Java Service Wrapper to make restart or stop if I get out of memory exceptions. Correct me if I'm wrong. Are there other alternatives?

**Comment by rsmilyanov** [comment]
Hi @ejona86 @carl-mastrangelo, how about if there is an API that provides a hook into ServerImpl in case of errors? The hook could be a ```Consumer<Throwable>``` and developers will have control whether the server process must exist on fatal errors or not.

**Comment by ejona86** [comment]
@rsmilyanov, I think what you are describing is `Thread.UncaughtExceptionHandler`. Call `Thread.setDefaultUncaughtExceptionHandler(handler)`, and when an OOME occurs then call `System.exit(1)`. There's some minor issues, like how we're wrapping the Error in RuntimeException, but that we can just fix. I also know that using `directExecutor()` will [break that a bit](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/SerializeReentrantCallsDirectExecutor.java#L67), but it's something we can work through. (We could call `UncaughtExceptionHandler` there manually, but it's unclear how many implementations use the fact that the Thread will be dying soon.)

However, I will note many async programs avoid propagating Errors. `FutureTask` (which powers `ExecutorService.submit()` and `schedule()`) [catches `Throwable`](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/concurrent/FutureTask.java/#268) and only sets the result of the `Future`. Really, though, that's almost the only sane thing to do. So your program will still need to be careful in places to make sure that it handles async exceptions.

**Comment by dconnelly** [comment]
@vleushin There is the `-XX:OnOutOfMemoryError` VM option which can be used to kill the process when OOM but it's known to be unreliable since it relies on fork. Instead, we have had much better luck with https://github.com/airlift/jvmkill.

**Comment by vleushin** [comment]
@dconnelly Thank you! This was very helpful.

**Comment by rsmilyanov** [comment]
@ejona86, sorry for the delayed response. Thanks for the clarifications!
