### ISSUE TITLE
Stub classes shouldn't be final to allow mocking

### ISSUE THREAD

**Issue by anuraaga** [grpc/grpc-java#2160]
#2077 Seems to have made stub classes final. As stubs do remote calls, it's usually important for them to be mockable to write unit tests, but mockito can't mock final classes. Previously users could use the interface I guess. While I understand the reasoning of dropping the interface for service classes in #1469, to allow stub upgrades without breaking service implementation code compile, does this apply to client stubs too?  It'd be nice for the stub classes to either be non-final or have interfaces to allow mocking.

**Comment by ejona86** [comment]
It was never our intention to allow mocking the stubs. Any time Mockito does its hacks to mock classes that shouldn't be mocked (like if they only have private constructors, like AbstractStub) it open the door to us breaking your test. We can't support tests that use Mockito to avoid API restrictions.

https://github.com/grpc/grpc-java/issues/1469#issuecomment-226873511 has some specific issues with mocking the stub. Instead of mocking the stub, we would suggest you to mock a service implementation and use InProcess transport for connecting the two. If you use `directExecutor()` for both client and server, all the calls happen immediately and within the testing thread.

If there are use cases that are poorly supported or utilities that could be useful (like #2051), we'd be happy to hear about them.

**Comment by srivastavag** [comment]
This thread is somewhat dated so not sure if info is upto but cant StubInterface be used for mocking ?
Thanks

**Comment by ejona86** [comment]
@srivastavag, there isn't a `StubInterface` in the Java generated code.

**Comment by srivastavag** [comment]
Oops, I was looking for c++, extremely sorry for my oversight.

**Comment by ensonic** [comment]
@ejona86 All the linked examples assume you mock the service you are testing, which sounds weird to me (see https://github.com/grpc/grpc-java/blob/master/examples/src/test/java/io/grpc/examples/helloworld/HelloWorldClientTest.java)
My grpc service talks to other grpc services and I'd like to mock out those. My Dagger module injects those secondary grpc service stubs and hence in the Test dagger module I'll need to provide mocked stubs and this is when things seem to fall apart.
