### ISSUE TITLE
Could not initialize class io.grpc.netty.Utils

### ISSUE THREAD

**Issue by Jo3McCarthy** [grpc/grpc-java#2161]
Hi, All;

I have made it through the grpc-java build process (thanks for all the help!).  

Now, when I run my application from a "fat jar" or uberjar, it succeeds.  However, when I incorporate that jar in another application, it get this error: Could not initialize class io.grpc.netty.Utils

I do not seem to be able to get any further details on the error because it does not occur when I run the code directly from the uberjar.

Where should I look to see why Netty Utils is failing?

Thanks,

Jo3

**Comment by ejona86** [comment]
"Could not initialize class" means that static initialization failed. You'd have to get more information in the failing environment as to why. It may be due to class path problems (e.g., multiple different class definitions for the same class). You're probably best off using a debugger and tracking down the exception with its causal chain.

**Comment by Jo3McCarthy** [comment]
Hi, Eric;


The only further hint I can find is: "io.netty.util.AttributeKey.valueOf(Ljava/lang/Class;Ljava/lang/String;)Lio/netty/util/AttributeKey;"


Thanks,


Jo3


________________________________

**Comment by Jo3McCarthy** [comment]
For completness, I am building my uberjar with grpcVersion '1.0.0-pre1'

Thanks,

Jo3

**Comment by ejona86** [comment]
Oh, that is really useful. There are probably two different versions of Netty in the classpath. You can either remove the older version or use shading/jarjar to prevent a collision.
