### ISSUE TITLE
Server should compressed responses if the client sent a compressed request

### ISSUE THREAD

**Issue by stephenh** [grpc/grpc-java#2196]
Currently the ServerCallImpl never implicitly turns on compression, and instead compression has to be enabled via an interceptor, e.g.:

```
  public static ServerServiceDefinition createWithCompressionEnabled() {
    return ServerInterceptors.intercept(new MyServer(), new ServerInterceptor() {
      @Override
      public <ReqT, RespT> Listener<ReqT> interceptCall(ServerCall<ReqT, RespT> call, Metadata headers, ServerCallHandler<ReqT, RespT> next) {
        call.setCompression("gzip");
        return next.startCall(call, headers);
      }
    });
  }
```

In theory, somewhere around here:

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L85

If the client sent a compressed request, the server could default it's compressor to the same compression codec, and return a compressed response.

**Comment by ejona86** [comment]
Servers can cast the provided `StreamObserver` to `ServerCallStreamObserver` and call `setCompression()`. We don't auto-enable compression in responses since they may not be compressible. Just because a request is compressible doesn't mean the response is (say, if it is a JPEG blob). Also, compression is per-message; the client can say "if I use compression, it is gzip" and then not actually compress anything.

Compression is still in its infancy, and we're still playing with it.

**Comment by stephenh** [comment]
Ah, nice, I missed the method call on ServerCallStreamObserver. I can use that instead.

I am not surprised there are nuances around turning compression on automatically; it just seemed great for my use case. :-)

Thanks.
