### ISSUE TITLE
Improve LoadBalancer API

### ISSUE THREAD

**Issue by lukaszx0** [grpc/grpc-java#2211]
Implementing `LoadBalancer` API at the moment is kinda hard and requires a lot of boiler plate to get you going. I proposed some changes in https://github.com/grpc/grpc-java/pull/2199 to improve this situation and we eventually come to the conclusion that this would you some reworking in core rather than simple wrappers and utility classes.

I'm coping @zhangkun83's and @ejona86 comments from the PR and let's continue design discussion here.

@zhangkun83's [comment](https://github.com/grpc/grpc-java/pull/2199#issuecomment-242873133):

The problems `SimpleLoadBalancer` is set to solve are:
- The handling of interim transports is repeated among all LoadBalancers
- The error handling is repeated among most LoadBalancers.

What I would like to see, is a new `LoadBalancer` interface that solves those problems, instead of fragmenting the API. The idea is to move those common logic into `ManagedChannelImpl`.

Inspired by your proposal, @ejona86 and I have come up with a strawman design:

``` java
abstract class LoadBalancer {
  void shutdown();
  void handleResolvedAddresses();
  void handleNameResolutionError(Status error);
  interface LoadBalancerListener {
    void loadBalancerReady(TransportPicker picker)
    void loadBalancerPending()
    void loadBalancerError(Status error);
  }
  abstract class TransportPicker<T> {
    public T pickTransport(Attributes affinity);
  }
}
```

The most important part is `LoadBalancerListener`, which is implemented by `ManagedChannelImpl`. It technically defines three states in the LoadBalancer:
- `PENDING`: this is the initial state. The channel holds requests in the interim transport.
- `READY`: when entering this state, the channel will close the interim transport with the transport from the picker, and use the picker to serve further requests.
- `ERROR`: the channel holds wait-for-ready requests in the interim transport, and fail fail-fast requests immediately. This is the behavior expected by #2209.
  `LoadBalancer` may enter any state any time with the methods in `LoadBalancerListener`, and no longer needs to worry about managing interim transports and returning failing transports.

Caveat: in the case of sharded load-balancing, the `LoadBalancer` may be able to serve some requests, but have to fail or hold other requests, because for example, some shards may be unavailable temporarily, but come back online shortly. We either keep `createInterimTransport()` on TransportManager to let LoadBalancer handle this manually, or tweak the API somehow to make it as nice as the non-sharded case.

I look forward to landing with a new `LoadBalancer` API after a few iterations with you, before we do any implementation work. Comments and ideas are welcome :)

@ejona86's [comment](https://github.com/grpc/grpc-java/pull/2199#issuecomment-242874394):

I'd just add that `PENDING`, `READY`, and `ERROR`, are analogous to `CONNECTING`, `READY`, and `TRANSIENT_FAILURE`, respectively, in the `Channel` connectivity semantics (and I might prefer we use those names, but I don't care much). This new LB API also makes the Channel state API (#28) much easier to design since the LB wouldn't need to directly participate (with caveat for the sharded LB case, but I think we punt on that for now).

**Comment by lukaszx0** [comment]
Updated the code example above with some style changes, added `#start(Listener)` and  `#handleTransport*()` methods which I think we'll continue to need. Also, I think we won't need `onPending` in listener - it'll be the initial state.

```
abstract class LoadBalancer {
  void start(Listener listener)
  void shutdown();
  void handleResolvedAddresses(List<ResolvedServerInfoGroup> servers, Attributes attributes);
  void handleNameResolutionError(Status error);
  // We probably still want these?
  void handleTransportReady(EquivalentAddressGroup addressGroup);
  void handleTransportShutdown(EquivalentAddressGroup addressGroup, Status status);
  interface Listener {
    void onReady(TransportPicker picker);
    void onError(Status error);
  }
  abstract class TransportPicker<T> {
    public T pickTransport(Attributes affinity);
  }
}
```

So for the simple cases, I understand that we'll have `SimpleLoadBalancer` which in `handleResolvedAddresses` will just trigger `listener.onReady` and in `handleNameResolutionError` the `listener.onError` respectively and more advanced `LoadBalancer`s will require custom impl of `handle*()`. The only thing to implement for simple cases will then just be `TransportPicker`.

Do I understand this correctly?

**Comment by ejona86** [comment]
@lukaszx0, yeah, that looks like I would expect.

The `Listener` _could_ be passed in `LoadBalancerFactory`, but that can introduce races in the listener implementation (if it ever needs to call into `LoadBalancer` in response to an event). I _think_ that's not a problem here, but it's been a problem so frequently it's reasonable to "always have a start". As an alternative, we may want to pass in `TransportManager`/`serviceName` during `start()` as well. But that's minor stuff.

**Comment by lukaszx0** [comment]
@zhangkun83 without minor things mentioned by @ejona86 I like the design. What do you think?

**Comment by zhangkun83** [comment]
@lukaszx0 the API looks good.

**Comment by zhangkun83** [comment]
I just realized an oversight for affinity case in the existing API -- the affinity keys are not used when completing the delayed (interim) transports: 
```java
InterimTransport {
  void closeWithRealTransports(Supplier<T> realTransports);
}
```
Although `DelayedClientTransport` saves the affinity keys for the delayed streams (in `CallOptions`), there is no way for it to pass those keys to `Supplier<T>`. This can be addressed by changing this method into:
```java
InterimTransport {
  void closeWithTransportPicker(TransportPicker<T> picker);
}
```
Similarly:
```java
DelayedClientTransport {
  void setTransportPicker(TransportPicker<T> picker);
}
```

**Comment by zhangkun83** [comment]
I have also been thinking about how the new LB API would handle sharded case, because I am not excited about moving the delaying logic into ChannelImpl, while still leaving the interim transport available to LB just because sharded case may need it.  I would like to see a unified API that works for both sharded and non-sharded cases.

I came up with this alternative proposal, which modifies `Listener` and `TransportPicker`:
```java
interface Listener {
  void pickerUpdated(TransportPicker picker);
}
abstract class TransportPicker {
  PickResult pickTransport(Attributes affinity);
}
class PickResult {
  // pseudo code
  oneof {DELAY, Error Status, real transport}
}
```
In a nutshell, `Listener` doesn't call out states. Instead it uses `TransportPicker` to dictate whether the ChannelImpl should use delayed transport, failing transport or a real transport.

1. Initially, ChannelImpl uses a default `TransportPicker` that always returns `DELAY`.
2. In simple cases, when LB is ready, it calls `pickerUpdated()` to give a `TransportPicker` that returns real transports.
3. In error cases, LB passes a `TransportPicker` that returns `ErrorStatus`.
4. In sharded cases, if some shards are unavailable,
 - LB gives a `TransportPicker` that returns real transport for some affinity keys, but `DELAY` or `ErrorStatus` for others.  ChannelImpl will always keep a delayed transport to host the requests whose pick results are `DELAY`.
 - When some shards become available, LB will give a new `TransportPicker`, which triggers Channel applying the new picker to all delayed streams.  As a result, streams for the newly available shards will proceed, while the others will still get a `DELAY` result thus be put in a new delayed transport.

Then we can remove `createFailingTransport()` and `createInterimTransport()` from `TransportManager`.

This approach doesn't solve the channel state as the previous proposal does, but it wasn't a goal for this API refactor anyway.

Maybe `Listener` and `TransportManager` should be merged into one interface, but that should be a trivial decision to make.

**Comment by ejona86** [comment]
I want to add that `ErrorStatus` would not cause a failure for "wait for ready" RPCs. I think today the equivalent does, but eventually we will need to fix that.

**Comment by zhangkun83** [comment]
> I want to add that ErrorStatus would not cause a failure for "wait for ready" RPCs. I think today this is not handled correctly, but eventually we will need to fix that.

This is tracked by #2209

**Comment by lukaszx0** [comment]
The proposals in this issue are no longer considered and we've decided to completly overhaul LB APIs.

Please refer to: https://github.com/grpc/grpc-java/issues/1600 & https://github.com/grpc/grpc/issues/7957 for future developments in this area.
