### ISSUE TITLE
Add testing helpers for ClientCall, ServerCall

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2216]
With DoNotMock being a thing, we should add some helper classes to the testing package to make them easier to use.

**Comment by ejona86** [comment]
@carl-mastrangelo, what sort of things would you like here?

**Comment by carl-mastrangelo** [comment]
This was supposed to be for NoopClientCall, and NoopServerCall, but those got marked as internal.

**Comment by ejona86** [comment]
So is there more to do here, or should it be closed?

**Comment by carl-mastrangelo** [comment]
Personally, I think so, but since they got moved it seems the rest of the team does not agree.  Testing ClientCall and ServerCall is still kind of annoying.  *We* still use NoopClientCall, which indicates it is useful.

**Comment by ejona86** [comment]
@carl-mastrangelo, how about you document what is difficult instead of just specifying a solution to an unnamed problem. Then there can be attempts to progress with a solution that has benefits of NoopClientCall but downplays the disadvantages; or at the very least we can make a clear decision that the solution is considered worse than the problem.

@dapengzhang0 and I worked on multiple different cases we were aware were problems, and arrived at the simplified testing protos in testing-proto/. I think we'd be interested in solving other testing problems.

**Comment by larry-safran** [comment]
Interop tests added a lot of utilities and in general this has improved over time.
