### ISSUE TITLE
Running grpc server on Android

### ISSUE THREAD

**Issue by anilmaddala** [grpc/grpc-java#2227]
Is there an example or implementation of GRPC server (Java/C++) running on Android?
I am following grpc java server example to implement the server i

```
private class GrpcServerTask extends AsyncTask<Void, Void, String>{

    @Override
    protected void onPreExecute() {
    }
    @Override
    protected String doInBackground(Void... params) {
        int port = 50051;
        Server server;
        try {
            server = ServerBuilder.forPort(port)
                    .addService(new GreeterImpl())
                    .build()
                    .start();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
}

private class GreeterImpl extends GreeterGrpc.GreeterImplBase {

    @Override
    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
        HelloReply reply = HelloReply.newBuilder().setMessage("Hello " + req.getName()).build();
        responseObserver.onNext(reply);
        responseObserver.onCompleted();
    }
}
```

I keep getting the error **io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty artifact**
on executing new GrpcServerTask().execute();

Thanks

**Comment by carl-mastrangelo** [comment]
gRPC Java is not supported on Android.   

That said, if you are just trying to do intra process communication you can use InProcessTransport to connect.  If you really want to accept network traffic, you can try using netty like the error message suggests (add a runtime dependency on it in your gradle file).

If that doesn't work, I think you'll have to use gRPC C++.

**Comment by harisvsulaiman** [comment]
@carl-mastrangelo netty now has support for android . would it work now ?

**Comment by carl-mastrangelo** [comment]
@harisvsulaiman I have not personally tried it, and we have no tests to ensure it works.  "Work" is a tricky word because it implies all the tiny details have been figured out.  There are many complications on android, such as proguard, that would make it fail mysteriously, but if not used work function just fine.  

SSL is another place where things tend to not work.  In netty, SSL is provided by netty-tcnative, which is a native code wrapprer around boringssl / openssl.  I don't think that works on Android (and if it does, you'd be on your own for keeping it working).   

If you can get it to work, I would be impressed.  gRPC + Netty has not be polished to the same extent gRPC + OkHTTP has.

**Comment by ejona86** [comment]
@anilmaddala, your issue is just a ProGuard one. Just add to your config:
```
-keep class io.grpc.internal.DnsNameResolverProvider
-keep class io.grpc.okhttp.OkHttpChannelProvider
-keep class io.grpc.netty.NettyChannelProvider
```

You may glance at https://github.com/ejona86/grpc-java/commit/5d193ad30654fabfd2c31ab9fd81ebf9874fc1a2, an un-merged commit of mine that shows how to use Netty from an example.
