### ISSUE TITLE
Client side NPE when sending large number of concurrent requests

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#2296]
Both server and client use GRPC 1.0.
Client log:

```
Exception in thread "grpc-default-executor-95" java.lang.NullPointerException: channel
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at io.grpc.netty.WriteQueue.<init>(WriteQueue.java:76)
        at io.grpc.netty.NettyClientHandler.startWriteQueue(NettyClientHandler.java:223)
        at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:172)
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:45)
        at io.grpc.internal.TransportSet.startNewTransport(TransportSet.java:215)
        at io.grpc.internal.TransportSet.obtainActiveTransport(TransportSet.java:188)
        at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:637)
        at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:579)
        at 
......
```

Server log:

```
WARN  [2016-09-22 21:28:41,870] io.netty.channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. [client=null]
! java.io.IOException: Too many open files in system
! at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_60]
! at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_60]
! at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_60]
! at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:140) ~[netty.jar:4.1.5.Final]
! at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) ~[netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551) [netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465) [netty.jar:4.1.5.Final]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty.jar:4.1.5.Final]
! at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty.jar:4.1.5.Final]
! at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty.jar:4.1.5.Final]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

**Comment by biran0079** [comment]
The server `Too many open files in system` error is probably caused by creating too many channels, but the client NPE does look like a bug to me.

**Comment by ejona86** [comment]
It's not clear to me how the NPE is being triggered. The NPE is caused by a null channel, but looking through Netty, I can't figure out how connect's future could have a null channel ([called here](https://github.com/grpc/grpc-java/blob/v1.0.0/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L156)). That said, there's quite a few code paths in Netty.

Related links:
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/Bootstrap.java#L162 (doResolveAndConnect)
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/AbstractBootstrap.java#L316 (initAndRegister)
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/Bootstrap.java#L264 (init dereferences channel, so it should "filter" any nulls)
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/SingleThreadEventLoop.java#L73 (register)

**Comment by ejona86** [comment]
Since https://github.com/netty/netty/commit/9bfeab2c8a802b24e867c8f1ba424969ce206903 the `ChannelFuture` returned during registration can return `null`. We can add a check for `channel() == null` [in `NettyClientTransport`](https://github.com/grpc/grpc-java/blob/v1.2.0/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L192). If it is `null`, then we can check `cause()`. If `cause()` is `null` we can just generate our own exception. When channel is `null`, we should return a `Runnable` that notifies the listener the transport has shutdown+terminated.

There is an additional complication: the code assumes that `channel != null` after start has been called, even in the case of error. That's a bit of a problem. I'm not sure how to fix that. Maybe we could use a closed Embedded channel; I'm not too hopeful given the trouble with Embedded channel I've had in the past.

**Comment by ejona86** [comment]
We'll also need to still create a write queue.
