### ISSUE TITLE
grpc-all on Maven repository does not contain anything

### ISSUE THREAD

**Issue by Helcaraxan** [grpc/grpc-java#2298]
Since version 0.14 the grpc-all JAR on Maven.org only contains a Manifest but no actual code. 0.13.2 is the last version still OK.

**Comment by goodsoldiersvejk** [comment]
I noticed this too. I'm assuming this isn't expected behavior?
I'm having trouble integrating this library in an SBT project (get NoClassDefFound errors for
io.grpc.netty classes), and wonder if this is related.

**Comment by Helcaraxan** [comment]
It would be weird for an "expected behavior" so I would definitely say no.
The integration problem you're mentioning is highly likely to be related to this issue as you would now need to include the ` grpc-netty` package from Maven. If this is the only error you're getting from the integration than you could probably just skip the `grpc-all` and go for the smaller one.

In the mean time I had to do manual inclusion of nearly all gRPC-Java packages as we depend heavily on it. Not very neat as a work-around. I would really appreciate it if the team could look into this.

Lots of thanks in advance for that! :smile:

**Comment by ejona86** [comment]
This is the expected behavior. grpc-all [depends on the other artifacts](https://repo1.maven.org/maven2/io/grpc/grpc-all/1.0.1/grpc-all-1.0.1.pom), so any package system pointed at it should still include the other JARs. If you manually download JARs, then yes, you will need to download each in turn.

It was changed in #1597 because making a large JAR of all the other packages breaks in odd ways because you can silently have duplicate versions of gRPC on the classpath at the same time (one copy from grpc-all, and another from, say, grpc-core).

**Comment by Helcaraxan** [comment]
Okay. Thanks for the explanation :+1:

Will default to downloading all manually. Too bad. :disappointed:
