### ISSUE TITLE
Use provider's class loader instead of context class loader

### ISSUE THREAD

**Issue by jonnyzzz** [grpc/grpc-java#2375]
In a multi classloader application it may easily turn out Thread#contextClassloader contains something unrelated to a classloader that indeed loads grpc classes.

``` java
@Internal
public abstract class ServerProvider {
  private static final ServerProvider provider =
      load(Thread.currentThread().getContextClassLoader());
...
```

It's better to check current classloader for ServerProvider.class too.

I use JRE 1.8.0_66, macos 10.12

**Comment by ejona86** [comment]
I don't quite disagree with you, but I've found it hard to get a definitive answer for what's best to do. Using the context class loader is what ServiceLoader does, so we followed suit. Since we store the results in a static variable, it would make sense to use `ServerProvider`'s class loader. But I find it to be pretty muddy waters.

**Comment by jonnyzzz** [comment]
Also noticed some android specific workarounds in the similar code for client, e.g. io.grpc.ManagedChannelProvider#load

**Comment by ejona86** [comment]
I'm going to try to swap away from the context class loader. I think I've been able to prove to myself that it is a pretty bad idea, and that ServiceLoader does differently because it expects the services to be provided by the platform.

**Comment by ejona86** [comment]
This is to happen in all the providers: name resolver, channel, server

**Comment by ejona86** [comment]
Another user got bit: they were making a Gerrit plugin. I suggested this temporary during plugin loading:

```
Thread.currentThread.setContextClassLoader(getClass().getClassLoader());
ManagedChannelBuilder.forTarget("trash"); // just causes class loading
// You could restore the context class loader here
```

Not all environments let you change the context class loader, so this is a workaround and does not negate the need to change which class loader we use.

**Comment by reltuk** [comment]
My two cents: I agree that the current use of Thread Context ClassLoader is not that helpful. From my understanding, we (might) want to use Thread Context ClassLoader if grpc-core was going to be loaded from a different ClassLoader than grpc-netty or grpc-okhttp and we needed the calling application to have a way to make the providers visible to grpc-core. But in such a situation, we probably _don't_ want to statically cache the Thread Context ClassLoader at the time that the grpc-core classes happen to be loaded. In the hypothetical deployment context, we leak the ClassLoader that happens to be seen, we prevent two deployed applications from having different provider implementations...we may even race on loading inconsistent provider implementations if two deployed applications with two different implementations are class loading grpc-core concurrently.

I agree that a better policy would be make the existing interfaces use the ClassLoader for the class doing the discovery. If calling applications really do need the flexibility to have the providers in a different ClassLoader from grpc-core, I would vote for an interface where the callers are responsible for providing the ClassLoader instances at the call sites. (Probably would want to keep a Map of weak ClassLoader references to the discovered Classes internally...)

**Comment by ejona86** [comment]
I don't think there is any real question whether we should swap the class loader. The only real hang-up is that the tests will have to be rewritten to load classes within a custom ClassLoader and then the test will need to use reflection to call methods into the ClassLoader.

**Comment by reltuk** [comment]
Which tests in particular? A quick change to ```ManagedChannelProvider.java```, ```NameResolverProvider.java``` and ```ServerProvider.java``` to just use ```load(X.class.getClassLoader())``` for setting their existing static Provider holder had ```./gradlew test``` passing completely for me.

**Comment by ejona86** [comment]
@reltuk, you're right, those problems are for fixing #2633, not this one. I'm now running tests to see if the change breaks users within Google as a proxy for whether it will cause pain for others when upgrading; if there are pains, I'll try to provide a migration strategy.

**Comment by ejona86** [comment]
@reltuk, the test results turned out well. (Sorry, it took me a bit to interpret the results.) Making the change in #3183.

**Comment by jhaber** [comment]
Just wanted to chime in with a related issue in protobuf-java: https://github.com/google/protobuf/issues/3474 My proposed fix was to switch to the context classloader, but this discussion gave me pause. Did you have any thoughts on other ways to solve that issue?

**Comment by ejona86** [comment]
@jhaber, I'll try to take a look at that other issue, but "classically" in my experience the current class loader has been the appropriate thing to choose. The exceptions: 1) the class doing the loading is in the JDK, 2) you're doing OSGi+spi-fly (see #3273). However, in JDK 9 case (2) may be extended to modules. The important thing to realize about (2) is it only really applies if you're using `ServiceLoader` (not `Class.forName`).

Because of how things have changed with JDK 9, I think I'd suggest: use Class.forName for optional "hard-coded class name" _dependencies_; you would need to be able to define them as an optional module dependency. If you need to reach "above" your class dependency tree and find some pluggable functionality, you need to use `ServiceLoader`. `ServiceLoader` is still a mess and different environments need different configuration of it, so I think I'd suggest copying the gRPC approach and try it first using your class's loader and if that finds nothing try again with the context class loader.
