### ISSUE TITLE
Run a grpc application not working

### ISSUE THREAD

**Issue by nagamanikandank** [grpc/grpc-java#2400]
According to link http://www.grpc.io/docs/quickstart/java.html#run-a-grpc-application , I must follow the below steps to execute a hello world sample client and server.

```
From the examples directory:
$ ./gradlew installDist
$ ./build/install/examples/bin/hello-world-server
$ ./build/install/examples/bin/hello-world-client
```

I am using Windows machine , so `gradlew installDist` command works for me. But after that, there is no `build/install/examples/bin` folder structure to execute hello-world-server.

There is a hello-world-server in `examples\build\tmp` folder, but that too gives following error
`Error: Could not find or load main class io.grpc.examples.helloworld.HelloWorldServer`

Please help

**Comment by carl-mastrangelo** [comment]
What directory did you run it from?

**Comment by nagamanikandank** [comment]
I am running from `examples `directory

**Comment by carl-mastrangelo** [comment]
Are you running from master?

**Comment by nagamanikandank** [comment]
There is no folder called `master`

**Comment by carl-mastrangelo** [comment]
What I mean to say is, what version of gRPC are you using?

**Comment by nagamanikandank** [comment]
I am in (v1.0.0) branch

**Comment by nagamanikandank** [comment]
@carl-mastrangelo  , any help pls

**Comment by carl-mastrangelo** [comment]
I am not sure what is wrong.  I am on linux, so the commands seem to work on my machine.  As a sanity check could you verify the following things:

1.  Windows uses `\` instead of `/`, could you replace the command with that, and remove the `./` at the beginning of the command?  
2.  Could you run `dir` while in the the examples directory?
3.  Can you also include the full output of  `./gradlew clean installDist`  ?

**Comment by nagamanikandank** [comment]
I found the solution!!!!!!I had to run `hello-world-client` and `hello-world-server` from  build/install/examples/bin/ folder and not `hello-world-client.bat` and `hello-world-server.bat`
