### ISSUE TITLE
Provide access to Method options in ServerInterceptor

### ISSUE THREAD

**Issue by oillio** [grpc/grpc-java#2423]
I'd like to be able to see the options on the method being called in a ServerInterceptor interceptCall method.
Is this currently possible, or are there plans to provide this?

Currently, a io.grpc.MethodDescriptor is available from the ServerCall.  This doesn't have the option data though.  I need a com.google.protobuf.Descriptors.MethodDescriptor, which I can't seem to easily access.

My use case:  I am writing an interceptor that provides user authentication.  I would like to add a custom option to the rpc methods in the proto files to indicate if a method requires authentication or not.

**Comment by ejona86** [comment]
There are plans to provide this. It is sort of part of #651, but not strictly so since the service can be implemented without providing the feature you need. But yes, providing access to the protobuf options via MethodDescriptor is a recognized use case. It should be close, since reflection overall is getting pretty close to completion.

**Comment by fgarsombke** [comment]
Yes, would love to see this!

**Comment by ejona86** [comment]
Fixed by #3451
