### ISSUE TITLE
Periodical refresh of DnsNameResolver

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#2514]
Please answer these questions before submitting your issue.

Original discussion:
https://groups.google.com/forum/#!topic/grpc-io/wxgLgjzkR30

Currently DnsNameResolver soles relies on `refresh()` being called to re-resolve. `refresh()` currently is called only when there is a connection failure, but there are cases where refreshing is needed without connection failure, e.g., rolling deploys, or simply adding a server.  We could introduce periodic refresh to DnsNameResolver.

**Comment by carl-mastrangelo** [comment]
Briefly talking with @a11r, I believe the correct thing to do is re-resolve the name on GOAWAY in addition to connection failure.

**Comment by zhangkun83** [comment]
We have already be doing so. What about the case of adding new servers while keeping the old servers?

**Comment by mightyguava** [comment]
@carl-mastrangelo that sounds like it would solve the bug in reconnect code you referenced in the Google Group discussion, but I'm not seeing how that solves making sure that new servers added to the name get picked up. Right now, if I add new servers to a DNS name, I think they would never get picked up by the clients until one of its connected servers goes down.

While re-resolving on connection failure and GOAWAY does make sure we have HA, it doesn't allow us to fully utilize resources. We only run 2-3 replicas per service right now (hopefully will scale up soon...), so being at N-1 would mean running at 50%-67% capacity.

**Comment by carl-mastrangelo** [comment]
DNS is not really designed to handle your use case.  Adding a method to force DNS refresh to pick up new servers would just be hacking around DNS shortcomings.

The proper solution would be to use a watchable name service like etc.d or something like that.

**Comment by mightyguava** [comment]
We actually did go down that route and implemented resolvers for our internal name service in Go and Java, but we pulled back because it seems the current method of adding resolvers in core (we need it for Python) is quite challenging, requires us to fork core, and I'm not sure how far core or Python is from supporting adding your own resolver, if that's intended at all.

Got any timelines or intended direction on core or Python's side?

**Comment by markdroth** [comment]
C-core does support adding third-party resolvers via the `grpc_register_resolver_type()` function, which can be called from a plugin function, which is registered with `grpc_register_plugin()`.

**Comment by mightyguava** [comment]
@markdroth is there documentation on how to add plugins to core? I thought I had to fork and statically build core to get another resolver plugged in. I'm fairly poor at C so I could totally be missing the obvious.

**Comment by markdroth** [comment]
There is no need to fork core or make any modifications to the library.  You can simply call `grpc_register_plugin()` to register your plugin code before you call `grpc_init()`.

Unfortunately, I don't think we have any good documentation on how to write plugins.

**Comment by mightyguava** [comment]
@markdroth I guess the part I can't seem to wrap my head around is how do I do this from the Python client?

**Comment by markdroth** [comment]
You would need to write the resolver plugin in C, and then have your python code call some C initialization function (either by writing a Python wrapper for the C code directly, or by using something like SWIG) to register the plugin before you initialize grpc in python.

I don't know much about the Cython side of things, but @nathanielmanistaatgoogle may be able to advise further on that.

**Comment by nathanielmanistaatgoogle** [comment]
@soltanmm-google may know more but I'd say that not only do we not offer a means of plugging in a DNS resolve in gRPC Python but this is the first I've ever heard of it being requested.

If it's a matter of calling `grpc_register_plugin` before any call to `grpc_init` I suspect you can do it entirely on your own (with your own language wrapping, Cython or otherwise) and ensuring that your call happens before you allocate any `grpc_init`-calling-on-instantiation object like a `grpc.Channel` or `grpc.Server`.

**Comment by soltanmm-google** [comment]
What @nathanielmanistaatgoogle suggested I think works. Having said that, maaaybe it's worth exposing those functions ourselves and propagating core errors if someone attempts to register a plugin after core initialization.

**Comment by sdorazio** [comment]
I agree with @zhangkun83 that the DNS-based resolver needs to handle periodic refresh. DNS is a common way to manage micro-services, load-balancing, and deployment. Waiting for connection failure to refresh the resolved addresses seems unreliable.

My proposed solution adds a scheduled task to execute as Java's DNS cache expires. The scheduled task is based on the `networkaddress.cache.ttl` environment variable in Java, which dictates the caching behavior. I have verified that this implementation works well with the `RoundRobinLoadBalancer` in our production environment. New instances were added to the load balancer as they became available, and the load was distributed accordingly.

**Comment by ejona86** [comment]
Reviving this discuss a bit: I sort of question if it'd be better to avoid polling but then change reconnecting to generally re-resolve the addresses and wait until the new ones are known. So that's two changes in grpc-java: 1) re-resolve on GOAWAY, 2) wait until resolution before reconnecting. I believe C core is already doing (2). Implementing (2) may be a bit interesting as it may intersect with LB policies/API.

**Comment by ejona86** [comment]
Oh, I failed to mention: the GOAWAY change is to work along with MAX_CONNECTION_AGE from grpc/proposal#23 (which is implemented in all languages). Re-resolving DNS by itself doesn't help if the current connection's address is in the list because the channel will just continue using the current connection.

**Comment by ejona86** [comment]
I think this is resolved. We do DNS refreshes when connections are disconnected. We're not going to solve (2) from above, where we wait for resolution before reconnecting; we're not seeing much problem with the current behavior and it would complicate things considerably. Users have been using MAX_CONNECTION_AGE for a while now and it seems to work.

@zhangkun83, do you agree?

**Comment by zhangkun83** [comment]
@ejona86, do you mean that because MAX_CONNECTION_AGE will close connections which will trigger re-resolution, thus it covers the use case that periodic polling would cover?

**Comment by ejona86** [comment]
@zhangkun83, yes. MAX_CONNECTION_AGE is also controlled by the server, which is better for deployment. In discussions with C and Go folks, I believe we don't have any use-case strongly needing periodic DNS polling (based on a client-side timer). C has shifted their behavior closer to Java/Go's and Go has been avoiding letting their polling frequency be configurable. The C changes are described at https://github.com/grpc/grpc/pull/14170#issuecomment-360563827 . It was seen that grpc-java didn't need to make any changes, because Java keeps a DNS cache; although with JNDI that's changing in #4745.

**Comment by zhangkun83** [comment]
Sounds good. Closing it.

**Comment by markdroth** [comment]
Note that we do still have a long-standing request open to automatically discover new backends when DNS and round_robin are in use (grpc/grpc#12295).  We haven't yet decided what (if anything) to do about it, but we could very well opt to address that by adding an optional ability to automatically re-resolve at some preset interval.

**Comment by ejona86** [comment]
@markdroth, that's a bit of a long issue. Why isn't `MAX_CONNECTION_AGE` sufficient? That works fine with DNS+round_robin, although it causes more connection churn than if you had DNS polling.

**Comment by markdroth** [comment]
That's the work-around that we're currently advertising, but honestly, I think it's kind of a hack.  We should not heve to force connection churn (and the resulting CPU overhead of a new handshake) just to get the client to re-resolve periodically.  If we want the client to re-resolve periodically, I think we should just be able to tell it to do that.
