### ISSUE TITLE
OkHttp may be missing flush after sending headers

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#257]
It looks like we aren't flushing after headers. This works okay because we don't have any tests that don't send data. We should add such a test to AbstractTransportTests and add the flush as appropriate.

https://github.com/grpc/grpc-java/blob/7865b031e1402b9bf2577485ad610db78c068490/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java#L192

On Friday I was playing with a change that allows removing the flush() on headers for unary and server streaming RPCs. We may be more interested in it now.

**Comment by madongfly** [comment]
Actually we do have the emptyStream() test in AbstractTransportTests which doesn't send data, and the header was sent out with the "halfClose".

And I think it's fine to leave the headers being sent with the first data Frame or the "halfClose".

**Comment by ejona86** [comment]
For client-streaming, the RPC can be created and neither half close nor request is sent, yet the call should still start on the server. I can double-check that that is what other people understand/have implemented.

**Comment by madongfly** [comment]
FYI, in Stubby bi-directional streaming, the server will not aware of the stream unless it receives a message or half close.

**Comment by ejona86** [comment]
I asked Abhishek and he confirmed that we would want the HEADERS to be sent.

**Comment by madongfly** [comment]
OK, I'll make a PR then.

**Comment by aholic** [comment]
hello @madongfly
I am stuck in such a scenario:
client send a http request to server (header size: about 1000B, body size: 500B).
As I capture the packet using tcpdump in the server side(I can't make contact with my user who is the client side)
The server got the first 1360B(due to the MTU) quickly.
But after a long time(about 30s), the server got the remain 140B.
And afterwards, the server get a FIN from the client immediately.

Do you think this issue will lead to my scenario? Or any other advice?
It will be nice if you could reply. Thank you very much.

**Comment by ejona86** [comment]
@aholic, you are probably facing something different and we shouldn't use this issue to discuss. This has been closed for well over a year and only applied to client-streaming RPCs. For unary (single request, single response) RPCs, we purposefully flush the headers and body at the same time. The FIN seems fishy, since gRPC wouldn't normally close the connection like that except if the client shutdown the channel and had a deadline on the RPC.

**Comment by aholic** [comment]
Thank you for your reply @ejona86 

I was searching "okhttp flush" and found this issue. Actually the http request in my scenario is not an RPC call. It just a simple request from the client side. So the FIN met my expectation.

It's not easy to illustrate my scenario, but I will try to make it clear for you.
We are the CDN supplier. One of our customers(companies who develop Apps) said that their App will wait for our server for a long time(30s in my scenario) in a probability(statistics in their App, about 0.1%). The wait seems fishy. Because we don't have client, the only thing we can do in the server side is to capture packet for long-time-last request. The packet is mentioned in my previous comment.

From the user-agent header in the packet I captured, I know they were using okhttp2.6.3.
I guess it's a bug in the client. Their client may forget to flush whole body to our server or something like that. So I try to search "okhttp flush" on github. I want to found someone who shares the same scenario. Due to some business reason, I can't demand my customer to check their client code before I am certain of the reason.

Really tough work :- )

I am also looking for help in https://github.com/square/okhttp

Thanks again for your reply.
