### ISSUE TITLE
gRPC 1.1.0 uses wrong Protoc

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2677]
For posterity:

Protobuf team released 3.1.0, which was accidentally built on a developer machine.  This caused the artifacts that were uploaded to Maven central to require glibc 2.14 or later.  This was not noticed at the time, and gRPC Java was changed to depend on 3.1.0.  Later it was [found out](https://github.com/google/protobuf/issues/781)  that this prevented users from using it since they use an older version of glibc.  

Maven central prevents removing or modifying an artifact once released, so Protobuf team uploaded a new version, built from the protoc-artifacts/Dockerfile, which does have the correct dependencies.  This was uploaded as 3.1.0-build2.  Unfortunately, none of the other artifacts of (like the java libraries) were uploaded.

Meanwhile gRPC was unaware of this rename (it happened during the 1.1 release cycle), and was using 3.1.0 successfully since all gRPC developers machines are using a later glibc.  1.1 was cut, but now doesn't build using the docker image, since Protobufs own docker image doesn't contain the dependencies of the artifact.  There are a couple ways forward:

1.  Revert v1.1.0, and rewrite the v1.1.x branch to use the proper protoc artifact.  This will break anyone who depended on the branch or tag in the brief window that it existed.    Once the correct protoc artifact is used, the branch will be rereleased and retagged.  This is probably okay, since the gRPC artifacts have not be released.  One downside is that the protoc and proto java libraries will not match, and will have an inconsistent  `protobufVersion` in the gradle file.
2.  Like 1, it would be possible to just upgrade to 3.2.0.  3.2.0 hasn't been as well tested, but solves the protoc version not matching the proto libraries.  It would also have to be fixed in master
3.  Don't rewrite history, dump the 1.1.0 tag, and move immediately to 1.1.1.  The errors of the past will be set in stone, and 1.1.0 will never exist as an artifact.
4.  Some sort of hack to use the 3.1.0-build2 proto artifact when building the grpc plugin, but keeping the dependencies the same in the gradle file.  This lets us keep the version, but anyone using grpc plugin will be force to use a later glibc.  (2.14 came out in 2011).  This might be okay, assuming that 1.2 will be released soon anyways and have this fixed.

@ejona86 @zhangkun83 thoughts?

**Comment by zhangkun83** [comment]
There are two questions:
### Should we rewrite the history?
I guess since we have not made the release, it's fine to do it.

### How do we make use of `3.1.0-build2`?

The released protoc artifact is used by:
1. Users of gRPC following the instructions from `README.md` to compile there protos.
2. Developers and contributors of gRPC, specifically when working on gRPC codegen, will invoke protoc artifact as programmed in `compiler/build.gradle`.

For (1), we could update `README.md` to use `3.1.0-build2` for `protoc`. The Protobuf and protoc versions are not enforced to be the same.

For (2), maybe we could leave the versions in `build.gradle` as-is, so that there is no inconsistency. This means developers/contributors must have a new version of glibc to work on gRPC codegen, which I think is acceptable. The reason for supporting old glibc is because there are customers running old systems in production, but they should be able to use new versions in dev environment, not to mention that only a small fraction of contributors would ever work on codegen.

**Comment by ejona86** [comment]
Since the tag had already been pushed, we chose to make a new tag 1.1.1. That is why there isn't a 1.1.0 release on maven central while there is a tag for it.
