### ISSUE TITLE
What happen when received many reset frame from grpc server!

### ISSUE THREAD

**Issue by wangjianwen** [grpc/grpc-java#2731]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

grpc v1.0.1
### What JVM are you using (`java -version`)?

jdk8
### What did you do?

If possible, provide a recipe for reproducing the error.

We developed a grpc proxy based on netty.  In grpc proxy, we adapt long connection for connect proxy to grpc server. After Gprc prxoy run some time, we received many reset frame(errorCode=8) from grpc server and have no date frame(endStream=true),  then the proxy dose no work any way.  

### What did you expect to see?
We expect to reveived header frame(endStream=false), data frame(endStream=false), header frame(endStream=true)

### What did you see instead?

But we really reveived header frame(endStream=false), reset frame(errorCode=8)

**Comment by ejona86** [comment]
The RPCs are being cancelled. That is generally caused by the RPC's deadline expiring, but it can happen in other ways. Your proxy should also relay any RST_STREAMS in both the client→server and server→client direction. When RST_STREAM is sent, the stream is considered dead and no more frames will be sent on that stream.

**Comment by yeyincai** [comment]
@ejona86   It can happen in other ways,for example?

We  look   the  log ，discover  RST_STREAM  when proxy  receive  GRPC server  exception data 
[INFO] -  msg=DefaultHttp2HeadersFrame(streamId=664125, headers=DefaultHttp2Headers[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip], endStream=false, padding=0)
[INFO] -  msg=DefaultHttp2DataFrame(streamId=664125, content=UnpooledSlicedByteBuf(ridx: 0, widx: 16384, cap: 16384/16384, unwrapped: PooledUnsafeDirectByteBuf(ridx: 16393, widx: 18432, cap: 32768)), endStream=false, padding=0)
[INFO] - msg=DefaultHttp2DataFrame(streamId=664125, content=UnpooledSlicedByteBuf(ridx: 0, widx: 16384, cap: 16384/16384, unwrapped: PooledUnsafeDirectByteBuf(ridx: 16384, widx: 22103, cap: 32768)), endStream=false, padding=0)
[INFO] -  msg=DefaultHttp2DataFrame(streamId=664125, content=UnpooledSlicedByteBuf(ridx: 0, widx: 5710, cap: 5710/5710, unwrapped: PooledUnsafeDirectByteBuf(ridx: 22103, widx: 22103, cap: 32768)), endStream=false, padding=0)

problem:
1.DefaultHttp2DataFrame   take place  exception，appear three times
2.Stream is no close,endStream=false
What  it happen?

**Comment by wangjianwen** [comment]
I search source codes in grpc-java, netty to find what will cause to reply reset frame to client. There are only two places to reply reset frame in source codes. 

first:
`    @Override
protected void doClose() throws Exception {
    if (!onStreamClosedFired && isStreamIdValid(streamId())) {
        Http2StreamFrame resetFrame = new DefaultHttp2ResetFrame(Http2Error.CANCEL).streamId(streamId());
        writeFromStreamChannel(resetFrame, true);
    }
    super.doClose();
}   `

second:

`@Override
public void onRstStreamRead(ChannelHandlerContext ctx, int streamId, long errorCode) {
    Http2ResetFrame rstFrame = new DefaultHttp2ResetFrame(errorCode);
    rstFrame.streamId(streamId);
    ctx.fireChannelRead(rstFrame);
}`

  The first be called in Http2MultiplexCodec. But Http2MultiplexCodec is not used in grpc. The second be called after client send a reset frame, the grpc prxoy we designed discard reset frame, so proxy never send reset frame to grpc server. So, I don't understand why received reset frame.

**Comment by ejona86** [comment]
@wangjianwen, it looks like you are looking through the "new" (yet unfinished... because of me...) HTTP2 API in Netty. gRPC isn't using that today. The API gRPC is using today doesn't use message passing nor the "child channel" stuff.

Taking a quick look (and ignoring some unlikely places I know rst is sent) for when gRPC code may send RST_STREAM:
 1. If the application calls [`Server.shutdownNow()`](http://www.grpc.io/grpc-java/javadoc/io/grpc/Server.html#shutdownNow--), that turns into [a forcefulClose](https://github.com/grpc/grpc-java/blob/v1.1.2/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L386). This would make sense if many streams closed simultaneously
 2. If the stream is cancelled. That ends up [as closeStream](https://github.com/grpc/grpc-java/blob/v1.1.2/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L374). Reasons for cancel are various, like deadline expiration and maybe some cases of exceptions being thrown. These would generally only impact a single stream.

**Comment by wangjianwen** [comment]
@ejona86 ,thank you for your help! We will carefully read the grpc source code and try to resolve the problem we encountered. Thanks again!
