### ISSUE TITLE
Pass "args" object to LoadBalancer2.SubchannelPicker.pickSubchannel()

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2737]
Right now the method looks like:
```java
public abstract PickResult pickSubchannel(Attributes affinity, Metadata headers);
```

Neither affinity nor headers feels inherent to the method. A bit "random." That is a symptom that we may need to add additional arguments in the future. For example, `MethodDescriptor`. To avoid overload troubles, we should probably just make it an object today. Say, something like:

```java
public abstract class PickSubchannelArgs {
  public Attributes getAffinity() { return Attributes.EMPTY; }
  public abstract Metadata getMetadata();

  // And an example of how we would add things in the future
  public CallOptions getCallOptions() {
    return CallOptions.DEFAULT;
  }
  public MethodDescriptor getMethodDescriptor() {
    return null;
    // or
    // throw new UnsupportedOperationException();
  }
}
```

**Comment by zhangkun83** [comment]
A transition plan may look like

1. In the next release, old `SubchannelPicker` is still working, but will switch to implement the new signature: 
```java
abstract class SubchannelPicker {
  @Deprecated
  public PickResult pickSubchannel(Attributes affinity, Metadata headers) {
    return pickSubchannel(new PickSubchannelArgsImpl(affinity, headers));
  }
  public PickResult pickSubchannel(PickSubchannelArgs args) {
    return pickSubchannel(args.getAffinity(), args.getHeaders());
  }
}
```
2. In the subsequent release, delete the old signature

If we do this, it has to be done as a `1.1.x` patch release, because `1.2` is going to have LBv2 API promoted, which is a API-breaking change anyway.

/cc @lukaszx0 @jhspaybar
