### ISSUE TITLE
Use CallOptions.withOptions instead of withAffinity

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2738]
`withAffinity` is a full `Attributes` to be type-safe, but it will generally only have one entry and _sometimes_ two. In more recent times we've added `withOptions`. This seems it could just use it instead. This would mean the `LoadBalancer` would be passed `CallOptions` instead of `Attributes affinity`, but that doesn't seem too bad.

Probably want to do #2737 at the same time as fixing this.

**Comment by zhangkun83** [comment]
The transition plan:

1. In the next release, mark `CallOptions.withAffinity()` and `getAffinity()` as deprecated
2. In the subsequent release, delete them.

**Comment by zhangkun83** [comment]
@lukaszx0 @jhspaybar

**Comment by infinityat0** [comment]
So, are you guys suggesting that the loadbalancer would get callOptions instead of affinity?

With that change, I'm expecting SubChannelPicker method to change from 
`public abstract PickResult pickSubchannel(Attributes affinity, Metadata headers);`

to 

`public abstract PickResult pickSubchannel(CallOptions options, Metadata headers);`

**Comment by lukaszx0** [comment]
@infinityat0 this is what has been already done in #2740 linked above.

**Comment by infinityat0** [comment]
@lukaszx0 Perfect. Which release are we to expect this change?

**Comment by lukaszx0** [comment]
@infinityat0 It'll be included in 1.2 (if you'll go to aforementioned PR, you can see that it's part of 1.2 milestone)

**Comment by infinityat0** [comment]
@lukaszx0 Oops! didn't notice that. Thank you!
