### ISSUE TITLE
Server does not send initial metadata on a stream with no messages

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc-java#2770]
The [gRPC wire spec](http://www.grpc.io/docs/guides/wire.html#responses) says:

> Most responses are expected to have both headers and trailers but Trailers-Only is permitted for calls that produce an immediate error. 

However, the only time that headers are sent by a Java server is in when `onNext()` is called (see [ServerCalls.java#L282]( https://github.com/grpc/grpc-java/blob/e67b6027afd57e8984d432f7a0ed68b46ffea00a/stub/src/main/java/io/grpc/stub/ServerCalls.java#L282)). This means that a stream where the server's behavior should be to send initial and trailing metadata (i.e., close the stream with no outbound messages), instead gRPC sends out a Trailers-Only response, skipping any initial metadata.

This popped up on the existing interop tests when PHP and Node were not setting the `response_parameters` field in the [`custom_metadata`](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#custom_metadata) interop test. See https://github.com/grpc/grpc/commit/ced8702d1d184fe83bbdcdfc97868a9f94868986. These tests are now passing since the test spec says to set the `response_parameters` field, and so the interop server calls `onNext()` to send the appropriate response(s).

But, if the wire spec's statement should be interpreted as Trailers-Only should only be sent for calls with an immediate error, this is a bug in Java's implementation. Even if Trailers-Only is a legal response even without errors, it seems like the Trailers-Only message should include any header metadata.

It seems to fix things to add the following check to `ServerCalls$ServerCallStreamObserverImpl#onCompleted()`, but I haven't tested this extensively enough to be sure this doesn't cause problems elsewhere:

```
    @Override
    public void onCompleted() {
       if (cancelled) {
         throw Status.CANCELLED.asRuntimeException();
       } else {
+        if (!sentHeaders) {
+          call.sendHeaders(new Metadata());
+          sentHeaders = true;
+        }
         call.close(Status.OK, new Metadata());
       }
    }
```

**Comment by ejona86** [comment]
> But, if the wire spec's statement should be interpreted as Trailers-Only should only be sent for calls with an immediate error

I don't think it should be read that way. It is undefined whether a zero-message stream has Response-Headers. While it is a Good Idea™ to use Trailers-only (even for OK), it is an implementation detail. And I think we want to keep it that way (although we may want our implementations to behave a particular way). I'm aware of no reason to use Response-Headers if the implementation knows Trailers-Only would suffice.

There are two reasons I'm aware of to have Response-Headers on a zero-message stream:
1. To inform the client the server is processing, or to provide particular metadata in the headers while the RPC is progressing. That is, the server needs to communicate with the client before it's able to send the Trailers.
2. The server doesn't know the future and so sends headers without realizing that Trailers-Only would have sufficed. This is more of an API/coding detail.

> Even if Trailers-Only is a legal response even without errors, it seems like the Trailers-Only message should include any header metadata.

Not quite that easy. Response-Headers vs Trailers/Trailers-Only is semantically important. gRPC should not move/copy information from one to the other, as that is asking for causing bugs in applications.

So while I don't think the gRPC implementation should be changed, maybe the _interop spec_ should. The problem may be that "initial metadata" isn't really defined in the [Echo Metadata server feature](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#echo-metadata). If that was clarified, then the interop implementation in Java could possibly include `x-grpc-test-echo-initial` in the case of Trailers-Only.

> It seems to fix things to add the following check to `ServerCalls$ServerCallStreamObserverImpl#onCompleted()`

That is insufficient because Java permits using `ServerCall` directly. To _guarantee_ the behavior we'd need to do something within the `ServerCall` itself, but that would circumvent interceptors. So the only technical solution is to break our `ServerCall` API, but we can't do that. It also wouldn't change previous implementations.
