### ISSUE TITLE
Tracking issue for Monitoring Service being Experimental

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc-java#2776]

**Comment by songy23** [comment]
OpenCensus java is preparing for a major API release recently, and we plan to update gRPC to use our new APIs. As I noticed the [Monitoring service](https://github.com/grpc/grpc-java/blob/master/services/src/main/java/io/grpc/services/MonitoringUtil.java) is still using the old census proto, which won't work with our new data models. Since OpenCensus hasn't updated the proto yet, can we remove these monitoring services for now?

/cc @dinooliva @sebright @zhangkun83

**Comment by zhangkun83** [comment]
My understanding is that the old API (and impl) will keep working because they have different names. Is it not the case?

**Comment by songy23** [comment]
That's right, they'll have different names.

**Comment by larry-safran** [comment]
All references in code have been removed
