### ISSUE TITLE
It might be a mistake returning type of ManagedChannelBuilder<?>.

### ISSUE THREAD

**Issue by lovepocky** [grpc/grpc-java#2813]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.1.2

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.

when I use grpc-java in scala,
for example
```
val channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).asInstanceOf[ManagedChannelBuilder[_]].build
```
the method `forAddress` returns `ManagedChannelBuilder<?>`,
so I have to add `asInstanceOf[ManagedChannelBuilder[_]]`.
otherwise, i can't call `build` of a object with `Any` type .

### What did you expect to see?
I think that `forAddress` might return `ManagedChannelBuilder<? extends ManagedChannelBuilder<?>>`.

**Comment by dapengzhang0** [comment]
What's the particular error message if not adding `asInstanceOf[ManagedChannelBuilder[_]]`?

Did you test that `ManagedChannelBuilder<? extends ManagedChannelBuilder<?>>` works? I think it still has problem, because the two wildcards are totally independent, the first wildcard became bounded but the second is still unbounded.

**Comment by lovepocky** [comment]
![image](https://cloud.githubusercontent.com/assets/10250869/23882506/04015a0e-089c-11e7-8383-4605366b84c1.png)
The program works well without `asInstanceOf`, even though the IDE gives an warning. 
Maybe this is a bug of intellij.

**Comment by ejona86** [comment]
Since `ManagedChannelBuilder` is defined as `ManagedChannelBuilder<T extends ManagedChannelBuilder<T>>`, the `?` represents a `ManagedChannelBuilder` in normal Java. I agree that it's not clear `ManagedChannelBuilder<? extends ManagedChannelBuilder<?>>` would even work around the problem. But maybe `<T extends ManagedChannelBuilder<T>> ManagedChannelBuilder<T>` would. I'd want to make sure there is a bug against IntelliJ or Scala before we try to workaround this.

**Comment by xuwei-k** [comment]
Scala 2.10

```
Welcome to Scala version 2.10.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions to have them evaluated.
Type :help for more information.

scala> io.grpc.ManagedChannelBuilder.forAddress("dummy", 1234).usePlaintext(true).build
<console>:8: error: value build is not a member of ?0
              io.grpc.ManagedChannelBuilder.forAddress("dummy", 1234).usePlaintext(true).build
                                                                                         ^
```

Scala 2.11 or later

```
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.

scala> io.grpc.ManagedChannelBuilder.forAddress("dummy", 1234).usePlaintext(true).build
res0: io.grpc.ManagedChannel = io.grpc.internal.ManagedChannelImpl@53999eb
```

**Comment by ejona86** [comment]
Woo! That looks like it was a Scala bug that has been fixed. @xuwei-k, you agree this can be closed?

**Comment by xuwei-k** [comment]
> you agree this can be closed?

👍
