### ISSUE TITLE
io.netty.handler.codec.http2.internal.hpack.Decoder removed in netty 4.1.9 Fina

### ISSUE THREAD

**Issue by xiangsky** [grpc/grpc-java#2841]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.1.2 / 1.2.0
 
### What JVM are you using (`java -version`)?
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

io.netty.handler.codec.http2.internal.hpack.Decoder been removed in the Netty 4.1.9 fina

**Comment by carl-mastrangelo** [comment]
That class was not removed, it just moved up a directory.  We know, and it is the reason why we haven't upgraded to Netty 4.1.9.

**Comment by beihaifeiwu** [comment]
+1

**Comment by nmittler** [comment]
@carl-mastrangelo @ejona86 

I've got a fix for this that will go into Netty 4.1.10.Final (https://github.com/netty/netty/pull/6589)

Also, I've got the [gRPC changes necessary for the upgrade](https://github.com/nmittler/grpc-java/commit/b42aec0c2f5cf976c05bc53b288b38a65ad5b187).  I think I'll just hand this off so that one of you can clean it up after the Netty release and run it through your import/presubmit workflow to make sure nothing is broken.  Sound good?

**Comment by carl-mastrangelo** [comment]
@nmittler excellent.  When 4.1.10 comes out I can merge this.

**Comment by nmittler** [comment]
@carl-mastrangelo SGTM, thanks!

Also, I just merged netty/netty#6589, so we'll be good to go.

**Comment by beihaifeiwu** [comment]
@nmittler I have seen that netty 4.1.10 is released

**Comment by guillaumecle** [comment]
Any progress on this?
In https://github.com/netty/netty/pull/6594, netty exposes the interface to be used by grpc for it's custom hpack decoder.

**Comment by eiswind** [comment]
+1 for spring reactive users
