### ISSUE TITLE
Don't block for settings frame

### ISSUE THREAD

**Issue by TamalSaha** [grpc/grpc-java#2862]
We are using gRPC 1.0.5. We server is implemented in Go and we use Java client. We are trying to use the wonderful https://github.com/soheilhy/cmux library to run both the grpc server and grpc gateway server on the same port. The issue is since Java gRPC client blocks until it receives a SETTINGS frame from the server, cmux has to do additional processing which results in very high cpu usage.

https://github.com/soheilhy/cmux/issues/40#issuecomment-290269251

My question is can Java clients can not block for SETTINGS frame and be more like go clients?

cc: @soheilhy, @sadlil

**Comment by carl-mastrangelo** [comment]
Not sure what you mean by blocks, gRPC and its delegate networking library Netty are pretty much non blocking to the core.

**Comment by TamalSaha** [comment]
By blocks, I mean, grpc client does not return any result. @soheilhy, do you mind explaining?

**Comment by soheilhy** [comment]
Hi @carl-mastrangelo, For some reason, unlike C and Go HTTP2, Netty sends a SETTINGS frame, and waits for the other side to reply with a SETTINGS frame. Because of that, in cmux, I have added a hack to reply back with a spoofed SETTINGS frame solely for getting the HEADERS frame from Java gRPC. This results in high CPU consumption in production workloads that want to use cmux and have Java gRPC clients.

Netty's behavior is indeed standard compliant, but it would lower the latency if it sends the HEADERS frame without waiting to receive SETTINGS (and also there'd be no need to spoof in cmux). Do you think that's feasible to do in Netty?

**Comment by carl-mastrangelo** [comment]
The code in question that causes this is here: 

https://github.com/grpc/grpc-java/blob/v1.2.0/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L636

It isn't an artifact of Netty.  When the first settings frame is received, all the queued RPCs are drained from the DelayedClientTransport.  I don't think there is anything too bad with moving that callback to channelActive.  The behavior was changed in https://github.com/grpc/grpc-java/pull/852  to fix a bug where data was sent before knowing the TCP connection was alive (issue https://github.com/grpc/grpc-java/issues/829)

@ejona86 might have more thoughts.

**Comment by soheilhy** [comment]
Ah, thanks! moving the callback to channelActive sounds awesome!

**Comment by ejona86** [comment]
> unlike C and Go HTTP2

I thought all of us are doing the same thing. This behavior comes in part due to the defined ["Reset Backoff"](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md#reset-backoff).

Basically, our internals don't have a distinction between "it is safe to send an RPC" and "this connection was successful." So the proposed movement of code to `channelActive` wouldn't actually suffice. We'd need to introduce a [new ManagedClientTransport.Listener callback](https://github.com/grpc/grpc-java/blob/v1.2.0/core/src/main/java/io/grpc/internal/ManagedClientTransport.java#L113).

> I have added a hack to reply back with a spoofed SETTINGS frame solely for getting the HEADERS frame from Java gRPC

Can you explain a bit more why that is necessary? Why isn't the server sending the SETTINGS frame?

> but it would lower the latency if it sends the HEADERS frame without waiting to receive SETTINGS

TLS resumption and false start can avoid the delay when using TLS. TCP fast open could avoid it with TCP.

While I'm okay with avoiding waiting from the SETTINGS from an optimization standpoint, I'm not comfortable guaranteeing that we will never wait for the SETTINGS.

**Comment by ejona86** [comment]
Actually, we can't move it to channelActive, because we must wait until TLS is done since the SslHandler says you aren't supposed to call it until the initial handshake is done. That means that the _negotiator_ needs to have another callback as well, to tell us when TLS is complete.

**Comment by soheilhy** [comment]
> Can you explain a bit more why that is necessary? Why isn't the server sending the SETTINGS frame?

[cmux](https://github.com/soheilhy/cmux) is a library to do port-sharing based on protocol signatures. It sniffs the payload and decides which server/protocol should serve the connection. So, the actual server wouldn't see the connection payload until cmux hands off the connection to that server. For gRPC, and HTTP2 in general, cmux cannot do any meaningful matching without getting the HEADERS frame.

Ideally, that is supposed to be done as a read-only matcher, and it's done for C and Go gRPC.

**Comment by ejona86** [comment]
> For gRPC, and HTTP2 in general, cmux cannot do any meaningful matching without getting the HEADERS frame.

Why is that? It seems like you would be forced to use a different connection for each RPC. Is that the case?

**Comment by soheilhy** [comment]
This is because all the important metadata, used by users of cmux to demux their connections, is in the HEADERS frame. For example, if you want to send HTTP2 traffic on one listener and gRPC on another one, you need that. Basically, you can't tell if a connection is gRPC unless you see the headers frame.

**Comment by ejona86** [comment]
> For example, if you want to send HTTP2 traffic on one listener and gRPC on another one, you need that.

Okay. That's what I was looking for. You are separating normal HTTP/2 traffic and gRPC traffic. And you don't mix types on a particular connection. I guess I see some of that documented in the cmux readme.

**Comment by soheilhy** [comment]
Exactly, and here is another example in case that helps clarifying the usecase:
https://github.com/soheilhy/cmux/blob/master/example_test.go#L115

**Comment by ejona86** [comment]
I talked with the C core devs and there was also some concern of relying on the current behavior (they believe C core doesn't wait for SETTINGS). Multiple things arrive in the initial SETTINGS and things get a bit fuzzy without waiting. While an implementation may not wait today, it seems a bit worrisome to depend on it never waiting.

**Comment by TamalSaha** [comment]
> I talked with the C core devs and there was also some concern of relying on the current behavior (they believe C core doesn't wait for SETTINGS). Multiple things arrive in the initial SETTINGS and things get a bit fuzzy without waiting. While an implementation may not wait today, it seems a bit worrisome to depend on it never waiting.

Does this mean something like cmux might have to fake SETTINGS frame for C/Go grpc clients at some point?

**Comment by ejona86** [comment]
> Does this mean something like cmux might have to fake SETTINGS frame for C/Go grpc clients at some point?

Yes. It means that C/Go could behave like Java in the future.
