### ISSUE TITLE
Improve documentation of contract of io.grpc.Call

### ISSUE THREAD

**Issue by wrwg** [grpc/grpc-java#290]
This class seems to be underspecified. A couple of issues which can't be easily derived:

- Can request(N) be called multiple times before the next payload is received, and is it accumulating.
- If not accumulating, what does it mean if request(0) is called after request(N) but before payload is received. Does it suppress the already scheduled output? How strong is the contract that there are never more than N responses?
- Can there be race conditions for request() calls and onPayload() calls on the listener.
- Is request() always be called before sendPayload() or can it be also called afterwards.
- What happens if any of the Call methods is called after halfClose, cancel, or onClose.
- if cancel is called, should it eventually report onClose(Status.CANCELLED) on the listener.

There might be more. Ideally we would specify the allowed sequences and interferences between call and listener.

I may follow up with a suggestion for the spec later.

**Comment by ejona86** [comment]
Bullet 1 and 2: Adding this seems like it would address them:
"If called multiple times, the number of messages able to be delivered will
be the sum of the calls."

We should also probably say something about how numMessages "must be positive." (or non-negative).

Bullet 3: No, there can't be a race, because you can't take back tokens you've given.

Bullet 4: request() and sendPayload() can be in any order. The only restrictions are those that apply to all methods in Call: start must be first, and nothing can follow cancel. It seems that is not well documented either, as we are missing the @throws IllegalStateException for request.

Bullet 5: This behavior seems to be well documented, except for request(). But we could explicitly say there is no interaction between the states on the Listener and Call: i.e., if Listener.onClose is called that has no bearing on the permitted operations on Call (but it may impact whether they do anything).

Bullet 6: Maybe. There is a race for whether cancel() has any effect (because the RPC could completed/fail in other ways). But we should specify that onClose(CANCELLED) is called if cancel() won the race.

**Comment by ejona86** [comment]
In 813, the documentation for request was changed to include:
`@throws IllegalStateException if call is already {@code halfClose()}d or {@link #cancel}ed`

However, that is incorrect. `request()` _must_ be allowed after `halfClose()`, otherwise server-streaming will deadlock.

The part concerning cancelled can be fine (although I do question if we want that behavior), but is not the current behavior of `ClientCallImpl`. The documentation and implementation should agree.
