### ISSUE TITLE
OkHTTP should stop using SSLCertificateSocketFactory

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2932]
The next version of Android will not work with setting ALPN protocols using `SSLCertificateSocketFactory`.  Instead, the recommended way is to reflectively find [`setAlpnProtocols`](https://android.googlesource.com/platform/external/conscrypt/+/f087968/src/main/java/org/conscrypt/OpenSSLSocketImpl.java#1438) on the created socket, and not directly reference `SSLCertificateSocketFactory` at all.  

From my understanding, setting the protocols using this class currently will become an effective no-op, because the protocols will already be set.

@kruton

**Comment by 15characterlimi** [comment]
I think there are still some misunderstandings here. Chiefly, this bug is in grpc, not in OkHttp. The bug affects all versions of Android, but is exposed more clearly (breaking apps) in the next version of Android. The issue is that ALPN is not supported on sockets constructed by SSLCertificateSocketFactory; you should probably avoid using that class at all. Because of this, grpc's use of ALPN doesn't work on any version of Android. To fix this, you should be using SSLSocketFactory.getDefault() or similar.

I've commented on internal bug 33090882 with more details.

**Comment by ejona86** [comment]
When we say "OkHttp" here we are talking about grpc's OkHttp transport. That may be a bug in grpc or a bug in OkHttp itself. Generally it is a bug in grpc, given how much grpc re-implements.

This is opening up a can of worms. It was really hard to arrive at the current behavior, due to applications needing to override our defaults and it seemed that only SSLCertificateSocketFactory performed the correct checks (like hostname verification). IIRC SSLSocketFactory was a dead-end.

**Comment by 15characterlimi** [comment]
I know that grpc carries a forked copy of OkHttp 2.5. What I was saying is that the code is outside of that forked copy of OkHttp. But now I can no longer find grpc's dependence on SSLCertificateSocketFactory? I think it was in a class GrpcClient but perhaps that was outside grpc altogether, on the client/app side?

I don't know the details of "hard to arrive at the current behavior". But you should be aware that the current behavior (in the app I debugged - please check out internal bug reference 33090882) is broken: grpc's logic for configuring ALPN on the socket never works when the socket has already done its handshake, which is the case for all sockets that come out of a SSLCertificateSocketFactory. Can of worms or not, this needs to be fixed.

**Comment by ejona86** [comment]
Apparently we don't use SSLCertificateSocketFactory. I remember it was going to be a pain. I think we ended up doing the hostname verification "ourselves" via [OkHostnameVerifier](https://github.com/grpc/grpc-java/blob/v1.2.0/okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/OkHostnameVerifier.java).

> grpc's logic for configuring ALPN on the socket never works when the socket has already done its handshake

Yes, I am aware of that. Some Apps configure things already, and if they do we are forced to trust them. If we're able to do the configuration, we do. Pretty ugly, but best of limited options.

It does seem a specific app's configuration is likely at cause here. Let's do some more testing with default gRPC defaults and if those are fine we'll just focus on fixing apps.

**Comment by 15characterlimi** [comment]
Ah, I think you're right. I thought the part of the code that used the SSLCertificateSocketFactory was part of grpc but I think it's actually part of the app. 

So I think this was probably a false alarm, sorry. It's late here but I will have another look tomorrow and confirm (will try to get one of the app developers to talk to).
