### ISSUE TITLE
Graceful shutdown gRPC in Tomcat

### ISSUE THREAD

**Issue by Zeymo** [grpc/grpc-java#2972]
My company uses WAR as the standard deployment mechanism so we use Tomcat deploying and undeploying application.
Since I provider gRPC server in Tomcat like below
```
@WebListener
public class ServletContextListener implements ServletContextListener {

    private Server server;

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    server = ServerBuilder.forPort(2017).addService(new H2cService()).build();
                    server.start();
                    server.awaitTermination();
                } catch (Exception e) {
                    throw new RuntimeException("start h2c error", e);
                }
            }
           }).start();
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {
        server.shutdown();
    }
}
```

and it occur Tomcat memory leak warnning
 > WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [grpc-shared-destroyer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

so what is right way to start and graceful shutdown gRPC in Tomcat ?

**Comment by carl-mastrangelo** [comment]
You need to actually await shutdown in the thread that called shutdown.  Otherwise, the thread that calls `contextDestroyed` will return immediately, leaving the thread created in `contextInitialized` still around.  

In the future, please use stack overflow or our [support forum](https://groups.google.com/forum/#!forum/grpc-io) for these types of questions.  You will get better answers, and they will be more discoverable.
