### ISSUE TITLE
OkHttp is incompatible with newer C-core binaries

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#3032]
As reported by grpc/grpc#11258. This is caused by grpc/proposal#19 and [a bug](https://github.com/grpc/grpc-java/blob/v1.3.0/okhttp/third_party/okhttp/java/io/grpc/okhttp/internal/framed/Http2.java#L304) in the OkHttp transport that doesn't ignore unknown settings frames (as required by the [HTTP/2 spec](http://httpwg.org/specs/rfc7540.html#rfc.section.6.5.2)).

It's unclear how this wasn't caught in the integration tests.

**Comment by makdharma** [comment]
@ericgribkoff to test in the Android interop he's working on.

**Comment by ejona86** [comment]
We don't run okhttp interop externally (full cross-product testing), but we do internally. We think the breaking change was delayed being brought internally for long enough that it was released without the test having failed yet.

**Comment by ericgribkoff** [comment]
Created https://github.com/grpc/grpc-java/pull/3036 to address this, although I'm not sure what restrictions we have with modifying the third_party okhttp code. The bug was noticed on OkHttp3 (https://github.com/square/okhttp/pull/2299), although I believe their fix still fails for the experimental settings ids used by C++.

> We don't run okhttp interop externally (full cross-product testing), but we do internally. We think the breaking change was delayed being brought internally for long enough that it was released without the test having failed yet.

This appears to have been the case. 

I did some work to add a gRPC Java OkHttp client to the grpc/grpc interop test suite, but encountered some issues with getting our test certificates working with OkHttp. I will look further into this tomorrow, as it seems like we definitely should be testing OkHttp clients as part of our external interops, to (help) avoid issues like this.

**Comment by ejona86** [comment]
This was fixed in #3036
