### ISSUE TITLE
MessageFramer produces too small message chunks

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-java#312]
MessageFramer uses

bufferAllocator.allocate(maxFrameSize) 

to produce chunks that the transport can write. Currently these chunks are always 4096 bytes regardless of transport or payload size.

Transports cannot coalesce these chunks and typically end up writing each one in a syscall. For large payloads this really hurts performance. Instead we should delegate to the buffer allocator and ask it to produce a chunk up to the payload size. E.g.

bufferAllocator.allocate(len)

Experimentation with HBase has shown that for a 51k payload this reduces syscalls on write by 3x.

**Comment by ejona86** [comment]
This change shouldn't change OkHttp much because 1) it will still use 2K sharded buffers under the covers and 2) it has [some extra buffering in place](https://github.com/grpc/grpc-java/blob/4bc2d6d9a4f3a0c8e035393d6de5c999472cfc45/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java#L298). However, it could benefit from fewer Runnables being added to the write executor.

In looking at Netty, the Nio implementation [is not](https://github.com/netty/netty/blob/da01902ea2216f6cbf9d1b2e0cd80d3b879af06b/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L200) currently using scatter/gather. The Epoll implementation [is](https://github.com/netty/netty/blob/acb6902f6850fda2e189dd7eabf40b348db2631a/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L109).

I really expect our long-term design to favor proper flushing and scatter/gather. Given those, I have a hard time determining what ways large buffers will impact performance (positive or negative).

**Comment by ejona86** [comment]
Apparently Nio [does use writev](https://github.com/netty/netty/blob/da01902ea2216f6cbf9d1b2e0cd80d3b879af06b/transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java#L300).

**Comment by nmittler** [comment]
Fixed by #313
