### ISSUE TITLE
proto-google-common-protos is built with Java 1.7

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc-java#3152]
Tracking issue to follow-up on https://github.com/googleapis/googleapis/issues/333#issuecomment-299289896. gRPC's status proto, and soon/now the example directory's error details proto (https://github.com/grpc/grpc-java/pull/3151), come from `com.google.api.grpc:proto-google-common-protos`, which is built with Java 1.7. My understanding is that this is fine as long as the `proto-google-common-protos` jar is bytecode compatible with Java 1.6, but this should be investigated.

**Comment by dapengzhang0** [comment]
Seems we can not build `grpc-protobuf` with JDK 6:
```
$./gradlew :grpc-protobuf:build -PskipCodegen=true
io.grpc.protobuf.StatusProtoTest > initializationError FAILED
    java.lang.UnsupportedClassVersionError: com/google/rpc/Status : Unsupported major.minor version 51.0
8 tests completed, 1 failed, 1 skipped
:grpc-protobuf:test FAILED
```

**Comment by dapengzhang0** [comment]
More precisely, it can build, but running test will fail.

> Seems we can not build `grpc-protobuf` with JDK 6:
> ```
> $./gradlew :grpc-protobuf:build -PskipCodegen=true
> io.grpc.protobuf.StatusProtoTest > initializationError FAILED
>     java.lang.UnsupportedClassVersionError: com/google/rpc/Status : Unsupported major.minor version 51.0
> 8 tests completed, 1 failed, 1 skipped
> :grpc-protobuf:test FAILED
> ```

**Comment by dapengzhang0** [comment]
If a user is trying to run grpc library with JRE 6 and use `io.grpc.protobuf.StatusProto`, then they should never put [`com.google.api.grpc:proto-google-common-protos:0.1.9`](https://search.maven.org/remotecontent?filepath=com/google/api/grpc/proto-google-common-protos/0.1.9/proto-google-common-protos-0.1.9.jar) in the class path due to the above `UnsupportedClassVersionError`; instead, they can first compile the source files `Status*.java` in [`com.google.api.grpc:proto-google-common-protos:0.1.9:sources@jar`](https://search.maven.org/remotecontent?filepath=com/google/api/grpc/proto-google-common-protos/0.1.9/proto-google-common-protos-0.1.9-sources.jar) into a JAVA 6 compatible output and then add it in the class path, and that will work.

**Comment by dapengzhang0** [comment]
Closing as we have dropped Java 6 support #3961.
