### ISSUE TITLE
how to pass exception cause from server to client

### ISSUE THREAD

**Issue by SeriousMa** [grpc/grpc-java#3494]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
1.8

### What did you do?
server throw IndexOutOfBoundsException 
`
observer.onError(new StatusRuntimeException(Status.INTERNAL.withCause(new IndexOutOfBoundsException()).withDescription(e.getCause().getClass().getName() + ":" + e.getCause().getMessage()), metadata));
`
client receive StatusRuntimeException but inside cause is null

![image](https://user-images.githubusercontent.com/464213/30791023-5c7b169a-a1e2-11e7-83d7-7a50a35139f0.png)

### What did you expect to see?
client receive IndexOutOfBoundsException

### What did you see instead?

client receive StatusRuntimeException but inside cause is null

**Comment by ejona86** [comment]
The cause is for local propagation of additional error information. You could use an interceptor to copy the cause to the Metadata (as text). You should probably only keep the first 1 KB or so of the text, otherwise you risk exceeding the client's max header list size (the sum of all headers) of 8 KB.
