### ISSUE TITLE
Bazel java_grpc_library(flavor="lite") doesn't work out-of-the-box

### ISSUE THREAD

**Issue by fis** [grpc/grpc-java#3585]
### What version of gRPC are you using?
Git master (@8187f1e)

### What JVM are you using (`java -version`)?
1.8.0_144

### What did you do?
Configured a Bazel project with `@grpc_java` pointing at this codebase (and protobuf deps as per the Bazel native protobuf rules, pointing at latest protobuf code), added a `java_grpc_library(..., flavor = "lite")` rule.

### What did you expect to see?
Successfully generated & compiled code from `bazel build`.

### What did you see instead?
A number of different build problems, starting with `no such package '@com_google_protobuf_java_lite//'`. Details for working around them below.

---

I've managed to successfully build an Android client using a lite-proto java_grpc_library, but it involved doing the following changes:

#### Adjust deps added by the `java_grpc_library` macro

```diff
--- a/java_grpc_library.bzl
+++ b/java_grpc_library.bzl
@@ -109,14 +109,19 @@ def java_grpc_library(name, srcs, deps, flavor=None,
   added_deps = [
       "@grpc_java//core",
       "@grpc_java//stub",
-      "@grpc_java//protobuf",
       "@com_google_guava_guava//jar",
   ]
   if flavor == "normal":
-    added_deps += ["@com_google_protobuf_java//:protobuf_java"]
+    added_deps += [
+        "@com_google_protobuf_java//:protobuf_java",
+        "@grpc_java//protobuf",
+    ]
   elif flavor == "lite":
     # TODO: This is currently blocked on https://github.com/google/protobuf/issues/2762
-    added_deps += ["@com_google_protobuf_java_lite//:protobuf_java_lite"]
+    added_deps += [
+        "@com_google_protobuf_javalite//:protobuf_java_lite",
+        "@grpc_java//protobuf-lite:protobuf_lite",
+    ]
   else:
     fail("Unknown flavor type", "flavor")
```

This removes `@grpc_java//protobuf` from being added unconditionally, as it was pulling in the non-lite protobuf runtime into the resulting APK. It's replaced by `@grpc_java//protobuf-lite:protobuf_lite` instead. It also renames the javalite remote repository from `@com_google_protobuf_java_lite` to `@com_google_protobuf_javalite`, because the latter name seems more "canonical", in the sense that it's what Bazel native `java_lite_proto_library` rules implicitly depend on.

Note that the [protobuf issue 2762](https://github.com/google/protobuf/issues/2762) referred in the TODO has been closed for a while now.

#### Make `//protobuf-lite:protobuf_lite` visible

```diff
--- a/protobuf-lite/BUILD.bazel
+++ b/protobuf-lite/BUILD.bazel
@@ -4,12 +4,12 @@ java_library(
         "src/main/java/**/*.java",
     ]),
     # TOOD(zdapeng): fix visibility and deps (https://github.com/google/protobuf/issues/2762)
-    visibility = ["//protobuf:__pkg__"],
+    visibility = ["//visibility:public"],
     deps = [
         "//core",
         "//core:internal",
         "@com_google_code_findbugs_jsr305//jar",
         "@com_google_guava_guava//jar",
-        "@com_google_protobuf_java//:protobuf_java",
+        "@com_google_protobuf_javalite//:protobuf_java_lite",
     ],
 )
```

I'm not sure if `//visibility:public` is the right choice, but it matches the `//protobuf:protobuf` target. I've also changed the protobuf dependency from `protobuf_java` to `protobuf_java_lite`, as this was again pulling the non-lite runtime in the resulting APK. Ditto for the issue in the TODO.

#### Add missing indirect dependency to `//stub`

```diff
--- a/stub/BUILD.bazel
+++ b/stub/BUILD.bazel
@@ -8,6 +8,7 @@ java_library(
         "//context",
         "//core",
         "@com_google_code_findbugs_jsr305//jar",
+        "@com_google_errorprone_error_prone_annotations//jar",
         "@com_google_guava_guava//jar",
     ],
 )
```

`AbstractStub`'s `@DoNotMock` annotation was causing a "[strict] Using type com.google.errorprone.annotations.DoNotMock from an indirect dependency" build error.

---

If you think these are changes that should actually be made upstream, I'm happy to submit them as a PR (though they're pretty trivial).

Two caveats:
* I still have a "DEBUG: Multiple values in 'deps' is deprecated" warning from my `java_grpc_library` rule, because I had to list the `java_lite_proto_library` targets of all the messages used by my service. It's possible I'm misconfiguring this. Should I instead put all the `proto_library`s as `deps` of a single `java_lite_proto_library`? How would I share those with Java code that doesn't need gRPC?
* I couldn't figure out how to make well-known protos to work. I think that's an instance of [protobuf issue 1889](https://github.com/google/protobuf/issues/1889).

**Comment by fis** [comment]
Forgot to mention: this was using the latest Bazel release (0.6.1).

**Comment by ejona86** [comment]
Haven't looked at all this yet, but since protobuf_lite is available from protobuf upstream, this should be possible. Thanks. I didn't realize that https://github.com/google/protobuf/issues/2762 had been closed (apparently, I didn't subscribe...).

Quick notes:
* We'll want separate `_android`-suffixed targets for things that need both protobuf and protobuf_lite versions (like grpc-protobuf-lite).
* The "DEBUG: Multiple values in 'deps' is deprecated" warning needs to be removed from the java_grpc_library. Previously it was an anti-pattern, but now it is required because Bazel started to enforce strict deps for protobuf. The fact that you need to list multiple deps is a workaround; we need some new support added to Bazel to avoid the strict_deps check.

**Comment by gorset** [comment]
Any news on getting grpc-java + lite working with bazel?

I've been digging into the protobuf code, and vanilla protobuf-java is using boxed integer lists while lite has primitive integer lists. I'm curious to test the performance difference in our system, but have been blocked so far by the lack of lite support with bazel and grpc-java.

**Comment by ejona86** [comment]
I worked on it some last week, but needed to have some discussions with Bazel team to figure out how I can use `select()` to avoid requiring duplicated targets for gRPC and its users. There was a Bazel conference last week though and the devs are using the occasion to meet face-to-face a lot, so I don't think they've had time for me yet.

It's one of these things where getting only Lite working is fine and getting only Full working is fine, but getting both working for different users is more difficult. Specifically, grpc-java/protobuf-lite depends on full protobuf today, because grpc-java/protobuf needs full proto.

**Comment by ejona86** [comment]
I think #4289 fixed this.
