### ISSUE TITLE
Examples load with errors in Eclipse

### ISSUE THREAD

**Issue by ndandanov** [grpc/grpc-java#3666]
### What version of gRPC are you using?
1.7.0

### What JVM are you using (`java -version`)?
```bash
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### What did you do?
```bash
git clone git@github.com:grpc/grpc-java.git
cd grpc-java/
git checkout v1.7.0
```
Then load the Maven project in latest stable Eclipse (Oxygen.1) via:

```
File -> Open Project from File System
```

Then run `maven clean` and `maven generate-sources`.

### What did you expect to see?

The examples open in Eclipse with no problems whatsoever.

### What did you see instead?

The project has 72 Java problems:
![screenshot_2017-11-06_17-30-07](https://user-images.githubusercontent.com/17270267/32448949-f927362a-c318-11e7-8804-60356850a422.png)

### What operating system are you using?

OS: Arch Linux x86_64
Kernel Release: 4.13.11-1-ARCH

### What does work

Running

```bash
mvn verify
mvn exec:java -Dexec.mainClass=io.grpc.examples.routeguide.RouteGuideServer
mvn exec:java -Dexec.mainClass=io.grpc.examples.routeguide.RouteGuideClient
```

in two terminals shows that the example code works as expected.

Perhaps this is an Eclipse/Java problem? 

I searched through the issues but found nothing similar at a first glance.

Thanks in advance!

**Comment by zpencer** [comment]
Can you verify that the java language level in eclipse is set to 1.6 or above? Searching the internet, it appears this may be related to how `@Override` can only be applied to interface methods starting with java 1.6. `io.grpc.BindableService` is an interface. I suspect this is what's happening, since your mvn+jdk8 runs the code fine.

Please reopen if you are still seeing the issue.
