### ISSUE TITLE
Stabilize useTransportSecurity API on ManagedChanneBuilder

### ISSUE THREAD

**Issue by ramaraochavali** [grpc/grpc-java#3713]
This allows the consumer of a builder to swap back from plaintext. `ManagedChannelBuilder.useTransportSecurity() ` is similar to ServerBuilder's method, but without args) method which will reverse the usePlaintext(). 

For Netty, useTransportSecurity() would be the equivalent of negotiationType(NegotiationType.TLS).

**Comment by ejona86** [comment]
API review:
 * While we will be stabilizing usePlaintext(), we're thinking of leaving this one experimental for longer as there is not a strong need for the method since useTransportSecurity() is the default.
 * We will be introducing a "replacement" usePlaintext()/useTransportSecurity() in the form of ChannelCredentials and making a decision for useTransportSecurity could easily wait until the new API is introduced
 * The API docs could probably be improved a bit to make it clear that useTransportSecurity() is the default

**Comment by ejona86** [comment]
API review:
 * ChannelCredentials is soon becoming stable, so we revisited this. We saw ~20 usages of `channel.useTransportSecurity()` internally, but none of them actually do anything as they are called on a freshly-created channel builder. The new ChannelCredentials API would seem to serve these users well in a "the code clearly shows TLS will be used" way.
 * The ChannelCredentials API does not allow changing the credential after creating the builder, which is different from the current API with `useTransportSecurity()`
 * A bit weird to consider stabilizing an API that most callers don't even need to call. But there's no rush to remove this API either. It could be perpetually-deprecated and not be an issue
 * Server-side does not have an equivalent `usePlaintext()`

**Comment by larry-safran** [comment]
API review:

- `useTransportSecurity` is the wrong approach with the new API, should just pass in credentials when you create the builder.  
- [Sergii] Have a fromBuilder that creates a new builder from another with overrides
  - Would be heavy and bug prone, so Eric recommends against
- Transport is selected based upon builder, so can't swap to different transport
- ManagedChannelBuilder new API throws exception if call usePlainText or useTransportSecurity
- Could put in text on old API to utilize useChannelCreds is preferred
- Stabilizing this creates consistency.  Deprecated decision can be made later for whole old API.
- Everyone is fine with stabilizing it.
