### ISSUE TITLE
ManagedChannel state/notify API

### ISSUE THREAD

**Issue by dcow** [grpc/grpc-java#3763]
I'd like to actually observe connectivity status on a gRPC channel so I can reflect the state in some other code (UI or whatever). Using the current API yields something like:

```
interface ConnectionObserver {
    fun onStateChanged(old_state: ConnectivityState, new_state: ConnectivityState);
}

fun connectChannel(observer: ConnectionObserver) {
    var channel // init channel 
    val state = channel!!.getState(true)
    fun registerForStateChange(old_state: ConnectivityState) {
        channel?.notifyWhenStateChanged(old_state) {
            val next_state = channel?.getState(false)
            next_state?.let { 
                observer.onStateChanged(state, next_state)
                registerForStateChange(next_state)
            }
        }
    }
    registerForStateChange(state)
}
```

which is a little unwieldy (I haven't tested that either so might not be exactly that). Is there any interest in a nicer API? Or is that an exercise left to the user?

**Comment by dcow** [comment]
Update: that indeed does what it intends to do. I imagine this could be a reusable pattern.

**Comment by ejona86** [comment]
The API is designed to fully-expose the inherent races involved. In your API, the old_state and new_state may be misleading. For example, it's possible for them to be the same state. It seems a bad idea to provide old state, because you can't draw any conclusions from it. You should only be looking at the current state.

Note that in your example, if you are waiting for the channel to be connected, you should pass `true` to each call to `getState()`. Yes, you requested it the first time, but things like [IDLE_TIMEOUT](https://grpc.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#idleTimeout-long-java.util.concurrent.TimeUnit-) can clear the request.

In general, I'd hope most users use waitForReady RPCs instead of relying heavily on the channel state API. The main use for the channel state API is to notify someone else that you're unhealthy, whether that's on Android by showing an "offline" icon to the user or updating your state for a load balancer.

Getting rid of the "old state" does simplify the code:
```
Runnable notif = new Runnable() {
  @Override public void run() {
    ConnectivityState currentState = channel.getState(false);
    // handle currentState
    channel.notifyWhenStateChanged(currentState, this);
  }
};
notif.run();
```

**Comment by dcow** [comment]
> In general, I'd hope most users use waitForReady RPCs instead of relying heavily on the channel state API.

@ejona86 yes I only intend to use this to signal info to the user, not as a way to submit RPCs. The idea is I'll have a channel established when the app is open, and I'd like inform the user if the channel "breaks" or at least provide feedback as the channel cycles through different states during its lifetime.

> The API is designed to fully-expose the inherent races involved. In your API, the old_state and new_state may be misleading. For example, it's possible for them to be the same state. It seems a bad idea to provide old state, because you can't draw any conclusions from it. You should only be looking at the current state.

I admit `old_state` and `new_state` are bad names. I understand they're the previous and current state and, with your explanation, that they can be the same (although the docs say that the Runnable gets fired when the state changes from the initial state passed in, so it's unclear to a first time user what to expect and indeed I expected that if I called getState in the Runnable callback it would not be equal to the state that I passed in initially). 

In my example, the call sequence looks like this:

    // Thread A
    ConnectivityState previousState = channel.getState(true);
    // registerforstatechange 
    ConnectivityState previousState = currentState;
    channel.notifyWhenStateChanged(previousState), #callback);
    
    // Thread B
    // callback
    ConnectivityState currentState = channel.getState(false);
    // =
    // = Call the observer with previous and current state so it can e.g. transition the
    // = UI displaying the previous state to UI displaying the current state. If previous is
    // = the same as current of course this can just be a no-op.
    // = Assume the observer serializes messages onto the UI thread for updates. Or
    // = assume an observer remembers the last state it sees or something and we don't
    // = even care about previousState.
    // = aka. // handle currentState
    // =
    previousState = currentState;
    channel.notifyWhenStateChanged(currentState), #callback);
    
    // Thread B'
    ConnectivityState currentState = channel.getState(false);
    // callback
    // ...

Without previous state, extracting the important stuff, mine is like:

    // Thread A
    ConnectivityState currentState = channel.getState(true); 
    channel.notifyWhenStateChanged(currentState), #callback);
    
    // Thread B
    // callback
    ConnectivityState currentState = channel.getState(false);
    // handle currentState
    channel.notifyWhenStateChanged(currentState), #callback);
    
    // Thread B'
    ConnectivityState currentState = channel.getState(false);
    // callback
    // ...

I *think* this does effectively the same thing as your provided code, except I have that `getState(true)`.

> Note that in your example, if you are waiting for the channel to be connected, you should pass true to each call to getState(). Yes, you requested it the first time, but things like IDLE_TIMEOUT can clear the request.

How do I know if I'm waiting for it to be connected? I'm unfamiliar with these peculiarities so I'm asking mostly out of ignorance. If the channel can be reset any time, wouldn't that mean your/my example only works once the channel has become connected (because we assume false after the first call)? If I'm understanding you correctly, to correctly use this API, one should keep track of a flag indicating whether they're "waitingToSeeConnected" or not and effectively pass it to getState, something like:

    state = getState(waitingToSeeConnected);
    notifyWhenChanged(state, callback);
    state = getState(waitingToSeeConnected);
    waitingToSeeConnected = state != CONNECTED;
    notifyStateChanged(state, callback);
    state = getState(waitingToSeeConnected);
    // ...

**Comment by ejona86** [comment]
> Note the docs say that the Runnable gets fired when the state changes from the initial state passed in, so it's unclear to a first time consumer what to expect and indeed I expected that if I called getState in the Runnable callback it would not be equal to the state that I passed in initially.

Since that is two separate operations, there's really not a way to make them the same other than "stopping the world" while the notification is processing. I've sent out #3965 to improve the docs.

Note that the behavior is as designed and some of the reasoning is mentioned in [the connectivity spec](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md#channel-state-api).

> Upon careful examination, I think I understand the importance of typically, now (=

It is typically because there's no way to enforce that, which is probably what you understand better now. But it does also permit alternative usages, like assuming the initial state. Consider this change from your initial code snippet:
```
    val state = ConnectivityState.IDLE
    // instead of
    val state = channel!!.getState(true)
```

> How do I know if I'm waiting for it to be connected?

Normally, I'd expect a piece of code to pass the same value every time. So I guess the question is more, "why do you pass `true` the first time?" It seems unnecessary.

I'd hope most code willing to wait to be connected should use [`AbstractStub.withWaitForReady()`](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md). It is possible with the connectivity API, but is harder and limits gRPCs knowledge of your intentions.

So that leaves the question of why does the `true` option even exist? It is useful for applications that know they always want a connection (so this would be in a "loop"), or for applications that know they'll need a connection "soon" (and this would be once before some operation). Both of those are to reduce the latency incurred by creating the connection.

> to correctly use this API, one should keep track of a flag indicating whether they're "waitingToSeeConnected" or not and effectively pass it to getState

Yeah, something like that would be fine. (CONNECTED should be READY, but otherwise looks fine.) Note that I'm of the opinion it is really weird to "wait for CONNECTED" non-continually, except for a particular RPC. Because otherwise:
```
waitForReady(channel); // Some utility; let's say it blocks until READY
// The connection can go down here. Or anywhere past this point.
// Why don't we care about the connection any more?
doWork();
issueRpcs();
doWork();
issueRpcs();
```

Note that I would partially understand a single call with `getState(true)` to avoid assuming the connection is good. Maybe that's what you were doing. So your application may call `getState(true)` to "prime" the channel state and get it to either READY or TRANSIENT_FAILURE, and then you use that state for your UI. This still may behave strangely in failure scenarios though, as reconnection attempts may stop.
