### ISSUE TITLE
after server shutdown client  trigger StreamObserver.onERROR(io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason) , client can still be invoke onNext without throw any Exception ？

### ISSUE THREAD

**Issue by SeriousMa** [grpc/grpc-java#3825]
after server shutdown client  trigger StreamObserver.onERROR(io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason) , client can still be invoke onNext without throw any Exception ？

**Comment by SeriousMa** [comment]
use client streaming

**Comment by ejona86** [comment]
Yes. The client can continue calling onNext(). This is because there's an inherent race between receiving the onError() notification and sending from another thread. Handling random and rare exceptions is error-prone, so we try to avoid throwing exceptions except when an API is being misused.

I assume you're familiar with server-side which will throw an exception. However, this is because on server-side gRPC will frequently have already called `onCompleted()` when the client half-closed, but the RPC continues in-progress. If an error/cancellation happens after gRPC has called `onCompleted()` then there's no way with plain StreamObservers to notify the server to stop sending (because only one of `onCompleted()`/`onError()` may be called). So we chose to have onNext() throw. This behavior existed before we added `ServerCallStreamObserver` and even with that class any notification is opt-in, which is of questionable use for something fundamental like this.

**Comment by wangzhenxyz1** [comment]
client stream:

imo....
before receiving onError(),any OnNext() make sense,
but after that any OnNext() should throw exception,

**Comment by ejona86** [comment]
> before receiving onError(),any OnNext() make sense,

I don't quite disagree with you. But there were also not many options at the time. Now that there's ServerCall, the behavior is probably unnecessary. But at this point it may be hard to change the behavior because servers may be relying on it.

Since this was for client-side, it seems the behavior is correct.
