### ISSUE TITLE
Security support like Kerberos

### ISSUE THREAD

**Issue by uronce-cc** [grpc/grpc-java#3841]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Still in the stage of investigation, not in production use.

### What did you expect to see?
Is there any plan on supporting more security features, including authentication, authorization, and encryption. For example, I would like to specify that only certain users can execute certain services; I would like the data is encrypted on the fly by the RPC framework; I would like to use Kerberos for authentication and authorization in the production system which is required by certain industries like finance.

**Comment by ejona86** [comment]
"authentication, authorization, and encryption" is far to broad to give any useful reply. Although I will say that gRPC has no plans to participate in authorization (authz).

> I would like to specify that only certain users can execute certain services

Authz is out-of-scope for gRPC, because different services handle this quite differently. gRPC can partially help with authentication (authn). If you are using TLS mutual authentication, then you can get the SSLSession for the request via `ServerCall.getAttributes().get(Grpc.TRANSPORT_ATTR_SSL_SESSION)`. Other forms of authentication (like OAuth), transmit some sort of credential in the request headers. Your application would need to access the Metadata and authenticate it.

The encouraged design is for your application to have a ServerInterceptor that authenticates the user and then places that identity in the `io.grpc.Context` via `Contexts.interceptCall()`

> I would like the data is encrypted on the fly by the RPC framework

I assume you'd like something easier to set up than TLS. The problem here is enforcing identity checks, which is hard to do without being opinionated. We could maybe integrate with some other system that makes it easier to obtain secrets and verifying the remote's identity, but we'd need to look at those in a case-by-case basis.

> I would like to use Kerberos for authentication 

Kerberos over HTTP/1.1 is weird, in that it authenticates the entire connection and falls outside the scope of normal HTTP/1 semantics. Thus, there isn't a direct mapping to HTTP/2. I've not seen any work to define a Kerberos handshake for HTTP/2.

If Kerberos on HTTP/2 existed, then we could discuss adding support for it. But I do think we would need help from the community as we have limited experience with Kerberos.
