### ISSUE TITLE
Bad transport may be used for starting stream.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#408]
Currently we reference activeTransport to the newly created transport before the new transport is started , so if the new transport failed starting with an exception, the subsequent stream still try to use the bad activeTransport.

**Comment by ejona86** [comment]
This is by design.

There are multiple, multiple races between channel and the transport that can't be solved in Channel because the Channel is creating streams on a different thread. Instead, the transport has to be coded to fail new streams [after it has failed by throwing IllegalStateException](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/transport/ClientTransport.java#L56).
