### ISSUE TITLE
Hints on setup (gc and threadpool)

### ISSUE THREAD

**Issue by mfirry** [grpc/grpc-java#4116]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What did you expect to see?
I'm starting to build another grpc service that's supposed to handle something like 5k message per second (on commodity hardware) on average.

Messages weigh about 1k.

What's a good setup when it comes to:

- gc (we give it up to 8GB using are configuring `-XX:+UseG1GC`, `-XX:ParallelGCThreads=8`, `-XX:ConcGCThreads=2`)
- thread-pool (we're now using `new NioEventLoopGroup(16)`

Is there any recommended setup?

Thanks

**Comment by carl-mastrangelo** [comment]
I recommend using fewer threads in your NioEventLoop, and more in your ManagedChannel / Server executor.   gRPC is usually less of your work load (i.e. your business logic) so it doesn't need so many resources.   I also recommend setting -Xmx and -Xms to the same value, and as high as you can allow.   This makes memory management (from a sysadmin POV) easier.   We typically set it to around 8GB in our benchmarks.   

A lot of the times getting the system to be fast involves running it and finding the slow parts.   Once you know the slow parts, we (gRPC team) can give more specific advice about what to optimize.   You can use a Java profiler (like FlightRecorder, YourKit, JProfiler, etc.  to get this information, so that you can see where to optimize next.

**Comment by mfirry** [comment]
For now we have `workerEventLoopGroup` set to `NioEventLoopGroup` with size 1 and executor set to `FixedThreadPool` of size 8.
We do have Xmx and Xms set at 8GB.
Using Yourkit as we speak to find bottlenecks

Thanks so much for your suggestions.

**Comment by mfirry** [comment]
Ok using Yourkit now.

Our settings is:
- NioEventLoopGroup with size 2
- bossEventLoopGroup default
- Executor set to ForkJoinPool with size 8

We noticed a SingleThreadEventExecutor that adds up to 40% of the `observer.onNext` calls.

We run this inside a docker container with 8 cores on mesos on a physical machine with 40 cpus.

**Comment by carl-mastrangelo** [comment]
That's very unusual, because the event executor doesn't invoke onNext.   Can you provide a sample stack trace?

**Comment by mfirry** [comment]
```
sun.nio.ch.EPollArrayWrapper.interrupt(int) EPollArrayWrapper.java (native)
sun.nio.ch.EPollArrayWrapper.interrupt() EPollArrayWrapper.java:317
sun.nio.ch.EPollSelectorImpl.wakeup() EPollSelectorImpl.java:207
io.netty.channel.nio.SelectedSelectionKeySetSelector.wakeup() SelectedSelectionKeySetSelector.java:73
io.netty.channel.nio.NioEventLoop.wakeup(boolean) NioEventLoop.java:708
io.netty.util.concurrent.SingleThreadEventExecutor.execute(Runnable) SingleThreadEventExecutor.java:753
io.grpc.netty.WriteQueue.scheduleFlush() WriteQueue.java:65
io.grpc.netty.WriteQueue.enqueue(WriteQueue$QueuedCommand, ChannelPromise, boolean) WriteQueue.java:97
io.grpc.netty.NettyServerStream$Sink.writeFrame(WritableBuffer, boolean) NettyServerStream.java:114
io.grpc.internal.AbstractServerStream.deliverFrame(WritableBuffer, boolean, boolean) AbstractServerStream.java:119
io.grpc.internal.MessageFramer.commitToSink(boolean, boolean) MessageFramer.java:332
io.grpc.internal.MessageFramer.flush() MessageFramer.java:282
io.grpc.internal.AbstractStream.flush() AbstractStream.java:59
io.grpc.internal.ServerCallImpl.sendMessage(Object) ServerCallImpl.java:136
io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(Object) ServerCalls.java:341
```

**Comment by carl-mastrangelo** [comment]
If the application logic you are doing is non blocking, you can try using the directExecutor() on your ServerBuilder which will avoid the wakeup.  Otherwise, this behavior is expected.  Youll need to do much more work in order to get the batching benefits.   Right now, if the work level is too low, the server will be constantly waking up the Nio thread.
