### ISSUE TITLE
can not compile with genetor code

### ISSUE THREAD

**Issue by loveai88** [grpc/grpc-java#420]
java version "1.8.0_40"
Mac OS X 10.10.3
gradle version 2.4
protobuf version 3.0

I can use `gradle compile` when `skipCodegen=true`,but I can not compile when I want code gen.

First,It show me 'google/protobuf/compiler/java/java_names.h' file not found,then I copy the cpp file from protobuf/share to compiler/src/java_plugin/cpp.It show me `unknown type name 'Atomic32'`.

How can I do it? Thanks.

**Comment by ejona86** [comment]
If you don't have java_names.h, then you are probably using too old of a proto 3 alpha. We need at least alpha 2.

Can you confirm that using alpha 2 (or master) fixes the issue for you?

**Comment by loveai88** [comment]
yes,I use 3.0.0-alpha-2

**Comment by ejona86** [comment]
So then you should have the include at a place similar to `/usr/local/include/google/protobuf/compiler/java/java_names.h`. You also need to make sure to run something similar to `export CXXFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"` so that our build script knows where to find it. You shouldn't need to copy that header to `compiler/src/java_plugin/cpp`.

**Comment by loveai88** [comment]
Thanks,I compile it success
