### ISSUE TITLE
ok http read header error

### ISSUE THREAD

**Issue by smartwjw** [grpc/grpc-java#4261]
### What version of gRPC are you using?
server: 1.10.0 / jdk8
client:  1.10.0/okhttp

Since nginx 1.13.10 support grpc proxy, we are considering replace envoy with nginx. It works very when client is `netty`, but got exception on Android.

```java
io.grpc.StatusRuntimeException: INTERNAL: Missing HTTP status code
trailers: Metadata(x-request-id=57743f9b-d196-4780-a689-8743e6fa7f9b,grpcjersey.headers-bin=,grpc-status=2,grpc-message=65)
```
After some dig, I found okhttp failed to parse `:status:` and `content-type` header.

![image](https://user-images.githubusercontent.com/1625837/37813085-8e714810-2e9e-11e8-9bfa-51a52a7ee5c8.png)

**Comment by ericgribkoff** [comment]
Thanks for reporting this. It's interesting this is only occurring with OkHttp, as both Netty and OkHttp clients go through the same trailers validation method where that error message is being generated. I likely won't have time to set up nginx and try to reproduce/diagnose this bug until Monday, but I will update this issue once I have some more information.

**Comment by ericgribkoff** [comment]
Update: I can reproduce this reliably. It's not specific to running on an Android device, and can be reproduced with the `--use_okhttp=true` option with our interop test client. 

nginx logs show that it is sending the HTTP status code, but OkHttp is failing to parse it from the response headers. Still digging in to identify the root cause of the bug; since gRPC with Netty is able to parse the HTTP status code, it's likely the bug is in our OkHttp transport rather than nginx.

**Comment by smartwjw** [comment]
@ericgribkoff But, when I change from Nginx back to Envoy, okhttp works well.

**Comment by ericgribkoff** [comment]
@smartwjw OkHttp was throwing out the previously processed headers when updating its dynamic table (used for decoding HPACK headers). This is improper behavior, but apparently "most" gRPC servers didn't set the max table size to zero as nginx is doing, so this bug wasn't encountered previously.

PR #4276 fixes the bug, and I am backporting it to get it in the 1.11.0  release.
