### ISSUE TITLE
Client-side Load Balancing

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#428]
For the moment, all things client-side load balancing. Designs, requirements, etc. Can be split into separate issues as appropriate.

There is an internal load balancing design that needs to be made public. This is on @a11r's plate.

There is want to support ZooKeeper. It may need a different Channel implementation than the one necessary for the doc @a11r will share.

@louiscryan 
@jhump
@mzhaom

**Comment by ejona86** [comment]
Consider supporting affinity, in addition to basic load balancing.

**Comment by ejona86** [comment]
Note that this includes a bit of Service Discovery, as the two are commonly interrelated.

**Comment by ejona86** [comment]
@zhangkun83

**Comment by dhendry** [comment]
Is there any active work being done on this or guesstimates on timelines for official support? Im in the process of throwing together a quick and dirty dynamic routing channel (backed by zk) which, if it works out, may be possible cleanup and contribute back to address this ticket.

**Comment by zhangkun83** [comment]
@a11r has a design doc (not finalized yet) for a general load-balancing solution across languages. The idea for now is to put all the complex algorithms in a stand-alone load-balancer. The client requests the load-balancer for a list of servers, and uses a dumb policy (e.g., round-robin) to distribute requests to these servers. I don't know when the design will be delivered.

**Comment by jhump** [comment]
I'd be very interested in seeing how this comes together. I have a more elaborate design that is based on what the abstractions look like in an existing protobuf-based RPC system. I can even share:

https://docs.google.com/document/d/1DfGLih1_uhCzFDi4gc99FQBFkJNdbEweVuIbsAAfC4o/edit#heading=h.ax3xfgj40nuq

There are some open issues that aren't solved in our existing systems -- mainly around managing dynamically sized connection pools. (Our current RPC system requires this be statically configured, but what we really want is something that is reactive and can add and close connections as needed based on desired levels of connection redundancy and traffic levels per connection.)

**Comment by zhangkun83** [comment]
@jhump: the design we have internally wants to put most of the server selection work in the gRPC-specific load-balancing server. The client would have minimal selection logic, e.g., round-robin. This is to prevent the duplicate work of implementing an algorithm in all languages. We have defined the protocols among the client, the server and the load-balancer. The design also defines a gRPC-specific service discovery protocol, which still needs work.

I feel we need a consensus over a general load-balancing solution before discussing any language-specific APIs or SPIs.

**Comment by jhump** [comment]
@zhangkun83 Interesting. When can you share more info about this solution? I'm curious about how all of the components interact and what capabilities you expect to support this way.

BTW, as soon as you provide a separate server that implements the logic, then it's not really an SPI so much as an actual implementation. I was under the impression that an SPI would be added to allow plugging in alternate implementations. I'm more interested in what those interfaces look like, because I already have my own implementation that I want to drop in. I guess we could switch to the approach and implementation you describe, but only if we don't lose any key features we already have in our existing system.

Going further, what you describe still fits fine with the interfaces I described in that doc. It just won't really need any "smarts" in any of the components, it won't have need for "backend metadata", and the `ServiceDiscoverySystem` interface can be implemented as a client of the GSLBs (and all of the "smarts" go there).

**Comment by zhangkun83** [comment]
@jhump Sorry for being silent for so long. I have some update for the design work from gRPC team. The service discovery (aka name resolution) functionality is now an independent part of the system, and LB relies on it. The work flow would be - 
 1. Application creates a top-level channel with a __service name__
 2. The top-level channel uses a __name resolver__, passes the service name, and gets a list of addresses, a channel factory, and possibly other service configurations. The name resolver is plug-able, e.g., there will be DNSNameResolver, ZooKeeperNameResolver etc.
 3. The top-level channel connects to a returned address, by creating an underlying channel with the returned channel factory. If connection fails, retry with next address in a round-robin manner.
 4. Once connected to an address, the channel sends an LB request. Three cases:
  1. Server returns not-implemented error, because it's not LB-aware. The client then can start making normal RPCs on this connection.
  2. Server is a gRPC load-balancer and returns LB response. The following will be covered by the LB protocol, in which the load-balancer dictates what servers the client should send RPCs to.
  3. Server is not a gRPC load-balancer but is LB-ware, and it redirects the client to a load-balancer.

That's the basic idea. There will be an SPI for the name resolver. As for LB, the client-side logic and the server-side LB-awareness logic are fixed, while the load-balancer is open-ended, as long as it complies with the LB protocol.

There are still moving parts in the design, and we look forward to sharing the design when it's ready.

**Comment by mwitkow-io** [comment]
@zhangkun83 it's great to hear the grpc working on this :) Few questions from a curious bystander:

Re 3. How is the channel picked? Can it be picked at random so that even if the backend is not LB-aware 4.i. will provide some load spreading?

Re 4.ii Is this for the purpose of implementing an in-band LB, or just an LB "lease" protocol that will control where the client sends the RPCs to? Will this come only from the first server the client connects to?

Re 4.iii By LB-aware, does it mean that the gRPC server can provide rich metrics? E.g. a load factor that can be used by the in-client load-balancing policies such as weighted round-robin?

Are you planning to introduce any healthchecking, so that a non-healthy backend can be eliminated from the channel factory, even though the service discovery indicates its there?

**Comment by zhangkun83** [comment]
@mwitkow-io I am answering based on the current status of the design. Please note it's not finalized yet. We will publish it once we feel it's ready.
> Re 3. How is the channel picked? Can it be picked at random so that even if the backend is not LB-aware 4.i. will provide some load spreading?

It's picked at random.

We will support a use case where name resolver returns just backend addresses, and the client does round-robin on them. 4.i. falls into this case.

> Re 4.ii Is this for the purpose of implementing an in-band LB, or just an LB "lease" protocol that will control where the client sends the RPCs to? Will this come only from the first server the client connects to?

By "in-band LB", do you mean a proxy-like LB server? The LB server won't proxy traffic. Periodically the LB server sends the client a list of servers for the client to round-robin on. Through the server lists the LB server controls the order and frequency in which the client uses the servers. If there are multiple LB servers returned by name resolver, they are equivalent. The client will just stick to one LB server.

> Re 4.iii By LB-aware, does it mean that the gRPC server can provide rich metrics? E.g. a load factor that can be used by the in-client load-balancing policies such as weighted round-robin?

LB-aware just means the server recognizes the LB protocol, so that even if the server is not an LB server, it can redirect the client to a real LB server. gRPC servers reports load information to LB servers. There won't be any in-client LB policies other than plain round-robin. Complex policies such as weighted round-robin is done by LB servers sending the client server lists where servers appear in the desired order and frequency. For example, by sending "A A B" to the client, the LB server makes the client split the load between server A and B by 66% and 33%.

> Are you planning to introduce any healthchecking, so that a non-healthy backend can be eliminated from the channel factory, even though the service discovery indicates its there?

gRPC will have health checking support, which will be used by LB.

**Comment by mwitkow-io** [comment]
The 4.i case of just round-robin between addresses sounds like an easy win for most early-starter use cases.

It's really great to see the out-of-band LB protocol providing much flexibility, leaving it up to the advanced user of gRPC to implement their policies outside the client.

However, there's one case that is not covered by this: soft-stickiness. E.g. RPCs for data of a given `userid` will most likely land on the same service instance for maximum caching. One can consistently hash the `userid` into the set of pre-opened channels, but that violates the RR rule. Will gRPC be flexible enough to accept custom channel pickup policies?

Also, are there any bugs/docs discussing how gRPC will do healthchecking? Just curious :)

**Comment by zhangkun83** [comment]
> However, there's one case that is not covered by this: soft-stickiness. E.g. RPCs for data of a given userid will most likely land on the same service instance for maximum caching. One can consistently hash the userid into the set of pre-opened channels, but that violates the RR rule. Will gRPC be flexible enough to accept custom channel pickup policies?

We will have built-in support for soft-stickiness and hard-stickiness. The client will send an affinity key (e.g., hash) to the LB server and the LB server will reply with servers for that key. We are still working on the design for this part, and it may not be included in the first version.

> Also, are there any bugs/docs discussing how gRPC will do healthchecking? Just curious :)

Health checking is tracked by grpc/grpc/issues/1791 and grpc/grpc-java/issues/647

**Comment by zhangkun83** [comment]
I have published a [design doc](https://docs.google.com/document/d/18sJ9PhZPqLHEluJfzKcCTMP8u_RbbOfDJxM2Hwflml0). Please take a look and feel free to comment.

**Comment by psaville-google** [comment]
I've seen commits over the last month or so that indicate a basic client-side LB may be ready. Is this a fair assumption? Will there be any announcements I can watch for?
Thanks.

**Comment by zhangkun83** [comment]
It's still under active development, and not considered ready at this moment. I will post any update, including when it is ready, on this issue.

**Comment by ejona86** [comment]
It's also a big enough feature we will note it on the release notes when it is released.

**Comment by viksit** [comment]
@zhangkun83 is there an update on this issue?

**Comment by zhangkun83** [comment]
@viksit Now we have the experimental [LoadBalancer](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/LoadBalancer.java) and [NameResolver](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/NameResolver.java) plugin interfaces. The channel can now work with custom NameResolver and LoadBalancers. While only primitive implementations have been provided, you can write and plugin your own.

**Comment by viksit** [comment]
@zhangkun83 thanks for the info. Are these changes being done only for the java interfaces, or are they available in all others (I'm using C++ and python for my use case).

**Comment by zhangkun83** [comment]
I only speak for Java. There have been a lot of progress on load-balancing in C core (C++ and Python wrap the C core). You'd better check https://github.com/grpc/grpc or ask on our mailing list (grpc-io@googlegroups.com) for details.

**Comment by szantopeter** [comment]
@zhangkun83 I created a netflix eureka loadbalancer for grpc, that works like this

        ManagedChannel channel = ManagedChannelBuilder
                .forTarget("eureka://127.0.0.1:8761/example-service")
                .nameResolverFactory(new EurekaNameResolverProvider())
                .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance())
                .usePlaintext(true)
                .build();

If there is interest in it, then I will clean it up and send a PR. I haven't tested it much, but it resolves services and handle failover as expected.

**Comment by roastario** [comment]
@zhangkun83 I have created a Zookeeper+Curator NameResolver for grpc, works very similarly to the above code @szantopeter produced:

```java
        //build a channel to targeted service
        ManagedChannel channel = ManagedChannelBuilder.forTarget("zk://pingPongService")
                .nameResolverFactory(new ZookeeperNameResolver.ZookeeperNameResolverProvider(zkHost))
                .usePlaintext(true)
                .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance()).build();
```

And a full unit-test demonstrating how it would be used: 

```java
    @Test
    public void shouldResolveMultipleAddressesAndProvideUpdatesWhenOneDisconnects() throws Exception {

        AtomicInteger server1Count = new AtomicInteger();
        AtomicInteger server2Count = new AtomicInteger();

        Server server1 = ServerBuilder.forPort(0).addService(new PingPongGrpc.PingPongImplBase() {
            @Override
            public void pingit(Common.Ping request, StreamObserver<Common.Pong> responseObserver) {
                server1Count.incrementAndGet();
                responseObserver.onNext(Common.Pong.getDefaultInstance());
                responseObserver.onCompleted();
            }
        }).build();
        server1.start();

        int server1Port = server1.getPort();
        Server server2 = ServerBuilder.forPort(0).addService(new PingPongGrpc.PingPongImplBase() {
            @Override
            public void pingit(Common.Ping request, StreamObserver<Common.Pong> responseObserver) {
                server2Count.incrementAndGet();
                responseObserver.onNext(Common.Pong.getDefaultInstance());
                responseObserver.onCompleted();
            }
        }).build();
        server2.start();
        int server2Port = server2.getPort();

        ZookeeperServiceRegistrationOps zookeeperServiceRegistrationOps = new ZookeeperServiceRegistrationOps(zkHost);
        zookeeperServiceRegistrationOps.removeServiceRegistry("pingPongService");
        //Register server1 providing pingPongServer
        zookeeperServiceRegistrationOps.registerService("pingPongService", URI.create("dns://localhost:" + server1Port));
        //Register server2 providing pingPongServer
        zookeeperServiceRegistrationOps.registerService("pingPongService", URI.create("dns://localhost:" + server2Port));

        //build a channel to targeted service
        ManagedChannel channel = ManagedChannelBuilder.forTarget("zk://pingPongService")
                .nameResolverFactory(new ZookeeperNameResolver.ZookeeperNameResolverProvider(zkHost))
                .usePlaintext(true)
                .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance()).build();
        
        //pingit!
        PingPongGrpc.PingPongBlockingStub stub = PingPongGrpc.newBlockingStub(channel);
        for (int i = 0; i < 100; i++) {
            Common.Pong pong = stub.pingit(Common.Ping.newBuilder().build());
            Assert.assertThat(pong, is(notNullValue()));
        }

        double weightedDifference = Math.abs(server1Count.get() - server2Count.get()) / (double) (server1Count.get() + server2Count.get());
        //check that the loadbalancer is not too skewed (less than 10% difference between the two server counts)
        Assert.assertThat(weightedDifference, is(lessThan(0.1)));

        //Simulate server2 disconnecting and de-registering
        zookeeperServiceRegistrationOps.deregister("pingPongService", URI.create("dns://localhost:" + server2Port));
        server1Count.set(0);
        server2Count.set(0);

        //pingit!
        for (int i = 0; i < 100; i++) {
            Common.Pong pong = stub.pingit(Common.Ping.newBuilder().build());
            Assert.assertThat(pong, is(notNullValue()));
        }

        //we de-registered server2, so server1count should be >> server2count
        double weightedDifference2 = Math.abs(server1Count.get() - server2Count.get()) / (double) (server1Count.get() + server2Count.get());
        //check that the loadbalancer is very skewed (more than 90% of calls went to server1, cant be 100% because it takes some time for the watch to propagate to zk and back)
        Assert.assertThat(weightedDifference2, is(greaterThan(0.9)));
    }
```

I am also currently working on a way for zookeeper to keep track of "preferred" service endpoints - and extending the RoundRobin loadbalancer so that it will prefer a given endpoint, and only use others if necessary. Would be useful to know where you see GRPC heading in this regard before jumping too far down the rabbit hole!

**Comment by ejona86** [comment]
> extending the RoundRobin loadbalancer so that it will prefer a given endpoint

RR expects the list of servers to be sorted in preference order. So the Name Resolver just should put the preferred address first and the RR LB should do the right thing.

**Comment by zhangkun83** [comment]
@szantopeter @roastario happy to see work based on LoadBalancer/NameResolver API :). I am not sure whether we want to include them in the gRPC library, or rather to leave them as individual packages. The cons of the former are:
 1. Additional dependencies in gRPC, i.e., eureka and zookeeper.
 2. Maintenance load on gRPC team
 3. Release timeframe: changes made on these LoadBalancers/NameResolvers would only be released when gRPC makes a release

Please be aware of an ongoing change on the LoadBalancer API ([design doc](https://docs.google.com/document/d/1exE0_QNwbHJesD-Opl2D6qX1wujADkUm5OpFykks3C8/edit)). Due to policy I cannot open anonymous access to the doc. Just request for access as prompted.

**Comment by szantopeter** [comment]
@zhangkun83 To eliminate dependency on Eureka I put the eureka integration into a sub module, so only that and not the core module will have dependency on Eureka. If there is a realistic chance that it can be merged then I will clean it up and create a PR.

**Comment by ryanchou1991** [comment]
How about using nghttp2 to load balance gRPC client requests to multiple-servers.

**Comment by zhangkun83** [comment]
Status update: [LBv2](https://docs.google.com/document/d/1exE0_QNwbHJesD-Opl2D6qX1wujADkUm5OpFykks3C8/edit) implementation is done, but not being used. It won't make it into the 1.1 release, but we will transition the channel builder to use the new channel impl on HEAD soon after we cut the 1.1 branch.

**Comment by szantopeter** [comment]
@zhangkun83 does it mean that I should do the Eureka integration after your LBv2 is integrated?

**Comment by zhangkun83** [comment]
@szantopeter I don't think you have to wait. IIUC Eureka is NameResolver, which is intact in LBv2.

**Comment by szantopeter** [comment]
ok, thanks

**Comment by z0mb1ek** [comment]
@roastario any news from your work? I want to use grpc with zookeeper balancing in production

**Comment by Haybu** [comment]
@szantopeter wonder what is the timeline to release your Eureka PR ?

**Comment by roastario** [comment]
@z0mb1ek I've stopped development of this, but the code is available at: 

https://github.com/roastario/grpc-zookeeper

**Comment by imberda** [comment]
Please can I enquire if there is work in progress to allow client-side load-balancing for java-grpc which allows integration with Eureka (as source of available service instances) - i.e. in much the same way as Ribbon does for pure REST based service calls?

**Comment by szantopeter** [comment]
@imberda I complete forgot about this project... the process around the PR is a bit more complex then I anticipated, but I will try once more in the coming weeks. I will either make a PR or create a separate artifact and release into maven central directly

**Comment by imberda** [comment]
@szantopeter that's fantastic news. I think / hope this could be widely used. Thanks in advance.

**Comment by szantopeter** [comment]
@imberda I refreshed my memory on the topic and maybe it is even easier to handle eureka integration outside of GRPC. You can register any service with Eureka the standard way, the only question is how do you read the registration. I have a working client / server example. The relevant files are this

https://github.com/ExampleDriven/spring-boot-grpc-example/blob/master/spring-boot-grpc-server/src/main/resources/application.yml#L15

https://github.com/ExampleDriven/spring-boot-grpc-example/blob/master/spring-boot-grpc-client/src/main/java/org/exampledriven/grpc/BookServiceGrpcClient.java#L47

Additionally meanwhile someone even created a Spring boot GRPC starter, that also has a good description of the eureka integration

https://github.com/LogNet/grpc-spring-boot-starter

**Comment by ejona86** [comment]
@szantopeter, if you make a SPI resource file for EurekaNameResolverProvider, then you don't need to specify nameResolverFactory on the builder. The `eureka://` will select the provider. See the 
[resource for DnsNameResolverProvider](https://github.com/grpc/grpc-java/blob/master/core/src/main/resources/META-INF/services/io.grpc.NameResolverProvider).

**Comment by imberda** [comment]
@szantopeter thanks for looking into this again. 

The referenced project [grpc-spring-boot-starter](https://github.com/LogNet/grpc-spring-boot-starter) contains some very useful stuff. The [example provided using Eureka](https://github.com/LogNet/grpc-spring-boot-starter#52-grpc-client-project) does provide load balancing (as `eurekaClient.getNextServerFromEureka(..)` will loop through instances and return them in series upon each call). However for my use cases it falls a little short as:

- It creates a new instances of `ManagedChannelBuilder` to be created on each request. This makes it quite inefficient (slow - hundreds of ms vs. a few ms using existing channel).
- It can't (automatically) take advantage of the retry functionality when a node is down (i.e. try another)
- The load-balancing can't be easily customised - its pure round robin

I actually prefer your implementation which registers a `NameResolverProvider` and creates the channel using `ManagedChannelBuilder.forTarget("eureka://service-name")`. The only issue I found (when testing) with your implementation is that it doesn't listen for updates to the list of service instances within the `EurekaClient` and pass them on via `Listener.onAddresses(..)`. So if nodes come online or go offline after the resolver is first initialised that change isn't picked up.

I think I now have a _reasonable_ handle on how to implement this. I'll give this a go at some point this week. Once done I'll post back with the code to look at. 

As an aside I need to think about use with and without Spring Cloud. When using Spring Cloud the normal Eureka `DiscoveryClient` is subclassed (as `CloudEurekaClient`) and the callback mechanism for publishing change events is overriden - from a simple observer callback interface to using Spring's `ApplicationEvent` mechanism.

@ejona86 I don't _think_ this can easily be automatically configured via the SPI resource mechanism, as the `NameResolverProvider` needs to be injected with a `EurekaClient` instance. Unless you can think of a neat way to handle this?

**Comment by ejona86** [comment]
@imberda, ah, I see, yeah, it can't. I've created #3644 to allow manually registering it, so that the app could construct it properly before passing it to gRPC.

**Comment by schmohlio** [comment]
fyi, I started a project for using etcd for thick client-side LB [here](https://github.com/schmohlio/grpc-etcd-java). it works like this:

```
ManagedChannelBuilder
    .forTarget("etcd://services/" + SERVICE_DIR) 
    .nameResolverFactory(EtcdNameResolverProvider.forEndpoints(endpoints))
    .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance())
    .usePlaintext(true)
    .build();
```

While working well for me I need to harden with tests, add release, & wait for stable etcd-io/jetcd api. Just thought I'd share in case anyone is interested.
