### ISSUE TITLE
ClientCall#cancel() implementations should be thread-safe

### ISSUE THREAD

**Issue by groakley** [grpc/grpc-java#4547]
Calling ```ListenableFuture.cancel(true)``` on the stub returned by ```ServiceNameGrpc.newFutureStub(Channel channel)``` calls through directly to the underlying ClientCall#cancel() method.  ListenableFuture#cancel() may be invoked from any thread.

ClientCall implementations (and in particular [ClientCallImpl](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ClientCallImpl.java)) should be fixed safely handle this, and the ClientCall docs updated.

See PR  #4539 for additional context.

**Comment by ejona86** [comment]
I think the ListenableFuture usage is safe because it is only for unary RPCs. At the point the ListenableFuture is returned the request has already been sent. Did a tool notice a race here or was it by code inspection?

Cancel can't be made thread-safe. Reason 1: because we can't force existing implementations (including interceptors) to become thread-safe retroactively. Reason 2: because we wouldn't want exceptions to be thrown when sending a message if the call has been cancelled in a different thread.

We could make a new method that is thread-safe, and I'm not entirely against that. To date, if someone really needs a thread-safe cancellation I suggest they create a CancellableContext when issuing the RPC and cancel that context when necessary. It's not as easy as a method on ClientCall, though.

**Comment by groakley** [comment]
This was only discovered by code inspection while trying to understand the threading/ordering requirements of ClientCall.

If the requirement is that cancel() must be called last and only for unary methods, I think that should be documented on the ClientCall API. Currently the documentation for halfClose() and sendMessage() says that these methods should throw if cancel() has been called (the scenario you describe in 2).

I'm surprised that there's no way that cancel() is invoked for server-streaming or bidi methods. Is there no way for a client to cancel these types of streams? For example, if the blockingStub of a server-side stream gets an interruption signal?

**Comment by ejona86** [comment]
> If the requirement is that cancel() must be called last and only for unary methods, I think that should be documented on the ClientCall API. Currently the documentation for halfClose() and sendMessage() says that these methods should throw if cancel() has been called (the scenario you describe in 2).

You can call those other methods, but the exception thrown would be an anti-pattern for me. In a multi-threaded API I don't want to receive exceptions because another thread happened to do something. A multi-threaded cancel would cancel the call and throw away all further sends (and not throw), which is actually what happens when the Context gets cancelled.

> I'm surprised that there's no way that cancel() is invoked for server-streaming or bidi methods.

Streaming is only exposed using async stubs today. You can call cancel with the async stub, but it's basically the same as calling ClientCall.cancel directly: you need to coordinate with other senders.

------

The stubs have been pretty good with the current not-thread-safe cancel. Frameworks are the thing I'd expect most potential problems, and that'd be mainly on the server-side. Note that today we actually don't have an API for "cancel" on server-side (only close, which is graceful).

I've been a bit surprised that there's not been a strong need for the thread-safe cancel.

**Comment by groakley** [comment]
> A multi-threaded cancel would cancel the call and throw away all further sends (and not throw), which is actually what happens when the Context gets cancelled.

So it sounds like you're leaning towards a new thread-safe cancel method (and presumably deprecating the existing cancel() method)?

> Streaming is only exposed using async stubs today.

I was thinking of https://grpc.io/docs/tutorials/basic/java.html#server-side-streaming-rpc-1. I would expect a blocking method like that to handle interruption.

**Comment by ejona86** [comment]
> So it sounds like you're leaning towards a new thread-safe cancel method (and presumably deprecating the existing cancel() method)?

If there's a need for it, I think it can only be a new method. I'd probably keep the existing cancel in-place as-is as it does have nicer protections (the throws to notice if "you're doing it wrong") for the common case.

> I was thinking of https://grpc.io/docs/tutorials/basic/java.html#server-side-streaming-rpc-1. I would expect a blocking method like that to handle interruption.

But you can simply call the current cancel() method for that one. All the sending is still from a single thread, so there's no concern about thread safety.

**Comment by ejona86** [comment]
Closing because it seems there wasn't an issue in the actual case mentioned. If someone needs a thread-safe cancel for other reasons later, please open another issue.
