### ISSUE TITLE
ServiceConfig example missing

### ISSUE THREAD

**Issue by nkrode** [grpc/grpc-java#4572]
Hi - Is there an example available for a sample service config with Hedging policy configured. I read https://github.com/grpc/proposal/blob/master/A6-client-retries.md#integration-with-service-config but wasn't sure what the actual values for methodConfig.name would look like.

Also are there any helper methods which take a json string and parses and returns Map<String,Object> which can be passed to attrs.set(GrpcAttributes.NAME_RESOLVER_SERVICE_CONFIG, serviceConfig);

**Comment by dapengzhang0** [comment]
Service config will be documented more thoroughly in the near future. There are numerous caveats with this feature and thus is not ready for general usage. + @carl-mastrangelo 

Hedging is not implemented yet.

**Comment by nkrode** [comment]
Ok thanks. Is retry implemented via service config?

**Comment by dapengzhang0** [comment]
Yes, retry is implemented via service config. However, currently we need to disable census (stats and tracing) so that retry can be enable. (Disabling census in AbstractManagedChannelImplBuild is protected not public api.) So technically it is very difficult for external users to make retry running, they might need coordinating with @carl-mastrangelo with service config and me with retry.

**Comment by nkrode** [comment]
Yeah it will be great if disabling stats and tracing is made a public api and not protected.

Thanks!

**Comment by dapengzhang0** [comment]
FYI: Hedging was implemented and hedging example was available at https://github.com/grpc/grpc-java/tree/v1.40.1/examples/src/main/java/io/grpc/examples/hedging
