### ISSUE TITLE
Basic setup doesn't work. make better documentation

### ISSUE THREAD

**Issue by Rivukis** [grpc/grpc-java#4615]
I used the autogenerated code from protoc. I tried to use the client to make a simple call and the dependencies are all messed up. This might not be the right location for this issue, but I'm not sure where else to post it. Also, seeing that you have over 300 issues, this will probably never be resolved. That being said, after having to figure out the correct gradle magic spell to pull in the correct library and version of tcnative, I finally got it to work (apparently it's different depending on the OS). Why doesn't grpc-java just pull in the correct version(s) of tcnative? or why don't the docs say anything about how/what/where to get the basic hello world example to work.

### What version of gRPC are you using?
1.13.1

### What did you expect to see?
something that builds without scouring the internet for days while wanting to blow my brains out

**Comment by ejona86** [comment]
There's many flows through the documentation you could have taken. Which one did you take? What documentation were you following?

The basic hello world doesn't use TLS, so there's no need for tcnative. There is a TLS-based hello world, and the Gradle build [has a comment above the tcnative dependency](https://github.com/grpc/grpc-java/blob/v1.13.1/examples/build.gradle#L44).

We do try to guide users through the problems with TLS, and you should have ended up at https://github.com/grpc/grpc-java/blob/master/SECURITY.md#openssl-statically-linked-netty-tcnative-boringssl-static (It's linked from the main README, for example). It's been quite a while since you've needed to use different versions of tcnative based no which platform, as the one we suggest with boringssl includes all the supported platforms. Where did you find documentation telling you to specify the specific version?

gRPC can't pull in the correct version of tcnative because not everyone needs tcnative. For example, some users are doing plain-text, and others are using Jetty ALPN or Java 9. None of those need tcnative, and tcnative is unfortunately large. Also, in the future we may recommend Conscrypt over tcnative instead.

FWIW, we should probably begin recommending using grpc-netty-shaded instead of grpc-netty. It does include tcnative, because it has shaded all of Netty. Although with it, you can't use any Netty-specific APIs.

**Comment by carl-mastrangelo** [comment]
@Rivukis Yeah, TLS is complicated mess.  I've been using Let's Encrypt to get my own certs (rather than self signing), but this is different for everyone.  It's little out of scope for gRPC to describe where SSL certs come from.

As for the server being plaintext by default:   it's too late to change that default behavior now, but we could warn if `usePlaintext()` is not explicitly called before building.  Would that have made things clearer?

**Comment by Rivukis** [comment]
Perhaps, that's really your call as you are much more familiar with this tool. I just wanted to give you some feedback (from a noob perspective) in hopes that it helps you.
