### ISSUE TITLE
can't connect to grpc server in docker dontainer

### ISSUE THREAD

**Issue by AhmadVatani** [grpc/grpc-java#4789]
I have grpc server in a docker container and run my docker container with below command:
`run -p 127.0.0.1:8090:9091 --name test -v "storage":"/usr/storage/test/" test`
When I want to connect to this container from grpc client on calling remote procedure I got network closed exception!
I'm using grpc v1.12.0

```
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:202)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:131)
```

Thanks in advance

**Comment by ejona86** [comment]
You hit the dreaded "Network closed for unknown reason." It's pretty rare now-a-days, congratulations! In short, it's hard to know what went wrong.

Do any RPCs work? I wouldn't be surprised if this was caused by a handshake failure. That would mean you're most likely mixing plain-text and TLS. FYI, clients expect TLS by default and servers are plain-text by default.

Can you test without Docker and see if it works? Either run the client in the container as well or run both outside the container. I would expect that Docker isn't part of the problem.

**Comment by ejona86** [comment]
Another option is to narrow down the failure to something I could reproduce. Then I could debug it.

**Comment by zhangkun83** [comment]
Closing this for lack of response.
