### ISSUE TITLE
Reset deadline timer / per message deadline

### ISSUE THREAD

**Issue by mmoehring** [grpc/grpc-java#4814]
### What version of gRPC are you using?
1.14.0

I have a bidirectional stream rpc where the call times vary wildly. Previously I had a default deadline but this call may take longer.
As I know the number of messages which have to be transported before the call, I could use a calculation like messages * time to get a deadline which might or might not be appropriate, i.g much too long for short call durations.

In most cases I don't care about the total call time but I would like to set a deadline that cancels the call if there was no message sent in the last X minutes.
A per message (+response) deadline or a way to reset the deadline timer every time a message is sent.

Is there any way to achieve this?

**Comment by carl-mastrangelo** [comment]
Hi @mmoehring 

I have an example showing something similar using a ClientInterceptor: https://github.com/carl-mastrangelo/grpc-java/commit/4a31a589c98f5f9c6f87206a6cb3c8d43b136924

This was written as an example for bidi streams that want to set a deadline between starting the call, and getting the first message.  You can do something similar, resetting the timeout on each message.

**Comment by carl-mastrangelo** [comment]
Interceptors are themselves lightweight, but you can obviously make them slow!  If you are familiar with JMH, you can modify `TransportBenchmark` to have an interceptor to see the effect.  My guess is that it would be in the noise, (e.g. ~200ns tops)

**Comment by mmoehring** [comment]
Good idea, I forgot about JMH. My question is answered, so I close the issue.

**Comment by carl-mastrangelo** [comment]
@jhaber We can take a strong stance on Unary RPCs, but streaming branches out in technical tradeoffs quickly.   Saying what people _should_ do for streaming would quickly diverge for different use cases.   Here are some things that reasonable people might disagree about:

1.  What's a reasonable "deadline" between messages?  Be aware that gRPC has a feature called "Keep Alives" which periodically ping the connection (like once every 45 seconds) to make sure the remote side is still connected.   Is this what the inter-message deadline is for?  Is 45 seconds too long or too short to notice that a connection is broken?  
2.  Should the deadline be just for the first message of the stream?  Should it be after receiving initial headers?  Should both sides set a deadline?  This really isn't clear, and I can come up with scenarios where one set of choices would be wrong for some of them.
3.  Anything flow control.  Streaming puts flow control front and center, because it's really not something gRPC the library can do, as it's an application-level decision.  Setting it too low and the RPCs will slow down.  Too high and you risk the program running out of memory.   In Java, this is exposed as `request()` and `isReady()` on the `ClientCall`.  Best practices here vary based on use.
4.  Can streaming calls be retried?   Maybe if no messages are sent it can, but maybe not.   A streaming file read request probably could, but not a streaming remote-logging system.  

I guess the point is dealing with streaming tends towards enumerating all the possible things you might want, what might go wrong, and what to do based on you memory/cpu/network/battery limits.  I think we need something like a flow chart.

**Comment by jhaber** [comment]
I think this list of considerations is extremely useful. And in a way, I think it answers the question. In other words, there's no one-size-fits-all answer for streaming, so what you _should_ do is consider _these_ sorts of factors on a case-by-case basis. Maybe I was looking in the wrong place, but I wasn't able to find this sort of information in the gRPC docs. I imagine there are a few buckets that cover most use-cases, so a flow chart like you suggested might be useful.

For the other part of my question, let's assume you follow the flow chart and find the bucket that your use-case falls into. Let's further assume that this dictates your desired behavior around things like deadlines, flow control, and retries. Now how might you go about actually getting this behavior? You could just rely on each client getting it right, or you could provide a client library that does the right thing (but you'd need to provide such a library in each language you want to support). Instead, we've started down the path of encoding this metadata as custom options in the proto file and then using interceptors that look for these custom options, but I don't know if this is reasonable or a dead end.

More generally, it seems like the docs are really good at explaining the high-level gRPC concepts and how to get started, but I think what's missing is something more prescriptive for teams looking to deploy and operate gRPC in production. But now I've ventured pretty far outside the scope of this github issue 😝
