### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by oferb** [grpc/grpc-java#4859]
Would it be possible to create binary releases for Linux Max and Windows, so people pinning to a released version don't need to compile it?
https://github.com/grpc/grpc-java/releases
See example:
https://github.com/bazelbuild/buildtools/releases

Here's an example for how to build Linux and Mac on a Mac. Mac is built with Docker:
https://github.com/oferb/startupos-binaries#grpc_java_plugin_linux

Thanks!

**Comment by dapengzhang0** [comment]
We ship release jar files and grpc-protobuf plugin binaries to the maven central repository 
https://search.maven.org/search?q=io.grpc
You don't need to compile it from source. (For bazel, use [maven_jar()](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar))

**Comment by dapengzhang0** [comment]
On a second look, did you mean that the `java_grpc_library()` rule need to compile grpc source?

**Comment by ejona86** [comment]
The protoc binaries are available on Maven Central: https://search.maven.org/search?q=g:io.grpc%20a:protoc-gen-grpc-java

**Comment by oferb** [comment]
Sorry, missed getting back to this issue. Thanks for all the answers.
What I'm looking for is actually a binary release for this target: `//compiler:grpc_java_plugin`.

Long story short:
We use https://github.com/johnynek/bazel-deps to get Maven deps. That's why we had to modify this:
https://github.com/google/startup-os/blob/master/third_party/java_grpc_library.bzl
since external targets get different names. Also, to avoid compiling `//compiler:grpc_java_plugin`, we use a release:
https://github.com/oferb/startupos-binaries#grpc_java_plugin_linux
Not sure this is the best way to do this. Happy to hear your opinions.
Thanks!

**Comment by ejona86** [comment]
@oferb, why are you using binary releases with Bazel? You shouldn't really be using binary releases with Bazel.

Supporting binary releases with Bazel would basically be a fork of the build. We don't have any desire to have Yet Another Build Configuration.

**Comment by oferb** [comment]
Well, it's not ideal of course, but compiling protobufs takes a lot of time (~2 minutes on a standard dev machine) and for tutorials like this it would make it a pretty bad experience: https://github.com/google/startup-os#hands-on-experience

**Comment by ejona86** [comment]
I see. I think we get to consider the _initial_ build time simply the cost of using Bazel. Incremental builds are very fast. Building locally increases the number of platforms supported. Avoiding distributing binaries is one of the wins of Bazel, because building the binaries is easy (yes, it may take time, but telling a user how to do it is easy).

We're already having some trouble with dependencies that aren't using Bazel (those on Maven Central), so I don't think we want to be maintaining whatever it would take to make the binaries work, especially since it doesn't increase easy of use and is just something else that might break.
