### ISSUE TITLE
how to scan inputs for xss and other similar attacks (server side) [need help]

### ISSUE THREAD

**Issue by MetaiR** [grpc/grpc-java#4867]
I need an example of scanning sent data (with for example Jsoup) inside a server inspector and if there is any problem (I mean XSS and other possible attacks inside a string or data) clean it and send it for processing

**Comment by carl-mastrangelo** [comment]
Could you include more detail about what you're doing?   On the surface I'm not how this is related to gRPC.

**Comment by carl-mastrangelo** [comment]
I'm sorry I still don't understand.  The correct way to handle this is to validate the username in your Service implementation.   Once validated, code that generates HTML (such as in the admin panel) always needs to escape the data.  (regardless of if it has been validated).  

I would strongly urge you to not "clean" user provided data, but instead "escape" it.  This preserves the most information, and is most resilient to attacks.  If having a username `<script>` is wrong for application reasons, then you can fail the RPC.  But what if the name was `O'Malley` ? You would accidentally remove the quote character and corrupt the data.  

In any case, I think gRPC interceptors are not correct, since the overall approach is suspect.

**Comment by MetaiR** [comment]
@carl-mastrangelo 

> The correct way to handle this is to validate the username in your Service implementation.

we have to write the same code for each service and if we want to change one single thing in all of them it will be a disaster

> I would strongly urge you to not "clean" user provided data, but instead "escape" it.

cleaning is just mean if user sent me `<script>location....</script>` I pick `location...` up and remove the tag. because it is unnessery to store <script> tags

> If having a username <script> is wrong for application reasons, then you can fail the RPC. But what if the name was O'Malley ? You would accidentally remove the quote character and corrupt the data.

we don't want to failed RPC request, and yes O'Malley is ok. thats why I said using `Jsoup` library. it just gets a white list and remove tags and attrabiutes that are not in the white list and take the rest which is pretty good actually and avoid any xss attacks and also prevent removing main data

plz take a look at `Jsoup` library

**Comment by carl-mastrangelo** [comment]
> @carl-mastrangelo
> 
> > The correct way to handle this is to validate the username in your Service implementation.
> 
> so we have to write the same code for each service and if we want to change one single thing in all of them it will be a disaster

What I mean to say is that you need to modify the data on your service's _outbound_ path.  Ideally, your RPC server should treat the data as opaque bytes and not worry if they contain HTML, JS, or other.  There won't be any disaster because when your code _generates_ the HTML, all the fields will be properly escaped.   There is no risk.  

> 
> > I would strongly urge you to not "clean" user provided data, but instead "escape" it.
> 
> cleaning is just mean if the user sent `<script>location....</script>` server will pick `location...` up and remove the tag. because it is unnecessary to store <script> tags

If you don't want to accept the user name for business logic reasons, that's okay.  I would agree it is unnecessary to store the `<script>` tags.  But I would also ask you, if someone submitted this username to your service, do you think the person is being legitimate?  Personally, I would view the entire request as bogus, and return an error.  How would storing the remaining part of the name, an obvious XSS attack, be correct?  


> 
> > If having a username <script> is wrong for application reasons, then you can fail the RPC. But what if the name was O'Malley ? You would accidentally remove the quote character and corrupt the data.
> 
> we don't want to fail RPC request, and yes O'Malley is ok. that's why I said using `Jsoup` library. it just gets a whitelist and removes tags and attributes that are not in the whitelist and take the rest which is pretty good actually and avoid any XSS attacks and also prevent removing main data
> 
> plz take a look at `Jsoup` library

I'm familiar with beautifulsoup, which is a similar library for Python.   I also ran a medium size website for some time, and am familiar with the attacks people use against them.  Cleaning each field, or escaping each field is error prone and tedious.   Using a templating library solves all these problems at once.  Best of all, it separates the programming concerns of the RPC server and the HTML generation.

**Comment by MetaiR** [comment]
@carl-mastrangelo 
we are disgusting about the possibility of implementing inside of server inspector or the need of doing this?

if it is not possible just say `it is not possible` but if it is possible, please tell me how

if u think it is not the right way or there is no need for doing this on the inspector (also if it is not possible) please give me a solution or a clue for doing it with the minimum code writing

**Comment by carl-mastrangelo** [comment]
@MetaiR It is possible, I am simply reluctant to help you do something I know to be buggy.  Please link to your code.

**Comment by MetaiR** [comment]
@carl-mastrangelo 
so what do u suggest for my case?

**Comment by carl-mastrangelo** [comment]
@MetaiR This is getting outside of what we can reasonably help with.  I think you should ask in a programming forum (like StackOverflow) about how to take untrusted web input that you plan on displaying.
