### ISSUE TITLE
Build fails on arm64 in ':grpc-protobuf-lite:protobufToolsLocator_javalite', ':grpc-compiler:compileJava_pluginExecutableJava_pluginCpp'

### ISSUE THREAD

**Issue by vielmetti** [grpc/grpc-java#4882]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

HEAD is now at 3134daf... Bump version to 1.15.0

### What did you expect to see?

Successful build on arm64

### What I saw instead

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Could not resolve all files for configuration ':grpc-protobuf-lite:protobufToolsLocator_javalite'.
> Could not find protoc-gen-javalite-linux-aarch_64.exe (com.google.protobuf:protoc-gen-javalite:3.0.0).
  Searched in the following locations:
      https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/protobuf/protoc-gen-javalite/3.0.0/protoc-gen-javalite-3.0.0-linux-aarch_64.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':grpc-compiler:compileJava_pluginExecutableJava_pluginCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling java_generator.cpp.
      C++ compiler failed while compiling java_generator.h.
      C++ compiler failed while compiling java_plugin.cpp.
  See the complete log at: file:///home/ed/src/github.com/grpc/grpc-java/compiler/build/tmp/compileJava_pluginExecutableJava_pluginCpp/output.txt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 5s
```

**Comment by zpencer** [comment]
I would recommend that you avoid building grpc-java from source, and instead run the protobuf code generation step from a supported platform such as x86. Once you have the codegen output, you can check in the .java files into your SCM, and use one of the released grpc-java artifacts. grpc-java itself  fine on arm JVMs.

Building from ARM is not officially supported, though some members of the community reported they were able to get it working. You're seeing an error because grpc depends on the javalite plugin for protobuf, and there is no pre-compiled artifact for aarch_64. protobuf and its related plugins are all native executables.

The general recommendation at the moment if you must compile everything on the arm device:
- use jdk10 to take advantage of its ALPN support, and avoid having to deal with netty-tcnative or conscrypt (this is recommended in general)
- download [protobuf](https://github.com/protocolbuffers/protobuf) and compile it, then set up the [protobuf gradle plugin](https://github.com/google/protobuf-gradle-plugin) to use your executable by seting `protoc { path = ... }`. This bypasses trying to download the precompiled protoc artifact.
- download [protolite](https://github.com/protocolbuffers/protobuf/issues/5072) and install it, then set up the gradle project property `protoc-gen-javalite` to point to your javalite plugin executable. This bypasses trying to download the precompiled protoc javalite plugin artifact.

Here is an unmerged PR wip resolves some known issues on 32bit arm v7: https://github.com/grpc/grpc-java/pull/4512/files

Alternatively, you can try building grpc-java using bazel, which is reported to have a smoother experience.

**Comment by ejona86** [comment]
Since #6441 in v1.27 we now have pre-built arm64 binaries.
