### ISSUE TITLE
grpclb-in-DNS clients fall back too early when the LB server ends the stream right after sending a server list

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc-java#4887]
context: I'm working on a set of grpclb-in-DNS interop tests in this PR: https://github.com/grpc/grpc/pull/16727, which uses a fake grpclb load balancer that's in: https://github.com/apolcyn/grpc-go/blob/grpclb_interop_client/interop/fake_grpclb/fake_grpclb.go

One of the scenarios is as follows:
  * One load balancer
    - the load balancer ends the stream with an OK status <i>immediately</i> after sending the server list.
  * DNS server that serves as an SRV record pointing to that load balancer
  * One "backend", which the load balancer points to
  * Zero "fallback" servers

The client, when ran in this test scenario, is expected to contact the balancer, get the backend address, and complete the test RPC with the backend. The Java client, however, actually ends up attempting to fall back to the non-existant fallback server right away.

I looked into this a bit and I believe the problem is as follows:
1) the client receives the server list, and [starts creating connections to backends](https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java#L365)
2) the client receives the "end-of-stream" from the balancer immediately afterwards and [checks if it should fall back](https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java#L618)
3) when deciding whether or not to fall back, the newly created subchannels are still in [connecting](https://github.com/grpc/grpc-java/blob/master/grpclb/src/main/java/io/grpc/grpclb/GrpclbState.java#L223) state, and so the client proceeds to fall back.

Because the fallback timer hasn't gone off yet, I believe the client should be waiting a bit longer to give the newly created subchannels more time to connect. I'd imagine that this balancer server behavior is OK and could be used e.g. when the balancer needs to shed load.

The test can be reproduced on a machine with docker installed, by checking out [this PR](https://github.com/grpc/grpc/pull/16727), creating a ../grpc-go directory with [this branch](https://github.com/apolcyn/grpc-go/blob/grpclb_interop_client/interop/fake_grpclb/fake_grpclb.go), and running:

```
tools/run_tests/run_grpclb_interop_tests.py -l java --scenarios_file=tools/run_tests/generated/lb_interop_test_scenarios.json scenario_name=client_referred_to_backend_insecure_short_stream_True --no_skips
```

**Comment by zhangkun83** [comment]
According to the spec (go/grpc-name-resolution-semantics) wrt initial fallback: "Note that this fallback is only used when the client first comes up before it has gotten an initial serverlist from the balancer", because the server list has been received, the initial fallback timeout should not apply. The spec doesn't cover this particular case, where the balancer closes the stream immediately after sending the server list, while the client is still connecting to the backends.

The question is whether "not connected to all backends yet" is equivalent to "loses contact with all backends". @markdroth, WDYT?

**Comment by markdroth** [comment]
Interesting -- I'm guessing that the reason this is a problem in Java but not in other languages is that neither of the other languages have yet implemented support for fallback mode after a balancer has already been contacted.

This does seem like an edge case, but let's go back to first principles to figure out the right way to handle it.  The intent of the spec is that we should generally be preferring data from a balancer whenever possible and only using fallback mode when we have no usable balancer data (i.e., either we were not able to contact a balancer after we started up, or we had been using a serverlist from a balancer but we have subsequently lost contact with all backends in that serverlist).  Given that, it seems like we should prefer to use the serverlist we just got instead of going into fallback mode, at least until we know that we're not going to be able to reach any of the backends in the serverlist.

That having been said, I don't think we want a timeout on going into fallback mode when we lose contact with the balancer and can't reach any of the backends from the last serverlist.  We've discussed that quite a bit and have decided that having no timeout is the right thing (internally, see go/grpclb-zombie-balancer-problem), and I don't want to reopen that debate.

So, I can think of two possible ways of addressing this:

1. Specially detect this specific edge case.  When we lose contact with the balancer, if we know that we have just gotten the initial serverlist and that the initial connection attempts are still in progress, we avoid going into fallback mode until the initial connection attempt completes.  Only if the initial connection attempt fails for all backends (i.e., they all go into TRANSIENT_FAILURE) do we go into fallback mode.

2. Try to solve this in a more general way by saying that even in fallback mode, we will continue to try to connect to the backends specified by the last serverlist we got from the balancer.  The idea would be that we could go into fallback mode right away but still continue trying to connect to the backends from the serverlist that we got from the balancer.  As soon as we establish contact with one of those backends, we would leave fallback mode.

Option 1 is probably easier to implement, but it feels more hacky.  Option 2 seems like a better general solution, but it's more complicated to implement; I think it would require creating two RR instances, one for the serverlist addresses and one for the fallback addresses, and then switching between the two based on their connectivity states.

I'd also like to get input from @AspirinSJL and @menghanl on this.  And we may want to discuss with the load balancer team at our next meeting with them.

Thoughts...?

**Comment by markdroth** [comment]
FYI @vishalpowar

**Comment by AspirinSJL** [comment]
I think option 2 is better. 

Option 2.1 is to enter fallback mode only after (1) the balancer disconnects AND (2) all the backends from the serverlist can't be contacted. This may delay some RPC's transiently compared to option 2, but will be easier to implement.

**Comment by markdroth** [comment]
How is option 2.1 different from option 1?  They seem like the same thing to me.

**Comment by vishalpowar** [comment]
I like Solution 2, we could also change the current triggers to move to fallback address and out of it use the same solution (two RRs).

**Comment by markdroth** [comment]
I think options 1 and 2.1 are basically the same.  The only difference between the initial serverlist and subsequent serverlists is whether we already have some backends that we are already connected to.

**Comment by menghanl** [comment]
Option 2 sounds good to me.

Do we only enter fallback mode when connection to balancer is lost __AND__ no backend is reachable?

**Comment by markdroth** [comment]
@menghanl Yes.  When we lose contact with the balancer, we keep using the most recent serverlist we got from the balancer, as long as we can reach at least one of the backends in that list.  Once we lose contact with all of them, we should go into fallback mode.

**Comment by AspirinSJL** [comment]
If option 1 and 2.1 are basically the same, I think option 1 is better.

The question here is: if the balancer disconnects, and the current embedded RR (which is, of course, created from the latest serverlist, no matter it's initial or not) is still CONNECTING, should we enter fallback mode?

There are two answers.

1. NO, we shouldn't enter fallback mode, because we are still trying the latest serverlist from the balancer. Just don't enter fallback mode prematurely.

Honestly, I don't feel it's hacky. It's just a choice/preference. 

The code will be like this:
```
def OnBalancerDisconnected():
    if RR is TRANSIENT_FAILURE:
        Fallback()
    # ...

def OnRrConnectivityChanged():
    if new_state is TRANSIENT_FAILURE and balancer_disconnected:
        Fallback()
    # ...
```

2. YES, we should enter fallback mode, because the balancer disconnects and the embedded RR is not READY yet. Since we know the RR is at least non-empty and CONNECTING, while the fallback addresses might be even worse than that, we will keep an eye on both.

Keeping two RR policies for the serverlist and the fallback addresses is more complex than above. The benefit is that we can increase the availability in some cases. If we choose this solution because of the availability gain, should we also enter fallback mode when the embedded RR is in TRANSIENT_FAILURE and the balancer is still alive but hasn't sent us a new serverlist for a long time?

**Comment by zhangkun83** [comment]
Option 1 is way easier to implement and it can be expressed in a pretty clear way.

The current condition for entering the secondary fallback mode is:
```
serverListReceived && !balancerStreamLive && numReadyBackendConnections == 0
```
We just need to add a boolean to this mix:
```
serverListReceived && !balancerStreamLive && numReadyBackendConnections == 0 && connectionToCurrentServerListEverBroken
```

Granted Option 1 does sound like a patch, and Option 2 sounds clearer of an idea, but it's more involved of a change (writing unit tests for any change in the GRPCLB plugin has been especially painful). If Option 1 just works, I would lean to Option 1.

**Comment by markdroth** [comment]
I am not strongly opposed to option 1, but I am concerned that it may be hard to get the behavior right without being flaky.  In particular, I think relying solely on the connectivity state reported by the RR policy may not be the right thing, because it may not have had a chance to transition from IDLE to CONNECTING by the time the balancer call is terminated.

Kun, in your example, how exactly is the value of `connectionToCurrentServerListEverBroken` computed?  I am thinking that what we should really do is something like this:

- When we get the first serverlist, set a bool `initial_serverlist_connection_attempt_in_progress` to true.
- When the RR policy goes to either READY or TRANSIENT_FAILURE, reset `initial_serverlist_connection_attempt_in_progress` to false.
- If the balancer call is terminated, do *not* go into fallback mode if `initial_serverlist_connection_attempt_in_progress` is set to true.

What do you think?

**Comment by markdroth** [comment]
After discussion at today's meeting, we're going to go with option 2.  This is because @AspirinSJL has pointed out that we do actually have this same problem with any serverlist, not just the initial one.  Any time the balancer sends us a serverlist and then terminates the call before we can establish a connection with the servers in that list, we want to attempt to connect to the servers in that list.  If we immediately go into fallback mode by telling the RR policy to use the fallback addresses, then we will never try to connect to the serverlist backends we just got.  The only way to solve this is to have two separate RR policy instances, one for the serverlist and one for the fallback addresses.  That way, we can go into fallback mode right away, but we will be able to leave fallback mode as soon as we've connected to one of the serverlist backends, even if we have not yet reestablished the balancer call.

**Comment by zhangkun83** [comment]
Fair enough. Option 2 would prevent unnecessary delay if the connection attempts to backend servers take time before eventually failing.

**Comment by zhangkun83** [comment]
After offline discussion with @a11r , @markdroth and @ejona86 , we think this is a corner case that isn't worth the effort to address in grpclb. In xds it won't be a problem because it will always trying to connect to the primary backends, regardless of whether in fallback mode or not.
