### ISSUE TITLE
Need a way to specify source address when creating ManagedChannel as a client

### ISSUE THREAD

**Issue by nikhilvgs** [grpc/grpc-java#4900]
Is it possible to provide an option to specify source address to use when creating the ManagedChannel as a client. At the moment, the choice of source address appears to have been left to the operating system?

Current:
`ManagedChannel channel = NettyChannelBuilder.forAddress(SERVER_ADDRESS, SERVER_PORT).usePlaintext().build();
`
Proposed:
`ManagedChannel channel = NettyChannelBuilder.forAddress(SERVER_ADDRESS, SERVER_PORT).sourceAddress(SPECIFIC_LOCAL_ADDRESS).usePlaintext().build();`

### What version of gRPC are you using?
1.14.0

### What did you expect to see?
An option to specify a source address to use on client side.

**Comment by carl-mastrangelo** [comment]
Seems reasonable.   @ejona86  Maybe we could allow setting localsocket ?

**Comment by ejona86** [comment]
What use-case do you have for specifying the client source address? (I know they exist, but am interested in your case.)

**Comment by nikhilvgs** [comment]
We have multiple addresses configured on loopback interfaces on our client host. However, the way the routing is set up, we have a default route pointing to the actual outgoing interface, so the kernel cannot help us pick up the right source address per destination. In addition, we need to use different addresses to reach different destinations within the network (per network policy) - so, applications need to bind to appropriate addresses before connecting out.

**Comment by ejona86** [comment]
@carl-mastrangelo, seems easy to let users to pass in a SocketAddress that we then copy to the Bootstrap.localAddress().

**Comment by carl-mastrangelo** [comment]
@nikhilvgs This turned out harder than I thought.  The number of connections the gRPC client makes could be more than 1.  If two connections are made, they can't both bind to the same local address, meaning that we can't pass a single address into the channel builder.  The first connection would work, but not in a multi connection place. 

It could kinda work by passing a SocketAddress with the InetAddr, and a port of 0.   Alternatively, it could be more dynamic like picking a separate local address for each connection.   Thoughts?

**Comment by nikhilvgs** [comment]
My current use case does not require a source port to be specified. I don't mind the kernel assigning a random source port to the individual gRPC connections. However, I definitely need each of the connections to use the same source IP address. So, passing a SocketAddress with the correct InetAddr, and a port of 0 would work, I think.

Maybe, for future use cases where the source port numbers also need to be restricted, we could provide a pool of ports from which the connections could be derived (btw, this implicitly restricts the number of parallel connections - so, it may need to integrate with any other mechanism that allows user to restrict the amount of parallelism), but that would definitely be a lot more complicated.

**Comment by carl-mastrangelo** [comment]
Surveying other language implementations of gRPC:

* Go allows this by merit of being able to use a custom dialer.   The Dialer takes a remote address and returns a `net.Conn`.  A custom local address can be used based on the remote address.  
* C++ does not allow a local address, and there has been no request for it as of yet.  

I think a custom local address per remote address is needed because a load balancer could return mixed addresses, which may need different outbound interfaces.  A single wildcard address would not be enough.  

@ejona86 & @zhangkun83 what do you think about:

```java
interaface LocalSocketPicker {
  SocketAddress pickLocalAddress(SocketAddress remote)/* throws IOException*/;
}
```

And having a setter on NettyChannelBuilder

**Comment by zhangkun83** [comment]
SGTM

**Comment by carl-mastrangelo** [comment]
@nikhilvgs  You can try out the nightly release of gRPC to see if this would work for you.  Our branch cut is tomorrow, and will be released as v1.16.0  in about two weeks if you want to wait.

**Comment by nikhilvgs** [comment]
Thanks. I will try this out and let you know. Can you point me to your development snapshot repository? I tried the sonatype repo and I don't see the 1.16.0-SNAPSHOT there.

https://oss.sonatype.org/content/repositories/snapshots/io/grpc/grpc-netty-shaded/

**Comment by nikhilvgs** [comment]
@carl-mastrangelo ^^^

**Comment by ejona86** [comment]
A single wildcard address would probably be sufficient. Most of the time this is just to select which interface or identity is used. There's not much reason to change that when talking to a LB.

**Comment by carl-mastrangelo** [comment]
One other reason to not make it single wildcard is IPv6 address.  It may be too early at channel construction time to pick an IPv4 or IPv6 address to bind to, since there could be mixed servers to connect to.

**Comment by ejona86** [comment]
@carl-mastrangelo, ah, yeah. That's definitely true.

**Comment by ejona86** [comment]
@nikhilvgs, I just uploaded a 1.16.0-SNAPSHOT

**Comment by xingchch** [comment]
@nikhilvgs
have you verified the fix, does it meet you requirement? I am not sure how to use the feature, could you please show me you test snappcode？
