### ISSUE TITLE
Let people use compression

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#492]
It's been implemented for a while, but no way to turn it on.

We don't have a way to determine if the remote supports compression; that may need to be considered. We should also make sure we interop with C, which is doing compression soon.

**Comment by roiaddi** [comment]
Hi @ejona86 - is this already available in "0.8.0-SNAPSHOT" ? we want to start testing it. if yes, how can we enable it in the server side? is it part of the ServerServiceDefinition or something more global?

Thanks,
Roi

**Comment by ohad7** [comment]
cc @ohad7 @danageva @olympium @dorongoffer

**Comment by ejona86** [comment]
No, it hasn't been implemented yet. We're looking to implement it within the next 2-3 weeks.

**Comment by roiaddi** [comment]
cool. thanks for the update

**Comment by ohad7** [comment]
We'd be happy to test it if you have a snapshot version

**Comment by ohad7** [comment]
Great news! Can you share some pointers on how to configure it? I assume we will also need to adjust the c++ code to enable compression.

**Comment by carl-mastrangelo** [comment]
The API For setting compression is currently contended, and subject to being changed,   It is currently Settable via the CallOptions.withCompressor

**Comment by ohad7** [comment]
Hi Carl
Trying to build the 0.9 snapshot on my machine, Can you please generate and upload the osx protoc-gen-grpc version to Sonatype ? seems like there's only the linux executables there

https://oss.sonatype.org/content/repositories/snapshots/io/grpc/protoc-gen-grpc-java/0.9.0-SNAPSHOT/

Thanks!

**Comment by carl-mastrangelo** [comment]
I believe we only do full builds for releases.  We are actually on the cusp of doing a release, so I would prefer not to do one yet.

**Comment by ohad7** [comment]
I see. Thanks, looking forward to 0.9.0

**Comment by ohad7** [comment]
Is there a way to turn on compression in the response? The C client is sending the request compressed, but the Java server response is uncompressed. I understand that CallOptions is used for setting up the stub, but when building the server i'm using bindService() which doesn't allow me to specify options, and then going through the Netty server building I code I couldn't find a hook there also.

Also, there are a couple of strange things that are potential issues in 0.9.0 (I don't think the latest master version is in Sonatype though, so could be it's just I need the latest version):
1. after calling Server.start() I have to call Server.awaitTermination() - seems like the GRPC thread is a daemon. wasn't that way in the previous version
2. Working with old C client, sending headers and intercepting them in an AuthInterceptor, call to Metadata.get(header) returning null even though the request debug line indicates the header has been sent - has something changed in headers access or are headers stored as it used to, in the Metadata object?
Let me know if I should (probably) open a separate issue on these...

**Comment by carl-mastrangelo** [comment]
@ohad7 Not quite yet.  The compression API that is being worked on is kind of large, so I am adding it in chunks.  I am going to be working towards adding in the server (slightly more complicated, since negotiation is involved) over the next few days.

As for the daemon threads:  This was changed in f641e081a09e6ea4edc43eeb73ea56d0a01fc9bb.  The reason for the change was in case the application code did not shut down the grpc library properly, the program would hang and could never shutdown properly.  As long as you have a non daemon thread to make and receive calls, your program will not terminate unexpectedly.  You can do this by providing your own executor to the Channel or Server builder.  Also, as long as you call awaitTermination from a non daemon thread, typically main, your code will work.  I have updated our examples to show this behavior in #970.

As for the second issue, what was the header you were intercepting?

**Comment by nickweibel** [comment]
Hi Carl, Is there an update on when the server might support returning a compressed response?

**Comment by carl-mastrangelo** [comment]
@nickweibel We are blocked currently on metadata header processing, which is needed for compression.  Compression is facilitated by a list of supported compression headers, typically concatenated by a comma ",".  Headers today in grpc disallow commas, and I have a few PRs out to address this.

**Comment by carl-mastrangelo** [comment]
Fixed in a3c79e87ae85205bbdb2ed4de03813760ce755ee
