### ISSUE TITLE
Simplify configuration of flow control windows

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#494]
Stream window should really always be the same as the connection window.  We should just expose a single lever for this ... default to 1MB.

**Comment by louiscryan** [comment]
This would probably address the anomaly in StreamingResponseBandwidthBenchmark where we need to use more concurrent streams to maximize bandwidth. We should be able to saturate using a single stream.

**Comment by iamqizhao** [comment]
On Wed, May 27, 2015 at 12:08 PM, Nathan Mittler <notifications@github.com>
wrote:

> Stream window should really always be the same as the connection window.
> We should just expose a single lever for this ... default to 1MB.
>
What is rationale behind this conclusion? I would think connection window
should be larger then stream window.

**Comment by ejona86** [comment]
@iamqizhao, we want stream and connection performance to be the same. We don't want the user running a benchmark and finding things go faster if they use multiple streams instead of one. Such a benchmark would be faulty since the flow control window of the stream would have been improperly sized, but the user wouldn't have any reason to look further.

Making the flow control window the same size between stream and connection means that gRPC would have more predictable performance, as it is one less way different traffic could cause different performance.

**Comment by iamqizhao** [comment]
On Mon, Jun 8, 2015 at 8:04 AM, Eric Anderson <notifications@github.com>
wrote:

> @iamqizhao <https://github.com/iamqizhao>, we want stream and connection
> performance to be the same. We don't want the user running a benchmark and
> finding things go faster if they use multiple streams instead of one. Such
> a benchmark would be faulty since the flow control window of the stream
> would have been improperly sized, but the user wouldn't have any reason to
> look further.
>
> Making the flow control window the same size between stream and connection
> means that gRPC would have more predictable performance, as it is one less
> way different traffic could cause different performance.
>
In my opinion, this is a reasonable knob to tune in benchmark. I would
prefer following the default setting for window sizes in http2 spec. Any
particular setting would speed up some scenario and slow down some others.
As a generic rpc framework, we should not assume what the "typical" use
patterns are without real data base. You could set it in your benchmark.
But it should not be the lib default.

**Comment by ejona86** [comment]
@iamqizhao, why would you need to tune stream window separately from connection window, even in a benchmark? I don't think that a setting could slow down one scenario and speed up another. At worst, it would speed up one scenario but use more memory. I'm not assuming typical workload, in any way.

**Comment by iamqizhao** [comment]
On Mon, Jun 8, 2015 at 11:22 AM, Eric Anderson <notifications@github.com>
wrote:

> @iamqizhao <https://github.com/iamqizhao>, why would you need to tune
> stream window separately from connection window, even in a benchmark? I
> don't think that a setting could slow down one scenario and speed up
> another. At worst, it would speed up one scenario but use more memory. I'm
> not assuming typical workload, in any way.
>
In a benchmark, we can tune a lot of params including stream window size
and connection window size to see their impact on the performance.

If a benchmark starts a number of concurrent streams on the same
connection, won't the connection window become the bottleneck in your
configuration?

**Comment by ejona86** [comment]
> If a benchmark starts a number of concurrent streams on the same
connection, won't the connection window become the bottleneck in your
configuration?

@iamqizhao, no, and that is part of the point. The flow control window (for both connection and stream) should be at least the size of bandwidth*delay (BDP). Increasing the connection flow control window more than the BDP should have no effect (except for large messages). Making a window less than BDP will cause poorer performance, independent of whether it is done on the connection or stream.

If the connection window is the bottleneck, that means it is smaller than the BDP. If you increase the connection window, then you should also increase the stream windows, otherwise they will be smaller than the BDP.

**Comment by iamqizhao** [comment]
On Mon, Jun 8, 2015 at 1:07 PM, Eric Anderson <notifications@github.com>
wrote:

> If a benchmark starts a number of concurrent streams on the same
> connection, won't the connection window become the bottleneck in your
> configuration?
>
> @iamqizhao <https://github.com/iamqizhao>, no, and that is part of the
> point. The flow control window (for both connection and stream) should be
> at least the size of bandwidth*delay (BDP). Increasing the connection flow
> control window more than the BDP should have no effect (except for large
> messages). Making a window less than BDP will cause poorer performance,
> independent of whether it is done on the connection or stream.
>
> If the connection window is the bottleneck, that means it is smaller than
> the BDP. If you increase the connection window, then you should also
> increase the stream windows, otherwise they will be smaller than the BDP.
>
That's not the point of flow control. If we want the max performance, flow
control should have been an opt-in feature instead of something always on
on the critical path. Plus, we are talking about the default value (I am
not saying 1M is an insane number). If 1M is a clear win over 64K, http2
spec should take 1M instead 64k as the default. My point is that there is
no configuration which is all-win. Why not take http2 default directly as
our default?

**Comment by ejona86** [comment]
> If we want the max performance, flow control should have been an opt-in feature instead of something always on on the critical path.

Different streams need to go at different rates. Period. HTTP/2 would be dead-on-arrival if flow control was opt-in. HTTP/2 on the web is very different from a multiplexing protocol that only communicates messages with a reasonable maximum size between trusted computers on high-bandwidth links.

>  Plus, we are talking about the default value

That's not what I'm talking about. This issue is primarily to combine the _configuration_ of the two window sizes into a single value, as described by the title "Simplify configuration of flow control windows" and the description except for the last three words "Stream window should really always be the same as the connection window. We should just expose a single lever for this."

> Why not take http2 default directly as our default?

This is a very different discussion. But in short, 64K is a good default for "home users to websites," but a poor default for GCE and similar high-BDP networks found on server networks. We don't want 1 MB to be the perpetual default though; we actually want to auto-scale the flow control window based on BDP,  similar to TCP.
