### ISSUE TITLE
CallCredentials in 1.16.0

### ISSUE THREAD

**Issue by njhill** [grpc/grpc-java#5002]
This may be a non-issue but I wanted to verify the precise intention of the staged changes described in https://github.com/grpc/grpc-java/issues/4901.

The first steps imply a transition release which doesn't break existing code, presumably this is 1.16.0.
> 1. Introduce `CallCredentials2`, which is the new API, which implements the old `CallCredentials`. Change all stock implementations to it. Deprecate the old `CallCredentials`.
> 2. Make a release, and ask all implementations (including [FirestoreCallCredentials](https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreCallCredentials.java)) to implement `CallCredentials2` instead.

But in its current form, the 1.16.0 `CallCredentials` breaks binary compatibility for implementations since `CallCredentials.MetadataApplier` has changed from an interface to an abstract class, and this is in a parameter of its only method `applyRequestMetadata()`. I guess maybe the answer is that because that method is an `@ExperimentalApi` then you are SOL. But since implementing libraries need to be rebuilt to work with this anyhow, why bother staging it at all?

And in the subsequent release, _users_ of `CallCredentials` will suffer the same fate despite the interface itself being non-experimental. I am curious why this break needs to happen - couldn't it be kept as an interface with an abstract `BaseCallCredentials` implementation added that implementors can extend to be insulated from further API evolution?

**Comment by njhill** [comment]
It's also not clear why `CallCredentials.MetadataApplier` needs to be changed from an interface at all - if I understand correctly this will only ever have an internal implementation?

**Comment by zhangkun83** [comment]
/cc @ejona86 

We didn't realize changing `MetadataApplier` from interface to abstract class would break binary compatibility.  This is indeed an issue.

The proper way may be keeping `CallCredentials.MetadataApplier` an interface and making `CallCredentials2.MetadataApplier` abstract class instead. GRPC would bridge those two.

We may need a patch release for this.

**Comment by njhill** [comment]
Thanks @zhangkun83! What is the rationale for changing it from an interface at all? Just so that it can have a package-private constructor to make it clear that it's not something that users would ever implement themselves?

And what are your thoughts on keeping `CallCredentials` an interface?

**Comment by ejona86** [comment]
We want `CallCredentials` an abstract class so we can modify it; it's too complicated of an API accept using an interface without being able to use Java 8 default methods. If it had already been an abstract class fixing the API here would have been much easier.

For MetadataApplier, we changed it mainly out of reflex; we were just burned by the CallCredentials interface and it's not outrageous that we may want an overload at some point. It doesn't need to be implemented by users (other than testing), so there seemed no tangible benefit for it being an interface.

**Comment by njhill** [comment]
Thanks @ejona86.
> We want `CallCredentials` an abstract class so we can modify it

Why can't it be modified if it is an interface? It can be made very clear that implementors must extend `BaseCallCredentials` (and can even log warning if they don't).

> For `MetadataApplier`, we changed it mainly out of reflex; we were just burned by the `CallCredentials` interface and it's not outrageous that we may want an overload at some point. It doesn't need to be implemented by users (other than testing), so there seemed no tangible benefit for it being an interface.

It's not equivalent to `CallCredentials` though for the reason that it's only ever passed out, not passed in, so you could never be burned in the same way. The benefit for it being an interface imo is that it's already an interface :) what is the tangible benefit of changing it?

I'm still curious about the details of staged plan. I can't see any advantage for dependent libraries in breaking compatibility with all prior grpc versions by moving to `CallCredentials2` if immediately after they need to break compatibility with all prior versions again when moving off of it.

**Comment by ejona86** [comment]
> It can be made very clear that implementors must extend BaseCallCredentials

Because there are enough gRPC users we don't feel we can just hope that users "do it right." We adhere to API and ABI compatibility, with the only exceptions called out explicitly (like ExperimentalApi). Given our experience, that agrees 100% with our experience _since_ the decision, as seen with `@ExperimentalApi` and `@Internal`. I also don't know how to issue a warning if someone did this "wrong," other than doing something like `thisUsesUnstableApi()`.

> It's not equivalent to CallCredentials though for the reason that it's only ever passed out, not passed in, so you could never be burned in the same way.

A CallCredentials implementation could implement MetadataApplier for a test. We have users inside Google and outside Google that uses identical code inside and outside Google. If we "broke" MetadataApplier, then it's simply not possible to get all the code to work. Instead, we have to go through a middle-man rename, like we're doing with CallCredentials2. (This is actually what happened for CallCredentials, and why we're bothering with CallCredentials2.)

Note that "Google" there isn't too special. Any time you require atomic code changes with a library update you're asking for pain, because the real world is not atomic.

> I'm still curious about the details of staged plan. I can't see any advantage for dependent libraries in breaking compatibility with all prior grpc versions by moving to CallCredentials2 if immediately after they need to break compatibility with all prior versions again when moving off of it.

It makes the update non-atomic. Each version of the library supports the "old" and "new" ways (although what is "old" and "new" changes). In the case here, users can freely upgrade to 1.16.1 (which will have the fix), migrate partially at their own leisure (one file at a time, potentially), and then grpc can remove the old API when that looks done. (For CallCredentials, we've got to do that twice, since we want to retain the CallCredentials name; if we were okay with just leaving it named CallCredentials2 we wouldn't need a second migration.)

This sort of technique is very common in Google since we have a mono-repo and many times it's simply not feasible to change all the code at once. It's also super-common when you consider _service_ migrations, because even if you can change the code all at once you won't have an atomic _deployment_. But this also exists in OSS. See https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-7.md , which is talking specifically about OSS libraries.

**Comment by njhill** [comment]
Thanks @ejona86 this makes sense, I do understand and agree with the non-atomicity / overlap, In fact I do the same thing routinely myself in the context of production service migrations.

I think what makes it less palatable here though is the necessity for _successive_ breaking changes. It's not a case of just having just one window of `@Deprecated` versions within which dependants must switch. This imposes a very narrow range of gRPC versions that certain versions of affected libraries can work with - i.e. if I release version x of my library depending on gRPC 1.17.x, I have to say that it won't work with versions < 1.17 and won't work with versions > 1.17 (or maybe 1.18 depending on when `@Deprecated` CC2 is removed).

I guess the desire to retain the precise `CallCredentials` name/package is the sole reason for this?

Maybe the solution to my whinging is to just sit out 1.17.x?

**Comment by ejona86** [comment]
We can easily leave CallCredentials2 in-place for many releases without any real problem. I don't know how long we'll leave it in, but it'll literally be a single line of code.

But it is fine if you simply don't want to port to CallCredentials2. You'll stay using CallCredentials and have code that will work <= 1.16 and different code that will work > 1.17. That requires atomicity, but it's atomicity at small scale.

On the bright side, with the new API we'll probably be fine stabilizing the API.

> I guess the desire to retain the precise CallCredentials name/package is the sole reason for this?

Yes. And the reason for that is the name "CallCredentials" is already declared API-stable, so that users can safely reference the objects. We could decide to just leave CallCredentials2 there forever, I guess...

**Comment by njhill** [comment]
Thanks again and sorry for belabouring this. Leaving `CallCredentials2` there for a long time would certainly help, thank you!

> And the reason for that is the name "CallCredentials" is already declared API-stable, so that users can safely reference the objects.

So API-stable doesn't necessarily mean binary-stable, only source-stable?

Also I could be wrong about this but I have a sense that modular versioned dependency graphs and microservices are more common in the outside world now than a monolith which depends on a single set of versions. It's easy to deal with the atomicity in those cases, whereas it can become a problem if there are tight restrictions on the supported version combinations.

Maybe `CallCredentials` isn't very widely used yet in which case it's unlikely to have much impact, it just happens that I have an OSS etcd library which uses it hence my specific interest :)
