### ISSUE TITLE
How to get client IP from HA Proxy 1.8

### ISSUE THREAD

**Issue by thuannt-uit** [grpc/grpc-java#5018]
Hi all,

I'm using grpc to translate data between client and server. Client call server via HA Proxy (version 1.8 support live reload) but server side not get real client IP. How can I get real client IP via grpc code or any config from HA Proxy.

This is my code server
```java
public final class Interceptor implements ServerInterceptor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Interceptor.class);

    @ExperimentalApi
    public static final Attributes.Key<SocketAddress> REMOTE_ADDR_KEY =
            Attributes.Key.of("io.grpc.RemoteAddr");

    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
            ServerCall<ReqT, RespT> serverCall,
            final Metadata requestHeaders,
            ServerCallHandler<ReqT, RespT> next) {

        SocketAddress socketAddress = serverCall.getAttributes().get(REMOTE_ADDR_KEY);

        String inetSocketString =
                serverCall.getAttributes().get(Grpc.TRANSPORT_ATTR_REMOTE_ADDR).toString();

        if (socketAddress != null) {
            LOGGER.info("socketAddress={}", socketAddress.toString());
        }

        LOGGER.info("inetSocketString={}", inetSocketString);

        return next.startCall(
                new ForwardingServerCall.SimpleForwardingServerCall<ReqT, RespT>(serverCall) {
                    @Override
                    public void sendHeaders(Metadata responseHeaders) {
                        super.sendHeaders(responseHeaders);
                    }
                },
                requestHeaders);
    }
}
```
Thank so much,
### What version of gRPC are you using?
1.11.0

### What did you expect to see?
Get real client IP

**Comment by zpencer** [comment]
I think haproxy might be acting as a TCP proxy rather than L7 http/2 proxy in this case, so it does not know that the traffic is http2 traffic. The best option would be to let the client add its IP info in the client metadata. If you are using `NettyChannelBuilder` and provide a [LocalSocketPicker](https://grpc.io/grpc-java/javadoc/io/grpc/netty/NettyChannelBuilder.html#localSocketPicker-io.grpc.netty.NettyChannelBuilder.LocalSocketPicker-) then you can control which local network interface gRPC uses, and thus you can add the local IP address info to the client metadata.

**Comment by zpencer** [comment]
Since this seems resolved I will close this issue. Please reopen if still a problem.
