### ISSUE TITLE
Any way to get the Channel target through the channel and stub?

### ISSUE THREAD

**Issue by yidongnan** [grpc/grpc-java#5019]
### Is there any way to get the server name through the channel or stub or status

When service-a calls service-b , if service-b goes down, It will get such an error , ``status.getCause()`` is .

````java
Connection refused: no further information: /127.0.0.1:9898
````

Through the ``status`` object, we can see the ip and port of server (127.0.0.1:9898). 

The ip and port is obtained by resolve the ``Channel`` target name of service-b through ``NameResolver``, 

But I can't find any way to get the ``Channel`` target [ManagedChannelImpl.java#L123](https://github.com/grpc/grpc-java/blob/f3e371c7121a8d4d5e29186249648e8f095d078a/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L123)  ( the target is my service-b instance name )  like ``channel.getTarget()`` or ``stub.getTarget()``  or ``status.getChannelTarget()`` etc..

Is there any way to get the ``Channel`` target ?

### What version of gRPC are you using?
1.13.1

### What did you expect to see?

The instance name of the server can be obtained in the status or channel or stub.

If I get the channel target, I will customize the log like this

````text
Connection refused: no further information: /127.0.0.1:9898 (service-b)
````

**Comment by ericgribkoff** [comment]
I'm actually not sure how you are going from a gRPC `Status` instance to a `Channel` instance. I don't think we retain a channel reference anywhere inside of a status object. If you have custom error handling and are able to map status -> channel, could you also just map this to your original target string before name resolution? Otherwise, as far as I know, gRPC's [`Channel#authority`](https://grpc.io/grpc-java/javadoc/io/grpc/Channel.html#authority--) method is the only available API method related to what host a channel is connected to.
