### ISSUE TITLE
Prevent sharing Context object between server and client thread

### ISSUE THREAD

**Issue by alex-x-x-x** [grpc/grpc-java#5041]
### What version of gRPC are you using?
1.9.0

The issue with sharing Context object between server and client calls.

I have a GRPC server that while handling bidirectional stream request (stream A) creates a client bidirectional stream to another GRPC server (stream B). The idea is that lifecycle of the streams A and B are different and it's not required to close stream B when stream A is cancelled.

But it doesn't work atm. As far as I understand the reason is that Context object attached to the thread handling Stream A is used by Stream B as well. Actually Stream B listens for cancellation event from the Context, that is undesirable.

The question is how to break this dependency of the Stream B from the original Context.
I have one option is to create the Stream B in a separate thread from a thread pool.
But would like to know whether this is correct or probably there are another options.

**Comment by carl-mastrangelo** [comment]
A few things:

* Context is a thread local, but the thread it is attached to changes frequently.   For streaming, there may be multiple threads which handle an RPC.   Each event on the RPC gets serially handled by the next available thread.
* Context is not shared per thread (unless you explicitly add code to do so).  You can see how context is attached in ClientCallImpl.  
* Contexts  *are* hierarchical.   If you don't want this behavior, you can swap out the context explicitly by calling Context.attach() before starting the subsequent RPC.


Normally people do want shared fate, because one RPC is being used to build the result for another RPC.

**Comment by zpencer** [comment]
In general, if you wish to prevent cancellation propagation, you can call [the fork() method](https://grpc.io/grpc-java/javadoc/io/grpc/Context.html#fork--) to create a new context, and attach _that new context_ for the affected unit of work.

**Comment by alex-x-x-x** [comment]
Thanks for your replies.

The option with the fork() method looks exactly what I need (In my case, there are no any key/values in the parent Context which are required to be propagated though).

So, my code would be as
```
        Context newContext = Context.current().fork();
        Context origContext = newContext.attach();

        try {
            //asyncStub.subscribe();
        } finally {
            newContext.detach(origContext);
        }
```

**Comment by carl-mastrangelo** [comment]
@alex-x-x-x let us know if it works out, and close this issue if it does.
