### ISSUE TITLE
Excessive logging of Status{Runtime}Exception in server

### ISSUE THREAD

**Issue by dconnelly** [grpc/grpc-java#516]
If a service throws Status{Runtime}Exception it gets logged regardless of error class. There should probably be a distinction between "client" errors such as NOT_FOUND, INVALID_ARGUMENT which should not be logged (or at least not as FATAL) and other server errors (INTERNAL, UNKNOWN, etc) similar to how HTTP errors are categorized.

**Comment by ejona86** [comment]
Currently, servers can provide Status via `StreamObserver.onError`. Although gRPC handles the exception, the always-on logging prevents there being two ways to communicate errors and guarantees important exceptions information isn't lost.

Conditionally logging exceptions based on status code doesn't seem very appropriate as it would be hard for applications to predict the behavior. It would be feasible to only log if the exception is not a StatusRuntimeException. However, I think we may still prefer the explicit onError call.

@zhangkun83, thoughts?

**Comment by zhangkun83** [comment]
The service handlers are technically asynchronous handlers, because the RPC can be completed from any thread. Therefore, ``StreamObserver.onError()`` is the only reliable thus appropriate way to propagate application-level errors. Throwing from the service handler method should be considered an error unexpected by application logic, and usually indicates more serious problems. I think always logging them as ``FATAL`` is appropriate.
