### ISSUE TITLE
copied .proto files in apk

### ISSUE THREAD

**Issue by beigirad** [grpc/grpc-java#5199]
### What version of gRPC are you using?
1.16.1

### What did you expect to see?
I'm using `grpc` in a java module in in android application.
But when I build application all of .proto files copied in root of .apk file!

If .proto files converted to java classes by protoCompiler and compiled application do not using of them, why this happen?

**Comment by carl-mastrangelo** [comment]
cc: @ericgribkoff

**Comment by zhangkun83** [comment]
The source proto files are included in artifacts by protobuf-gradle-plugin because if the artifact is used as a library, its dependents may define protos that refer to the protos from the library. If the artifact is an application, certainly those protos should not be included. Please file an issue to https://github.com/google/protobuf-gradle-plugin. Closing this issue because it's not a GRPC issue.
