### ISSUE TITLE
How do I create a grpc over local socket (unix domain socket)

### ISSUE THREAD

**Issue by avnerbarr** [grpc/grpc-java#5239]
I want to create a grpc server over local host - i guess using a local domain socket (unix domain socket) would be prefereable. I saw some places that say to do:

`io.netty.channel.unix.DomainSocketAddress
`
but couldn't figure out how to do it in the context of the `io.grpc.netty`

Also want to note, locally I'm developing on a Mac, in deployment will work on CentOS, perhaps I need to do some special config for this to work properly.

**Comment by ejona86** [comment]
This was answered via [a StackOverflow answer](https://stackoverflow.com/a/54189910/4690866). Closing since it seems the question was posted to both places. @avnerbarr, if it's still not working, you can comment here if you'd like instead of SO (although we may also tweak the SO answer if it needs to be).
