### ISSUE TITLE
Cleanup io.grpc package

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#529]
- [x] Rename DeferredInputStream as it doesn't necessarily have to be deferred.  Consider making it an interface. 

- [x] Move SharedResourceHolder into transport

- [x] SerializingExecutor into transport

- [x] Rename KnownLength

- [x] Add `available` method with documentation to KnownLength

- [x] Move MethodType into MethodDescriptor

- [ ] Move Marshaller into MethodDescriptor

**Comment by zhangkun83** [comment]
@ejona86 What's the reason for moving `SharedResourceHolder` to `transport`? It's not only used for transports. `Context` and `ChannelImpl.TIMER_SERVICE` are also using it.

I don't see a reason why `SerializingExecutor` would belong to `transport` either. If we want to move them out of `io.grpc`, maybe a different package, e.g., `io.grpc.impl`, is more appropriate. `MutableHandlerRegistryImpl` and `ClientCallImpl` may also be there.

**Comment by ejona86** [comment]
`SharedResourceHolder` has to be public, because things in multiple packages use it (as you point out). However, anything in io.grpc is supposed to be API-stable, whereas io.grpc.transport won't have such a requirement (we consider it more like "internal"). The same is true for SerializingExecutor. We don't want them as part of our "public" API, but we still want to reuse them internally.

**Comment by zhangkun83** [comment]
Shall we move them to `io.grpc.internal`, and reserve `io.grpc.transport` only for transport API?

**Comment by carl-mastrangelo** [comment]
FYI, if KnownLength does get the available() method, it should have its javadoc changed to indicate that it is no longer a tagging interface.
