### ISSUE TITLE
Remove  compileOnly libraries.truth

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#5301]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

HEAD

```
    // Use compileOnly to avoid dependencyConvergence problem with the Guava
    // pulled in via Truth, for users that don't use Truth. Truth requires a
    // more up-to-date Guava than we support elsewhere, which would trigger
    // convergence failures in tests that only our users could resolve. Using
    // compileOnly means only users using Truth would have the problem and
    // they'd have to resolve it like normal anyway.
    compileOnly libraries.truth
```

This is out of date. Truth 0.42 and HEAD are now both at 25.1-android.

**Comment by ejona86** [comment]
We don't want to add a compile dependency on truth because basically none of our users need it and it can cause the Guava version to be different during tests vs production.

Instead, the plan is for us to move the internal bits of grpc-testing into core, and depend on core's tests directly when needed.

**Comment by suztomo** [comment]
I created a demo project to produce an issue of grpc-testing.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/447/files

**Comment by suztomo** [comment]
Thank you for the enhancement.
