### ISSUE TITLE
GoogleDefaultChannelBuilder does not support user-provided CallCredentials

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#5303]
GoogleDefaultChannelBuilder overrides the CallCredentials on CallOptions. This means that the user can't supplement the credential. Other languages will perform the union of the CallCredentials in the CallOptions and the GoogleDefaultCreds.

CC @jiangtaoli2016

**Comment by apolcyn** [comment]
Is a union of call creds, when the user provides them, a proposal here? C's google default creds don't allow user-provided call creds at all.

**Comment by jiangtaoli2016** [comment]
In gRPC C core, when using GoogleDefaultCredentials, it will automatically use default channel credential and default call credentials (OAuth2 token). 

User can put additional metadata credentials per RPC using MetadataCredentialsPlugin (grpc_metadata_credentials_plugin)

@markdroth correct me if I am wrong.

**Comment by andreamlin** [comment]
Please take a look at https://github.com/googleapis/gax-java/pull/650

**Comment by apolcyn** [comment]
I suppose one might be able to compose a google default creds C object with another custom call creds, but is that the desired functionality? I.e. is the idea here to combiner the call creds that google default creds uses, with a user-provided one, or to have the user-provided one override the default call creds of google default creds?

**Comment by ejona86** [comment]
@apolcyn, since the beginning of the auth API I was told union is what was "expected" (by the people writing this code, not by users) and that's why ChannelCredentials are unioned with CallCredentials specified per-RPC. That seemed bizarre to me, but it was arguing in a vacuum. At this point it is part of all C-core derived languages, so it would probably need a new API to change the behavior.

**Comment by apolcyn** [comment]
Hmm, might be seeing this differently, but to me the ability to union channel credentials with call credentials in C-core derived languages is one thing, but this issue is specific to the fact that google default credentials "internally-composed creds" don't have overrideable call creds. If we union call creds and have the user-provided one run after the google call creds one, then I suppose that would work - but I do think it sounds surprising. FWIW, none of the C wrapped languages currently expose C-core's "google default credentials", C++ is the only surface API that exposes it.

**Comment by ejona86** [comment]
@apolcyn, in C-based languages, ChannelCreds can include CallCreds. When you specify ChannelCreds that contain CallCreds when creating a new Channel, then if you specify per-RPC CallCreds you will get the union of both sets of CallCreds. So in all C-based languages you cannot _override_ the CallCreds.

Yes, I understand that the wrapped languages aren't directly exposing the C-core implementation, but they cloned the behavior or are wrapping the behavior (e.g., [CreateNativeCredentials in C#](https://github.com/grpc/grpc/blob/v1.18.0/src/csharp/Grpc.Core/ChannelCredentials.cs#L200)).

**Comment by ejona86** [comment]
@apolcyn and I talked offline. He was pointing out that today GAX isn't using GoogleDefaultCredentials if the user specifies custom credentials.

For example, in Java:

https://github.com/googleapis/google-cloud-java/blob/7fc4b3b2973faa23292b4f92f49ef1445d19934d/google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L272

**Comment by andreamlin** [comment]
@ejona86 Does this mean a patch isn't needed?

**Comment by ejona86** [comment]
@andreamlin, it means that the cloud libraries might need to use ManagedChannelBuilder if the user specifies a Credential and by default use GoogleDefaultChannelBuider. With that, the limitation of GoogleDefaultChannelBuilder wouldn't impact the cloud libraries (it would still be present, but the cloud libraries wouldn't trigger it).

**Comment by andreamlin** [comment]
@ejona86 The code that you referenced above is only used by a few select thick manual clients (Pubsub, BigQuery, Logging, Spanner, etc). The other OnePlatform API clients don't use the `ServiceOptions` class. It seems that this wouldn't affect the OnePlatform Java clients because the Credentials object is fetched from a CredentialsProvider object, which is separate from the TransportChannelProvider.

What I really want to know is, should I merge that hotfix? I would like to release gax-java soon, and I'm not sure if that should go in or not.

Later, we can set it up to toggle on ManagedChannelBuilder/GoogleDefaultChannelBuilder if need be.

**Comment by ejona86** [comment]
@andreamlin, I'm not sure I understand. How could you knowingly break Pubsub, BigQuery, Logging, Spanner, etc clients in a release? I don't know how you could release without the hotfix.

I don't what what TransportChannelProvider is and how it is involved.

It sounds like you have two issues, as CredentialsProvider seems like it would have the same problem as ServiceOptions but may need a different solution. I don't know your API and the guarantees you provide, so I can only tell you how it would behave and you may have to think through the consequences for your library.

**Comment by andreamlin** [comment]
@ejona86 it wasn't clear to me if the previous discussions meant that this issue is a non-issue for us.

We'll switch off of GoogleDefaultChannelBuilder for now then.

**Comment by ejona86** [comment]
GoogleDefaultChannelBuilder in #7294 is using GoogleDefaultChannelCredentials which is compatible with the channel itself combining the CallCredentials.
