### ISSUE TITLE
BC BREAK on NettyChannelBuilder.newClientTransport after 1.13

### ISSUE THREAD

**Issue by fabiocarneiro** [grpc/grpc-java#5370]
### What version of gRPC are affected?
1.14.0, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.17.0, 1.17.1, 1.17.2, 1.18.0

### What did you expect to see?
After 1.13, the signature of the method newClientTransport was modified. Since this is a public method, and not package private, this should be done only in MAJOR releases (2.x).

## v1.13.1
https://github.com/grpc/grpc-java/blob/9a3e0705bdd5a8fe01c764c11f2a9e40422c8ad2/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L510-L512

## v1.14.0
https://github.com/grpc/grpc-java/blob/0bed6067f9a0610b02cb867d74167a678498740a/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L510-L511

My dependency manager (Gradle) considers 1.16 as backwards compatible with 1.13  (which is correct and make sense), so as some of my dependencies is requesting 1.16, it installs that version. There is another library that depends on 1.13 and relies on the old signature of newClientTransport.

As per semver rules (https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version), please release a new MINOR version (1.19) reverting back the signature to the old one, OR alternatively maintaining both and identifying the old one as DEPRECATED, so it can be removed in 2.x.

For anyone else facing the same issue, temporarily add the following to gradle:
```
configurations {
    all{
        resolutionStrategy {
            force 'io.grpc:grpc-core:1.13.1'
        }
    }
}
```

**Comment by carl-mastrangelo** [comment]
Hi @fabiocarneiro 

I don't think you'll like this answer, but we don't consider NettyChannelBuilder as public API.  We have tried to be careful to indicate this, but annotating it with `@ExperimentalApi`.  Additionally, it returns an Internal type (one that lives in `io.grpc.internal`), which is solely meant for consumption by the superclass.   We are working within the limitations of Java's visibility and packaging restrictions, and do our best effort to clarify what is public and stable API.  Therefore, we don't consider this to be a violation of semver.

**Comment by fabiocarneiro** [comment]
Well, in my humble opinion there is no "consider" in regards to violations of Semver. It either complies or it doesn't.

There is a public method, and that automatically means anyone using it as a dependency can rely on it. Your annotations don't matter.

The method signature was modified in a MINOR version, breaking backward compatibility.

Your library does not comply with Semver.

Please note that you could still make the same changes, but release 2.x, 3.x, 4.x instead of 1.13, 1.14.... The effort for you is exactly the same, but in the latter case you would be compliant and the dependency managers would not install incompatible versions.

**Comment by carl-mastrangelo** [comment]
@fabiocarneiro Can you point to which library is using this?

**Comment by vjpai** [comment]
Semver literally says: "For this system to work, you first need to declare a public API. This may consist of documentation or be enforced by the code itself."

If this is defined as being non-public, semver is not an issue here.

**Comment by ericgribkoff** [comment]
Our practice with regards to `@Experimental` and `@Internal` apis is also documented in the repo's [readme](https://github.com/grpc/grpc-java/tree/05b6156d430970adcc628f7f1305d578094fa029#api-stability). We provide the [grpc-java-api-checker](https://github.com/grpc/grpc-java-api-checker) build tool to help libraries detect accidental consumption of these non-public APIs, following the practice of guava's [beta checker](https://github.com/google/guava-beta-checker).

**Comment by fabiocarneiro** [comment]
@carl-mastrangelo Sorry for the delay https://github.com/AxonFramework/AxonFramework/blob/axon-4.0.3/pom.xml#L135

**Comment by carl-mastrangelo** [comment]
> which makes the call to the `newClientTransport` method here

I cloned the repo, and grepped for `newClientTransport`, but I don't see where the call is being made.  Is it possible it's coming from somewhere else?

> `io.grpc:grpc-netty:1.13.1` is a "external" client, and it calls your @ExperimentalApi method

gRPC's package management puts the majority of stable APIs under the `grpc-core` package.  The transport (i.e. the connection specifics) are split into pluggable packages, namely grpc-netty, grpc-okhttp, and grpc-cronet.   Each of these is either Experimental, or Internal.  The recommended way of using them is with `ManagedChannelBuilder.forTarget`, which is stable API.  

> I recommend again that you stick to the language and avoid breaking public methods (or simply release a new MAJOR when you do that).

I don't think you have thought through the ramifications of this.  Java forces methods to be public if they are to be invoked across package.  To bypass this, we would have to invoke all cross-package methods via reflection, even if they were solely for our internal usage.  This would increase the binary size of Android applications,  make static analysis of our code worse, and have a chilling effect on any API becoming public.  

What's an alternative to this?  Put all code in one big package and make all the methods package private.  This greatly increases the number of dependencies every package has to pull in.  Actually good API boundaries are broken down, resulting in tight coupling of all the pieces.  Binaries bloat.  Dependencies become a nightmare.  Code health suffers.  

Or perhaps you are suggesting we should never try out new APIs, because they may be accidentally considered stable.  gRPC should freeze in place the nothing change ever again.  Utility and usefulness reach their high watermark, and every piece of code that depends on gRPC can rest assured it will never break again.  

Or I can take your suggestion to bump the major version at face value.  A wide swath of users now have to deal with version incompatibility between 1.x.x and 2.x.x, which all share the same Java package path.  Diamond dependency problems reign over all else.  The gRPC, which is small enough, is spread even thinner across maintaining numerous versions.  

All this because one library wrongly used some API, that they were specifically told not to, and which we we tried our best to indicate its instability.  We do our best to not break backwards compatibility.   I don't think we have acted in bad faith.   You should consider filing a bug against projects Axon, because it is likely they have misunderstood what that method is for.  (or, they are causing version skew between minor versions of gRPC).

**Comment by fabiocarneiro** [comment]
> I cloned the repo, and grepped for `newClientTransport`, but I don't see where the call is being made. Is it possible it's coming from somewhere else?

io.grpc:grpc-netty:1.13.1 is making the call to newClientTransport [here](https://github.com/grpc/grpc-java/blob/v1.13.1/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L510-L512)

You need to install io.grpc:grpc-netty:1.13.1 with io.grpc:grpc-core:1.16.1 

And that is possible because io.grpc:grpc-core:1.16.1  is considered backward compatible with io.grpc:grpc-netty:1.13.1

**Comment by ejona86** [comment]
> In languages that doesn't support methods with the same signature, I have seen newClientTransportFromA(A) and newClientTransportB(B) but in Java that you even have the advantage of being able to define newClientTransport(A) and newClientTransport(B) at the same time, we decided to remove old signatures...

I've not read everything here in detail (there's a bit too much), but I'll note that this is not possible since these were interfaces. I'm fully aware of Semantic Versioning but 1) we are not _required_ to follow semantic versioning (although we are general supporters of it and follow it) and 2) we [state our API stability excludes certain things in our main readme](https://github.com/grpc/grpc-java#api-stability).

Honestly, semantic versioning does virtually nothing in the current Java ecosystem because 1) there's no resolution for incompatible major versions and 2) Maven is a weak package manager (it will happily _downgrade_ versions!!!). Because of (1) any new major version will likely rename the package as well, which makes it _very_ expensive. For more reference, you may find [JLBP-3](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-3.md) and [JLBP-6](https://github.com/GoogleCloudPlatform/cloud-opensource-java/blob/master/library-best-practices/JLBP-6.md) informative as to our approach.

The APIs here are clearly marked as internal and yes, it is unfortunate that Maven is not a powerful enough package format to prevent these breakages, but it's also been clearly documented that these APIs are not API stable.

Note that in the to-be-released-today v1.19.0 there will be a BOM which can make it easier to align the versions.

I've been removing the few usages of `internal` package references (although this wouldn't work for Experimental API in io.grpc) that would break if `internal` was shaded. I don't plan on shading, but it would be good to have the option available. If Jigsaw ever becomes useful to separate major versions, then maybe we could use it (but I'm not holding my breath).

**Comment by ejona86** [comment]
Another quick detail: grpc-netty 1.13.1 depends on grpc.core version [1.13.1]:

```
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
      <version>[1.13.1]</version>
      <scope>compile</scope>
    </dependency>
```

So we are pinning the exact version required and the package manager would be able to notice there's an incompatibility. Last I tested, this works fine for Maven but Gradle doesn't notice.

**Comment by fabiocarneiro** [comment]
> Gradle doesn't notice

Yes, and I am on Gradle.

There are 3 very simple steps that solve this problem and doesn't require any fiddling with "pinned" version patterns that are specific to A or B package manager.

1. If you want to modify a public method, just create a new one
2. Mark the old method with the `@deprecated` annotation
3. Remove the old method before releasing the next MAJOR version.

It works for any package manager, it complies to Semver, your package will be backwards compatible with other packages you and others maintain, other libraries that are not aware of what is an `@ExperimentalApi` annotation will be able to rely on your public method, it requires very few, if any, additional effort. Everyone is happy.

> any new major version will likely rename the package as well
What?

**Comment by ejona86** [comment]
It doesn't seem anything productive is happening in this conversation any more. Locking.

@fabiocarneiro, I'm sorry you were bitten, but things aren't as simple as you seem to imply. We're aware of what you're mentioning but it isn't practical.

> If you want to modify a public method, just create a new one

I said that we were dealing with an interface here. You can't do it for interfaces.

> It works for any package manager

No it doesn't. As I mentioned, Maven will happily upgrade a dependency to a new major version without any warning. I didn't think Gradle did either, although it really doesn't change anything if they do, since Maven is _very_ heavily used.

> Do you mean you need a new repo, a new package url for a new version?

No. A new Java package. Say, `io.grpc2`.

> There are 3 very simple steps that solve this problem

Just for the record, these API changes between modules may be happening every release. I agree it is "simple" to understand, however it is not "easy."

> I think it would be reasonable if you were marking methods as @ExperimentalApi as long as you were not using them yourselves.

ExperimentalApis have to be implemented, so most ExperimentalApis require internal goo to make them work. So one changing tends to break the other.

> From the moment you have another library (released separately on Maven repo) and you call public methods between them, you are violating your own annotation.

No we aren't, because we say "it doesn't apply to us." We get to define what the annotation means.
