### ISSUE TITLE
grpc-java latency seen more than 1-2ms for 0.6% txn(Total 2M txn)

### ISSUE THREAD

**Issue by ankurmadan09** [grpc/grpc-java#5389]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.18.0
Java 8
### What did you expect to see?
Hi,
I am running simple sync java "Hello" client & server and sending around 2M messages from client to server.
At start the latency is in milliseconds due to warmup & after sometime latency seen is 400-600 micro seconds.
But approx 0.6 % of the messages show latency of  more that 1-2 ms and this is seen through out the run not just at the startup.

Please help me why this happening and is this expected behavior,If yes,why?
If NO, then what is the possible way to debug this.

**Comment by sanjaypujare** [comment]
The latest release is 1.18.0. Can you run your test on the latest? Also can you describe your underlying setup  - VM, same host, different host/VM for client & server ?

**Comment by carl-mastrangelo** [comment]
@ankurmadan09 Are you using your own executor on your ManagedChannel and Server?   Are you running on a quiet machine?   How much memory do you have, and do you set Xmx and Xms?   How big is the payload?

**Comment by ankurmadan09** [comment]
@sanjaypujare : I am using the latest 1.18.0 version,sorry for the typo in description,have corrected that now.I am running both client & server on same VM.
@carl-mastrangelo : I am not using our own executor for ManagedChannel & Server,Running Hello World example provided in grpc-java/examples,just tweaked the code to send hello message  in loop after every 1ms. I am running both client & server on same  quite VM having 16GB of memory/4 core CPU and Xms1g & Xmx2g set for both client & server.

**Comment by carl-mastrangelo** [comment]
@ankurmadan09 A few things:

* The defaults we set on gRPC are the "safe" defaults.    We can't pick some options for you, because they may result in deadlocks.  Specifically, we can't use a fixed threadpool or ForkJoinPool, because those depend on knowing your RPCs complete eventually.  For the Hello World examples, you can call `executor()` on the ManagedChannelBuilder and the ServerBuilder to set it to ForkJoinPool.  (anyone else reading this, don't misinterpret fixed thread pools as unsafe.  They are quite safe, just require application knowledge!).
* Some wide swings in performance are due to CPU changing frequency.  This is really noticeable on laptops, where they care alot about scaling down for power.   If you are on Linux, consider running `sudo cpupower frequency-set --governor performance`, which will make the processor not sleep between RPCs.

gRPC is tunable, so you'll need to do some basic profiling to see what's slow.  1-2ms above the 99th pct is not unreasonable knowing nothing else about the system.

**Comment by ankurmadan09** [comment]
@carl-mastrangelo  : Thanks for the help,with providing own executor to ServerBuilder, I could see improvements. :) Now only 0.1 % txn takes more than 1 ms and few txn takes around 6-8 ms.

Just wanted to understand,is there any document or reference where we can see in which scenario we need to define our own executor or use directexecutor or any other option.

Also what is performance grpc-java in unary blocking calls,i could see google VM shows median time of 300-400 micro seconds but doesnt show if we can have few txn taking more than 1-2ms.

**Comment by carl-mastrangelo** [comment]
> Also what is performance grpc-java in unary blocking calls,i could see google VM shows median time of 300-400 micro seconds but doesnt show if we can have few txn taking more than 1-2ms.

We run blocking benchmarks with [TransportBenchmark](https://github.com/grpc/grpc-java/blob/v1.19.0/benchmarks/src/jmh/java/io/grpc/benchmarks/TransportBenchmark.java#L188).  I see around 150us median time, and usually less than 400us for 99th.    You can run these yourself to tune and see where your overhead is from.   JMH is pretty versatile.

**Comment by ejona86** [comment]
Seems resolved. Closing.
