### ISSUE TITLE
tcp SEND-Q keep accumulating bytes

### ISSUE THREAD

**Issue by JunHoPark93** [grpc/grpc-java#5400]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.18

### What did you expect to see?
I'm currently using two spring boot application, one for client, one for server, using grpc-lognet dependency in server side.
I created client side with ManagedChannelbuilder.

```java
@Configuration
public class GrpcConfig {
    @Bean
    public ManagedChannel setChannel() {
        return ManagedChannelBuilder.forAddress("[server ip]", [port])
                .usePlaintext().build();
    }
}
```
I use channel as a bean and injected in class. and use like this

```java
@Slf4j
@Component
public class GrpcClient {
    private UrlClickServiceGrpc.UrlClickServiceStub urlClickStub;
    private UrlStatsServiceGrpc.UrlStatsServiceBlockingStub urlStatsServiceBlockingStub;

    public GrpcClient(ManagedChannel channel) {
        urlStatsServiceBlockingStub = UrlStatsServiceGrpc.newBlockingStub(channel);
        urlClickStub = UrlClickServiceGrpc.newStub(channel);
    }
```
is that okay to do this??
and it gives me unavailable io exception intermittently. (also I have no idea that it works in production level)
I checked my server status of tcp, and it shows some accumulated bytes in Send-Q. and sometimes this value goes up like over 2000. And the connection between server and client stopped.
like this

Proto  Recv-Q  Send-Q  Local Address  Foriegn Address  State
tcp                 0                     67          [mylocal ip]       [grpc server ip]   established

is that alright to use plaintext? or am I missing something?

plus, I've tried using withDeadlineAfter option on each grpc stub. It gives me an [error] deadline exceeded instead of [error] grpc unavailable io exception.

**Comment by carl-mastrangelo** [comment]
Avoid using `usePlaintext()` unless you know the client and server are running locally.

The send and receive queues look like you aren't using flow control properly (i.e. calling `isReady`, and `request`)

**Comment by JunHoPark93** [comment]
> Avoid using `usePlaintext()` unless you know the client and server are running locally.
> 
> The send and receive queues look like you aren't using flow control properly (i.e. calling `isReady`, and `request`)

Thanks for the reply !

1. So you mean I have to use SSL both server and client instead of plaintext right? 
2. And the second thing you mentioned quite confusing. you mean grpc calling flow control ?
Do I have to close the channel manually after each stub call? (my grpc server is listening in 6565 port, and it never shuts down).

my symptom is sometimes working well, and sometimes just stopped with lots of bytes in Send-Q. Thanks again.

**Comment by carl-mastrangelo** [comment]
>  So you mean I have to use SSL both server and client instead of plaintext right?

You definitely should.   It makes connecting more robust by negotiating the protocol (`h2`) early, and prevents transparent (but buggy)  proxies from interfering with the traffic.  There is also a minor perf win due to the batching behavior of SSL.  We run all our benchmarks with SSL turned on.

> 2. And the second thing you mentioned quite confusing. Do you mean grpc calling flow control?

In gRPC (and really HTTP/2) flow control moves more towards the application instead of the TCP socket.   This is so applications can manage their memory more precisely (such as avoiding huge buffer sizes, like you see).   You do this by explicitly requesting more data from the remote endpoint by calling `request()`.   You can check if the remote endpoint wants to receive more data by calling `isReady()`.

 > 3. And is there any big difference between ManagedChannelBuilder and NettyChannelBuilder in production level?

ManagedChannelBuilder reflectively constructs NettyChannelBuilder the NettyChannelBuilder is on the class path.  There is no substantial difference.   (you can change some options on NCB, but you generally don't need to).

**Comment by ejona86** [comment]
This looks like a problem with the network. If Send-Q is non-zero and communication stopped between client and server, then that's an issue at the TCP level. Since you're also seeing unavailable io exception, that's another symptom of a network issue.

With a flaky network, you may want to enable ManagedChannelBuilder.keepAliveTime() which will detect broken TCP connections and trigger a reconnect. Using a value greater than or equal to 5 minutes may be appropriate. To use something smaller you will need to configure NettyServerBuilder.permitKeepAliveTime().

The stuff about `request()` and `isReady()` is true, but only really applies to streaming RPCs. And while TLS is better to use than plaintext from a security standpoint, it shouldn't really impact the behavior seen here.

**Comment by JunHoPark93** [comment]
Thanks for your reply! one more question,
I set ManagedChannelBuilder.keepAliveTime() to 5 mins as you said. Nevertheless, I made a scheduling system that sending rpc call automatically once in 4 minutes. And io exception never happens.
So I think the connection issue is relevant to the number of calls per some time period through the channel. 
The last question is... do we have to set periodical rpc call through the channel in production level? (if there are not many requests in the server)

**Comment by ejona86** [comment]
In many environments the network will break TCP connections after a period of inactivity. (And break them very poorly, like not even sending RST.) When an RPC is in progress, addressing such networks is done via keepaAliveTime.

There are two ways to address this when no RPC is in progress. The first is to prematurely close the TCP connection; this can be achieved by ManagedChannelBuilder.idleTimeout() or the server-side maxConnectionIdle. The other way is to continue keepalive even without RPCs via keepAliveWithoutCalls(). We discourage this approach unless you have very low latency requirements. You will also need to use permitKeepAliveWithoutCalls() on the server-side.

**Comment by dapengzhang0** [comment]
Seems the original problem is resolved. @JunHoPark93  Feel free to reopen or file a new issue if you have more questions.
