### ISSUE TITLE
InProcessChannel with optional stack trace

### ISSUE THREAD

**Issue by bojanv55** [grpc/grpc-java#5439]
### What version of gRPC are you using?
1.19.0

### What did you expect to see?
Error Stack trace.

In reference to this stack overflow question: [here](https://stackoverflow.com/questions/55003239/grpc-java-logging-in-tests)

Is it possible to have an option to show full stack trace for InProcessChannel, since I use this in integration tests and I need to see full reason of exception?

**Comment by ejona86** [comment]
An option here is to add causal information to the Status, with the original Exception. That would happen here:
https://github.com/grpc/grpc-java/blob/e2bb44106a5d1132a960124ef0c12c7a0bd974d5/core/src/main/java/io/grpc/internal/ServerImpl.java#L761-L763

We would then need an option in-process to also copy cause here:
https://github.com/grpc/grpc-java/blob/e2bb44106a5d1132a960124ef0c12c7a0bd974d5/core/src/main/java/io/grpc/inprocess/InProcessTransport.java#L845-L859

It's probably best to still create a new Status in in-process, just so that no pesky `status1 == status2` code crops up, which should be using equals() instead.

**Comment by reggiemcdonald** [comment]
Im a computer science student thats new to open source - could I give this one a try?

**Comment by ejona86** [comment]
Go for it.

**Comment by reggiemcdonald** [comment]
Following your suggestion, I added the cause to the status in internalClose:
```java
private void internalClose(Throwable t) {
    stream.close(Status.UNKNOWN.withCause(t), new Metadata());
}
```

and I added the ability to copy status over in `InProcessTransport`:
```java
private static Status stripCause(Status status, boolean includeCauseWithStatus) {
    if (status == null) {
      return null;
    }
    if (includeCauseWithStatus) {
      return Status
          .fromCodeValue(status.getCode().value())
          .withCause(status.getCause())
          .withDescription(status.getDescription());
    }
    return Status
        .fromCodeValue(status.getCode().value())
        .withDescription(status.getDescription());
  }
```

But all the unit tests assume that `ServerImpl` does not pass cause back. Would you recommend refactoring the unit tests, or approaching this in a different way?

**Comment by ejona86** [comment]
`includeCauseWithStatus` should default to `false`, the current behavior. Then you can add a single new unit test that configures the value to `true` and verify that the original exception is propagated. I don't see an ideal example to copy, but one of the failing tests may prove to be one. Could you mention some that are failing?

Nit: you may consider this code flow:
```java
Status status = Status
    .fromCodeValue(status.getCode().value())
    .withDescription(status.getDescription());
if (includeCauseWithStatus) {
  status = status.withCause(status.getCause());
}
return status;
```

**Comment by reggiemcdonald** [comment]
Thats much cleaner syntax! Will revise.

I do set the default of `includeCauseWithStatus` to false. However, there are six unit tests failing. They are all failing for the same reason. Here is why: 
https://github.com/grpc/grpc-java/blob/ee8b395f79a1154df602e7add4d4e2828799e5e1/core/src/test/java/io/grpc/internal/ServerImplTest.java#L1188-L1211

In the catch block there is a call to `ensureServerStateNotLeaked()`. It uses an argumentCaptor to assert that the call to `stream.close` in `ServerImpl.internalClose` is equal to `Status.UNKNOWN`. Furthermore, it asserts that the status has a null cause
https://github.com/grpc/grpc-java/blob/ee8b395f79a1154df602e7add4d4e2828799e5e1/core/src/test/java/io/grpc/internal/ServerImplTest.java#L1441-L1446

**Comment by ejona86** [comment]
Looks like that code originates from https://github.com/grpc/grpc-java/commit/2b1eee90e5bd7f5ad905e34f73f2040d6c9a3568 . Since the cause is not actually transmitted, it seems safe to remove the `assertNull(statusCaptor.getValue().getCause());` check. We might want to actually change at least one of those tests to verify that the cause _is_ set (with a comment saying it is used by in-process, and potentially debugging).
