### ISSUE TITLE
Have different abstract base types for each stub type; use it instead of Calls

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#548]
Currently, `channel` (and soon, `callOptions`) are defined in AbstractStub, but the generated code uses them. It could be a good idea to have abstract base types for each stub type that uses `channel` so that the generated code doesn't.

This also moves the call of `Channel.newCall` into non-generated code. In all, this should have the generate code hard-code fewer things.

**Comment by zhangkun83** [comment]
Discussed offline with @ejona86 and @louiscryan and we agreed that this change was not very necessary and didn't justify the effort.
 
We were thinking about removing ``ClientCalls`` since abstract base stub types would take over its meat. As a result, this would eliminate ``asyncUnaryCall(ClientCall, params)``-like APIs in favor of ``asyncUnaryCall(MethodDescriptor, params)``-like APIs. The former is depended by @wrwg's Callable API and we cannot simply remove it.

The original argument that generated code would not use ``channel`` is not true, because ``channel`` would still been seen in the build pattern.

We are going to keep ``ClientCalls``, only to sanitize it because we are going to support it as a public API.
