### ISSUE TITLE
Use AndroidTicker instead of default system ticker

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#5533]
The internal import detected an errorprone from #5491 : http://go/errorprone/bugpattern/SystemTickerUnreliable 
```
Stopwatch.createUnstarted(AndroidTicker.systemTicker())
```

**Comment by dapengzhang0** [comment]
Also, I would like  to add another `GrpclbLoadBalancer` constructor without the `StopWatch` argument. The old constructor is just `@VisibleForTesting`, and `GrpclbLoadBalancer.java` will call the new constructor. In this way, `GrpclbLoadBalancer` can fully manage the lifecycle of the `StopWatch`.

**Comment by ejona86** [comment]
AndroidTicker is internal-only. But it uses https://developer.android.com/reference/android/os/SystemClock.html#elapsedRealtime()

However, the suggestion is woefully incomplete and I think should be ignored for gRPC because there's no way to use the clock for sleeping. The suggestion may make more sense for apps. See https://b.corp.google.com/issues/122550453#comment4

**Comment by dapengzhang0** [comment]
Okay. Created #5534 for another cleanup.
