### ISSUE TITLE
OpenCensus grpc method is not set

### ISSUE THREAD

**Issue by TheMarex** [grpc/grpc-java#5593]
### What version of gRPC are you using?

We are using 1.19.0 in combination with OpenCensus 0.19.2.

### What did you expect to see?

When using the `RpcViewConstants.GRPC_SERVER_SERVER_LATENCY_VIEW` from `opencensus-java` I would expect to see the metric split up by gRPC method, as is intended by them grouping the metric by the tag `grpc_server_method`.

However, `grpc-java` still sets the deprecated `method` tag which means this grouping is broken when using `grpc-java:0.19.0` with `opencensus-java:0.19.2`.

The easy fix would be to set both tags, to ensure a wider compatibility with opencensus. I can prepare a PR if that sounds like a good approach.

**Comment by TheMarex** [comment]
I did some digging in the history and this regression basically boils down to the decision in https://github.com/grpc/grpc-java/pull/4494 to not also support the new constants. Seems like OpenCensus decided to switch to using the new constants in their default views anyway, which broke the metrics for clients using these views.

#4494 mentioned a performance regression, I would like to start a discussion about quantifying the problem and potentially taking the slow-down if necessary. Right now OpenCensus integration with gRPC is broken in my opinion, since there is no current gRPC version for which OpenCensus will work.

gRPC seems like the right place for the fix, since it would allow a wide range of OpenCensus versions to be compatible and give people time to migrate in any code that references the old `method` while partially porting to the new `grpc_{client,server}_method`.

**Comment by ejona86** [comment]
CC @songy23, @sebright

**Comment by songy23** [comment]
Thanks @TheMarex for looking into this. Initially I was taking the same approach in https://github.com/grpc/grpc-java/pull/5601, but it has caused performance problem because it's expensive to attach more tags to every client and server RPC. At that time we suggested to keep using the old constants for backwards-compatibility, and after a certain time of deprecation window we'll just replace the old constants with the new ones. 

Since you brought this up, maybe it's a good time to revisit the approach that adding both new and old OpenCensus tags. @zhangkun83 would you be able to benchmark https://github.com/grpc/grpc-java/pull/5601? 

If performance is still a problem, I think we can try migrating to the new tags in gRPC code first, and then do some tricks in OpenCensus to map the new tags to old ones in order to keep backwards-compatibility.

By the way in the meanwhile you can still use `RpcViewConstants.RPC_SERVER_SERVER_LATENCY_VIEW` which has the old dimension `method`. It provides same metrics to `GRPC_SERVER_SERVER_LATENCY_VIEW`, the only difference is the metric and tag name.

**Comment by gertvdijk** [comment]
Is this also the reason that I don't see anything on the [`GRPC_REAL_TIME_METRICS_VIEWS_SET`](https://github.com/census-instrumentation/opencensus-java/blob/v0.20.0/contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java#L130-L139) via `registerRealTimeMetricsViews()`?
