### ISSUE TITLE
HOL blocking for multiple bidi streams

### ISSUE THREAD

**Issue by nimahajan** [grpc/grpc-java#5650]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.19

I would like to know more details on how grpc bidi streaming works on top of HTTP2 streams.
Specifically, in this issue - https://github.com/grpc/grpc-java/issues/3849 below statement got me a little confused 

```
An RPC* corresponds to one HTTP/2 stream. All streaming RPCs use the same HTTP/2 stream.
```

So does this mean - if I have 2 or more streaming GRPC requests on a single connection, it will lead to no multiplexing and head of line blocking? Is there any way to avoid that?

**Comment by ejona86** [comment]
Each RPC gets its own stream. The quote should have probably said "all streaming RPCs use the same HTTP/2 _connection_" or "all messages on for a streaming RPC use the same HTTP/2 stream."

There is no head-of-line blocking due to sending large messages/streams. Small streams can "flow past" large streams. The exact order we choose to send streams is based on a scheduler. Right now the scheduler will predominantly round-robin over each stream sending 1 KB at a time. So if you have a really large RPC and then start a new small RPC, the small RPC would only need to "wait" for up to 1 KB before being sent itself. There's details involved depending on how deep you go.

**Comment by nimahajan** [comment]
Thanks for the explanation. That clarifies many things. I am wondering if we can plug a preemptive scheduler. Can you please point me to java package/classes that implement the round-robin scheduler? 

My Use case:
We are working on a use case to stream messages to mobile apps from the server. Users can be on very poor mobile networks. Our messages have priority - high medium and low. Messages are generated out of order. We can keep 3 different streams and let the round robin scheduler send 1KB for each. But if we can specify some kind of priority for each stream and then use a preemptive scheduler, I can make high priority messages go even faster.

**Comment by ejona86** [comment]
They are implemented in Netty: [UniformStreamByteDistributor](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/UniformStreamByteDistributor.java) and [WeightedFairQueueByteDistributor](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/WeightedFairQueueByteDistributor.java).

We are using WeightedFairQueueByteDistributor today, but it will behave similarly to UniformStreamByteDistributor since we don't use priorities and dependencies. The behavior you want is possible to describe to the WeightedFairQueueByteDistributor. See the [http2 spec](https://httpwg.org/specs/rfc7540.html#StreamPriority) for the meaning of priorities and dependencies in http2.

However, all that doesn't _immediately_ help you because 1) gRPC doesn't let you change out the scheduler (if you wanted a custom one) and 2) we don't provide an avenue to control the priority/dependency through gRPC. (2) being the bigger issue.

Also, which side knows the relative priorities? The receiver (in this case the client) controls the priorities/dependencies of what it wants to receive in the http/2 protocol (because that's the only time you need to send something on-the-wire). If you want the sender to control the priority that could be done, but I don't know how that looks in Netty (how you would notify the scheduler of your configuration).

**Comment by ejona86** [comment]
Seems this has been answered. Closing.
