### ISSUE TITLE
NameResolver refresh not triggered if empty addresses returned

### ISSUE THREAD

**Issue by pkwarren** [grpc/grpc-java#5692]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.20.0

### What did you expect to see?

I've implemented a custom NameResolver to resolve addresses in Consul (DNS or HTTP). We're pairing this name resolver with the RoundRobinLoadBalancer to provide simple client-side load balancing.

While integration testing, I found that if we return an empty list of addresses in the name resolver, no refresh is ever triggered on the NameResolver (leading to a permanent error of UNAVAILABLE for all calls). If I change the NameResolver implementation to call Listener.onError() instead when no addresses are found, refresh() will eventually be triggered and the problem can resolve itself.

When writing the name resolver, I believe I may have gotten tripped up on this comment (which makes it sound like onAddresses() with an empty list is equivalent to onError()): https://github.com/grpc/grpc-java/blob/980dd9671d26ab3dfb0cadfe5f226d840d4ac124/api/src/main/java/io/grpc/NameResolver.java#L285

For reference, the DNS name resolver doesn't pass an empty list of addresses: https://github.com/grpc/grpc-java/blob/206a2e39333e991963adc7da74cb05dd2410c1a5/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L282-L286

I'm not sure if this is expected behavior and I know this is an experimental API, but wanted to report in case this wasn't the desired behavior.

**Comment by pkwarren** [comment]
Here's a sample program that illustrates the issue: https://gist.github.com/pkwarren/3fa55f642de17b797f7f7d8dae080d71

If you comment out line 98 and uncomment line 101, then the client will eventually refresh and succeed.

**Comment by zhangkun83** [comment]
The Channel normally converts empty address results to an error when passing it to the LoadBalancer, but we are currently not scheduling any retry in this case. We should probably do that, otherwise this is a hanging state the Channel can never get out of.

**Comment by zhangkun83** [comment]
@ejona86, the problem is in AutoConfiguredLoadBalancer. It returns `true` for `canHandleEmptyAddressListFromNameResolution()`, and converts empty address to error if the delegate returns `false` for that:
https://github.com/grpc/grpc-java/blob/v1.20.0/core/src/main/java/io/grpc/internal/AutoConfiguredLoadBalancerFactory.java#L144

This by-passes the NR retries which would be in effect if the top-level `canHandleEmptyAddressListFromNameResolution()` returned `false`.

Making `AutoConfiguredLoadBalancer.canHandleEmptyAddressListFromNameResolution()` returns the delegate value when available would introduce another problem -- if the delegate returns `false`, `AutoConfiguredLoadBalancer` can no longer handle pure-ServiceConfig results.

A possible solution is that we deprecate `canHandleEmptyAddressListFromNameResolution()`, and introduce `boolean tryHandleResolvedAddresses()`.

**Comment by ejona86** [comment]
@zhangkun83, there's no requirement for `AutoConfiguredLoadBalancer` to be a "normal" LB. We can make whatever internal APIs we want. I wouldn't change the public API because of AutoConfiguredLoadBalancer.
