### ISSUE TITLE
Maven plugin instructions are incomplete

### ISSUE THREAD

**Issue by borud** [grpc/grpc-java#575]
The build instructions do not seem to work.  The maven-protoc-plugin is neither in Maven Central nor does it appear to be in the Sonatype snapshot repository.  Which repository should we use?

**Comment by ejona86** [comment]
The plugin's source is at https://github.com/sergei-ivanov/maven-protoc-plugin/ . It does show that it isn't on Maven Central. It probably worked for us because we have it cached locally (in .m2) from a different test. You will want to add the Bintray repository as described on the maven-protoc-plugin's GitHub page (note that it _does not_ tell you that is necessary [on its documentation](http://sergei-ivanov.github.io/maven-protoc-plugin/usage.html) elsewhere).

@zhangkun83, I guess we need to update our README.md to include the pluginRepositories configuration. You want to take that on, or should I?
