### ISSUE TITLE
OkHttp's cancellation is not properly synchronized

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#583]
[`OkHttpClientStream.sendCancel()` calls `finishStream()`](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientStream.java#L213) from an application thread. But `finishStream()` [calls transportReportStatus() without any lock held](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java#L463). That is not synchronized correctly, as `transportReportStatus()` may only be called from the transport thread (i.e., while `lock` is held).

It seems that all usages of `streams` is done while `lock` is held except for within `finishStream()` and [data()](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/transport/okhttp/OkHttpClientTransport.java#L570). `data()` can actually race with `finishStream()` and end up sending DATA frames after the RST_STREAM. It seems it would be best to just have `stream` protected by `lock`, because it having its own synchronization isn't providing much benefit and isn't leading to correct code.

**Comment by madongfly** [comment]
Since we have a per stream lock inside of OkHttpClientStream, you may want to review the races you concerned.

But it does expose a potential deadlock, while we have both lock acquiring sequence of `transport lock -> stream lock` and `stream lock -> transport lock`.

We can go two directions, one is removing the stream lock, use the transport lock to lock every stream operations, which will hurt the performance, but should be fine since Android will not have much stream concurrency. Another one is rearranging the code, and define a clear order of acquiring locks, most likely `stream lock -> transport lock`, i.e. all stream operations should be called out of transport lock.

**Comment by madongfly** [comment]
Per our offline discussion, we are going to remove the stream lock and use transport lock instead.
