### ISSUE TITLE
The plugin should add boilerplate configuration and not require the user to do it

### ISSUE THREAD

**Issue by asarkar** [grpc/grpc-java#5864]
It is bad practice for Gradle codegen plugins to depend on the user to add new `sourceSets`. The plugin should do the following:
```
sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}
```

Also, the following seems to be boilerplate too. What does it do, and can the plugin do it as well?
```
protobuf {
    protoc { artifact = "com.google.protobuf:protoc:${protocVersion}" }
    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}" }
    }
    generateProtoTasks {
        all()*.plugins { grpc {} }
    }
}
```

**Comment by dapengzhang0** [comment]
Actually the `sourceSets` does not need be added, it's only for the convenience of some IDEs that do not know there are protobuf generated code. See the comment in the [examples](https://github.com/grpc/grpc-java/blob/v1.21.0/examples/build.gradle#L53)

**Comment by voidzcy** [comment]
The second piece allows the user to configure `protoc` (e.g., version, path if using a local binary or artifact if using binary from remote repo) and the _protoc plugin for grpc-java_ (to generate grpc java code, you need both `protoc` and [protoc plugin for grpc-java](https://github.com/grpc/grpc-java/tree/master/compiler)).

**Comment by asarkar** [comment]
@dapengzhang0 without the `sourceSets`, code doesn’t compile in IntelliJ, so I’ve no idea what your claim is based on. What IDE has knowledge of Protobuf generates code, and how? It’s not like there’s an option to create a “new project with to-be-generated protobuf code”.

**Comment by voidzcy** [comment]
@asarkar You should be able to compile without the `sourceSets` closure, even in Intellij. I tried with one of our examples with that closure deleted. Everything works fine.

Besides that, without that closure, Intellij (we are talking about Intellij only) should be able to identify the directories for generated java code and mark them as sources. This is because the in protobuf-gradle-plugin's implementation, we already added the output `sourceDirectorySet`s of `GenerateProtoTask` (which performs code generation) as inputs of compile tasks (e.g., `compileJava`, `compileTestJava`). So you don't need to set that to compile. For Intellij specifically, the protobuf-gradle-plugin applies the [IDEA plugin](https://docs.gradle.org/current/userguide/idea_plugin.html), which informs Intellij about generated code. The comment "Inform IDEs like IntelliJ IDEA, Eclipse or NetBeans about the generated code" should really be "Inform IDEs like Eclipse or NetBeans about the generated code" I guess.

**Comment by zhangkun83** [comment]
Please refer to https://github.com/google/protobuf-gradle-plugin#intellij-idea for how to use the Gradle plugin with IDEA. Also, this is not an issue with gRPC. Please file issues on https://github.com/google/protobuf-gradle-plugin for the related topics.
