### ISSUE TITLE
Cannot use generated classes

### ISSUE THREAD

**Issue by marcoliceti** [grpc/grpc-java#5990]
### What version of gRPC are you using?

1.22.1

### What did you expect to see?

I'm trying to generate and use classes from [the example in the quickstart](https://grpc.io/docs/quickstart/java/).

This is the proto file:

```protobuf
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";

package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```
According to the instructions in the quickstart guide, after compiling the proto file I should have a `GreeterGrpc`. This is what I get instead:

```
$ ls src/main/java/io/grpc/examples/helloworld
HelloReply.java  HelloReplyOrBuilder.java  HelloRequest.java  HelloRequestOrBuilder.java  HelloWorldProto.java
```
According to the guide I should extend `GreeterGrpc.GreeterImplBase`, but none of the generated classes contains `GreeterImplBase` (or even simply the string "ImplBase").

**Notes:** I compiled the proto file with `protoc` 3.9.0. More precisely:

```
protoc --java_out=src/main/java src/main/proto/HelloService.proto
```

**Comment by voidzcy** [comment]
```
protoc --java_out=src/main/java src/main/proto/HelloService.proto
```
only generates message types in Java, which are for `HelloRequest` and `HelloReply`. They are solely for data serialization/deserialization and its usage is not limited to gRPC.

In order to generate code for grpc-java IDL, you need to use grpc-java codegen plugin along with `protoc`. Its usage can be found in [this doc](https://github.com/grpc/grpc-java/tree/master/compiler) (basically you need to feed `protoc` with `--plugin=protoc-gen-grpc-java=PATH_TO_protoc-gen-grpc-java`).

If you are using Gradle as your build tool, [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin) makes your life much easier (you don't need to manage protoc compiler dependencies and invoke it manually). You can look at the [buildscript](https://github.com/grpc/grpc-java/blob/master/examples/build.gradle) in the examples directory.

**Comment by marcoliceti** [comment]
Hi, thank you. Actually, I used `protoc` because I was having trouble using the plugin. I'm using Maven and VS Code. This is basically what I was experiencing:

* no automatic generation of Java sources from proto files (a manual `mvn compile` was needed)
* generated sources were not included in the classpath -> several errors in VS code

I've just discovered that these problems are caused by `os-maven-plugin`. Solved by changing the example in the README from:

```xml
<build>
  <extensions>
    <extension>
      <groupId>kr.motd.maven</groupId>
      <artifactId>os-maven-plugin</artifactId>
      <version>1.5.0.Final</version>
    </extension>
  </extensions>
  <plugins>
    ...
  </plugins>
</build>
```
to:

```xml
<build>
  <plugins>
    <plugin>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.6.1</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>detect</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
  </plugins>
  ...
</build>
```
...as [documented here](https://github.com/trustin/os-maven-plugin#issues-with-eclipse-m2e-or-other-ides).

Now Java sources are correctly included in the classpath and automatically generated on project import and on changes to proto files. Hope this can be useful to other VS Code users :)
