### ISSUE TITLE
Protoc compiler plugin is being created with .exe suffix for all systems

### ISSUE THREAD

**Issue by jadekler** [grpc/grpc-java#6023]
See: https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.22.1/

Only windows binaries should have .exe, but all platforms have it. This is annoying because you have to change the file type manually.

**Comment by carl-mastrangelo** [comment]
Why is exe a problem for other platforms?

**Comment by sanjaypujare** [comment]
.exe is not a problem for other platforms but I think it creates the wrong impression that this is a Windows binary. Although I didn't understand the part saying "...you have to change the file type manually" in the original comment by @jadekler

**Comment by jadekler** [comment]
Yes, it's creating the impression that these are windows things. And, macs display .exes differently: Finder will show `name` instead of `name.exe`, for example. It'd be much more idiomatic to just use .exe with windows binaries since they're the only ones where it's a meaningful suffix.

**Comment by ejona86** [comment]
The Maven repository system requires artifacts to have file extensions. Since we must use a file extension, `.exe` seemed as good as any. Finder trimming the extension is what Finder does; I don't see how we can deal with that.

Most users should not touch these files, and the Maven/Gradle plugin will download them and execute them automatically.

**Comment by jadekler** [comment]
> The Maven repository system requires artifacts to have file extensions

What.. the heck. Hahaha. Ok, well, doesn't seem like something actionable. Thanks for investigating!
