### ISSUE TITLE
Deadline silently overflows at ~292 years

### ISSUE THREAD

**Issue by kluever** [grpc/grpc-java#6082]
Inside of `Deadline`'s constructor, there's this snippet of code:

```java
deadlineNanos = baseInstant + offset;
```

A `long` of nanoseconds overflows after ~292 years, so for all intents and purposes, it's _probably_ OK, but it still might be worth checking that an overflow didn't occur (either using a library like Guava's `LongMath.checkedAdd(long, long)` or Java8+'s `Math.addExact(long, long)`, or even just making sure the result isn't negative.

**Comment by dapengzhang0** [comment]
It makes sense to throw if Deadline overflows. However, we can not depend on Guava for `io.grpc.Deadline`, and currently we have not migrated to Java 8. Maybe it's nice to have just a plain implementation of check and throw.

**Comment by ejona86** [comment]
Nanotime by definition overflows, in the integer sense. From System.nanoTime()'s documentation:
> one should use t1 - t0 < 0, not t1 < t0, because of the possibility of numerical overflow.

A negative nanotime is not a bug. This is because nanotime has no defined epoch.

**Comment by kluever** [comment]
There's still a small issue: `units.toNanos(duration)` silently saturates

**Comment by ejona86** [comment]
@kluever, why is that an issue? Deadline "saturates" after 100 years, at a lower value than `TimeUnit`. See `MAX_OFFSET`.

**Comment by kluever** [comment]
Ahh, I missed that. Might be worth calling that out in the public javadocs so people don't have to read the source?

**Comment by dapengzhang0** [comment]
Should we throw when `Deadline.after(300, TimeUnit.YEARS)`?

**Comment by ejona86** [comment]
@dapengzhang0, we should not throw. It is very easy to end up doing variations of  Deadline.after(Long.MAX_VALUE, TimeUnit.NANOS). And 100 years in the future vs 200 years in the future doesn't really make much of a _practical_ difference, so I don't want people to have to code around it. (This came up in Netty for example; they threw when scheduling something too far in the future and it broke us.)

We could document that Deadline saturates. That's very easy and fair. We can explicitly mention that the saturation is 100 years, but we should be careful and say that it is an implementation detail. The only guarantee is that Deadline will saturate instead of overflowing.
