### ISSUE TITLE
Question: Fastest unix socket setup for single-request server

### ISSUE THREAD

**Issue by ronlut** [grpc/grpc-java#6150]
### What version of gRPC are you using?
4.1.39.Final

I need to run a server that will respond as fast as possible for a future request. This server's only purpose is to serve this single request and die, so I don't care about multiple requests or high load.

Currently what I'm doing is:
```
EpollEventLoopGroup elg = new EpollEventLoopGroup(1);
Server server = NettyServerBuilder
                .forAddress(new DomainSocketAddress(socketPath))
                .bossEventLoopGroup(elg)
                .workerEventLoopGroup(elg)
                .directExecutor()
                .channelType(EpollServerDomainSocketChannel.class)
                .withChildOption(ChannelOption.SO_KEEPALIVE, false)
                .addService(service)
                .build();
server.start();
```

Can I change something in this server/ELG setup to make it act faster?
I'm using directExecutor as I guess it should be faster that starting a thread for the request.
Not sure about the 1 thread ELG though.

Please remember I only need to serve 1 request as fast as possible. I will never receive more requests after this request.

Thanks a lot 👍

**Comment by dapengzhang0** [comment]
If it's in the same machine, you can try it over Unix Domain Socket (UDS), as far as I know, Java and Python support UDS for grpc. However, I don't know how to optimize Netty server for single client single request.

**Comment by ejona86** [comment]
That sounds like a quite reasonable approach.

"most performant" isn't a helpful metric, as there are diminishing returns; you could encode a message as a C struct instead of using protobuf, and that would be marginally faster but with usability losses. Even faster would be to use shared memory and have the server busy-poll the memory waiting for a request. But wastes CPU and lots of usability and needs some knowledge to set up.

directExecutor() is fine if you only expect to receive one request. You have chance of blocking I/O from other connections and if there was multiple RPCs on a connection you could slow down the other RPCs. But none of that matters to you.
