### ISSUE TITLE
Support for introducing custom tags to metrics

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#6236]
### Is your feature request related to a problem? Please describe.
@mackenziestarr [mentioned on Gitter](https://gitter.im/grpc/grpc?at=5d95143024509b60469b2e74):
I'm using the prometheus exporter and the grpc latency metrics look like this `grpc_io_client_roundtrip_latency_cumulative_bucket{method="google.bigtable.v2.Bigtable/ReadRows"}` but i would like to add an additional tag to achieve something like `grpc_io_client_roundtrip_latency_cumulative_bucket{method="google.bigtable.v2.Bigtable/ReadRows", table="my-bigtable-table"}`

### Describe the solution you'd like
Be able to access the opencensus contexts defined in the CensusStatsModule — pretty similar to this github issue census-instrumentation/opencensus-specs#142 which suggests maybe it is possible in grpc-java

It is fine to add the tag manually in the application; google-cloud-java doesn't need to do this automatically at present.

### Describe alternatives you've considered
Re-implement latency stats :slightly_frowning_face:

**Comment by zhangkun83** [comment]
The gRPC client creates the local per-RPC TagContext [as a child of the current TagContext](https://github.com/grpc/grpc-java/blob/v1.24.0/core/src/main/java/io/grpc/internal/CensusStatsModule.java#L687). @bogdandrutu, does the child TagContext inherit the tags from its parent? If so, the application could create a new TagContext with the custom tag, make it the current, before calling into google-cloud-java.

**Comment by bogdandrutu** [comment]
Is the table label coming from the client or from the server? If you can determine the table on the client side something like:

```java
    TagContext tags = tagger.currentBuilder().put("table", "TABLE_NAME").build();
    try (Scope scopedTagCtx = tagger.withTagContext(tags)) {
      ... // do work that makes the gRPC call
    }
```

**Comment by mackenziestarr** [comment]
thanks @bogdandrutu I will give this a try and report back — if it works out, maybe I can contribute some documentation back so others can take better advantage of the opencensus integration for their specific use cases.

**Comment by ran-su** [comment]
@mackenziestarr contributions are always welcomed here.

**Comment by cgardens** [comment]
@mackenziestarr how did this work out for you for the client metrics?

The more pressing case that I am grappling with right now, is that we want we want to add custom labels for metrics pushed in the opencensus _server_ metrics. e.g. label latency metrics (`grpc.io/server/error_count/minute`) by customer id. 

I'd be curious if the same approach by @bogdandrutu described would work on the server side (e.g. wrap the contents of my server endpoint in a new tagger context). Will probably give it a shot unless someone can tell me that is obviously not going to work.

**Comment by asafdav2** [comment]
@mackenziestarr @cgardens did any of you manage to make it work? thanks

**Comment by ericgribkoff** [comment]
I can (belatedly) confirm that the client-side approach from [the earlier comment](https://github.com/grpc/grpc-java/issues/6236#issuecomment-544643271), of creating a new `Scope` with the desired tags, does work:

```
Tagger tagger = Tags.getTagger();
TagContext tags = tagger.currentBuilder().putLocal(TagKey.create("table"), TagValue.create("TABLE_NAME")).build();
try (Scope scopedTagCtx = tagger.withTagContext(tags)) {
    // send RPC
}   
```

(Probably an obvious point to users of OpenCensus, but I believe that you will need to also define a custom `View` that includes the `"table"` `TagKey` in its `columns` parameter in order to aggregate/see the custom tag values set by the client).

However, as mentioned in [another comment](https://github.com/grpc/grpc-java/issues/6236#issuecomment-541984312) this approach only seems possible on the client-side where the `TagContext` used by gRPC [inherits](https://github.com/grpc/grpc-java/blob/e4215b422d142ea0288c6236fb703141b380f60d/census/src/main/java/io/grpc/census/CensusStatsModule.java#L687) from the current context. This is not the case on the server-side, where we take the context sent over the wire by the client in the [RPC metadata](https://github.com/grpc/grpc-java/blob/e4215b422d142ea0288c6236fb703141b380f60d/census/src/main/java/io/grpc/census/CensusStatsModule.java#L668). 

The [linked issue](https://github.com/census-instrumentation/opencensus-specs/issues/142) on OpenCensus remains unresolved, and will likely stay that way given that OpenTelemetry is in the process of replacing OpenCensus. From my reading of that thread, the only suggestion there that this feature might already "just work" with gRPC centered on directly manipulating the thread-local `Tags`.

@ejona86 Would we want to mark this closed (works-on-client, doesn't-work-on-server-but-OC-is-going-away) or keep this around as an enhancement request for whatever eventually replaces OC (presumably OpenTelemetry)?

**Comment by asafdav2** [comment]
Is there a way to leverage this approach and add tags in a client interceptor? I have a `ClientInterceptor` that implements `interceptCall` by retuning an instance of `ForwardingClientCall.SimpleForwardingClientCall<ReqT, RespT>` which overrides the `sendMessage(ReqT message)` method as shown above (wrapping the `super.sendMessage` call in a try-with-resources clause that creates a tag context with additional tags). However, these additional tags are not received in the server-side. any ideas?

**Comment by ejona86** [comment]
@ericgribkoff, let's go ahead and close this. It seems it is more of an OC issue than gRPC.

@asafdav2, the context used by the call is the current one when the call is created. After that point the thread's current context is ignored. So you should set the Context before calling `next.newCall()`. If you are pulling out the details from the request, you'll need to buffer the initial methods and wait for sendMessage or halfClose before calling newCall.
