### ISSUE TITLE
Are grpc-benchmarks and grpc-interop-testing for users?

### ISSUE THREAD

**Issue by suztomo** [grpc/grpc-java#6354]
The artifacts grpc-benchmarks and grpc-interop-testing are part of grpc-bom. Are they intended to be used by users?

# grpc-java/benchmarks
https://github.com/grpc/grpc-java/tree/master/benchmarks

# grpc-java/interop-testing
https://github.com/grpc/grpc-java/tree/master/interop-testing

Background:  https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1004

Our static analysis shows that transitive dependencies of the two artifacts have missing class references. I'm wondering whether these missing references would cause problems for Google Cloud users or not. If they will not go users' class path, then it won't cause a problem.

**Comment by ejona86** [comment]
They aren't intended to be used as libraries. We don't attempt to provide API stability. Users may want to run them (especially interop-testing) which is why they are published. We could remove them from the bom without issue. They are included now just because we included all artifacts that are published on maven central.

There's multiple other artifacts that we publish that are not used by Google Cloud users, but are intended for general consumption.

**Comment by suztomo** [comment]
Thanl you for the answer!
https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1004 turned out an mistake on imports. No action required.
