### ISSUE TITLE
Bidirectional streaming in Android gRPC disconnect after about 20 seconds

### ISSUE THREAD

**Issue by mohammadnejad** [grpc/grpc-java#6462]
Bidirectional streaming in Android gRPC disconnect after about 20 seconds in Cellular internet. With wifi everything is OK. I use AndroidChannelBuilder with default config in client, and I use NettyServerBuilder with default config in server. 

Server Exception is: 
Sending GOAWAY failed: lastStreamId '11' , errorCode '2' , debugData 'readAddress(..) failed: Connection reset by peer' . Forcing shutdown of the connection.
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: writeAddress(..) failed: Broken pipe

**Comment by voidzcy** [comment]
Does this happen consistently in Cellular environment with decent signal strength? What's your Android device and which SDK version do you use?

Did you configure [`context`](https://github.com/grpc/grpc-java/blob/7db873f1f6523349d3e51e9613b807b68e4abcde/android/src/main/java/io/grpc/android/AndroidChannelBuilder.java#L134) for network state monitoring? If you didn't, can you try with that added? If you did, can you try with that removed? Since it worked fine with WiFi, gRPC itself should have no problem. So we want to see if Android connectivity manager makes any difference.

**Comment by mohammadnejad** [comment]
Yes, This problem happen consistently  in Cellular environment.I tested with many device with different android version and problem didn't solve . I have found that when  I change port  number from 8080 to other port for example 8081 in server my problem is solved.

**Comment by voidzcy** [comment]
That's very wired. But seems the issue is caused by server side. You probably have some other processes on server side that affect your gRPC service (its port). I cannot think of any reason in gRPC that causes it to work for port 8081 but break for port 8080.

**Comment by sanjaypujare** [comment]
> ...You probably have some other processes on server side that affect your gRPC service (its port). 

That doesn't explain the cellular vs wifi behavior difference. This [post](https://stackoverflow.com/questions/29547278/android-app-that-connects-to-server-port-8080) talks about issues with ports specific to using cellular.

**Comment by voidzcy** [comment]
Oh, that post is surprisingly interesting. Good to know. Thanks

**Comment by ericgribkoff** [comment]
It doesn't seem like there's anything else for us to do here, so I'm going to mark this closed. @mohammadnejad Feel free to comment if there's anything else I'm missing and you'd like me to reopen.
