### ISSUE TITLE
implement health checking service

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc-java#647]
defined in "gRPC Health Checking Protocol"

**Comment by jhump** [comment]
Square's current RPC implementation (pre-GRPC) does peer-to-peer health checking via polling. However, when moving to GRPC, we intend to take advantage of streaming support to do this in a better way:

1. Clients can be configured to send HTTP/2 ping frames to the server, just to verify connectivity (and keep the connection alive).
2. Clients can issue a "GetStatus" RPC that each server would support. The response is streaming. Whenever the server's state changes, it pushes that info as a message on all outstanding response streams for clients that have started a "GetStatus" RPC.

Since push from the server eliminates the polling interval as a source of latency, the ping frames can have a reasonably high duration between. Clients and intermediary load balancers could both use this to gather health info from backends.

Is this at all like what is being done? Please provide details on how this will be solved as soon as you have them.

Thanks.

**Comment by ejona86** [comment]
@jayantkolhe, I have this in 0.8.0 milestone for the moment because of the possible API impact.

**Comment by ejona86** [comment]
@jhump, the health checking service alluded to here is a protobuf-based gRPC service. It used to be streaming-based, but for some reason it was changed back to a unary request. @yang-g, could provide more info. It isn't very magical; you would typically issue an empty request and get back a response that contains an enum of UNKNOWN, SERVING, NOT_SERVING.

But importantly, this won't be part of "core"; it is an add-on. It may be an easy-to-enable add-on, but an add-on none-the-less.

On Friday I discussed with @a11r about some troublesome aspects of it. It appears he didn't get a chance to make the changes (and push them to GitHub) on Friday, and he will be gone for two weeks. @yang-g, did he discuss the changes to be made to health checking with you? We were going to remove host and clarify service.

Because of the changes discussed with @a11r, I am no longer concerned about the API ramifications of this change, although it would be nice to add a `HandlerRegistry.lookupService` method before API-freeze so that it can be abstract.

**Comment by yang-g** [comment]
Yes. I am updating the PR. Regarding the streaming to unary change, it was
done to start with a simple(r) protocol.

**Comment by ejona86** [comment]
@jhump, you can find the protocol in grpc/grpc#2806

**Comment by ejona86** [comment]
Are confident adding this won't require API breakage, so moving to post-Beta.
