### ISSUE TITLE
grpc server restarted, client cannot connect immediately.

### ISSUE THREAD

**Issue by johnhec** [grpc/grpc-java#6473]
when grpc server restarted, the grpc client cannot connect the server immediately.
Sometimes a few seconds, sometimes a few tens of seconds.Why is that？

**Comment by creamsoup** [comment]
if the server restarts, client tried to reconnect with exponential backoff. depends on the timing, it can wait a few more attempts which can be order of seconds to tens of seconds.

**Comment by johnhec** [comment]
> if the server restarts, client tried to reconnect with exponential backoff. depends on the timing, it can wait a few more attempts which can be order of seconds to tens of seconds.

Is it possible to set up an immediate connection mechanism, and if so, is there any other problem with this mechanism?

**Comment by creamsoup** [comment]
for the client point of view, it has no information about when the server will be available. if it does it should be already connected, because this involves network communication. if the client do some sort of busy waiting, it can achieve near immediate connection. this will have the same problem of busy waiting; wasting a lot of resources (cpu, network, etc). if there are many clients doing this behavior, this is essentially attacking the server.

**Comment by johnhec** [comment]
> for the client point of view, it has no information about when the server will be available. if it does it should be already connected, because this involves network communication. if the client do some sort of busy waiting, it can achieve near immediate connection. this will have the same problem of busy waiting; wasting a lot of resources (cpu, network, etc). if there are many clients doing this behavior, this is essentially attacking the server.

Is there a configuration that can set the maximum reconnection time to ensure that the client can connect within a certain time.

**Comment by creamsoup** [comment]
`ManagedChannel#resetConnectBackoff` could be used to accelerate the reconnect (not highly recommended, please read the javadoc). 
`#notifyWhenStateChanged(ConnectivityState, Runnable)` can call `resetConnectBackoff` or `shutdown` with custom timer can achieve what you asked. Note that those APIs are experimental.

**Comment by johnhec** [comment]
> `ManagedChannel#resetConnectBackoff` could be used to accelerate the reconnect (not highly recommended, please read the javadoc).
> `#notifyWhenStateChanged(ConnectivityState, Runnable)` can call `resetConnectBackoff` or `shutdown` with custom timer can achieve what you asked. Note that those APIs are experimental.

In the helloword program, I added the following code:
public HelloWorldClient(String host, int port) {
        this(ManagedChannelBuilder.forAddress(host, port)
                // Channels are secure by default (via SSL/TLS). For the example we disable TLS to avoid
                // needing certificates.
//                .defaultServiceConfig(retryPolicy())
//                .enableRetry()
                .usePlaintext()
                .build());
        channel.notifyWhenStateChanged(ConnectivityState.SHUTDOWN, new Runnable() {
            @Override
            public void run() {
                System.out.println("reset---");
                channel.resetConnectBackoff();
            }
        });
    }
Except for the first run of the client, the run () method was run. At other times, I closed the server and the run method did not run again.

**Comment by creamsoup** [comment]
the javadoc says it will only run once, so what you observed is correct. also, the API expects to have current state otherwise it will be fired immediately which will be essentially no-op because it hasn't retried yet. 
one other thought is, usually the connect should be refused immediately if the server is completely down. so assuming if the server is not in a good state and the connect takes long time to be fail, you could provide a `ChannelOption` of shorter connection timeout via `NettyChannelBuilder#withOption` setting `CONNECT_TIMEOUT_MILLIS`.

**Comment by johnhec** [comment]
> the javadoc says it will only run once, so what you observed is correct. also, the API expects to have current state otherwise it will be fired immediately which will be essentially no-op because it hasn't retried yet.
> one other thought is, usually the connect should be refused immediately if the server is completely down. so assuming if the server is not in a good state and the connect takes long time to be fail, you could provide a `ChannelOption` of shorter connection timeout via `NettyChannelBuilder#withOption` setting `CONNECT_TIMEOUT_MILLIS`.

Thanks, via NettyChannelBuilder#withOption setting CONNECT_TIMEOUT_MILLIS  works
