### ISSUE TITLE
Allow creating context with more than 4 keys

### ISSUE THREAD

**Issue by nathanhleung** [grpc/grpc-java#6507]
### Is your feature request related to a problem?
I'd like to create a context with more than 4 keys (limit seems to be 4 according to: https://github.com/grpc/grpc-java/blob/master/context/src/main/java/io/grpc/Context.java#L359)

### Describe the solution you'd like
Ideally, an overload to `withValues` that potentially could take a `Map<Key, V>` of Context keys and values, enabling an arbitrary number of context keys to be used in a single context if a consumer of this library wanted more than 4

### Describe alternatives you've considered
We could just use a single Context key and store all of our context in a single map associated with that key, but before I do that I wanted to understand if there was a reason for limiting `withValues` to taking 4 key-value pairs

**Comment by ejona86** [comment]
You can just chain together multiple withValues.

```java
context.withValues(K1, V1, K2, V2);
// is same as
context.withValues(K1, V1).withValues(K2, V2);
```

The only difference is that the first produces a bit less garbage and in the initial implementation of Context was slightly more efficient to do lookups (since keys were stored as a linked list).

I will note that Context should not be treated like a general purpose map, throwing lots of stuff in it. That is to say, combine multiple related items together into a single key instead of having them separate. But if there are two unrelated things, have two keys for them. `Key`s should virtually always be constants.

**Comment by nathanhleung** [comment]
Ok, thanks! I'd be open to creating a PR to add overloads for `withValues` for more key-value pairs (up to 4, 5, etc) if that would help, or updating the Javadoc of the existing `withValues` method with the example you just mentioned. What would you prefer?

**Comment by ejona86** [comment]
A PR to update the `withValues` Javadoc to say it is equivalent of the separate calls sounds good.

**Comment by nathanhleung** [comment]
Opened #6545

**Comment by ran-su** [comment]
#6545 added detailed documents for `withValues`. So this issue is resolved.
