### ISSUE TITLE
http to https change over to Maven not yet available in Maven

### ISSUE THREAD

**Issue by randykweinstein** [grpc/grpc-java#6606]
In reference to #6536 which appears to have been fixed just after 1.26.0 was released.  There are no later versions or patch versions available at https://mvnrepository.com/artifact/io.grpc/grpc-protobuf or the other required grpc dependencies that includes this critical fix.

Thanks!

**Comment by ejona86** [comment]
I don't understand the problem you are explaining. Could you explain what "required grpc dependencies" are missing the fix? For now I would expect Bazel users to use the commits on the release branches directly. It is very easy for Bazel users to specify a commit on the release branch, instead of a tagged version. Part of the trouble is that all the releases are impacted and it isn't clear how many people were on v1.26.0 already.

**Comment by davidlee1435** [comment]
👋 Bazel user here.

We fixed this by switching to using `git_repository` in our WORKSPACE on the latest master instead of using `http_archive` to download the tarball.

**Comment by ejona86** [comment]
We're discussing some here making patch releases to make it easier for Bazel users to find.

You can continue using http_archive, using a link like https://github.com/grpc/grpc-java/archive/b6f5233929463431c8e5595fd793c41e280695b4.zip . [We have done something like that](https://github.com/grpc/grpc-java/commit/024a46bd11120e706f2ee8fb10d1cbefc9be9b5a#diff-515bc54a0cbb4b12fb4a7c465758b011) for protobuf several times.

**Comment by systemlogic** [comment]
@ejona86 Do you think, upgrading of bazel version solves the http to https flip on maven central ?
Current bazel version is use is 0.29.1

**Comment by systemlogic** [comment]
@ejona86 Do you think, upgrading of bazel version solves the http to https flip on maven central ?
Current bazel version is use in below 1.0.0

**Comment by ronaldmiranda** [comment]
/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/io_grpc_grpc_java/compiler/BUILD.bazel:18:1: @io_grpc_grpc_java//compiler:java_grpc_library_deps__do_not_reference depends on @com_google_code_findbugs_jsr305//jar:jar in repository @com_google_code_findbugs_jsr305 which failed to fetch. no such package '@com_google_code_findbugs_jsr305//jar': java.io.IOException: Error downloading [http://central.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar] to /root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_google_code_findbugs_jsr305/jsr305-3.0.2.jar: GET returned 501 HTTPS Required

**Comment by ronaldmiranda** [comment]
`rules_grpc_commit = "a4299eb6bed3c2f2497f583d0c4620c9f31ec455"
rules_grpc_java_sha = "62b0dc1403321e716fc550349011cab008ae158cb4ebb1931644a68f45567387"

http_archive(
    name = "io_grpc_grpc_java",
    urls = [
        "https://github.com/grpc/grpc-java/archive/%s.zip" % rules_grpc_commit,
    ],
    sha256 = rules_grpc_java_sha,
    strip_prefix = "grpc-java-%s" % rules_grpc_commit,
)

load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")

grpc_java_repositories()`

**Comment by ejona86** [comment]
@ronaldmiranda, it would be must better to use commit b6f5233929463431c8e5595fd793c41e280695b4 instead of a4299eb6bed3c2f2497f583d0c4620c9f31ec455, since the former is on the v1.26.x release branch. But, yes, that approach is what I was suggesting.

There is a backport for multiple versions (as seen at the end of #6543).

grpc version | commit
------------|---------
v1.23.x | f967a13
v1.24.x | 62e8655
v1.25.x | 8140435
v1.26.x | b6f5233929463431c8e5595fd793c41e280695b4

**Comment by ejona86** [comment]
For the record, I've not considered this too big of a deal because using "random commits on a release branch" was par for the course in the ecosystem for several years due to Bazel upgrade breakages.
