### ISSUE TITLE
Invert User-Agent order so application-provided string comes first

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#668]
[RFC 7231§5.5.3](http://tools.ietf.org/html/rfc7231#section-5.5.3) says:
> By convention, the product identifiers are listed in decreasing order of their significance for identifying the user agent software.

Combined with the example, it seems that we should put the application-provided string first.

**Comment by carl-mastrangelo** [comment]
Did you expect to support arbitrary numbers of product identifiers and/or comments?

**Comment by ejona86** [comment]
@carl-mastrangelo, I don't think any of us were worried about the application providing multiple. Is there a reason we should provide a limit?

**Comment by carl-mastrangelo** [comment]
Looking at the implementation in ClientCallImpl it doesn't appear that most of the http2 rules are followed?  Specifically:

> User-Agent = product *( RWS ( product / comment ) )
* From the spec, it looks like multiple product versions are collapsed into a single line, rather than having multiple headers.  

> product / comment
* It looks like our lib accepts an arbitrary string from the application.  The spec makes it seem like it needs to be a specific ascii format.

**Comment by ejona86** [comment]
> From the spec, it looks like multiple product versions are collapsed into a single line, rather than having multiple headers.

I thought we do put them all in a single header. Is there a reason you think we don't?

> It looks like our lib accepts an arbitrary string from the application. The spec makes it seem like it needs to be a specific ascii format.

I'm not quite sure I follow. If we added documentation saying the user agent the user specifies to `AbstractChannelBuilder` must be valid according to RFC 7231§5.5.3, would that satisfy the concern?
