### ISSUE TITLE
FR: Cancellable Response Iterators for Server-side streaming calls

### ISSUE THREAD

**Issue by BrandonY** [grpc/grpc-java#6727]
### Is your feature request related to a problem?

I'm implementing a client that streams responses. It's really easy to do this:

```
Iterator<Feature> features;
features = blockingStub.listFeatures(request);
for( Feature feature : features ) {
   processFeature(feature);
}
```

But I want to stop processing at some point when I find the response I'm looking for:

```
Iterator<Feature> features;
features = blockingStub.listFeatures(request);
for( Feature feature : features ) {
   if(featureIsPerfect(feature)) {
      return feature;
   }
}
```

This unfortunately leaves the connection hanging. I want to close the connection. This is surprisingly difficult, but it shouldn't be. Here's what I think is maybe the right way?

```
CancellableContext withCancellation = Context.current().withCancellation();
try {
     withCancellation.run(new Runnable() {
       public void run() {
         Iterator<Feature> features;
         features = blockingStub.listFeatures(request);
         while (!Context.current().isCancelled() && features.hasNext()) {
            Feature feature = features.next();
            if(featureIsPerfect(feature) {
                   withCancellation.cancel(new Exception("After this, I think I need to explicitly drain the iterator, too"));
                   while(features.hasNext()) {
                      features.next();
                    }
               return feature;
            }
         }
       }
     });
     doSomeWork();
   } catch (Throwable t) {
      withCancellation.cancel(t);
   } finally {
       if(!withCancellation.isCanceled()) {
            withCancellation.cancel(new Exception("Everything is fine but all cancellableContexts must be canceled"));
       }
   }
```

This seems unnecessarily complicated. I'm have no idea if it's even right.

### Describe the solution you'd like

I'd like the return for a server-side streaming call to be subclass of Iterator that implements AutoCloseable, which when closed would cancel the request. That would allow me to do this:

```
try (ClosableIterator<Feature> features = stub.listFeatures(request)) {
   for(Feature feature : features) {
     if(featureIsPerfect(feature))
          return feature;
   }
}
```

### Describe alternatives you've considered

If there were a way to explicitly request something like `Context.of(responseIterator).cancelCurrentRequest()`, that would also probably be fine.

I could explicitly kill the entire channel, but I'd prefer not to.

### Notes

I'm still learning the Java gRPC interface, so it may be that I have overlooked an existing solution.

**Comment by ericgribkoff** [comment]
The blocking stub for server-streaming does return an iterator that should be drained to end the call normally, but you could also interrupt the thread. There is discussion around the available options [here](https://groups.google.com/g/grpc-io/c/quToVM4NhdQ/m/Msmfdo4NAgAJ) and [here](https://github.com/grpc/grpc-java/issues/3095#issuecomment-338724284).

Probably the simplest approach is to use a cancellable context, as in your example, but I think it can be simplified quite a bit to look more like the following, adapted from the documentation at https://grpc.github.io/grpc-java/javadoc/io/grpc/Context.CancellableContext.html

```
 try (CancellableContext c = Context.current()
     .withDeadlineAfter(100, TimeUnit.MILLISECONDS, executor)) {
   Context toRestore = c.attach();
   try {
       for( Feature feature : blockingStub.listFeatures(request) ) {
           if(featureIsPerfect(feature)) {
               return feature;
           }
       }
   } finally {
     c.detach(toRestore);
   }
 }
```

There is a `ClientCallStreamObserver.cancel()` method that makes this simpler with our asynchronous API and bidirectional or client-streaming calls. @ejona86's comment [here](https://github.com/grpc/grpc-java/issues/3095#issuecomment-338724284) mentions passing in your own implementation of `ClientResponseObserver` in the passed-in `StreamObserver` for a server-streaming async call, but I don't see any simple way to do this, and it would seem at that point you may be better off interacting with the `ClientCall` API directly instead of using the generated-stubs.

**Comment by BrandonY** [comment]
Thanks, that sounds like a reasonable alternate. I'm confused on terminology, though. What's the difference between cancellation and detaching? Do both signal to the server that the RPC is over?

**Comment by ericgribkoff** [comment]
Detaching the context does not signal to the gRPC client library that the call should be cancelled. But in the 'try-with-resources' block from the docs/my comment above, which only works since the CancellableContext implements Closeable, the context will automatically be closed when the try block finishes - and `close()` is equivalent to a `cancel(null)` call. This close ends the call on the client, which is also relayed to the server.

**Comment by BrandonY** [comment]
Sounds good, thanks. I'll look into using your suggestion.

That said, I think that the ClosableIterator I suggested would still be a nice usability improvement, although perhaps there are downsides? I see in the documentation that it is apparently important that CancellableContexts include a timeout.

**Comment by ejona86** [comment]
People would still have to know to cast the return value to a ClosableIterator, and overall still wouldn't be extensible. There is a way now, and we'd rather keep the iterator API as-is.

I think we strongly agree things could be improved. But any work on this front should probably be to create a new better, more complete blocking API that works for bidi as well and we try to supplant the existing iterator API.
