### ISSUE TITLE
CallOptionsTest is flaky

### ISSUE THREAD

**Issue by creamsoup** [grpc/grpc-java#6757]
https://travis-ci.org/grpc/grpc-java/jobs/655139606?utm_medium=notification&utm_source=github_status (java8)

```
io.grpc.CallOptionsTest > withDeadlineAfter FAILED
    expected               : 59.983802256s from now
    but was                : 59.983668916s from now
    outside tolerance in ns: 10000000
        at io.grpc.CallOptionsTest.withDeadlineAfter(CallOptionsTest.java:140)
```

i've seen this more than one time.

**Comment by ejona86** [comment]
@larry-safran noticed that the expected/actual were within the tolerance (which is actually visible here). He was fixing that up, but I overhead and that means we the BigInteger classloading is probably what is actually introducing the flakiness, because later the values appear somewhat close together (not guaranteed okay, since there's String processing so they could just _happen_ to be close together after the string processing, but seems unlikely). If we get rid of the BigInteger handling (because overflow is actually not a problem after the subtraction), then this long-time flake will hopefully go away.
