### ISSUE TITLE
Attaching Metadata to error Status responses...

### ISSUE THREAD

**Issue by dconnelly** [grpc/grpc-java#681]
I'm not sure what the "best practice" is for returning application-level error information (would be very useful to understand Google's own internal practice for guidance), but certainly one approach is to attach trailing headers with application error information to error responses. Setting additional headers via thread-local using a server interceptor seems easy enough, but for client-side it seems particularly awkward capturing metadata on a per-call basis using an interceptor. I see examples in MetadataUtils for capturing "last set headers" on a stub or channel but this is only useful for testing and cannot capture on a per-call basis. Other option would be to use the async stub and a thread-local to pass the metadata information along to StreamObserver.onError() but this loses the convenience of using the blocking and future stubs. I'm not sure if the same approach works for a blocking or future stub since the listener may be invoked in a different thread. 

Will the context api once fully integrated make this easy, or would it make sense to have a way to "attach" metadata to a Status object (perhaps this would be desirable anyway for convenience)?

**Comment by ejona86** [comment]
> I'm not sure what the "best practice" is for returning application-level error information (would be very useful to understand Google's own internal practice for guidance), but certainly one approach is to attach trailing headers with application error information to error responses.

Yes, that is what I would suggest, and I think that is what we would encourage. However, it may not be very-well supported in the various languages, simply because the use-case may not have been thought about. I simply don't know if it is. I do know that we discovered that it was hard to do in node.js recently and so the design has been changed to make it easier.

> Setting additional headers via thread-local using a server interceptor seems easy enough, but for client-side it seems particularly awkward capturing metadata on a per-call basis using an interceptor.

You can install a different interceptor per-call on client-side. In master, the reconfiguring of stubs is also easier since we've removed the builder pattern; you can do `stub.withInterceptors(someInterceptor)` to attach an interceptor to a particular call. Reconfiguring the stub per-call is not something to be avoided. Our design assumed that reconfiguring would be cheap enough and easy enough to permit frequent reconfiguration.

> Will the context api once fully integrated make this easy

I think the Context API would still have any problems outlined with the blocking stub. Future stub _could_ actually be fine, since the thread-local can be propagated through the executor (via `wrapDynamic()` method in #659).

> would it make sense to have a way to "attach" metadata to a Status object (perhaps this would be desirable anyway for convenience)?

I'm not against the idea, but there was push-back from @louiscryan when the idea was proposed internally. He felt that interceptors would function well in Java, and in general it was just a "nice to have."

If we did it, I think we would want it to be automatic and a cross-language feature. It may be more along the lines of some metadata would be "error" related, say by appending "-error" to the name, and any such Metadata is automatically made available from the Status. Or maybe we make a special "grpc-status-extra" Metadata key, with the [Any protobuf type](https://github.com/google/protobuf/blob/master/src/google/protobuf/any.proto) for protobuf users, that is included with the Status.

That's a longer discussion, and I think would be most easily discussed by trying to demonstrate issues with the status quo. So at present I would recommend just installing a new interceptor each call.

**Comment by dconnelly** [comment]
Thanks Eric. I'm proceeding with the interceptor approach and should be able to produce a standalone example service for review and discussion.

**Comment by dconnelly** [comment]
Eric, see https://github.com/dconnelly/grpc-error-example for an example of how we are passing app error information via metadata, and capturing it client side. Especially client side, things are a bit tedious when using the generated stubs. It turns out to be much easier to implement using direct unary calls, let me know what you think and if you see any areas for improvement.

**Comment by ejona86** [comment]
@dconnelly, that appears to be a pretty fair implementation. If you didn't make your own error type and required call sites to manually look at the atomic it would be less code. However, making your own error type is appropriate in many ways. Thanks for doing that! It is pretty thorough.

At the moment, @louiscryan is on vacation (for a few weeks). I expect when he comes back we will discuss, along with @wrwg, who is also pro-"have an easy way to propagate application-specific error information". I don't think this blocks us going Beta (where we are supposed to be mostly API-stable), but it would also be good to figure out the usability sooner rather than later.

**Comment by zackangelo** [comment]
+1

**Comment by ejona86** [comment]
@jcanizales and @carl-mastrangelo, FYI

**Comment by louiscryan** [comment]
So a couple of options are on the table with varying merits:

1. Attach trailer Metadata to Status. Clients use Status.from(Throwable) to extract where necessary
2. Attach trailer Metadata to StatusXXXException. Use similar mechanism to extract from Throwable
3. Do nothing an let folks use interceptors and Context (now that its bound to callbacks) to do what they see fit
4. Allow interceptors to control how errors are converted from the Status received in ClientCall.Listener#onClose to the exception propagated to the application code.

Generally I'd favor (2) over (1) as some of the lower level callbacks take both Status & Metadata. This pattern works fairly well with Futures / blocking

(3) has it's attractions but it does have a hard requirements that Context is properly bound to the thread handling the error and this is hard to guarantee for blocking / Future

(4). This might simply boil down to having the interceptor create an application specific error and putting it in the causal chain for StatusXXXException which the application code could then extract

I think (3) is probably the least attractive option. Between 1/2 & 3 I guess it would depend how developers would prefer to handle typing for their exception data and how structured they want to be about it

**Comment by jcanizales** [comment]
OAuth2 error details go in the header Metadata; we might want to include both instead of only the trailers.

**Comment by carl-mastrangelo** [comment]
@louiscryan I tried locally option number 1, and it wasn't straightforward.  There are a lot of places that we initialize Status, and finding them all and testing it would take some time.  I agree 3 is definitely bad for long term; trying to do this pattern myself in the interop tests was a pain.

Despite the pain of option 1, option 2 is less attractive in my mind.  Exceptions are for exceptional things right?  Option 1 is most similar to how we are doing things internally, which would ease adoption.

**Comment by ejona86** [comment]
I'm generally in favor of 2 and 4. I'm on the fence on which of the two I prefer.

1 could be fine, but it seems strange to include `Metadata` in `Status`, since at other times `Status` is inside `Metadata`. I'm also uncomfortable with `Status` sometimes having `Metadata` and sometimes not; it'll be confusing for APIs to know whether they use the `Metadata` or not. It seems like it would cause a mess.

2 seems to maintain general semantics well, and (effectively) only changes only the stubs. @carl-mastrangelo, in my mind the metadata is on the exception _because_ it is expected to be error-related. It would be nice to only include the metadata that is error related, but that doesn't seem on the table.

3 can work, but seems to just be abusing `Context.` I would expect this to cause a bit of a mess.

4 is intriguing to me. It wasn't obvious from the description, but Louis said offline it could take the form of the interceptor calling `Status.withCause()` to fill in details. That seems strictly better than 3.

**Comment by zackangelo** [comment]
Was a decision made on which option to move forward with?

**Comment by ejona86** [comment]
I still feel really good about adding the trailer Metadata to Status{,Runtime}Exception. Let's try to finish this up in the coming weeks. I'd be pretty disappointed if we still didn't have a decision by 1.0.

**Comment by parkan** [comment]
+1 definitely very interested in best practices here

**Comment by ejona86** [comment]
General agreement to go with option 2, adding `Metadata` to `Status*Exception`.

**Comment by Ykid** [comment]
How is this approach better than simply using oneof ?

```
enum Error {
    WRONG_CREDENTIAL = 0;
   //something else
}
oneof result {
   Data data = 1;
   Error error = 2;
}
```
