### ISSUE TITLE
Remove dependency on javax.annotation.Generated

### ISSUE THREAD

**Issue by ulfjack** [grpc/grpc-java#6833]
A similar issue was previously reported in #5343, which I cannot reopen. The problem with the solution proposed there is that the upstream library that is pulled this way is licensed under the CDDL. You should probably talk to a lawyer about the implications of that, and whether they apply here.

In any case, given that gRPC seems to be intended to be licensed as Apache 2, it seems wiser to remove the dependency entirely or at least provide an option to avoid it.

**Comment by ejona86** [comment]
A quick note that `org.apache.tomcat:annotations-api` is available and under Apache 2. It appears that long-term the annotation is being renamed to jakarta.annotation.Generated.

The biggest problem with the annotation is there are so many different artifacts containing it, which causes classpath collisions.

**Comment by ulfjack** [comment]
Java 9 has javax.annotation.processing.Generated, which seems to be the proper replacement?

**Comment by ejona86** [comment]
See #3633 concerning `javax.annotation.processing`.

**Comment by ulfjack** [comment]
Ok, I'll try hard not to reopen that discussion. Would it be a hardship for you to add a flag that allows the user to select the annotation (or disable it)?

The mentioned ```org.apache.tomcat:annotations-api``` contains a source file *jakarta*/annotation/Generated.java. Misread?

I've worked around the issue for us, but it seems risky to recommend using CDDL-licensed code.

**Comment by ejona86** [comment]
There is `org.apache.tomcat:annotations-api` (`javax.annotation`) and `org.apache.tomcat:tomcat-annotations-api` (`jakarta.annotation`). Apparently all of J2EE moved to the Eclipse Foundation and is being renamed Jakarta EE and moving packages.

Normally we can't have options for the generated code because we need there to be a canonical version used by everyone (otherwise we start seeing diamond dependency issues). Since this annotation is source-level only, it would be possible to have an option for it. But in general it would be best for everyone to resist options. For example, in this case we may change our recommendation to use `org.apache.tomcat` or, depending how the tools are implemented, make a `io.grpc.Generated`.

**Comment by creamsoup** [comment]
closing it due to inactivity, please feel free to reopen.

**Comment by ulfjack** [comment]
I can't reopen bugs in this project, so that statement feels a bit passive-aggressive. I think having a dependency on CDDL-licensed code is a problem - even if only a burden on your users to make sure that they don't accidentally include it in whatever they're distributing -, and I'm happy to send a patch if there's agreement on what to do.

Personally I would use the javax.annotation.processing.Generated annotation in the JDK; I understand the concern that it's intended for annotation processing, but I personally think that concern is academic. I'd also be happy with removing the annotation, but I don't know if anyone's relying on it.

**Comment by ejona86** [comment]
(@ulfjack, @creamsoup was not aware you couldn't reopen issues. All the same, we normally would say "comment with more information and we can reopen")

I saw this had been closed, but I didn't realize it was _this_. Yeah, this should remain open. The inactivity is on our side.
