### ISSUE TITLE
OpenCensus 0.26.0 update

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#6928]
Can we update OpenCensus to 0.26.0 from the current 0.24.0? 

if not, what needs to be fixed before we can proceed?

**Comment by ejona86** [comment]
Good question. I don't know of any reason it would be an issue. Nobody has looked into it to my knowledge. Is there a known issue with that version?

It looks like they updated some of their dependencies. That should be fine, but may be minorly annoying to update the excludes. But that's the "normal process."

**Comment by elharo** [comment]
I'm not sure exactly why the last two releases went out, but the default position is to stay up to date unless there's a known issue preventing an upgrade. Otherwise we accumulate dependency conflicts and outdated versions downstream.

**Comment by ejona86** [comment]
> but the default position is to stay up to date unless there's a known issue preventing an upgrade

We do not commit to always being on the most recent version. When we upgrade, we go to the latest version, but we don't upgrade continuously. We expect to be on a "recent" version, not the absolute latest. And our version was still up-to-date a little over 2 months ago.

It also appears v0.25 changed _nothing_ for existing users; they added a new artifact. So that means v0.26 is the first to bring actual changes, and it isn't even a month old at this point.

> Otherwise we accumulate dependency conflicts

There should be no dependency conflicts. That is something we have all committed to. So this doesn't mean anything unless you are meaning _undetected_ dependency conflicts.

> outdated versions downstream

Downstream is free to upgrade to a newer version at-will.
