### ISSUE TITLE
How To use Java client With TLS But ignore the service endpoint certs

### ISSUE THREAD

**Issue by Storm-Born** [grpc/grpc-java#6974]
I'm asking for help if I want to ignore the service certs,How cloud I do this throw java client since 
it is easy through httpclient or with GUI tools such as postman.

**Comment by voidzcy** [comment]
You could create a SSLContext with an allow-all (no-op) TrustManager and let gRPC channel use that SSLContext.

**Comment by ejona86** [comment]
We do not support such a use-case. Generally this is needed because the server hostname does not match the certificate. For that we have `managedChannelBuilder.overrideAuthority()`. If you want to ignore the certificate validation completely, then TLS is offering no value and you should simply use plain-text.
