### ISSUE TITLE
Retry policy does not provide visibility into failures

### ISSUE THREAD

**Issue by jeffalder** [grpc/grpc-java#6994]
### Is your feature request related to a problem?
If:
1. A retry is configured for `UNAVAILABLE`
2. And there was user misconfiguration (a typoed hostname, or no ALPN provider)

Library consumers get no notification that a retry is underway or the reason for the retry.

### Describe the solution you'd like
There are several options:
1. Allow the library consumer to provide an Observer during channel creation. It could get notified for many different types of events that could happen during a channel's lifetime.
2. Log to a logging facade that library consumers can supply their own implementation for. This is particularly important with shaded dependencies (which gRPC provides their own).

### Describe alternatives you've considered
The alternative we implemented is to remove the retry policy configuration from our channel. Not much of an alternative.

### Additional context
Discussion on issue #1577 

cc: @ejona86

**Comment by ejona86** [comment]
Ah, I see. You want to be told "things are going wrong" before they actually fail? That's tougher.

We could do a better job of "telling you all the failures" when an RPC that was retried failed. Would that help?

I'm not wild about logging the failure or an observer on the Channel, since those divorce the RPC from the callsite. That is probably too niche. I guess we could just log from RetriableStream and let you increase the log level (yes, with log configuration issues resolved). That is easy (except for the log configuration issues :smile: ), but is still niche. I'd sooner expect a per-RPC callback that you could register a listener for non-terminal-failures.

@jeffalder, could you explain what you will be doing with this logging? Is this so that the user knows "you made this silly mistake" without having to wait for all the retries+backoffs to complete?

@dapengzhang0, I feel like someone else may have asked for something similar. Do you remember the details?

**Comment by dapengzhang0** [comment]
#6569 might be a similar issue. It's also about observability of retry event.

**Comment by jeffalder** [comment]
> Is this so that the user knows "you made this silly mistake" without having to wait for all the retries+backoffs to complete?

Yes. In our case, it's not my organization that is _configuring_ the host, it's our customers. All of our customers using this functionality are paying support customers. So then the onus lands on our support team and back on us in engineering.

I can accept that this particular use-case is niche, but separation of configuration and code is _not_ niche. What about systems that deploy with centralized config via etcd, ZK, or anything else? Were I administering that kind of system, I would want to know "oh, I mistyped this hostname" rather than have the service just sit idle, not making calls, and I have to wonder what I might have done wrong.

Our protocol also uses async bidi streams, and isn't 1:1, so that makes it more difficult to observe the results of any given call.

**Comment by ejona86** [comment]
@jeffalder, could you share what sort of settings you are using for retries (maxAttempts, backoff settings), to give an idea of how long it will take for your RPCs to fail?

**Comment by dapengzhang0** [comment]
@jeffalder Is using the following API help for your problem?
```java
CallOptions.withStreamTracerFactory(ClientStreamTracer.Factory factor)
```
```java
ClientStreamTracer.inboundTrailers(Metadata trailers)
```
and
```java
StreamTracer.streamClosed(Status status)
```

**Comment by jeffalder** [comment]
@ejona86 

Our internal spec said: "15 seconds exponential to 300 seconds; retry at 300 seconds forever".

We had configured the retry policy like this, because who wants to rewrite an exponential backoff?

```java
        final double maxAttempts = 100;
        final double multiplier = 1.82; // this value gives us a final timeout of about 5m.

        Map<String, Object> retryPolicy = new HashMap<>();
        retryPolicy.put("maxAttempts", maxAttempts);
        retryPolicy.put("initialBackoff", toJsonDuration(15, TimeUnit.SECONDS));
        retryPolicy.put("maxBackoff", toJsonDuration(5, TimeUnit.MINUTES));
        retryPolicy.put("backoffMultiplier", multiplier);
        retryPolicy.put("retryableStatusCodes", Collections.singletonList(Status.UNAVAILABLE.getCode().toString()));

        Map<String, Object> methodConfig = new HashMap<>();
        methodConfig.put("name", Collections.<Object>singletonList(Collections.<String, Object>singletonMap("service", serviceName)));
        methodConfig.put("retryPolicy", retryPolicy);
        return Collections.<String, Object>singletonMap("methodConfig", Collections.<Object>singletonList(methodConfig));
```

At this time, in order to get visibility, we've removed this entire policy and written our own backoff management. Unfortunately, due to the async bidi RPC, we lose data every time we try to connect and fail.

@dapengzhang0 - I can't say. Perhaps? We don't have any tracers set up currently, and we haven't investigated that possibility.

**Comment by ejona86** [comment]
Interesting. You may be interested in [waitForReady](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md) (withWaitForReady on the stub). (Although waitForReady still has the visibility problem. The tracing solution also wouldn't help with waitForReady as-is today.)

The maxAttempts will be clamped to 5. [From the spec](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#validation-of-retrypolicy): "Values greater than 5 are treated as 5 without being considered a validation error." So that means you'd see it take 15s + 27s + 50s + 90s = 182s ≈ 3 minutes to fail, excluding any actual server-side processing time. I agree 3 minutes is a long time to wait.

Given your call is a bidi call, it seems you'll need custom retry logic anyway. The built-in retry can only really handle single responses from the server (unary, client-streaming). So for this _specific case_, the retry visibility probably doesn't matter.

The tracer would have probably worked. Although I'm not sure we want to encourage it for this use-case since it is easy to misuse (e.g., by doing I/O in a callback).

**Comment by dapengzhang0** [comment]
We do have limitations on visibility about retry, but other than workarounds provided above, we are not planning any enhancement for the moment. Closing the issue for being inactive. Feel free to reopen with new thoughts or updates.
