### ISSUE TITLE
Upgrade to Gradle 6 to support Java 13

### ISSUE THREAD

**Issue by netent-perty** [grpc/grpc-java#7006]
### Is your feature request related to a problem?

If you run gradle with Java 13, you will get "Unsupported class file major version 57". This can be fixed by changing to Gradle 6.

### Describe the solution you'd like

Patch:
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index 7c4388a92..562e2c884 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -1,5 +1,5 @@
 distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-bin.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-6.0-all.zip
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists

**Comment by ericgribkoff** [comment]
I'm not aware of any blockers that would stop us from upgrading to Gradle 6. Would you care to send a pull request for the upgrade? It should mainly require updating the `gradle.properties` files used by the main build and our examples, as in https://github.com/grpc/grpc-java/pull/5843, and making sure everything builds. Otherwise I can try to send out a PR later next week to do this. Thanks.

**Comment by netent-perty** [comment]
I'll talk to my other me @perty so I get the credit where it is due. :)

**Comment by perty** [comment]
It strikes me that the travis build needs to get a parallell build with Java 13.
