### ISSUE TITLE
Compress behavior difference between grpc-java and grpc-go

### ISSUE THREAD

**Issue by yann9** [grpc/grpc-java#7035]
Client: 
grpc-java append `grpc-accept-encoding` header even if  compress calloption has not set. 
https://github.com/grpc/grpc-java/blob/cc2d376a93b67bd475adc3f7987f08ee0eb1951f/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L196  
```java 
    byte[] advertisedEncodings =
        InternalDecompressorRegistry.getRawAdvertisedMessageEncodings(decompressorRegistry);
    if (advertisedEncodings.length != 0) {
      headers.put(MESSAGE_ACCEPT_ENCODING_KEY, advertisedEncodings);
    }
```

grpc-go append `grpc-accept-encoding` header only if compress calloption has set.   
https://github.com/grpc/grpc-go/blob/a6ab4473c5a469332c1bdee691293affeaaece25/internal/transport/http2_client.go#L444  
```go 
 if callHdr.SendCompress != "" {
	headerFields = append(headerFields, hpack.HeaderField{Name: "grpc-encoding", Value: callHdr.SendCompress})
	headerFields = append(headerFields, hpack.HeaderField{Name: "grpc-accept-encoding", Value: callHdr.SendCompress})
 }
```

Server: 

grpc-java will check the `grpc-accept-encoding` header which client send to server and compression is not enabled by default. Compressor will be set with the `grpc-accept-encoding ` message compression method 

https://github.com/grpc/grpc-java/blob/cc2d376a93b67bd475adc3f7987f08ee0eb1951f/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L114  
```java 
    if (compressor == null) {
      compressor = Codec.Identity.NONE;
    } else {
      if (messageAcceptEncoding != null) {
        // TODO(carl-mastrangelo): remove the string allocation.
        if (!GrpcUtil.iterableContains(
            ACCEPT_ENCODING_SPLITTER.split(new String(messageAcceptEncoding, GrpcUtil.US_ASCII)),
            compressor.getMessageEncoding())) {
          // resort to using no compression.
          compressor = Codec.Identity.NONE;
        }
      } else {
        compressor = Codec.Identity.NONE;
      }
    }
``` 

grpc-go will not check the `grpc-accept-encoding` header which client send to server and compression is enabled by default. Compressor will be set with the `grpc-encoding` message compression method 
https://github.com/grpc/grpc-go/blob/a6ab4473c5a469332c1bdee691293affeaaece25/server.go#L1123  
```go 
if s.opts.cp != nil {
	cp = s.opts.cp
	stream.SetSendCompress(cp.Type())
} else if rc := stream.RecvCompress(); rc != "" && rc != encoding.Identity {
	// Legacy compressor not specified; attempt to respond with same encoding.
	comp = encoding.GetCompressor(rc)
	if comp != nil {
		stream.SetSendCompress(rc)
	}
} 
```

Why? Are there any other reasons for the inconsistency？

**Comment by ericgribkoff** [comment]
I believe the discrepancy is due to https://github.com/grpc/grpc-go/issues/2786. Go only recently (https://github.com/grpc/grpc-go/pull/3139) added the client-side setting of `grpc-accept-encoding`, and the open issue identifies that some more items still remain to be done there.

Since this seems to be more of a gRPC Go question - as far as I can tell, gRPC Java is compliant with the spec and compression is advertised/configured as expected - I'm going to mark this closed here. If there's other Java-specific concerns feel free to comment and I will reopen; otherwise for the Go side of things adding a comment to https://github.com/grpc/grpc-go/issues/2786 is probably the right place.
