### ISSUE TITLE
Force client to refresh DNS during service cell drain event

### ISSUE THREAD

**Issue by cobookman** [grpc/grpc-java#7085]
I have a gRPC service running in multiple [cells](https://en.wikipedia.org/wiki/Cellular_architecture). Each cell is backed by its own AWS NLB. There can be multiple cells in a given AWS AZ.

I want to move clients to a new cell to help balance the load over a long period of time.
The service requires a customer's traffic to be served out of the same cell.

The issue is that grpc-java keeps a TCP connection open unless it gets a `TRANSIENT_FAILURE` by use of max connection age. There is no way to server side send a 302 redirect or forcibly close the TCP connection.

Any ideas how to issue a 302 redirect or force-connection re-estalbish server-side to the client? 

If this were an HTTP RestAPI at say foo.com, I could send an HTTP 302 to a sub-domain pointing to the new cell (cellb.foo.com), forcing the client to redirect traffic to the new cell, including a DNS fetch + new TCP Connection

Any ideas on how to server-side direct the client to a new endpoint / IP Address / TCP Connection.

**Comment by cobookman** [comment]
If in `ServerInterceptor` it is possible to get the Netty `ChannelHandlerContext`, then it'd be possible to drain a given client from the service. Forcing the client to re-connect/re-dns flow...etc.

**Comment by ejona86** [comment]
If you are _draining_ the cell, just shut down the server. That will cause the client to re-resolve DNS and reconnect.

However, it sounds like you don't want to actually drain. You are wanting to re-balance. Max connection age addresses that.

However, you have the constraint "The service requires a customer's traffic to be served out of the same cell." That requires a specialized load balancer to do consistent hashing or similar on the customer id so that each client for a particular customer uses the same address. Simply re-resolving DNS and reconnecting will not cause clients for a particular customer to go to the same cell.

The solution probably will depend on how strict "The service requires a customer's traffic to be served out of the same cell" is interpreted. You could do the equivalent of an HTTP 302 by doing that in your application, where the server directs you to a particular subdomian and the client connects to it for further RPCs. Even in HTTP that wouldn't generally be transparent, because there is no automatic redirect for POST (due to security issues); it would only be transparent for GETs.

**Comment by cobookman** [comment]
@ejona86, draining a client from the cell but not the entire cell.

A given cell might has multiple customers on it. There's certain situations where we need to re-balance which customers are on which cells...e.g: Customer `foo` increases load by 10x, move `foo` to a cell with lower utilization.


> Simply re-resolving DNS and reconnecting will not cause clients for a particular customer to go to the same cell.


The application requires a given customer to be served out of the same cell. This is done by having a unique subdomain per customer, with DNS records used to route them to a given cell. Customers are moved to a new cell by changing the respective subdomain record.



> However, it sounds like you don't want to actually drain. You are wanting to re-balance. Max connection age addresses that.

Max-Connection age does address it. But there's better performance to be had by letting the server force a given client to re-connect. Max-Connection requires a lot of connection churn or a long period of time between clients re-balancing. We're talking millions of clients across many customers. 


> Even in HTTP that wouldn't generally be transparent, because there is no automatic redirect for POST (due to security issues); it would only be transparent for GETs.

Lots of HTTP client libraries offer configuration to follow 302 for POST. 
https://www.baeldung.com/httpclient-redirect-on-http-post
https://stackoverflow.com/a/32540337

**Comment by ejona86** [comment]
> This is done by having a unique subdomain per customer, with DNS records used to route them to a given cell. Customers are moved to a new cell by changing the respective subdomain record.

Ah, I see. Note that the swap-over cannot be atomic, because of DNS caches. After changing the subdomain records, you'll have to wait the TTL before dropping connections to clients, otherwise you can trigger a connect loop as the client keeps reconnecting to the previous stale backend.

How will you handle RPCs that arrive to the stale cell during the transition? Do you have the server proxy them to the appropriate cell or do the operations with non-local data? That is to say, when transitioning, the client would see reduced performance but no errors.

> Any way to configure a ServerInterceptor to be passed ChannelHandlerContext.

In no way will be provide the ChannelHandlerContext. That's just asking for trouble. Years ago there was discussion of adding an advanced API to allow active rebalancing by letting the application close specific connections. It was a sort of "future optimization" sort of work, and really hasn't been necessary. It would address your problem, though.

[RLS](https://github.com/grpc/grpc-proto/tree/master/grpc/lookup/v1) would solve these sorts of needs, but in a very different way. All clients are provided the same hostname and then a "lookaside" server directs RPCs based on custom logic. The server controls how long routing results are cached by clients. That leaves the service owner in more control, at the expense of needing additional infrastructure. RLS is still in development and I'm not sure when we'd be ready for third-party implementations of the server. So I'm not entirely suggesting it.

> Lots of HTTP client libraries offer configuration to follow 302 for POST.
https://www.baeldung.com/httpclient-redirect-on-http-post
https://stackoverflow.com/a/32540337

`LaxRedirectStrategy` and `followAllRedirects: true` are not generally secure, although this varies depending on how credentials are handled and some other details. Since HttpClient let's you provide your own policy you could make it secure, but it would be easy for `LaxRedirectStrategy` to open you up to attacks. This is a security discussion, and the precise solution depends on a lot of details.

------

I recognize I don't have a clear solution for you at the moment.

**Comment by cobookman** [comment]
Thanks Eric for clarifying & confirming my thoughts.
