### ISSUE TITLE
Add protobuf-bom into grpc-bom

### ISSUE THREAD

**Issue by onyn** [grpc/grpc-java#7112]
Please consider adding `com.google.protobuf:protobuf-bom` into grpc-bom. This will allow not specifying version of additional libraries from protobuf family.

Example how this might be implemented:

```xml
  ...
  <groupId>io.grpc</groupId>
  <artifactId>grpc-bom</artifactId>
  <version>1.30.0</version>
  <packaging>pom</packaging>
  ...
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protobuf-bom</artifactId>
        <version>3.12.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    ...
    </dependencies>
  </dependencyManagement>
```

After that I can specify protobuf-java-util without version in my project:

```xml
  ...
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-bom</artifactId>
        <version>1.30.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty-shaded</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-stub</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java-util</artifactId>
    </dependency>
    ...
```

With this feature protobuf-java-util stay aligned with protobuf version that was got transitively from `io.grpc:grpc-protobuf`.

**Comment by ejona86** [comment]
As I understand it, it is bad-practice to include transitive BOMs in a BOM. https://jlbp.dev/JLBP-15 talks some about avoiding transitive BOMs, but is not quite precise enough. [gax-bom](https://search.maven.org/artifact/com.google.api/gax-bom/1.56.0/pom) does not include transitive boms, and I know the developer of that looked much more into BOMs than I have. I think transitive BOMs are to be avoided because that would cause conflicts/confusion if the same transitive bom (say, protobuf) is included from _both_ grpc and, say, gax, since they can have different versions.

**Comment by onyn** [comment]
If developer choosed grpc and gax that depends on different version of protobuf, than conflict is already here. No matter via imported bom or direct dependency. This is developer's fault, not library's.

Protobuf bom should be included only by library that directly depended on protobuf. Because that library explicitly declares which version of protobuf is fully supported and thoroughly tested. 

JLBP-15 is quite focused on library modules and not on their dependencies. But if interpret this paragraph more broadly:

> Your project’s BOM should include every non-test-scoped module in the project. Otherwise, a consumer who depends on an unspecified module must specify and upgrade the version of that module, defeating the purpose of the BOM.

Then when I take grpc for my project and want to use some fancy classes from protobuf-java-util library, then I must explicitly specify version for it. Which effectively "defeats the purpose of the BOM". And when I want to bump grpc version, I forced to examine if protobuf version also changed and bump protobuf-java-util too. And if I work in a team, this inconvenience must be documented. But who read docs really? Another developer from my team may just skip this check and introduce version conflict.

**Comment by ejona86** [comment]
> Then when I take grpc for my project and want to use some fancy classes from protobuf-java-util library, then I must explicitly specify version for it. Which effectively "defeats the purpose of the BOM".

I don't think so. In my mind "the purpose of the BOM" is to let _you_ easily choose the version of dependencies to use. Transitively including BOMs does not improve that goal. It is obvious when you see importing a BOM for grpc that it will set the versions for grpc. It isn't obvious it will include a protobuf BOM. Especially if you aren't using grpc-protobuf, or don't even know it exists (yes, unlikely for protobuf+gRPC, but in general would cause trouble).

I'll note that gax has the same author as JLBP-15, so it'll be really hard to argue an interpretation of the document that does not align with gax-bom. You can totally argue the approach is broken, and that is fine, but it is unclear if you were arguing my interpretation was wrong or if the document was wrong.

As another example of a BOM that does _not_ include transitive BOMs is spring-bom. spring-webflux has a dependency on io.projectreactor:reactor-core and there is a corresponding reactor-bom, since there are quite a few related artifacts. But not transitive BOMs in spring-bom.

I don't see _any_ evidence what you are suggesting is a good idea. If you can find a library or documentation "that probably knows what its doing" and uses transitive BOMs, then I could look into it more. But my pre-existing understand and cursory research points in the opposite direction.

**Comment by onyn** [comment]
You referring to other projects who don't use bom importing. I think they don't used it not because bad practice but because they don't know about this feature or simply there is nothing to import. Or this is may be chicken-or-egg problem - no one using transitive bom importing because no one used it before.

I'm not saying that your argumentation is bad or JLBP-15 is broken. I just can't find any information that against/encourage using transitive bom usage (including JLBP-15). The only project I know who use this feature is [micronaut](https://micronaut.io/) (unreleased yet but should be in the upcoming RC).

If you find my argumentation still not convincing enough, just close the issue without comments. This is my final thoughts and I have nothing to say more on this topic.

**Comment by ejona86** [comment]
> I think they don't used it not because bad practice but because they don't know about this feature or simply there is nothing to import.

I 100% expect Spring knows about the feature and I demonstrated there was something that could have been imported.

> Or this is may be chicken-or-egg problem - no one using transitive bom importing because no one used it before.

I have explicitly discussed the option with others (e.g., gax), and we decided _not_ to do it, and decided it would be _a bad idea_ to do it. I'm honestly surprised a recommendation not to do transitive BOMs is missing from JLBP-15.

Okay, I'll go ahead and close this. It seems like a bad idea, but if it becomes clearer that it is a good idea we can do it.
