### ISSUE TITLE
Does netty-codec-http2 still need an exact version match?

### ISSUE THREAD

**Issue by jfancher** [grpc/grpc-java#7159]
While trying to upgrade the netty version of a large project, I ran into a version conflict with `grpc-netty`. This looks to be because it requires an [exact match](https://github.com/grpc/grpc-java/blob/417d7700ddb2f39198728363866f4c2af434944e/build.gradle#L162) on the version of `netty-codec-http2`. This seems a bit strange given that most other deps do not have strict requirements, including the other netty libraries.

I see that this was added by #1459, but this seems to date to when netty http2 support was in a pre-release state. I would hope that it's more stable now, although I don't have personal knowledge of the subject. Could this limitation be relaxed going forward?

(I realize that using `grpc-netty-shaded` would sidestep this issue, and this may be my solution for now. I'd rather not have to, though)

**Comment by dapengzhang0** [comment]
Only exact version match can guarantee grpc-netty works properly with io.netty. There are a lot of known failures or bugs for mismatched grpc-netty and io.netty. `grpc-netty-shaded` is recommended if mismatched versions are inevitable otherwise.

**Comment by ejona86** [comment]
The API's used, like `Http2ConnectionHandler`, are marked as `@UnstableApi` in Netty. They have become semi-"stable" at this point in a "don't touch it" way, but Netty (I'm speaking also as a Netty maintainer here) can't really guarantee compatibility with them because they are far too brittle. Netty does not plan to stabilize the API.

We need to migrate to Http2FrameCodec (and maybe even Http2MultiplexHandler). That API is also unstable, but is "the way forward" to getting a stable API. It's something we pick up once every couple of years (#2332), but is invasive and has been hard for us to make a priority.

We are okay if you use a different version of Netty (e.g., by excluding our dependency), and other versions may work. But we can't really support it.

**Comment by jfancher** [comment]
That additional context is very useful, thank you!

I guess I find it somewhat weird (and the issue I linked sort of calls it out) that only the http2 version is locked. The other `netty` user I have doesn't need http2, so right now I have:
````
"io.grpc:grpc-netty": "1.17.1",
"io.netty:netty-codec": "4.1.44.Final",
"io.netty:netty-codec-http2": "4.1.30.Final",
"io.netty:netty-[other-stuff]": "4.1.44.Final",
````

And Maven is just fine with this. But based on what you wrote, I understand it may actually be correct if the `grpc-netty -> netty-codec-http2` edge is the unstable one. In any case, I'll live with this for now and try to get around to upgrading grpc soon such that the versions align. Thanks.
