### ISSUE TITLE
SDS: avoid using deprecated envoy api v2 fields 

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#7166]
There are some usages of deprecated fields in current code base:

---

https://github.com/grpc/grpc-java/blob/2e1cd05d54184e64845f7849ff8bf638bfde2b01/xds/src/main/java/io/grpc/xds/internal/sds/trust/SdsX509TrustManager.java#L226
is using 
https://github.com/envoyproxy/envoy/blob/019353e8aabd28da8c73204167997cf9e51220a5/generated_api_shadow/envoy/api/v2/auth/common.proto#L286

---

https://github.com/grpc/grpc-java/blob/2e1cd05d54184e64845f7849ff8bf638bfde2b01/xds/src/main/java/io/grpc/xds/internal/sds/FileBasedPluginCredential.java#L61
is using
https://github.com/envoyproxy/envoy/blob/019353e8aabd28da8c73204167997cf9e51220a5/api/envoy/api/v2/core/grpc_service.proto#L88

---

https://github.com/grpc/grpc-java/blob/2e1cd05d54184e64845f7849ff8bf638bfde2b01/xds/src/main/java/io/grpc/xds/EnvoyServerProtoData.java#L296
is using
https://github.com/envoyproxy/envoy/blob/019353e8aabd28da8c73204167997cf9e51220a5/api/envoy/api/v2/listener/listener_components.proto#L180

---

https://github.com/grpc/grpc-java/blob/ae7a482d9a6b9b846f21cc6ee7f37ba6fdbefeae/xds/src/main/java/io/grpc/xds/XdsClientImpl.java#L1084
is using
https://github.com/envoyproxy/envoy/blob/5f1348bbc6c530b6adf118f41718bc4200fb55e1/api/envoy/api/v2/cluster.proto#L603

**Comment by sanjaypujare** [comment]
This is just as a reminder/note for future. Based on the initial analysis these need to be resolved as follows:

1) Replace `verify_subject_alt_name` with `match_subject_alt_names` in `CertificateValidationContext` after verifying that the control plane (xDS server) will use this new field to provide the server authz info. (also note that with CertificateProvider the `CombinedCertificateValidationContext` will be used where the server authz info comes thru default_validation_context and the cert info comes via `validation_context_certificate_provider`).

2) Just replace the config with typed_config and figure out (from the xDS server) what type is supplied in this config and unpack it using that type (assuming this type is known on our side which is most probably the case).

3) & 4) These are straightforward: since remove the deprecated field access and return null (or whatever is appropriate to indicate the config doesn't exist)

**Comment by sanjaypujare** [comment]
Based on offline discussions:

- for 1 it looks like verify_subject_alt_name will be replaced with match_subject_alt_names and the latter will use EXACT_MATCH and pass the same string. On the gRPC side we just need to accept the StringMatcher and as part of EXACT_MATCH do the exact same processing as today.

- change the logic to use typed_config and assuming the underlying type is available extract the values to instantiate the FilebasedPluginCredentials with those values. Will need to see a sample of that. Also another input is that with the change from node agent to istio agent, the istio agent will be able to load the cred locally so there is no need to pass it from the client (us) so this most probably won't even occur.
