### ISSUE TITLE
//services:reflection should export its java_proto dependency

### ISSUE THREAD

**Issue by Kernald** [grpc/grpc-java#7171]
Here's the current definition of `//services:reflection`:
https://github.com/grpc/grpc-java/blob/b6a63e75e2fb14eb6b1bc0de0b52571adac956d9/services/BUILD.bazel#L45-L64

It depends on `//services:_reflection_java_grpc`, which is private. However, the generated service exposes those private symbols as part of its public API:

```
public final class ProtoReflectionService extends ServerReflectionGrpc.ServerReflectionImplBase
    implements InternalNotifyOnServerBuild {
```

As a result, IntelliJ for example complains about `ProtoReflectionService` not being fully defined because its supertype isn't accessible as a dependency. Is there a reason why this `_reflection_java_grpc` target is neither public nor exported? (The same is likely true for `_channelz_java_grpc` and `_health_java_grpc` in the same package.)

**Comment by dapengzhang0** [comment]
I'm not sure understanding your question. `ProtoReflectionService` is a public class (because all generated services are public classes) but it's not a public API of grpc-services library. Users should not use the class directly.

**Comment by dapengzhang0** [comment]
As the comment in `services/BUILD.bazel` shows

```
# These shouldn't be here, but this is better than having
# a circular dependency on grpc-proto and grpc-java.
```

these generated code are definitely not part of public API of `//services`. If users do want to send RPC to the services, use API in [grpc-proto](https://github.com/grpc/grpc-proto/blob/master/BUILD.bazel) instead.

**Comment by ejona86** [comment]
> IntelliJ for example complains about ProtoReflectionService not being fully defined because its supertype isn't accessible as a dependency

This sounds like an IntelliJ problem. It is not normal practice to export transitive dependencies. Bazel produces "hjar"s to avoid the need for transitive dependencies to be available when compiling.

> If users do want to send RPC to the services, use API in grpc-proto instead.

It should be very easy to define your own java_grpc_library targets for the protos in grpc-proto. I will note, however, that today it will produce multiple definitions for the classes. However, Bazel is "okay" with this because the multiple definitions will be bitwise identical (because they were produced with the same protoc and proto-gen-grpc-java binaries). It is a goal of mine to use artifacts in java_grpc_library to avoid the duplicate code generation, but it's not been a priority since what we have now "works."

**Comment by Kernald** [comment]
Yeah, sorry, it seems that the actual issue I have is related to the Kotlin rules specifically (which seems to have been ([fixed](https://github.com/bazelbuild/rules_kotlin/pull/338)) - I just tried with a Java target and don't have any issue. Sorry for the noise.
