### ISSUE TITLE
Decrease minimum allowed keepalive time interval

### ISSUE THREAD

**Issue by Excpt0r** [grpc/grpc-java#7180]
Currently there is a limitation on the minimum value that can be set as keepalive time, defined in KeepAliveManager.MIN_KEEPALIVE_TIME_NANOS with 10 seconds.

The rationale behind the minimum limitation is probably to allow a high number of connections and throughput without creating too much overhead.
But there are also situations where not many connections/throughput is required, but a fast response time instead.

There are already gRPC implementations that allow lower values (I'm using ETCD on server side).
I suggest to reduce KeepAliveManager.MIN_KEEPALIVE_TIME_NANOS to 1s or 10ms to allow using the full range available on server-side. Maybe instead a hard limitation just logging a warning for setting keepalive times below 10s?

**Comment by sanjaypujare** [comment]
> ...
> But there are also situations where not many connections/throughput is required, but a fast response time instead.
> ...

Are there cases (transports) where a keep-alive time of less than 10 seconds is needed to keep the connection alive? If there aren't any, that might be the reason the minimum is 10s.

**Comment by Excpt0r** [comment]
The use-case is to detect a gone connection to the ETCD server on client-side quicker, to be able to connect to an other instance.

**Comment by Excpt0r** [comment]
@sanjaypujare I made a PR for this enhancement

**Comment by ejona86** [comment]
The rationale behind the 10 second limitation is because you can't reliably detect failures of less than ~10-20 seconds as the network and the remote server may _need_ that much time. This is to avoid congestion collapses, as a connection being killed will create a new connection in its place which can substantially increase load when things are bad triggering cascading failure.

Also, having a keepalive of 1s means you will spend a considerable amount of CPU just on keepalives. 10s is already pretty aggressive if there are many clients. Are your connections short-lived?

Most users are not network specialists, so do not understand the dangers in aggressive settings. We hear of users wanting 100ms keepalives.

The keepalive setting is also dependent on how frequent you expect failures. If you are in a datacenter network, why are you so concerned about TCP failures? Are you experiencing them frequently? What is the cause of those failures?

**Comment by Excpt0r** [comment]
My use case is a stateful application that needs a leader/follower mechanism.
The leader is written to an ETCD cluster, and followers are watching for leader-key to get a lease timeout and take over.

The keep-alive is needed that the follower watch detects when the server side node has gone (VM failure).
There will be only up to 5 clients, most of the time just keeping the watch alive.
So I don't expect much load, but require a very fast detection in case of a failure.

ETCD (3.4.9 here) is setting a default of 5s for grpc-keepalive-min-time and I'm using 1s, but 3s on client side to avoid too many pings.

**Comment by ejona86** [comment]
> The keep-alive is needed that the follower watch detects when the server side node has gone (VM failure).

That doesn't sound right. It sounds like you actually want to know when the current leader becomes broken. You want more of a [watchdog](https://en.wikipedia.org/wiki/Watchdog_timer) where the application itself is involved and sends heart-beat pings. This would be better at the application-level using normal RPCs.

Keepalive is not appropriate for this use-case. It is intended for 1) keeping a connection alive in the face of NATs and similar that will disconnect inactive TCP connections and 2) detecting TCP failures. In your case, you don't really care whether the failure is a TCP failure; you're probably more likely to experience application failures.

**Comment by Excpt0r** [comment]
Hi @ejona86 thanks for your reply. I think there are different scopes to discuss.

1) scope: ETCD watch in general (using jetcd with grpc-java)
I think the only way to detect a silently gone ETCD backend during a client watch is to activate keepalive at grpc level.
Without sending data, it is not possible for the waiting watch client to detect the TCP issue for a very long time.
That applies to ETCD watches in general, not only to my special case with the leader election, and I contributed to jetcd for a default keepalive (https://github.com/etcd-io/jetcd/pull/753)
Do you think that is wrong? (note that the introduced default keepalive time is 30s)

2) scope: potential issues with very low keepalive time
I understand there are cases where a very low keepalive time leads to trouble.
You already pointed that out, for example situations with many clients, or when the service takes longer for processing than the keepalive time.
But the fact that ETCD server uses a default minimum keepalive of 5s and allows lower values is a statement, isn't it?
As I reported, I tried with 1s on server and 3s on client side, and it worked very good.
My request is only to allow lower values, for use cases where it works (local network and low-latency requirements) - NOT to set a low value as a default.
Why would we prevent users of the lib from optimizing the settings for their use case?

3) scope: my use case (leader election via etcd)
Not sure if I understood you correctly. Your suggestion is to keep using ETCD for leader election itself,
but implement a direct connection from followers to the leader for heart-beats?
Didn't think about that so far, but where would be the difference between heartbeat and keepalive packets?

The app should detect a gone watch, reconnect, and elect a new leader within 10s.
Not all follower need to be that quick and in sync, as the quickest will get the new lead.
If a follower watch reconnects due to a missed keepalive, but the server is not really gone, just too slow:
That wouldn't be a problem, the follower just connects to a different ETCD instance, and will become follower again, if there's still a valid leader.

**Comment by ejona86** [comment]
> I think the only way to detect a silently gone ETCD backend during a client watch is to activate keepalive at grpc level. Without sending data, it is not possible for the waiting watch client to detect the TCP issue for a very long time.

Yes. Although it may not be a gone ETCD but a network failure.

> As I reported, I tried with 1s on server and 3s on client side, and it worked very good.

"Worked on my machine" doesn't really help the discussion much. Because someone else does it doesn't mean it is something that we want to allow/encourage. It is really tempting to use keepalive with frequent polling and short timeouts, but it is poorly suited.

> Your suggestion is to keep using ETCD for leader election itself,
but implement a direct connection from followers to the leader for heart-beats?

I wasn't providing something that specific. I didn't really understand the specifics of your solution. Are you using an approach like https://www.projectcalico.org/using-etcd-for-elections/, with TTLs and compare-and-swap? What TTLs are you using? Using a TTL is basically the same as a watchdog.

Poking more, it seems the TTL isn't on the key itself, but on a lease and the lease is associated with the key. So watchers of keys won't see updates each time the TTL is refreshed.

For there to be a problem, there needs to be a dual failure: 1) the current leader breaks (or can't communicate) and 2) the follower's watch is broken. (2) could be caused by 1) etcd server being broken or 2) the network. If it is the network, then reconnecting will probably have trouble as well and so in that case keepalives would let the follower know something is broken, but not help with leader election.

So we're really looking at the dual failure: 1) the current leader breaks since the last TTL and 2) an etcd server breaks since the last keepalive. But you might actually need additional failures on top of that, depending on what your followers do (e.g., depending on whether they serve traffic). And details like "what happens if a follower can't communicate with etcd" come into play. Unless you have a very crashy etcd and leader, 10s seems within the realm of "fine."

If I was really pessimistic, I might choose to poll the lease. Note that this is not quite the same as keepalive because it means at least some part of the etcd application logic is still alive, vs keepalive which can succeed even if etcd is 100% wedged (since keepalive is managed by grpc in its own goroutine).

> Why would we prevent users of the lib from optimizing the settings for their use case?

"Optimizing." For small blips, reconnecting is generally harmful, as the connection isn't actually dead. In systems where you need low latency reactions to events (vs just failing, etc) you tend to leave connections in-place and just change the system's behavior (e.g., having connections to multiple backends all the time and going to a different backend when things get slow, but not tearing down the slow connection). In such systems you need to plan on it taking multiple seconds to resolve networking issues and decide how you want to behave.

**Comment by Excpt0r** [comment]
> Are you using an approach like https://www.projectcalico.org/using-etcd-for-elections/, with TTLs and compare-and-swap? What TTLs are you using? 

Yes, the election is done as etcd transaction, with a compare to revision 0 and then putting the leader key, combined with a lease. TTL is currently 5s and keepalive every 1s.
As far as I could see, jetcd and etcdctl V3 is not supporting PUT in combination with a TTL, so using a lease is the right way to go I guess.


> For there to be a problem, there needs to be a dual failure: 1) the current leader breaks (or can't communicate) and 2) the follower's watch is broken.

I was testing the worst case: All etd clients are using the same etcd server, and this etcd server is running on the same worker as the current app leader.
Then a single failure of that worker VM will lead to loss of the leader, and all follower clients need to detect the gone etcd and re-connect to another.


> Unless you have a very crashy etcd and leader, 10s seems within the realm of "fine."

I can spend around 10s to detect a leader problem and elect a new. That's why in worst case already taking 10s just for watch problem detection was too much.


> If I was really pessimistic, I might choose to poll the lease. Note that this is not quite the same as keepalive because it means at least some part of the etcd application logic is still alive, vs keepalive which can succeed even if etcd is 100% wedged (since keepalive is managed by grpc in its own goroutine).

Good point, didn't consider a broken etcd with a working grpc layer so far.
Polling would also allow short intervals without modifying the keepalive mechanism, assuming that connections for each poll can be re-used and the network/processing cost is similar to keepalive. 
I will explore that approach further.


> ... you tend to leave connections in-place and just change the system's behavior (e.g., having connections to multiple backends all the time and going to a different backend when things get slow

This is a good point too, I'm already trying to figure out how to open connections to all 3 etcd backends in parallel from every client with grpc-java.

**Comment by ejona86** [comment]
> Then a single failure of that worker VM will lead to loss of the leader, and all follower clients need to detect the gone etcd and re-connect to another.

I see. The etcd failure can _cause_ the loss of leader, even though the current leader is healthy. So a single failure is all that's necessary.

> Polling would also allow short intervals without modifying the keepalive mechanism, assuming that connections for each poll can be re-used and the network/processing cost is similar to keepalive.

The network cost is virtually the same. The processing cost is higher, as there will be Metadata, protobuf, and etcd must do some processing. But that's also sort of the point. It's a cost/benefit trade-off.

> I'm already trying to figure out how to open connections to all 3 etcd backends in parallel from every client with grpc-java

That sort of thing is possible from a LB policy, but can be easier from the application, depending on how you choose between the backends and which backends. Although, actually, you could probably use round_robin if you limited the number of addresses passed to it to 3. Even if you chose to implement a Channel instead of an LB policy, round-robin _just for updating the lease_ would be simple and make sure that the lease is refreshed in the face of a single etcd server failure. That would avoid the current leader losing the lease, and so it could be okay that it takes ~30s for followers to notice their etcd server is dead using gRPC's keepalive (so they could continue just using a watch). To have issues you'd have to have multiple simultaneous failures.

Polling the lease still has some advantages, since it checks that etcd itself is alive. And if you did polling then round-robin, again, would make sure you eventually hit a working etcd server. But it seems you aren't "forced" to do polling. You have options and can choose which you prefer.

**Comment by Excpt0r** [comment]
@ejona86 thanks for having the discussion. I've closed the related PR.

In the end, I found a completely different solution.
The leader election is now done directly between application instances with a raft library (sofa-jraft), that saves the indirection via an ETCD backend. First results look promising, new leader is elected below 5s.
