### ISSUE TITLE
How to get a client response  when using StreamObserver to push a message to client at server

### ISSUE THREAD

**Issue by shiyiyue1102** [grpc/grpc-java#7261]
Context:
I'm using grpc's StreamObserver to push data from the server to the client. I found that StreamObserver#onNext has no return value, so I can't know whether the client has successfully processed the message. 

Question:
I hope the server can sense whether the client has  successfully processed the message. If some exception throw in client , the server needs to try again. Is there a way to achieve this function through gRPC java？

**Comment by ericgribkoff** [comment]
In order to accomplish this, you would need to have your client send an acknowledgement back to the server for each message, or batch of messages, or else signal to the server when a message was *not* processed successfully. 

In general this can be a hard problem - for example, if the client's connection gets broken, the server will likely not know whether the client received the last message(s) or not - but a ack/nack sent from the client to server can handle the basic scenario outlined here. If you're worried about an exception thrown in your client application, you should probably extend your service definition so that, instead of throwing an exception, the client can send a response back to the server indicating the message could not be parsed.

**Comment by shiyiyue1102** [comment]
> In order to accomplish this, you would need to have your client send an acknowledgement back to the server for each message, or batch of messages, or else signal to the server when a message was _not_ processed successfully.
> 
> In general this can be a hard problem - for example, if the client's connection gets broken, the server will likely not know whether the client received the last message(s) or not - but a ack/nack sent from the client to server can handle the basic scenario outlined here. If you're worried about an exception thrown in your client application, you should probably extend your service definition so that, instead of throwing an exception, the client can send a response back to the server indicating the message could not be parsed.

**Comment by shiyiyue1102** [comment]
> In order to accomplish this, you would need to have your client send an acknowledgement back to the server for each message, or batch of messages, or else signal to the server when a message was _not_ processed successfully.
> 
> In general this can be a hard problem - for example, if the client's connection gets broken, the server will likely not know whether the client received the last message(s) or not - but a ack/nack sent from the client to server can handle the basic scenario outlined here. If you're worried about an exception thrown in your client application, you should probably extend your service definition so that, instead of throwing an exception, the client can send a response back to the server indicating the message could not be parsed.

Thank you for your reply. Because StreamObserver#onNext has no return value ，so I have  to implement  the ack mechanism base on  it , it is a very large cost and   an ugly way.

**Comment by ericgribkoff** [comment]
We have some support for automatic retries on the client-side when RPCs fail, but there's no such mechanism planned for equivalent server-side failure (in fact, if the client breaks the stream, the server can't initiate a new connection so there's no way for it to retry at all, the client has to take responsibility for retries here). 

It might help if you expand on your use case a bit - you just mentioned that the error case is when the client throws some exception. If you mean *any* client failure, the gRPC server implementation can't automatically handle this for a number of reasons: the connection may be gone, the client may have actually processed the important part of the message (e.g., committed a database transaction) and automatic re-send from the server would result in unwanted duplication, etc. 

If, however, you have application-specific semantics here, it should be possible to rearchitect things so that whatever exception you are currently throwing in the client is instead caught and triggers the client itself to retry, e.g., re-request the message from the server.

**Comment by ericgribkoff** [comment]
I'm going to mark this closed as there hasn't been any more discussion in the last week.
