### ISSUE TITLE
Review the generics on ServerCallHandler

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#728]
Maybe add a super and extends.   The context for this issue was how would a proxy be implemented.

**Comment by ejona86** [comment]
So... this will cause a bunch of generics noise for all ServerCallHandler implementations. However, I'm concerned it may not help anyone.

```java
// Request/ResponseMessage would be a class like MessageLite.
// Request/Response would be actual protos
public interface ServerCallHandler<RequestMessage, ResponseMessage> {
  <Request extends RequestMessage, Response extends ResponseMessage>
  ServerCall.Listener<RequestMessage> startCall(
      MethodDescriptor<Request, Response> method,
      // Handler can't actually send responses, because they would need to be
      // Response, but the class only interacts with ResponseMessage
      ServerCall<? extends Response> call,
      Metadata headers);
}

public static <RequestT, ResponseT> ServerMethodDefinition<RequestT, ResponseT> create(
      MethodDescriptor<RequestT, ResponseT> method,
      ServerCallHandler<? super RequestT, ? extends ResponseT> handler)
```

In `ServerMethodDefinition.create()`, `ServerCallHandler` can support `Object` requests for instance. But it can't use `Object` responses, because that won't be a serializable by `MethodDescriptor`.

It seems a proxy should create their own `MethodDescriptor`s instead, with the more generic type, to be able to reuse their `ServerCallHandler`.

@carl-mastrangelo, do you agree?

**Comment by carl-mastrangelo** [comment]
Honestly, I think I would have to write some code that implements to really feel confident that it would work out.  

I would prefer to complicate call sites as little as possible.  If adding wildcards makes common case usage annoying, and makes proxying slightly easier (by not having to cast, etc.), then I would say ditch it.   Making a faux MethodDecriptor each time doesn't seem horrible.

So, yeah, there probably isn't anything more to do for this issue.  The generics have been reviewed.
