### ISSUE TITLE
Lack of compat with grpc-web due to lack of HTTP 1.x support

### ISSUE THREAD

**Issue by alexanderkyte** [grpc/grpc-java#7377]
There is currently a stalemate between grpc-java and grpc-web around use of HTTP 1.x. 

Could you fix it in this repo? It doesn't seem like the other project in this organization plans to fix this. 

https://github.com/grpc/grpc-web/issues/432

**Comment by ericgribkoff** [comment]
The use of HTTP/2 is (was) pretty fundamental to the design of gRPC. grpc-web was developed using HTTP 1.x because most browsers did not support the HTTP/2 protocol. This does lead to the lack of direct compatibility between gRPC servers, speaking HTTP/2, and these grpc-web clients, speaking HTTP/1.x. The recommended approach to handle this is to proxy the grpc-web client through Envoy, as described in their helloworld example: https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld#configure-the-proxy. Envoy will handle the translation between HTTP1 and HTTP2.

**Comment by alexanderkyte** [comment]
Thanks!

That is unfortunate, hopefully one day the servers can support the upgrade without requiring a third server to handle the network protocol used by the most common client library for gRPC. 

Thanks for making me aware of the workaround for this.

**Comment by ericgribkoff** [comment]
Looking at the grpc-web roadmap (https://github.com/grpc/grpc-web/blob/master/doc/roadmap.md), it looks like they do have a plan for a solution here: [in-process proxies](https://github.com/grpc/grpc-web/blob/master/doc/in-process-proxy.md). This would put an equivalent to the envoy proxy in process in the browser, and all grpc-web clients to seamlessly talk with existing gRPC servers.

gRPC Java and other server languages are unlikely, at this time, to plan for supporting HTTP1.x directly, as many features that gRPC was specifically designed around - such as streaming - are not fully possible in the HTTP1.x protocol.

I'm going to mark this closed since the current roadmap for this is taking place within the grpc-web ecosystem.

**Comment by tobq** [comment]
With browser supporting HTTP2, [today](https://caniuse.com/http2), why is grpc-web still limited to HTTP1.1 - forcing people to deploy HTTP 1.1 to HTTP 2 proxies?
