### ISSUE TITLE
Change Default Thread Executor of the Server

### ISSUE THREAD

**Issue by brunoborges** [grpc/grpc-java#7381]
Currently, the default Thread Executor defined for the gRPC Server is `Cached`. This executor is known for being extremely slow, even when compared to a Single Thread executor.

Since developers are more likely to build a gRPC server following default configuration, many who do not tweak their servers will assume that a Java implementation of the gRPC Server cannot perform well.

Therefore, I'd like to first ask for the reason behind choosing this executor type instead of other options available.

Secondly, given that developers are most likely not going to benchmark the different executors, I'd like to propose to switch to a `Fixed` executor, with the number of threads based on the number of `availableProcessors()` for the JVM.

Third, if we agree that there is certainly no need for the default behavior to guarantee the order in which requests are submitted, and that this is how other implementations are also doing it, then we should consider `WorkStealing`.

Lastly, if we cannot agree in changing the default Thread Executor, I'd like to then propose that we make the ServerBuilder require user to indicate a Thread Executor, therefore not having a default.

In this benchmark with a 2 CPU server and a 6 CPU client (ghz; 5 connections; 50 concurrency requests), we can easily see how every other thread executor is nearly, or more than, 2x as faster as the Cached executor:

```
==> Running benchmark for java_grpc_pgc_bench...
                    Requests/sec:       56205.88
==> Running benchmark for java_grpc_pgc_cchd_bench...
                    Requests/sec:       24171.14
==> Running benchmark for java_grpc_pgc_fixd_bench...
                    Requests/sec:       46419.32
==> Running benchmark for java_grpc_pgc_sngl_bench...
                    Requests/sec:       48263.82
==> Running benchmark for java_grpc_pgc_ws_bench...
                    Requests/sec:       46944.97
```

- `pgc` stands for Parallel GC
- `ws` stands for WorkStealing (2 threads in this bench)
- `fixd` stands for Fixed (2 threads in this bench)
- `sngl` stands for Single
- `cchd` stands for Cached (the default today)
- `java_grpc_pgc_bench` uses the `Direct` thread executor

Source for benchmark: https://github.com/brunoborges/grpc_bench

**Comment by jamesward** [comment]
What executor does the first/fastest use?

**Comment by jamesward** [comment]
Oh, direct. :) I was looking for it in the name but found it below the results.

**Comment by brunoborges** [comment]
Yes, `direct` is faster for obvious reasons, but would only work correctly with non-blocking code, which is how the benchmark code is implemented - a mere 'return "hello"'.

**Comment by argha-c** [comment]
>Secondly, given that developers are most likely not going to benchmark the different executors, I'd like to propose to switch to a Fixed executor, with the number of threads based on the number of availableProcessors() for the JVM.
+1. Though this is subject to benchmarks and specific application profiles, `2 *  availableProcessors()` is usually a proven heuristic for queues of this nature.

Additionally, the idea of allowing injection for a custom Executor, and the above don't necessarily have to be mutually exclusive imho.

**Comment by ericgribkoff** [comment]
cc @ejona86

**Comment by ejona86** [comment]
> Yes, direct is faster for obvious reasons, but would only work correctly with non-blocking code, which is how the benchmark code is implemented - a mere 'return "hello"'.

Direct is fast for noop processing. It's easy for it to be slower in practice, even with non-blocking code. It depends on the workload. A noop service isn't all that useful for tuning, other than to see some low-level costs.

> This executor is known for being extremely slow, even when compared to a Single Thread executor.

It's _definitely_ faster than a single threaded executor for _performing work_. And yes, you pay a penalty when using a queue with MPMC instead of MPSC, but as long as your work is non-trivial it's still a win. We'd expect the work to be non-trivial with gRPC.

> Therefore, I'd like to first ask for the reason behind choosing this executor type instead of other options available.

Because blocking. When the application blocks it greatly impacts the number of threads necessary for throughput and to avoid deadlock. A fixed-size thread pool commonly can't really be configured properly when blocking is being done.

ForkJoin pool does have the "managed blocking" goo to manage a user-configured minimum concurrency level, but it doesn't seem used enough for a library to assume it will solve any problems. It's also unclear what sort of impact it has on performance.

We realized very early we couldn't use a default fixed-size thread pool for the user's execution. And that left us with only cached thread pool, which is pretty weak. I've considered creating a new thread pool a few times, as it seems relatively easy to do better than cached thread pool in multiple ways. But we also don't really want to get into the business of custom thread pools; we'd probably try to contribute it to Guava or something.

> Secondly, given that developers are most likely not going to benchmark the different executors, I'd like to propose to switch to a Fixed executor, with the number of threads based on the number of availableProcessors() for the JVM.

That's assuming asynchronous processing.

I'll also note that `availableProcessors()` is an okay first approximation, but we've had some serious trouble tuning the netty thread pool as we have a _very_ wide user base in terms of load. It's been "good enough" to get us to this point, but it is an issue that never quite goes away.

> +1. Though this is subject to benchmarks and specific application profiles, 2 * availableProcessors() is usually a proven heuristic for queues of this nature.

Not really. `2*cores` is a "probably not bad" value when _all your work is processed by one thread pool asynchronously_ on _a dedicated machine (or VM)_. That's definitely not that case here, which is part of the source of complexity.

> Third, if we agree that there is certainly no need for the default behavior to guarantee the order in which requests are submitted, and that this is how other implementations are also doing it, then we should consider WorkStealing.

There's no guaranteed order.

By `WorkStealing` I assume you mean `ForkJoinPool`. In benchmarks in the past, we've seen it depend quite a bit on the workload whether `Executors.newFixedThreadPool()` or `ForkJoinPool` is faster.

> Lastly, if we cannot agree in changing the default Thread Executor, I'd like to then propose that we make the ServerBuilder require user to indicate a Thread Executor, therefore not having a default.

That'd break lots of existing users. We can't do an API change like that. Nope.

**Comment by argha-c** [comment]
>Not really. 2*cores is a "probably not bad" value when all your work is processed by one thread pool asynchronously on a dedicated machine (or VM). That's definitely not that case here, which is part of the source of complexity.

Yeah, I definitely assumed that the entire workload being asynchronously processed. If I hear you, the point is being a lib, the constraint is you can't make that assumption?

**Comment by ejona86** [comment]
> If I hear you, the point is being a lib, the constraint is you can't make that assumption?

Yeah. Also, we don't trust users to run on the same work executor as gRPC (i.e., directExecutor). It's just far too easy to accidentally block in Java. In a "normal" async application there's commonly small lurking places that block, but it doesn't impact the overall performance enough to notice. If sharing threads with gRPC you'd need to be _much_ more careful.

There's also problems with the type of executors being handled. gRPC needs to use Netty threads for Netty, for example; you can't "share" an arbitrary executor with Netty even though Netty is asynchronous because Netty needs to block on epoll. So you're left with at least two threads pools: the one for the application and the one for gRPC.

If you are in a world where you are 100% asynchronous, you can still configure gRPC to use a single shared Netty executor along with your application and have everything all nice. But that's out-of-reach of "the masses" as you have to be very careful with what libraries you use.

**Comment by brunoborges** [comment]
But then, being a lib that sets `Cached` by default, the constraint has already been broken.

To exemplify, I changed the benchmark to add a disk IO operation (create a temporary file).

```java
    public void sayHello(HelloRequest req, StreamObserver<HelloReply> responseObserver) {
      var reply = HelloReply.newBuilder().setMessage(req.getName()).build();

      try {
        var path = Files.createTempFile("grpc_", "_helloworld");
        Files.writeString(path, "Some text", StandardCharsets.UTF_8);
      } catch (Exception e) {
        System.err.println("Error on sleeping thread...");
      }

      responseObserver.onNext(reply);
      responseObserver.onCompleted();
    }
```

These are the results:

```
--------------------------------------------------------------------------------------------------------------------------------
| name               |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
--------------------------------------------------------------------------------------------------------------------------------
| java_grpc_pgc      |    3966 |       12.51 ms |       18.79 ms |       31.10 ms |       86.32 ms |   64.58% |    262.78 MiB |
| java_grpc_pgc_fixd |    3806 |       13.05 ms |       24.15 ms |       36.82 ms |       74.07 ms |  120.23% |    317.15 MiB |
| java_grpc_pgc_sngl |    3773 |       13.17 ms |       21.09 ms |       33.63 ms |       68.36 ms |   94.05% |    332.63 MiB |
| java_grpc_pgc_ws   |    3432 |       14.49 ms |       15.16 ms |       30.39 ms |       59.89 ms |  137.67% |    299.71 MiB |
| java_grpc_pgc_cchd |    1026 |       48.62 ms |       12.64 ms |       50.61 ms |       61.04 ms |  111.41% |    339.53 MiB |
--------------------------------------------------------------------------------------------------------------------------------
```

`java_grpc_pgc` uses `Direct`

`fixd` and `ws` are using `Fixed`/`WorkStealing` with 4x the # of cores (2 cpus; 8 threads total).

`cchd` is `Cached` (default).

**Comment by kabutz** [comment]
Hi Bruno, could you please run your benchmark with a configuration like this.  It should have comparable performance to a fixed thread pool, but it is "unbounded" in terms of threads like a cached thread pool. We would have at least 16 threads, but with more than 8 "processors" (which can be hardware threads) this would increase. Threads would stay at the core until the ArrayBlockingQueue is full and then the pool would create additional threads. These threads would stay around for 10 minutes. The queue would have at least 128 capacity, but with more processors this could also increase. Not sure if a smaller queue would make more sense with more processors?

```
int processors = Runtime.getRuntime().availableProcessors();
ExecutorService pool = new ThreadPoolExecutor(
    Math.max(processors * 2, 16), 
    Integer.MAX_VALUE,
    10,
    TimeUnit.MINUTES, 
    new ArrayBlockingQueue<>(
        Math.max(processors * 10, 128)
    )
);
```

**Comment by brunoborges** [comment]
Hi @kabutz,

I did a new bench with your suggestion, and here are the results:

```
Benchmark finished. Detailed results are located in: results/201009T075303
--------------------------------------------------------------------------------------------------------------------------------
| name                |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
--------------------------------------------------------------------------------------------------------------------------------
| java_grpc_pgc_pool  |    4153 |       11.96 ms |       21.72 ms |       45.64 ms |       60.30 ms |  137.89% |    355.94 MiB |
| java_grpc_pgc_ws    |    4100 |       12.11 ms |       14.37 ms |       28.84 ms |       49.27 ms |  127.26% |    335.36 MiB |
| java_grpc_pgc       |    4091 |       12.13 ms |       17.48 ms |       26.72 ms |       66.47 ms |    74.5% |     264.9 MiB |
| java_grpc_pgc_fixd  |    3999 |       12.42 ms |       20.33 ms |       33.55 ms |       54.84 ms |  118.22% |    331.72 MiB |
| java_grpc_pgc_sngl  |    3585 |       13.87 ms |       12.04 ms |       20.28 ms |       44.63 ms |  108.43% |     318.4 MiB |
| java_grpc_pgc_pool2  |    2742 |       18.16 ms |       15.18 ms |       31.06 ms |       55.96 ms |  116.62% |    320.94 MiB |
| java_grpc_pgc_cchd  |     990 |       50.39 ms |       16.70 ms |       49.44 ms |       64.33 ms |  115.78% |     304.7 MiB |
--------------------------------------------------------------------------------------------------------------------------------
Benchmark Execution Parameters:
 - GRPC_BENCHMARK_DURATION=5m
 - GRPC_BENCHMARK_WARMUP=1m
 - GRPC_SERVER_CPUS=2
 - GRPC_SERVER_RAM=512m
 - GRPC_CLIENT_CONNECTIONS=5
 - GRPC_CLIENT_CONCURRENCY=50
 - GRPC_CLIENT_QPS=0
 - GRPC_CLIENT_CPUS=6
 - GRPC_REQUEST_PAYLOAD=100B
```

## Notes:

1. The function operation is to create a random, very small (< 50 bytes), temporary file in the disk.
1. `java_grpc_pgc_pool` uses the `Direct` executor
1. `java_grpc_pgc_pool` uses the following Thread Pool: `new ThreadPoolExecutor(50, 200, 60L, TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>(200))`
1. `java_grpc_pgc_pool2` uses the Thread Pool Executor you suggested.
1. `java_grpc_pgc_ws` and `java_grpc_pgc_fixd` are, respectively, WorkStealing, and Fixed, with 8 threads.
1. `java_grpc_pgc_sngl` uses a Single Thread executor.
1. `java_grpc_pgc_cchd` is GRPC's default CachedThreadPool.

**Comment by brunoborges** [comment]
I modified the kind of operation to a Network operation (HTTP call).

The gRPC endpoint receives the request and then triggers `httpClient` on a new NetworkOperation object (that reuses the httpClient object).

```java
private static final HttpClient httpClient = HttpClient.newBuilder().version(HttpClient.Version.HTTP_1_1)
      .connectTimeout(Duration.ofSeconds(10)).build();

  static class NetworkOperation {
    public void execute() {
      try {
        var request = HttpRequest.newBuilder().GET()
            .uri(URI.create("https://httpbin.org/get"))
            .setHeader("User-Agent", "GRPC Benchmark")
            .build();

        var response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        // print response headers
        var headers = response.headers();
        headers.map().forEach((k, v) -> System.out.println(k + ":" + v));

        System.out.println(response.statusCode());
        System.out.println(response.body());
      } catch (Exception e) {
        System.err.println("Error on sleeping thread...");
      }
    }
  }
```

Here's the result:

```
Benchmark finished. Detailed results are located in: results/201009T090213
--------------------------------------------------------------------------------------------------------------------------------
| name                |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
--------------------------------------------------------------------------------------------------------------------------------
| java_grpc_pgc_cchd  |     574 |       86.90 ms |       84.99 ms |       85.73 ms |      274.06 ms |   63.14% |    216.08 MiB |
| java_grpc_pgc_pool  |     574 |       86.94 ms |       84.43 ms |       85.36 ms |      276.71 ms |   60.64% |    218.18 MiB |
| java_grpc_pgc_ws    |     564 |       88.52 ms |       84.73 ms |       85.78 ms |      294.35 ms |   62.71% |    226.85 MiB |
| java_grpc_pgc_pool2 |     182 |      274.80 ms |      302.61 ms |      326.69 ms |      499.76 ms |   20.29% |    206.79 MiB |
| java_grpc_pgc_fixd  |      93 |      538.27 ms |      591.04 ms |      630.50 ms |      744.58 ms |   11.84% |    145.66 MiB |
| java_grpc_pgc       |      22 |         2.25 s |         3.34 s |         4.06 s |         4.81 s |    5.77% |    121.68 MiB |
| java_grpc_pgc_sngl  |      11 |         4.33 s |         4.80 s |         4.94 s |         5.37 s |    3.73% |    120.07 MiB |
--------------------------------------------------------------------------------------------------------------------------------
```

This bench ran with the same configuration as the [previous one](https://github.com/grpc/grpc-java/issues/7381#issuecomment-690090788).

**Comment by brunoborges** [comment]
I did another benchmark on the same NetworkOperation code, now with `sendAsync` instead. The results came out pretty much the same to all of them. 

HttpClient will use a CachedThreadPool by default when `sendAsync` is used, to complete the task.


```
Benchmark finished. Detailed results are located in: results/201009T101836
--------------------------------------------------------------------------------------------------------------------------------
| name               |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
--------------------------------------------------------------------------------------------------------------------------------
| java_grpc_pgc_pool2 |     569 |       87.66 ms |       90.01 ms |      103.98 ms |      244.11 ms |   94.57% |    327.96 MiB |
| java_grpc_pgc_ws   |     553 |       90.20 ms |       93.86 ms |      105.18 ms |      291.19 ms |   93.25% |    308.06 MiB |
| java_grpc_pgc_cchd |     553 |       90.31 ms |       93.09 ms |      104.41 ms |      286.45 ms |   94.03% |    328.83 MiB |
| java_grpc_pgc_pool |     557 |       89.60 ms |       90.07 ms |      104.84 ms |      282.86 ms |   96.69% |    339.69 MiB |
--------------------------------------------------------------------------------------------------------------------------------
Benchmark Execution Parameters:
 - GRPC_BENCHMARK_DURATION=5m
 - GRPC_BENCHMARK_WARMUP=1m
 - GRPC_SERVER_CPUS=2
 - GRPC_SERVER_RAM=512m
 - GRPC_CLIENT_CONNECTIONS=5
 - GRPC_CLIENT_CONCURRENCY=50
 - GRPC_CLIENT_QPS=0
 - GRPC_CLIENT_CPUS=6
 - GRPC_REQUEST_PAYLOAD=100B
```

**Comment by brunoborges** [comment]
These results are showing me that for most scenarios of GRPC Server endpoints, there are much better options than `Cached`.

**Comment by kabutz** [comment]
Resource deadlocks are tricky to resolve, which is why having a fixed thread pool is dangerous.

Could you please also track what the largest pool size is for the cached thread pool (and others where it makes sense). For example, add this:

```
    Runtime.getRuntime().addShutdownHook(new Thread() {
      public void run() {
        if (pool instanceof ThreadPoolExecutor) {
          System.out.println("Largest pool size: " +
              ((ThreadPoolExecutor)pool).getLargestPoolSize());
        }
      }
    });
```

Then at the end of the run you can see what happened.

My suspicion is that you had a lot more active threads in the cached thread pool than you realized. With my pool configuration, it might make sense to decrease the length of the queue, so that we can have more active threads more quickly.

**Comment by ejona86** [comment]
@brunoborges, creating a 30 byte temporary file is not I/O in a useful sense. That is probably going to a ramdisk and even if on a normal disk it wouldn't actually need to delay for the file to be persisted. It is much easier to see the rough performance impact of blocking by throwing a `Thread.sleep(1000)` in the code. Note that you need more requests than whatever fixed-sized pools you are using.

_Any_ pool with a maximum thread count can deadlock. Java is not in a place to address that. That's why I considered writing my own; I think it would be relatively easy to do better than cached while also avoiding bloating the number of threads and removing deadlock potential. None of the alternatives you described avoided the deadlock.

@kabutz's suggested configuration for ThreadPoolExecutor can perform better, but also exposes some serious edge cases. I don't think there's a way to configure it to avoid those edge cases. For example, if the core pool size is 16, each RPC is blocked for 1s for processing remotely, and clients have 32 outstanding RPCs then you'll see 2s processing times instead of 1s as with cached thread pool. You also still have deadlock potential (due to the queue). I'll also note that we don't want to create 16 threads "just in case;" there are many low qps users of gRPC.

Honestly, I don't trust most benchmarks and there's not been anything convincing me that it is worth-while to look into this. I agree that other executors can perform better and you are free (and I'd encourage you) to configure those. The server executor is very easy to change. I am disappointed we can't use a better default, but I feel like "that's the world we live in."

**Comment by brunoborges** [comment]
At the very least, the default executor of the Java implementation should follow similar design of the default thread pool model of the other implementations (e.g. Go, Rust, .NET).

Is that the case?

**Comment by kabutz** [comment]
Agreed that the benchmarks are unrealistic and which I also said from the beginning that the CachedThreadPool, even though it might not have the best performance in all cases, is the safest option to use in this case. Except of course that we can run out of physical threads (OOME) and then that could cause other issues for the system.

**Comment by ejona86** [comment]
> At the very least, the default executor of the Java implementation should follow similar design of the default thread pool model of the other implementations (e.g. Go, Rust, .NET).

I don't think that's quite true as a _requirement_, as different languages may be quite different, but I agree it may provide guidance. Last I saw, Rust is not a serious enough implementation to compare to. Go is similar to Java: it creates a new goroutine for each request. I'm not as confident about Python, but I think it uses a fixed-size thread pool and rejects RPCs if the pool is exhausted. C# seems to rely on async/await, although there is some completion queue handling that may impact it. C++ is similar to Java and will create as many threads as necessary.

**Comment by ejona86** [comment]
It seems this issue is resolved, as Java does behave similarly to multiple other languages. There are opportunities for other potential changes, like documentation improvements or finding ways to make things easier, but changing the default executor is non-trivial. We all agree it is not great.

I will mention that we've not seen any _huge_ gains by swapping executors. We've seen latencies decrease IIRC on the order of few µs (maybe upwards of 10). Performance would be one reason to switch, but I think there's also a big case to switch from a resource consumption standpoint as the current solution does create more threads than necessary and helpful. But it also doesn't seem like existing executors fit the bill.
