### ISSUE TITLE
CheckedForwardingClientCall should cancel delegate on failure

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#739]
It should also document whether it cancels or not, even if we end up not cancelling the delegate. 

@ejona86 do you remember if there were reasons to not do this?  If so, are they stronger than the reason that cancelling should still be done?

**Comment by ejona86** [comment]
"It's hard" or even "it's impossible."

There are a lot of edge cases that have to be handled, and it didn't seem immediately needed.

**Comment by zhangkun83** [comment]
@ejona86 I don't remember if we discussed about the edge cases that would make it impossible. The current `ClientCall` API doesn't require `cancel()` to be called, that means either case should be fine. @carl-mastrangelo do you have any concern over not cancelling that I may have overseen?

**Comment by ejona86** [comment]
In discussing with @zhangkun83, we recalled that we can't call `cancel()` because if the call was already started(), then `ClientCall.Listener.onClose` would be called twice. Since `CheckedForwardingClientCall` has no way to detect if `start()` was called, it simply prohibits implementations from throwing after `start()` is called.
