### ISSUE TITLE
Make backoff policy in AbstractManagedChannelImplBuilder and subclasses customizable

### ISSUE THREAD

**Issue by vitarb** [grpc/grpc-java#7456]
Currently AbstractManagedChannelImplBuilder.build() method creates backoff policy with default values:
```
  @Override
  public ManagedChannel build() {
    return new ManagedChannelOrphanWrapper(new ManagedChannelImpl(
        this,
        buildTransportFactory(),
        **new ExponentialBackoffPolicy.Provider(),**
        SharedResourcePool.forResource(GrpcUtil.SHARED_CHANNEL_EXECUTOR),
        GrpcUtil.STOPWATCH_SUPPLIER,
        getEffectiveInterceptors(),
        TimeProvider.SYSTEM_TIME_PROVIDER));
  }
```

This makes it impossible to configure backoff policy when using sub-classes such as NettyChannelBuilder.

Ideally we should be able to customize backoff policy on each builder implementation (NettyChannelBuilder is the one that I specifically care about at the moment) and use default policy if custom value hasn't been provided.

Please let me know if there are any other ways of configuring this policy or if I'm missing something.

**Comment by voidzcy** [comment]
This issue has been brought up for a couple of times (see #6873, #6952), but using the current exponential backoff is an essential behavior in gRPC based on the [cross-language design](https://github.com/grpc/grpc/blob/v1.32.0/doc/connection-backoff.md). Please see discussions in #6873.

**Comment by vitarb** [comment]
Thanks for the context, Are you suggesting that having ability to configure backoff policy would go against cross-language design?

**Comment by voidzcy** [comment]
Yes, the design was for protecting the server from being overloaded and the specially designed backoff algorithm is an essential behavior. It isn't intended to allow end users set whatever backoff they want as that could flood the network/server easily.

**Comment by vitarb** [comment]
Can you please elaborate why 2 minutes has been chosen as a maximum retry interval and why do we think that this value is universally good for all application owners irrespective if their specific use case?

**Comment by ejona86** [comment]
Too-aggressive reconnecting can hammer the network extending outages and harm the server when things recover. The worst-case is a congestion collapse of the network, [which isn't theoretical](https://en.wikipedia.org/wiki/Network_congestion#Congestive_collapse) and has even been seen in datacenter networks. Most users are not knowledgeable enough to understand the implications of their changes and knobs like this can be _very_ tempting to workaround problems. It's not like you can easily set the backoff policy used with Ethernet, DNS, connect(), and TCP as an application author.

The bigger problem for me is the API surface it exposes, as that can prevent future changes to the strategy. Could you share your use-case and why the current backoff is inappropriate?

**Comment by mfateev** [comment]
Our use case is business-level transactions going through the system. The number of clients connecting the backend service is usually small (less than 100) and each minute of the outage has a high business impact. So any 5-minute network or DB outage is extended another 2 minutes by the backoff configuration that we cannot control. We also hide the gRPC client behind our client side library, so we don't ever expect any of the issues that you outlined as we control the maximum timeout.

Do you have any empirical data on how many clients are necessary to kill service or network with the reconnect requests only with 10-second maximum reconnect timeout, for example? I have a suspicion that your concern is mostly theoretical for 99.9% of real-life deployments outside of the google infra. And looking at the number of developers that asked for this change the lack of the feature causes real pain.

**Comment by ejona86** [comment]
> And looking at the number of developers that asked for this change the lack of the feature causes real pain.

Who are you talking about? Can you share a link?

**Comment by vitarb** [comment]
@ejona86 your colleague @voidzcy shared links in his first comment above. It looks like this is at least 3rd attempt to request this feature by the community.

**Comment by voidzcy** [comment]
There isn't an _optimal_ solution, but a _good_ solution. We are leveraging the risk of potentially overloading the server/network and trying to reconnect as quickly as possible. It can never be perfect as the client does not know when the server is back to normal. The idea of exponential backoff is similar to TCP Additive Increase Multiplicative Decrease (AIMD). It tries to backoff more aggressively when the number of consecutive reconnect failure increases and resets the backoff if it successfully reconnects. It's proven to work well for such cases.

As quote from https://github.com/grpc/grpc-java/pull/6873#issuecomment-607387480

> With the backoff policy, you should never wait more than ⅔ the amount of time the server was down. So if the server was down 30 seconds, the maximum wait time would be 20 seconds after the server is started. That normally works amazingly well, but I can understand how waiting those 20 seconds would be annoying to the development cycle.

Again, the biggest concern for exposing this knob to users is most users are not knowledgeable enough to understand the implications of their changes and it can be very tempting to workaround problems (e.g., a max backoff of 10ms is harmful in production). We are targeting on a solution that works generally well for most cases without opening up such risks.

**Comment by mfateev** [comment]
Could you make it configurable, but put some minimal limit to the value? I agree that 10 ms doesn't make sense in any situation. But 2 minutes can be completely unacceptable for some scenarios. I propose something like 2-minute default with 10 seconds as an allowed minimum. This would allow us to maintain reasonable SLA while eliminating the danger of users shooting themselves in the foot.

**Comment by voidzcy** [comment]
/cc @ejona86 
Is it possible to make that happen?

**Comment by vitarb** [comment]
Any updates?

**Comment by vitarb** [comment]
For now made a temporary work-around that runs a separate thread, which resets connection backoff periodically. What do you guys think, can we expose connection backoff as an option, the way Maxim suggested above?

**Comment by ejona86** [comment]
While I'm not all that bothered by exposing some options for configuring the backoff logic, I don't think people (generally) really understand what they are messing with (as has also been evidenced by keepalive; I failed to restrict keepalive timeout).

I do find the issue of "DB goes down and connections take a while to reconnect" to be strong. But I'm dubious of a 10s MAX_BACKOFF. I'd look much more favorably with adjusting the MULTIPLIER used for increasing the exponential backoff. If someone wants "1.4" instead of the "1.6", that's not outrageous.

Requests to adjust the max backoff down to 5/10 seconds though I don't think understand what is in play, and the conversations have seemed to expose that. `connect()` timeout can confuse the conversation here, and we do have open issues to resolve it (#1943). #6873 is actually more about the connect timeout. Since MIN_CONNECT_TIMEOUT isn't implemented in Java so the behavior isn't really what we'd hope, but it is a can of worms to discuss as the "even better" thing to do is let the `connect()` continue while simultaneously considering it failed after a timeout.

If there's interest in this from further users, I'd be glad to hear about it. Right now this issues seems to be the only case where the 2 min setting is causing harm.

**Comment by NielsUll** [comment]
I have a concrete usecase. We are using gRpc to communicate between a main container in and a sidecar container running in a kubernetes pod. The sidecar is the server, and the main application is the client. So there will only ever be one client communicating with the server.

The main application regularly polls the sidecar to ensure it is running, so the main application knows it can process messages from external parties. If the poll fails, the main container will stop processing messages until the sidecar is ready.

If the sidecar crashes for some reason and is restarted, the grpc client in the main container will backoff when reconnecting to it. This lead to an undesired extra delay before the main application is operational again, even though the sidecar is up and running again.

We would very much like to be able to disable the exponential backoff, since it makes no sense in our usage scenario.

**Comment by hmendesB2C2** [comment]
I have a side car app running in kubernetes that receives about 5k GRPC calls per second from a client, if there is a disconnect then the client can be waiting minutes for reconnecting. We need to be able to control the initial and max backoffs at least. 
It doesn't make any sense to wait large seconds to reconnect. If my app was to kill the network then the 5k calls per second would have done that already.

**Comment by hmendesB2C2** [comment]
I have a side car app running in kubernetes that receives about 5k GRPC calls per second from a client, if there is a disconnect then the client can be waiting minutes for reconnecting. We need to be able to control the initial and max backoffs at least. 
It doesn't make any sense to wait large seconds to reconnect. If my app was to kill the network then the 5k calls per second would have done that already.
