### ISSUE TITLE
Add javadoc to clarify equality on Status

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#751]
Are Statuses equal based on code, code and message, or even as far as the throwable?  The javadoc for equals should clarify this.

**Comment by ejona86** [comment]
I thought this action item was to "Add a warning to avoid doing someStatus == Status.UNAVAILABLE instead of "someStatus.getCode() == Status.Code.UNAVAILABLE".

**Comment by carl-mastrangelo** [comment]
Not sure about publicly, but this could be made into an error prone check.   Not sure what to do about people using == indiscriminately.  

If someone does status.equals(otherStatus) though, that should have expected equality semantics.

**Comment by ejona86** [comment]
The problem was that it is really easily to accidentally use one form over the other, even if you know which form is correct. Using `==` for enums is a common practice. Note that using `equals()` instead of `==` doesn't help, because the problem is that you really intended the opposite.

At present, `Status` does not override `equals` and `hashCode`.

**Comment by ejona86** [comment]
There is agreement to keep the equals() the same as it is today (instance equality). We will just add docs to point out that equals() does not provide semantic equality (Code is for that).
