### ISSUE TITLE
About the size of the NettyServer thread pool

### ISSUE THREAD

**Issue by ifermo** [grpc/grpc-java#7520]
I read the size initialization code for numEventLoops in the io.grpc.netty.Utils.DefaultEventLoopGroupResource class. I understand that "io.netty.eventLoopThreads" is a property that customizes the value of numEventLoops, but System.getProperty("io.netty.eventLoopThreads") does not seem to be useful. Why is this?

**Comment by dapengzhang0** [comment]
The property "io.netty.eventLoopThreads" is for Google's internal use only as introduced in #6619. It has no use for open source users.

**Comment by dapengzhang0** [comment]
>  but System.getProperty("io.netty.eventLoopThreads") does not seem to be useful

Why are you saying it is not useful? Can you clarify?

**Comment by ifermo** [comment]
> > but System.getProperty("io.netty.eventLoopThreads") does not seem to be useful
> 
> Why are you saying it is not useful? Can you clarify?

**Comment by ifermo** [comment]
`if (numEventLoops == 0 && System.getProperty("io.netty.eventLoopThreads") == null) {
        this.numEventLoops = NettyRuntime.availableProcessors();
      } else {
        this.numEventLoops = numEventLoops;
      }
      this.eventLoopGroupType = eventLoopGroupType;`
The above is the source code. From the point of view of this code, the program does not use the value of the "io.netty.eventLoopThreads" property.

**Comment by ifermo** [comment]
In fact, what I want to know is how to set the size of the thread pool of NettyServer workerGroup and confirm that this is not a bug.

**Comment by dapengzhang0** [comment]
That property is also used by netty library, e.g. https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/MultithreadEventLoopGroup.java#L41

> I want to know is how to set the size of the thread pool of NettyServer workerGroup

You can use `NettyChannelBuilder.workerEventLoopGroup(nonnullValue)` to set a workerGroup. Otherwise, it will use a default workerGroup, and the existence and/or value of the property "io.netty.eventLoopThreads" may have some affect on the instance of EventLoopGroup created, which is a subclass of `MultithreadEventLoopGroup`.

**Comment by ifermo** [comment]
Thank you @dapengzhang0 .
