### ISSUE TITLE
Question about overrideAuthority and OkHttpBuilder settings

### ISSUE THREAD

**Issue by BioZrod** [grpc/grpc-java#7536]
Hello, I am trying to implement a GRPC connection using swift GRPC and I run into a 401 unauthorized issue I asked for help there and they pointed me to include an http header called "authorization".

The connection to the server using GRPC-Java is done like this:
```
java.security.cert.Certificate[] certChain = new java.security.cert.Certificate[1];
            certChain[0] = certTest1;
            clientStore.setKeyEntry("gw_key", privateKey, null, certChain );
            kmf.init(clientStore, password.toCharArray());
            // Create an SSLContext that uses our TrustManager
            SSLContext context = SSLContext.getInstance("TLS");
            context.init(kmf.getKeyManagers(), tmf.getTrustManagers(), new SecureRandom());
            channel2 = OkHttpChannelBuilder.forAddress("controller.openschema.magma.etagecom.io", 443)
                    .useTransportSecurity()
                    .sslSocketFactory(context.getSocketFactory())
                    .overrideAuthority("metricsd-controller.openschema.magma.etagecom.io")
                    .build();
```

So I have two questions:
1.- What exacty does ".overrideAuthority" property do?
2.- In this particular case does using OkHttpBuilder include that header and if yes what would be the value on that header?

I am curious as I have little experience with networking and http and so far after researching the 401 error all I can find is setting the header to use a token but in Java the implementation did not add any token as far as I understand (There is no login on the server all I get from it is a signed csr from an earlier connection to the server)

**Comment by sanjaypujare** [comment]
> So I have two questions:
> 1.- What exacty does ".overrideAuthority" property do?

`overrideAuthority` has nothing to do with authorization header. It is used solely for overriding the authority i.e. hostname used in validating the name(s) presented in TLS certificates. You can check the [doc](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/ManagedChannelBuilder.java#L172).

> 2.- In this particular case does using OkHttpBuilder include that header and if yes what would be the value on that header?

The header won't be automatically used with OkHttpBuilder. You will have to use a [`CallCredentials`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/CallCredentials.java#L37) as described in the [jwt-auth-example](https://github.com/grpc/grpc-java/blob/master/examples/example-jwt-auth/src/main/java/io/grpc/examples/jwtauth/Constant.java#L31). Of course you need to know what value to provide in the header.

> 
> I am curious as I have little experience with networking and http and so far after researching the 401 error all I can find is setting the header to use a token but in Java the implementation did not add any token as far as I understand (There is no login on the server all I get from it is a signed csr from an earlier connection to the server)

It's quite possible then the server expects you to present this certificate (aka signed csr) in an mTLS connection from your side. But instead of getting an mTLS connection failure you got a 401-Unauthorized which might point to a missing Authorization header.

**Comment by sergiitk** [comment]
@BioZrod FYI [Javadoc](https://grpc.github.io/grpc-java/javadoc/index.html?overview-summary.html) for v1.33.0 (was just released) fixes the docs for `OKHttpChannelBuilder`'s inherited methods, including `overrideAuthority()`:  https://grpc.github.io/grpc-java/javadoc/io/grpc/okhttp/OkHttpChannelBuilder.html

**Comment by BioZrod** [comment]
Thank you for the information on what overrideAuthority does and the tip on 401 error not actually being related to a missing header.
