### ISSUE TITLE
Passing multiple --plugin args to protoc with java_grpc_library?

### ISSUE THREAD

**Issue by simontoens** [grpc/grpc-java#7566]
Hi, we have been using `java_grpc_library` for a while and it works great!  We are now adding Kotlin code to our monorepo and we'd like to support [kroto-plus](https://github.com/marcoferrer/kroto-plus), which is implemented as a protoc plugin (passed to protoc using `--plugin`). It looks like java_grpc_library [currently doesn't allow multiple](https://github.com/grpc/grpc-java/blob/master/java_grpc_library.bzl#L92) --plugin args.

The question: is this something that's already on your radar?  I didn't see an existing issue for this.  Or is there a workaround already?  If you are not planning to support this, we can probably contribute a fix ...

Thanks!

**Comment by ejona86** [comment]
The Kotlin codegen would need its own Bazel rule. Bazel actually has a plugin structure to allow running multiple plugins with a single invocation of protoc, but last I checked it was not available from Starlark. That's why java_grpc_library executes protoc itself. Any other code generator should just execute protoc itself. java_grpc_library actually uses `--descriptor_set_in`, which _requires_ that protoc has already been run.

**Comment by simontoens** [comment]
Thanks @ejona86.
