### ISSUE TITLE
Use grpc-bom in the examples

### ISSUE THREAD

**Issue by bogdandrutu** [grpc/grpc-java#7583]
# Is your feature request related to a problem?
Examples will be copy paste a lot and it is good to show there all the best practices.

### Describe the solution you'd like
Use gRPC bom in the example code.

### Describe alternatives you've considered
Keep things as they are.

**Comment by ejona86** [comment]
What's missing?

https://github.com/grpc/grpc-java/blob/7009c1a863944a07ab6f5a2ccb7741d48f274777/examples/pom.xml#L23-L33

**Comment by bogdandrutu** [comment]
I looked at Gradle sorry

**Comment by ejona86** [comment]
I'm a bit more nervous for BOM in gradle, as I don't fully know how it impacts the version resolution process and need to look into the platform stuff more. Specifically, I need to see what happens with `enforcedPlatform()` when it downgrades a transitive dependency.

I'm fine with others using it, but if users have trouble, I wouldn't be able to help them currently. I'm also not as convinced of the importance of bom for gradle. In Maven, it is working around the useless version selection logic. But gradle's version selection is actually good. gRPC is a special case, though, since it wants the versions of its various artifacts (grpc-*) to match. Although using Gradle's module metadata (which I also haven't looked into much) is probably better than encouraging users to use the BOM.

**Comment by ejona86** [comment]
I looked into `enforcedPlatform()`, and our users shouldn't use it; it silently downgrades versions. `platform()` is good and fine and would help some situations, but I don't think it would be "best practices" like using a BOM+requireUpperBoundDeps would be in Maven. It still allows individual artifacts to be upgraded separately from others, which could cause the normal troubles; I think we'd need gradle module metadata to lock the versions together.

Do you know something about it that I don't?

**Comment by ejona86** [comment]
Closing since it seems there is little benefit. If we hear back about benefits then we can reopen.
