### ISSUE TITLE
client fatjar seems too big

### ISSUE THREAD

**Issue by kristofsteindl** [grpc/grpc-java#7596]
Hello,
I try to build a client-server communication channel via grpc, where the server is a Spring app and the client is an oracle JVM. I need to build a fatjar which contains all the runtime dependencies for my code. If I do this, I get a ~10 MB jar with ~10 thousand classes, which seems to be too big and complex for oracle to load and resolve the classes.
My build.gradle:

dependencies {
...
    implementation "io.grpc:grpc-stub:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-api:${grpcVersion}"
    implementation "io.grpc:grpc-netty:${grpcVersion}"
}
jar {
    from configurations.runtimeClasspath.collect  {zipTree(it).matching { exclude 'module-info.class'}}
}
My question is am I doing something wrong? I thought grpc client app should be a lightweight thing, but 10 MB and 10 thousand class is everything but not lightweight.
Thanks

**Comment by ericgribkoff** [comment]
Could you clarify how the produced fatjar "seems to be too big and complex" for an Oracle JVM to run? That doesn't sound right to me. 10 MB also does not sound particularly large for a fat jar, particular one that is also bringing in Netty via the grpc-netty dependency.

You can construct a lighter weight gRPC client app, similar to what we do on Android, by using grpc-okhttp instead of Netty and taking advantage of proguard to reduce file size, where our sample client apk comes in at 1MB. But I'm not aware of any concerns about size in non-mobile environments, and am suprised that 10MB seems too big for your environment.

**Comment by kristofsteindl** [comment]
I tried to load jar into the oracle with the 'loadjava' command, but threw a stream of 'cannot be resolved' errors for the classes (ORA-29534). If I leave out for instance the netty package, the 6MB jar can be uploaded with the same command, without any errors (unfortunately I need this dependency for runtime). Simultaneously I reported this issue with 'loadjava' for oracle, because I don't think neither that 10MB should be a problem to resolve.

I was suspicious that I made something wrong with the dependencies and the build, and the fatjar is somehow unnecessarly fat. But now I am assured, that the client jar being 10 MB is not particularly big. 
And thanks for the hint for grpc-okhttp!

**Comment by ericgribkoff** [comment]
I'm not familiar enough with the build rules for a fatjar to have any suggestions for why you encountered the stream "cannot be resolved" error when loading the resulting jar. I don't _think_ it's due to the jar being too big - my impression is that many deployed Java jars can be quite large, so it would seem more likely its a build issue with how some of the Netty dependencies are being pulled in. But that's just a guess.

As for the size issue - yes, as far as I'm aware 10MB is not particularly big, and in resource-constrained environments (like mobile) grpc-okhttp can cut the application size down significantly more, which should work for most users where 10MB is too big.

I'll mark this closed since I don't think there's anything actionable here for us to do at this point. If there's a concern that I've missed, please let me know and I will reopen.
