### ISSUE TITLE
Error While Calling Api

### ISSUE THREAD

**Issue by akkie2106** [grpc/grpc-java#7602]
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: RecognitionAudio not set
how to solve this? in my android App
![image](https://user-images.githubusercontent.com/67181037/98433042-d18bc900-20e9-11eb-92ad-a510c568d20d.png)

**Comment by ericgribkoff** [comment]
This is an error message coming back from the server you're communicating with, rather than an error/issue with the gRPC library itself (which is what this repository handles). It looks like you are using the Cloud Speech API. You can see a quickstart example of how to use the API at https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/speech/cloud-client/src/main/java/com/example/speech/QuickstartSample.java, and the Cloud Speech library itself lives at https://github.com/googleapis/java-speech. If you have trouble getting the quick start code to work, either the java-docs-samples or the java-speech APIs would be the place to file an issue to get help with those respective libraries.

**Comment by akkie2106** [comment]
It's the error showing in Android Studio

**Comment by ericgribkoff** [comment]
@akkie2106 Thanks for the additional info, but the error you're seeing is not caused by the gRPC library, we are just relaying that information for you back from the Cloud Speech API. You will probably want to try the quick start example I linked above, and if that doesn't work then follow up with either of the repositories I mentioned above to get help with this issue.

**Comment by akkie2106** [comment]
Oke thank you sir

**Comment by akkie2106** [comment]
how to convert into inputStream From a path ? in java Android
