### ISSUE TITLE
CPU utilisation is not 100%

### ISSUE THREAD

**Issue by nimit95** [grpc/grpc-java#7802]
I have written a basic grpc server, 
```java
            NettyServerBuilder.forPort(port)
                .bossEventLoopGroup(bossGroup)
                .workerEventLoopGroup(workerGroup)
                .channelType(channelClass)
                .directExecutor()
                .addService(new GreeterImpl())
                .build()
                .start();
```

While load testing CPU utilisation is never 100%, current maximum I could take is 25%.

Any ideas how to get 100% usage for maximum throughput?

**Comment by ejona86** [comment]
How many cores is the machine? How many threads are in the workerGroup? How many clients are being used?

Since you are using `directExecutor()` (and the greeter service is close to a noop in complexity), all activity for each client's channel will be isolated to one thread and thus cannot expand to additional cores.

**Comment by nimit95** [comment]
CPU is 8 core, I have tested with worker group threads ranging from 72 to 2000, clients I have tested ranging from 50 to 5000.

As far as I understand, it is least operation so it should be high throughput, I am getting close to 60k req/s while the load average hover around 1. 
When I test with Netty, for the same test I am getting close to 110k req/s and CPU utilisation is high.

**Comment by nimit95** [comment]
Also for my understanding, each client channel has 1 thread by default, if any I/O op is performed then the worker group threads are used right?

**Comment by ejona86** [comment]
> I have tested with worker group threads ranging from 72 to 2000

I'd expect 8-16, when using `directExecutor()`. But more shouldn't prevent using more CPU.

> clients I have tested ranging from 50 to 5000.

That's plenty. Assuming they are actually separate processes. (Separate processes are not necessary, you could use multiple Channels, but is the easiest way to define "client" without getting into nitty-gritty details.)

Did you see the same performance for 50 and 5000 clients?

> I am getting close to 60k req/s while the load average hover around 1.
When I test with Netty, for the same test I am getting close to 110k req/s and CPU utilisation is high.

Since the QPS changes, it seems you are doing a closed-loop benchmark where each client has X outstanding RPCs. How many concurrent RPCs does each client do?

Unclear what your Netty benchmark is (HTTP/1, HTTP/2, TCP, etc), but since you aren't saturating CPU I would expect the problem is you aren't sending enough RPCs concurrently. You may be seeing a difference in latency that changes the req/s (although a 2x increase in latency would be unexpected, I don't know what this Netty benchmark is, or even the gRPC benchmark, so can't really comment much).

> each client channel has 1 thread by default

All processing for a particular connection is performed from a single thread. A Channel defaults (via pick_first LB) to connecting to only one backend with one connection, and thus uses one thread.

> if any I/O op is performed then the worker group threads are used right

Yes. Connection processing uses worker group threads.

> And with using directExecutor() it would be using the threads from the workerGroup?

Unclear what "it" is. Using `directExecutor()` means that `GreeterImpl` code would use the same thread in workerGroup that the connection uses.

**Comment by nimit95** [comment]
Oh yeah got the issue. I was increasing the concurrency for a single RPC connection, while what was needed to be increased were the concurrent connections.

Thanks for all the help @ejona86 :)

**Comment by ejona86** [comment]
Excellent! Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by nimit95** [comment]
Just to understand more correctly, each client onnection has one thread. All the sync operations are performed on that thread. If there is any I/O on that thread(eg Db call), that is handled by a separate worker thread. 

I am trying to compare this model with Netty model, where each handler is executed on a different thread.

**Comment by ejona86** [comment]
The gRPC connection model is the Netty model. Each worker thread (from `workerEventLoopGroup()`) can service multiple connections. Each connection is associated with a single worker though. The normal Netty model does not schedule each handler on a different thread; there are ways to do that, but they are not encouraged.

I don't know what you mean about "sync" operations. As a general rule you should not do any blocking on the worker thread as it can produce deadlock-like situations. The worker thread should perform CPU computation, but I/O must be handled by Netty itself (which will use non-blocking I/O along with select/epoll).

If you do a DB call, that is asking for trouble if you are using `directExecutor()`, as that is normally a blocking call and it will prevent any further processing on that worker until it is complete. You should instead use default executor or provide your own via `executor()`, at which point callbacks to your application will happen on a separate thread pool and not impact the Netty threads.
