### ISSUE TITLE
I found a bug when I use the plugin(protobuf-maven-plugin:0.5.1)

### ISSUE THREAD

**Issue by hejia1111** [grpc/grpc-java#7821]
Codes of server are Python, and codes of client are JAVA. I hava an arg named "sentences" whose type is String[]. So I use setSentences() to build a Request. It's in the file QueryRequest.java :

```
  public Builder setSentences( int index, java.lang.String value) {
     if (value == null) {
    throw new NullPointerException();
  }
  ensureSentencesIsMutable();
      sentences_.set(index, value);
      onChanged();
      return this;
    }
```

The sentences_'s type is List.  I met a error of 'java.lang.IndexOutOfBoundsException' because its size is 0 at the beginning.
Then I change the codes of setSentences() (though IDEA tell me I should not)
```
    public Builder setSentences(java.lang.String[] value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSentencesIsMutable();
      for (String s : value) {
          sentences_.add(s);
      }
      onChanged();
      return this;
    }
```
Finally it works.

**Comment by ericgribkoff** [comment]
If I understand correctly, you are calling `setSentences(0, "some_string")` on a newly created instance of your `sentences` proto's generated class. There's probably a better source of documentation I could link to, but if you look at https://developers.google.com/protocol-buffers/docs/reference/java-generated#repeated-fields, you'll see that there is a `setSentences(int index, String value)` _and_ a `addSentence(String value)` in the generated code. You're correctly seeing that calling `setSentences(0, "some_string")` when there is no value at index 0 throws an exception. Instead, you should use `addSentence("some_string")`. The `#setSentences` method would be appropriate when you already have a value at index 0 and want to replace it.  This is analogous to how `#add(index, value)` works on a Java [ArrayList](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#add-int-E-).

I'll note that the protobuf generated code you're pointing to here is not actually part of this repo (it's part of protobuf itself, not gRPC), but I want ahead and answered here anyways since it seems to have a straightforward answer.
