### ISSUE TITLE
How to ensure the retries are working

### ISSUE THREAD

**Issue by garuna-m6** [grpc/grpc-java#7911]
I have some confusion in the implementation of [retry methods](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldClient.java)

I have a grpc service jar and I am trying 3 parallel request to the service as mentioned in the example above with the retry config created and attached (provided 5 max retries). How does the retry mechanism works
-> Say the request that I have sent receives a fail code from server , it checks the config if the fail code is in `retryableStatusCodes` then does it resends the same request (`totalRpcs` remain 3 only) or does it mark that request as complete and create a new identical request (`totalRpcs` = 4, 3 initiated out of which 1 failed and hence 1 more started )

**Comment by YifeiZhuang** [comment]
The `totalRpcs` is still 3. Retry process happens inside the library and won't return to the application layer until it's committed, e.g. retry succeeded or max attempt exhausted. So from the application perspective, it only sees 3 RPCs.

> How to ensure retries are working

You run the [retry server](https://github.com/grpc/grpc-java/blob/master/examples/src/main/java/io/grpc/examples/retrying/RetryingHelloWorldServer.java), half of the responses will be failed. But because your client is configured retry, you would see most of the RPCs are eventually successful. You should run larger number of parallel RPCs so it is more visible.

**Comment by garuna-m6** [comment]
Yep to verify if my retries are working fine I increased params `initialBackoff` and `maxBackoff` and the program now takes significantly more time so assuming the retry logic is connected, however even after applying retry logic I find sometimes the run ended as failure, for my application I am going to do create around 50 parallel threads and even if one fails then I would have to rerun the whole job again. @YifeiZhuang  any advices on how to overcome this ?
