### ISSUE TITLE
io.grpc.Server#SERVER_CONTEXT_KEY for transcoding

### ISSUE THREAD

**Issue by kenix** [grpc/grpc-java#7927]
Quote from comment on that field:
> Key for accessing the Server instance inside server RPC Context. It's unclear to us what users would need. If you think you need to use this, please file an issue for us to discuss a public API.

Now I'm reaching out to ask for help:
1. as io.grpc.InternalServer#SERVER_CONTEXT_KEY can use it. May the "external"?
1. actually not interested in Server itself at all, but the io.grpc.Server#getImmutableServices. Is there any other way to get it ONLY in knowing "I'm on the Server side"?

Context:
Working on a simplistic http-grpc-spring-web transcoder at https://github.com/kenix/http-grpc-spring-web and needs the list of ServerMethodDefinitions to setup the pipes properly.

See also: lines [70 - 83] in https://github.com/kenix/http-grpc-spring-web/blob/main/lib/src/main/java/io/github/kenix/httpgrpc/spring/HttpGrpcMapper.java

Any general suggestions are also appreciated.

**Comment by sanjaypujare** [comment]
> as io.grpc.InternalServer#SERVER_CONTEXT_KEY can use it. May the
"external"?

Sorry - not clear what you are asking. Can you expand?

> actually not interested in Server itself at all, but the
io.grpc.Server#getImmutableServices. Is there any other way to get it ONLY
in knowing "I'm on the Server side"?

Not enough to know you are on the server side. If you have access to the
built Server you can use getImmutableServices()
<https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/Server.java#L97>
to
get the services.

**Comment by kenix** [comment]
Background: wants to provide a small __library__ to dynamically configure REST endpoints using ServerMethodDefinitions, won't manage the Server lifecycle at all, but the library will be used on the server side with whatever mechanism managing the Server.

The example is using a grpc-spring-boot-starter which manages the Server. But as a library, it should not depend on a specific starter-implementation. Basically something like `io/grpc/protobuf/services/ProtoReflectionService.java:89` is preferred.

**Comment by sanjaypujare** [comment]
> ... Basically something like `io/grpc/protobuf/services/ProtoReflectionService.java:89` is preferred.

`ProtoReflectionService` is gRPC's own service for supporting reflection and hence is given access to the server via `SERVER_CONTEXT_KEY`. Allowing one service implementation access to all other services bound to a `Server` might violate isolation and privacy so may not be a supported use-case. @ejona86 can add some more context.

**Comment by kenix** [comment]
Totally understandable. I should have said something like `io.grpc.protobuf.services.ProtoReflectionService#getRefreshedIndex` is preferred, namely the ability to `getImmutableServices()` and `getMutableServices()`, e.g. through other `Context.Key`s, given `ServerServiceDefinition` is immutable. `ProtoReflectionService` could also be refactored that way - not interested in `Server` itself.

**Comment by ejona86** [comment]
> as io.grpc.InternalServer#SERVER_CONTEXT_KEY can use it. May the "external"?

A transcoding use-case is interesting and I have no security/isolation concerns. But I don't think SERVER_CONTEXT_KEY is what you need. And I don't see a way to provide what you need.

You actually have access to SERVER_CONTEXT_KEY right now, via the InternalServer. Yet you aren't using it and instead are doing a horrible `setVisible(true)` hack. Basically it isn't clear how SERVER_CONTEXT_KEY would help you, since you don't have a gRPC service. SERVER_CONTEXT_KEY is only set when serving an RPC in a gRPC service.

> Basically something like io/grpc/protobuf/services/ProtoReflectionService.java:89 is preferred.

That only works because _it is a gRPC service_. Note that there can be multiple Servers running simultaneously and this works fine, because it will get the Server instance on which the RPC arrived.

Your use-case starts from an HTTP server; there's no way in gRPC to know which Server you'd want. It seems like you _must_ integrate with net.devh:grpc-spring-boot-starter in order to determine which server you're interested in. But once you have a Server instance, the existing gRPC APIs are sufficient.

If you know what _port_ you are interested in, you could communicate with the reflection service and get back much of the same reflection information. Although I recognize that introduces its own functional and performance issues since you are running within the application.

> actually not interested in Server itself at all, but the io.grpc.Server#getImmutableServices.

Only using getImmutableServices is actually fine; right now that's the only usage of it, for reflection service.

> Is there any other way to get it ONLY in knowing "I'm on the Server side"?

You can get it only knowing "you are servicing an RPC." "Server-side" doesn't really exist except from the network's perspective, as servers are generally clients as well. And it is really "servers (plural) side".

**Comment by kenix** [comment]
> You actually have access to SERVER_CONTEXT_KEY right now, via the InternalServer. Yet you aren't using it and instead are doing a horrible setVisible(true) hack.
Already tried `InternalServer`, always got `null`, on line 69, commented out. When that had worked, totally fine. Maybe I'm doing something wrong there. I'll be great if you can help me out.

> If you know what port you are interested in, you could communicate with the reflection service and get back much of the same reflection information. Although I recognize that introduces its own functional and performance issues since you are running within the application.
I also need `ServerCallHandler` to forward the call.

> You can get it only knowing "you are servicing an RPC." "Server-side" doesn't really exist except from the network's perspective, as servers are generally clients as well. And it is really "servers (plural) side".
I cannot follow. It'll be nice if you can elaborate on that a little more.

**Comment by ejona86** [comment]
Server is not global in gRPC. You can't just go and grab the instance. SERVER_CONTEXT_KEY allows _services_ to learn what server _the current RPC_ is being serviced for. You got `null` because the code wasn't processing an RPC for any specific server.

**Comment by kenix** [comment]
That explains it, thanks. That leaves me:

1. use reflection service to route the call in order to not depend on a specific grpc-starter
2. ask for provision of the ServerMethodDefinitions

Do you have other suggestions?

**Comment by kenix** [comment]
> But I expect the spring plumbing is different for each starter.

Exactly. I'll support 2 and 1 in that order.
