### ISSUE TITLE
abnormal delay，version 1.32.1

### ISSUE THREAD

**Issue by chenguangsu** [grpc/grpc-java#7958]
My RPC service has an abnormal delay problem. From the monitoring point of view, there is irregular jitter. And the delay presents a bimodal pattern. From the perspective of network packet capture, there are abnormal TCP packets. As shown in the figure, there is an abnormal time interval between the head and data of the same grpc http2, and the same TCP packet contains multiple http2 packets. Please help me solve this problem. Thank you very much.
![企业微信截图_55aeb950-cbe1-4ad2-a4f7-e4442046fee4](https://user-images.githubusercontent.com/80389661/110729450-b5e02d00-8259-11eb-9049-3d84d0b63dd2.png)
![企业微信截图_485af9b8-dbcd-4458-82e1-dae6585be070](https://user-images.githubusercontent.com/80389661/110729474-bf699500-8259-11eb-9023-89101d6c42eb.png)
<img width="1410" alt="WeChatWorkScreenshot_ad056a21-6fb3-4c71-bc2d-d2c27d170b09" src="https://user-images.githubusercontent.com/80389661/110729489-cee8de00-8259-11eb-9248-b9016abd6a74.png">
![WeChatWorkScreenshot_8bab4cf5-7a83-4251-ac7f-88eced81036a](https://user-images.githubusercontent.com/80389661/110729559-e4f69e80-8259-11eb-9af0-93f62e931ee8.png)

**Comment by sanjaypujare** [comment]
> ...
> From the perspective of network packet capture, there are abnormal TCP packets.

Are you talking about the `GRPCGRPCGRPC` protocol packets? That's weird and I can't explain it - other than it being a tooling problem in Wireshark. 

> As shown in the figure, there is an abnormal time interval between the head and data of the same grpc http2,

The interval is between the 200OK header and the data packets which could very well be because of the server application sending the payload/data after some computational/processing delay.

> and the same TCP packet contains multiple http2 packets. 

That seems normal and possibly how the tool chooses to render it rather than an issue in the actual network communication. What problem do you suspect?

**Comment by chenguangsu** [comment]
My RPC request rate is very low, less than 20 per second. Server quota 52 VCPU 96 GIB, almost no load. Is there any parameter configuration that can reduce the occurrence of such abnormal delay? Thank you very much.

**Comment by sanjaypujare** [comment]
> My RPC request rate is very low, less than 20 per second. Server quota 52 VCPU 96 GIB, almost no load. Is there any parameter configuration that can reduce the occurrence of such abnormal delay? Thank you very much.

Request rate and server resources/quota may not be the factor but the actual latency in the application where the server is waiting on something (either an event or result of a calculation) before it can use `onNext()` to send the data packets. Can you instrument the server application to see if such latencies exist? Or can you share the structure/code of your server application?

**Comment by chenguangsu** [comment]
The following are the codes of the client side and the server side. Please help me check them. Thank you very much

Client code :
![企业微信截图_869bb61c-9ba3-4566-86a5-9dbc1cec2102](https://user-images.githubusercontent.com/80389661/110743288-c81a9500-8272-11eb-8872-07bb439b5694.png)
![企业微信截图_9cb2b7f8-1ae1-48a5-8628-8f38fc88ab99](https://user-images.githubusercontent.com/80389661/110743473-0b750380-8273-11eb-98dd-b5ed4a633e66.png)
Server code :
![企业微信截图_5a7db56c-34cb-440a-94ef-0dd3a29f8ea7](https://user-images.githubusercontent.com/80389661/110743935-d61ce580-8273-11eb-832e-98b525d8a90f.png)
![企业微信截图_e9efb5c4-e746-4eac-80b2-d1198a4a5010](https://user-images.githubusercontent.com/80389661/110744812-4415dc80-8275-11eb-8d66-38de873914c7.png)
![企业微信截图_2ec75260-10e3-45fc-9924-0f005fcd82ac](https://user-images.githubusercontent.com/80389661/110744169-36ac2280-8274-11eb-94b4-010994cfd7fe.png)

**Comment by sanjaypujare** [comment]
Couple of comments:
- what's the reason for using `childOption` with SO_RCVBUF, SO_SNDBUF and TCP_NODELAY? Is that needed or you are experimenting?
- I still don't see what happens before you call `onNext` after you get notified of an incoming call on the server side. Is there a lot of processing happening?

Otherwise I don't see anything obviously wrong.

**Comment by chenguangsu** [comment]
At present, the parameters of childoption are only tests. It is not yet possible to determine the best configuration. The processing time from the server receiving the request to onNext presents a unimodal pattern, so I think the abnormal delay should occur after onNext.

**Comment by chenguangsu** [comment]
And the same code deployed two systems, the first system did not appear bimodal delay, but the second system appeared. The two systems are deployed on the same cloud service. Is this abnormal delay related to system hardware configuration or operating system version?

**Comment by qshian** [comment]
@sanjaypujare  @chenguangsu 
This problem, like the one below, should be caused by thread pools，please confirm
https://github.com/grpc/grpc-java/issues/7381

**Comment by chenguangsu** [comment]
The problem is a performance problem with high frequency access. But my service has less than 20 requests per second, and the machine is a 52-core, 98GB memory cloud host, so I don't think that's the reason.

**Comment by sanjaypujare** [comment]
@ejona86 can comment on #7381 and thread pools.

@chenguangsu you should use a profiler to find out more. May be @ejona86 has some info.

**Comment by ejona86** [comment]
There are a _lot_ of things that could cause a bimodal distribution, and we're not really in a place to help find it. For starters, there are no units on the x axis of the very first image. And the y axis doesn't look like percentage, unless .4 is 40% instead of .4%. There's no information on the packet trace screenshot which side is local on the trace and which is remote, so it is unclear which side of the network we are viewing. And as was mentioned, there's not enough context around the `streamObserver.onNext()` to gain any useful information about how the service operates.

So this could be as simple as a TCP-level retransmission or the scheduling delay of a thread having to be woken up. Normally I'd be quite happy to blame the small additional latency on the cost of waking up a sleeping thread, although in this case directExecutor() means there may not be many threads involved. If the service does any processing on another thread, then I'm fine blaming a thread that unfortunately ran out of work to go to sleep just before it was needed again, which means it had to be woken up.

Why are you using `InternalClientCalls.StubType`?

**Comment by ejona86** [comment]
Oh, one other detail I should mention: since you are using directExecutor() your application can trivially impact gRPC network performance.

**Comment by ejona86** [comment]
No response to provide more information, so closing. This may just be unlucky kernel scheduling timing. More information can be provided and then we can reopen.
