### ISSUE TITLE
Discuss StreamObserver

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#799]
abstract class?
rename to Observer/do we are how closely it matches RxJava?
onValue -> onNext?

just depend on RxJava for stub?

**Comment by ejona86** [comment]
There is agreement that we should rename onValue -> onNext. Other pieces seem unlikely.

**Comment by louiscryan** [comment]
Naming alignment should take into account the proposed Java9 API
http://cs.oswego.edu/pipermail/concurrency-interest/2015-January/013641.html

**Comment by ejona86** [comment]
@louiscryan, can this be closed?

**Comment by louiscryan** [comment]
I think the other pieces are out of scope for the moment.

It's not clear that AbstractClass adds any real value that we wouldn't get from 'default' methods in interfaces at some point. It would also prohibit a class from implementing both StreamObserver and Observer thus making bridging GRPC into an RX pipeline harder.

I'm wary of renaming to Observer because of the potential for collision when adapting GRPC to RX. They're both Observer

**Comment by ejona86** [comment]
I agree that the other things are mostly "no"s. Just depending on Rx for stub is still possible to do in the future. We should either close this issue or make it clear what is left to be done and then remove it from the Beta milestone.

**Comment by ejona86** [comment]
Closing, because it seems the things we plan on doing right now are done.
