### ISSUE TITLE
RoundRobinLoadBalancerFactory$Picker  index  start from 0

### ISSUE THREAD

**Issue by mistlxj** [grpc/grpc-java#8026]
I use grpc in production,  and choice rr lb(RoundRobinLoadBalancerFactory$RoundRobinLoadBalancer), 
because server release is a continuous process，when server nodes is releasing,  the Constructor  `RoundRobinLoadBalancerFactory$Picker(Picker(List<Subchannel> list, @Nullable Status status)`  will be called every time.
due to the index is alaways start from 0 ,  the qps sent to different nodes is unbalanced,  Cause fluctuations in availability when the server nodes is releasing.  

Any comments are welcome.

**Comment by ejona86** [comment]
RoundRobinLoadBalancerFactory was renamed in #4996 over two years ago, so you are certainly using an old gRPC client. This problem was resolved in [grpc-java v1.15.0](https://github.com/grpc/grpc-java/releases/tag/v1.15.0) via #4462. You need to upgrade. If you continue having trouble after upgrading, please provide the grpc-java version you are using.
