### ISSUE TITLE
Is it ok to use the gRPC-level proxying example?

### ISSUE THREAD

**Issue by djungyvr** [grpc/grpc-java#8050]
Hello!

I noticed there is an example for gRPC level proxying\* that was never merged and was wondering if it is ok to use as a reference?

\* https://github.com/ejona86/grpc-java/blob/grpc-proxy/examples/src/main/java/io/grpc/examples/grpcproxy/GrpcProxy.java

Thanks!
David

**Comment by ejona86** [comment]
Yeah, it is fine to use it as a reference.

I didn't actually sent it out for review. Since you are intended to copy it, it should really have more comments to help you follow along. But you wouldn't be the first to use it, and I've only heard of one issue with it where someone noticed missing synchronization, but that was fixed years ago.

**Comment by djungyvr** [comment]
Fantastic! Thank you very much!
