### ISSUE TITLE
Retry in bidirectional streaming

### ISSUE THREAD

**Issue by jackycdc** [grpc/grpc-java#8136]
I am utilize gRPC Java to wrap a leagcy system. There is one use case is the payload size for request / response could be 1~2 gigabyte. One proposal is chunk request / response into small binary blocks and transport them by bidirectional streaming.  We would like the client could retry certain message if any expeption happens on server side.

I found some questions are similar to the problem we have.
Bidirectional streaming RPC [#5631](https://github.com/grpc/grpc-java/issues/5631)
The _"How to get the failed message to retry,"_ is the exact question I have. which method should I 

Way to implement a fail-over client (especially for bidistream call) [#5822](https://github.com/grpc/grpc-java/issues/5822)
In this question
_"In gRPC the entire RPC/stream is what would tend to be retried/failed-over, not individual messages. If some of the messages of a stream may fail while others are fine, then 1) it may be an inappropriate use of streaming or 2) you need to handle this at the application-level and need support from the streaming RPC schema. There is no generic metadata mechanism per-message in a stream."_ commented by _ejona86_, it looks like reasonable, but our request / response payload size is exceed maximum gRPC payload limitation (2^32, right?).

How could I make gRPC rety works on message level? or trigger gRPC build in retry (request level) when client StreamObserver.onError?

**Comment by ejona86** [comment]
It sounds like you are transferring large files. Depending on your error rate and network, re-sending the entire file after an error is easy and may be acceptable. For example, re-sending 1 GB rarely in a datacenter network wouldn't be noticeable. But frequently we aren't that lucky and it can't be solved so simply.

1-2 GB is pretty close to the gRPC message size limit. Right now for Java I think we have limited it to 2^31. 2^32 is possible on-the-wire, but would need some effort to support in Java since it overflows int. So chunking the messages is appropriate. See also https://stackoverflow.com/a/65797934/4690866

You will want custom application-level retries. Built-in retries can't help the download case at all, as retries are no longer possible after the server's response is accepted. Built-in retries could be used with the upload case, but it would require buffering the upload and the entire upload would be re-sent on failure.

For large downloads (responses), server-streaming with custom app retry can work fine and isn't too involved. The client would include a "start at"/"resumption" position in the request and the server would start its responses at that position. If no start at/resumption is provided in the request, the server would start from the beginning.

Upload (request) resumption is more complicated, as they client needs to be informed of where to start sending and it may not hit the same server for a second RPC. The approach here will tend to vary a bit depending on what the data is and how it is stored and synchronized across servers. The simplest, approach would to use client-streaming for the upload RPC and add a method to tell the client where to resume; when an upload RPC fails, it would call that method before starting the resumption. Another approach is to use bidi streaming and have the server provide periodic "checkpoints" of where the client should resume. Note that wouldn't just be what the server has received, but has been _stored_, as maybe the server crashed after receiving something but before it could be saved. In all cases the client would want to include a "start at"/"resumption" position in its request, so the server knows what data it is looking at.

**Comment by jackycdc** [comment]
@ejona86 thank you for reply.

I cannot agree with you more for upload case. Application-level retry must hit the different server in our case. The data uploaded to particular server would not have opportunity to receive the further data once client retry and point to another server, unless the solution of centralized cache.  

Appreciate your valuable information, please allow me 1 ~ 2 days to discuss this with team and update here.
Have a good day!

**Comment by jackycdc** [comment]
We think "resumption" might be a good choice. Thank you.
