### ISSUE TITLE
android-interop-testing doesn't build

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#817]
With the renames to packages, it is now broken. I expect that the generated code needs to be regenerated as well (for other reasons).

We should backport the fix to the 0.8.x branch.

**Comment by madongfly** [comment]
I think Kun has updated the references already, the breakage is actually that you did't update gRpc on your local maven repository, but install it now can not fix because the android-interop-test depends on 0.8.0-SNAPSHOT while our head is 0.9.0-SNAPSHOT now.

I'll send you a PR to update the dependency.

As for the generated code, they are not checked in (we used to check them in, then removed after the gradle plugin for nano is available).
