### ISSUE TITLE
How to restart bi-directional stream after network disconnection android

### ISSUE THREAD

**Issue by Y2Kot** [grpc/grpc-java#8177]
I'm using AndroidChannelBuilder to build ManagedChannel and subscribe on android network changes. My rpc function works well after network reconnection, but on my bi-directional stream it dies forever both when I'm using CoroutineStub and StreamObserver. How can I restart bi-directional stream after network reconnection?

**Comment by sanjaypujare** [comment]
I have seen this [SO post](https://stackoverflow.com/questions/64467790/unavailable-keepalive-failed-the-connection-is-likely-gone)  about how AndroidChannelBuilder recovers from network changes but does not specifically discuss bi-di streams.  @voidzcy anything you want to add?

**Comment by Y2Kot** [comment]
AndroidChannelBuilder works well with usual rpc, however it seems that bi-directional streams doen't restoring on reconnect

**Comment by sanjaypujare** [comment]
Just realized: take a look at this https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#stream-identification .

Any gRPC stream will be mapped to the underlying http2 stream which is lost when the connection is lost and recreated because of network changes. So it would be impossible to re-establish bi-di streams the way you expect.

**Comment by Y2Kot** [comment]
> http2 stream which is lost when the connection is lost and recreated because of network changes

so why grpc streams don't recreate?

**Comment by voidzcy** [comment]
> My rpc function works well after network reconnection, but on my bi-directional stream it dies forever

I am a bit confused by "rpc function" vs "bi-directional stream". What exactly do you see for one working well while the other doesn't? To be clear, auto reconnecting after network recover _re-establishes the TCP connection_ and sends out _RPCs buffered during the period of network lost_. Those are new RPCs. If your application does not reattempt by making a new RPC when the current one fails, no RPC will be _recreated_ after the connection is re-established.

If you do want the feature of automatically reattempting the failed RPC due to network lost, that's what _[transparent retry](https://github.com/grpc/proposal/blob/master/A6-client-retries.md)_ does. You can enable it on [ManagedChannelBuilder](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#enableRetry--), there are a couple of other knobs for configuring retry.

**Comment by Y2Kot** [comment]
To be clear:
I have such methods in protofile:
```
rpc StopDeviceTracking(DevicesTracking.StopTrackingRequest) returns (DevicesTracking.StopTrackingResponse) {
  }

  rpc StartDeviceStream(stream DevicesTracking.StreamDeviceMessage) returns (stream DevicesTracking.StreamServerMessage) {
  }
```
StopDeviceTracking - works after reconnecting
StartDeviceStream - can't send data and can't receive it after reconnection

**Comment by sanjaypujare** [comment]
> ...
> StopDeviceTracking - works after reconnecting
> StartDeviceStream - can't send data and can't receive it after reconnection
> 
> > If your application does not reattempt by making a new RPC when the current one fails
> 
> It seems to be happend

The RPC needs to be re-established after a reconnection whereas you are expecting the existing streams of an RPC to be resumed after reconnection which won't happen.

**Comment by KostadinAlmishev** [comment]
Does grpc support some reconnection mechanism like in rsocket: [Reconnect after server restart in rsocket](https://github.com/rsocket/rsocket-java/issues/900)?

**Comment by sanjaypujare** [comment]
> Does grpc support some reconnection mechanism like in rsocket: [Reconnect after server restart in rsocket](https://github.com/rsocket/rsocket-java/issues/900)?

Take a look at https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md#states-of-connectivity especially: "Channels can also handle errors on established connections and reconnect, or in the case of HTTP/2 GO_AWAY, re-resolve the name and reconnect."

But in case of a broken bi-di call, the RPC will have to be re-initiated (after the reconnection) since the previous streams are lost.

**Comment by Y2Kot** [comment]
> But in case of a broken bi-di call, the RPC will have to be re-initiated

Does re-initialize means that we need to create new channel?

**Comment by Y2Kot** [comment]
> 
> 
> > Does grpc support some reconnection mechanism like in rsocket: [Reconnect after server restart in rsocket](https://github.com/rsocket/rsocket-java/issues/900)?
> 
> Take a look at https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md#states-of-connectivity especially: "Channels can also handle errors on established connections and reconnect, or in the case of HTTP/2 GO_AWAY, re-resolve the name and reconnect."
> 
> But in case of a broken bi-di call, the RPC will have to be re-initiated (after the reconnection) since the previous streams are lost.

can you give java code sample?

**Comment by sanjaypujare** [comment]
> Does re-initialize means that we need to create new channel? Or is any possibilities to re init stream on current channel?

You don't need to re-create the channel - just re-do the streaming RPC on the current channel

**Comment by sanjaypujare** [comment]
> can you give java code sample?

Check this out https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/errorhandling . Once you detect your streaming call has aborted due to an error you just need to re-invoke the call e.g. put a loop around `asyncCall()` or `advancedAsyncCall()` and continue in the loop only if there was an error.

**Comment by Y2Kot** [comment]
> 
> 
> > can you give java code sample?
> 
> Check this out https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/errorhandling . Once you detect your streaming call has aborted due to an error you just need to re-invoke the call e.g. put a loop around `asyncCall()` or `advancedAsyncCall()` and continue in the loop if there was an error.

how should I re-invoke coroutine flow?

**Comment by sanjaypujare** [comment]
> how should I re-invoke coroutine flow?

These calls recreate the streamObservers and re-invoke the call via the stub which re-invoke your callbacks.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
