### ISSUE TITLE
Dealing with MAX_CONCURRENT_STREAMS limitations

### ISSUE THREAD

**Issue by erikjoh** [grpc/grpc-java#8252]
Hi!

A few days ago, we ran into some issues when implementing a system that needs to open a few hundred long lived (~15 mins) bidirectional streaming RPCs. We noticed that most of these RPCs seemed to be intermittently frozen for long durations without any indication of why.
After some digging it turned out that we were hitting the `MAX_CONCURRENT_STREAMS = 100` limit advertised by the server.
It seems like the behavior of grpc-java and netty in this case is to silently queue/buffer the RPCs until new HTTP2 streams are available.
I think this is happening in netty [here](https://github.com/netty/netty/blob/ada9c38c0a96e593b895b93dd4600d5299e77cef/codec-http2/src/main/java/io/netty/handler/codec/http2/StreamBufferingEncoder.java#L160-L167).

From what I can tell, there doesn't currently seem to be any way of either accessing the limit sent by the server or surfacing the fact that we are hitting this limit on the channel.
Any ideas or options of how we could surface this information?

To work around the limit, I also think our only option right now is to create multiple channels. Since we probably don't want to open one channel per stream, I think we might need to do something similar to this [ChannelPool.java](https://github.com/googleapis/gax-java/blob/master/gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java) (which unfortunately is package-private).
Is there anything in grpc-java that might help us here or is this approach our best bet right now?

**Comment by ejona86** [comment]
Something like ChannelPool is your best option at the moment. Even if we plumbed up MAX_CONCURRENT_STREAMS information, it is hard for you to make use of it because it can vary over the lifetime of the connection (even to zero, which gRPC C core is capable of doing). Per the HTTP/2 standard, MAX_CONCURRENT_STREAMS is the maximum number of streams to be created _to the server_ (as you aren't supposed to open more connections), so semantically it is weak to be used to decide to open more connections.

I agree extra connections need to be created in a scenario like this, but it is hard to prevent them from causing extra problems if the server is overloaded. At least in Java the ChannelPool can implement Channel so most of your application doesn't need to be aware of the hack.

**Comment by ejona86** [comment]
Closing since this seems "resolved." If not, comment and it can be reopened.

"gRPC should use multiple connections" feature request is tracked cross-language at https://github.com/grpc/grpc/issues/7957, and we are well aware it can be useful outside of L4 scenarios (like internet-scale L7 load balancers). This request is related to that, but techincally different, but we did seriously consider adding such an API in the past and gave up trying to make it work. That's not saying it isn't possible, but I am doubtful and we'd really need to work with some concrete suggestions.
