### ISSUE TITLE
Requests with too many nested levels fail

### ISSUE THREAD

**Issue by jsannemo** [grpc/grpc-java#8256]
I'm running in to
```
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.setRecursionLimit() to increase the depth limit.
	at com.google.protobuf.InvalidProtocolBufferException.recursionLimitExceeded(InvalidProtocolBufferException.java:125)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:885)
```
when parsing a request message that happens to have a very deep, nested structure. The marshaller `ProtoLiteUtils.java` seems to use the default of 100.

100 is of course a lot in most cases, but not when e.g. sending over serialized expressions of 30-ish deep function calls, which doesn't seem too unlikely (I ran in to it implementing the expression language [CEL](https://github.com/google/cel-spec) for example).

Is it possible to raise this limit a bit, or make it configurable?

**Comment by voidzcy** [comment]
Given that we are setting the [maximum message size limit](https://github.com/grpc/grpc-java/blob/2cbc7fc3a5b98122cdd67bc881aefa3eef8e1b65/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L212) to Integer.MAX_VALUE for deserializing from an InputStream. It seems OK to use a large recursion limit as well. 

I'd consult @ejona86 for any implications for doing so.

**Comment by ejona86** [comment]
> Given that we are setting the maximum message size limit to Integer.MAX_VALUE for deserializing from an InputStream. It seems OK to use a large recursion limit as well.

Definitely not. gRPC does its own message size limits check before calling protobuf, so using Integer.MAX_VALUE is just a convenient way to avoid plumbing the max message size to protobuf yet still have the same behavior.

Related: https://github.com/grpc/grpc/issues/24633. Note that I mention an approach that may work for Java.

> sending over serialized expressions of 30-ish deep function calls

@jsannemo, you are inlining the function calls? That sounds problematic, as you essentially need an infinite limit. The concern with such deep call stacks is overflowing the stack. That is especially a concern in C++ (and the other wrapped languages that use the C++ parser, like Python) where you get memory corruption instead of an exception.

**Comment by ejona86** [comment]
No response to provide more information, so closing. We're not against adding an API here, but we want to make sure it is useful; bumping the limit to just have Java throw StackOverflowError isn't all that interesting. More information can be provided and then we can reopen.
