### ISSUE TITLE
Validation prevents integer value in service config

### ISSUE THREAD

**Issue by mattmetlis** [grpc/grpc-java#8300]
### What version of gRPC-Java are you using?
1.33.1

### What is your environment?
Linux, JDK 11

### What did you expect to see?
Parsing a service config like in [this example](https://github.com/grpc/grpc-java/blob/master/examples/src/main/resources/io/grpc/examples/retrying/retrying_service_config.json), and passing it to defaultServiceConfig() on a NettyChannelBuilder (method is implemented on AbstractManagedChannelImplBuilder) should work.

### What did you see instead?
Parsing a service config like in [this example](https://github.com/grpc/grpc-java/blob/master/examples/src/main/resources/io/grpc/examples/retrying/retrying_service_config.json), and passing it to defaultServiceConfig() on a NettyChannelBuilder results in an IllegalArgumentException, saying the Integer type is not supported, from [this validation code](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java#L508-L524). If I pass a double, e.g. I put "5.0" instead of "5" in the json file, then it works as expected; however, [the retry proposal](https://github.com/grpc/proposal/blob/master/A6-client-retries.md) specifies that maxAttempts must be an integer.

### Steps to reproduce the bug
Pass a Map for a service config that contains an Integer value for maxAttempts to NettyChannelBuilder's defaultServiceConfig() method.

**Comment by dapengzhang0** [comment]
This is expected as described in the javadoc
https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#defaultServiceConfig-java.util.Map-

| Json entry | Java Type |
|------------|-----------|
| object     | Map       |
| array      | List      |
| string     | String    |
| number     | Double    |
| boolean    | Boolean   |
| null       | null      |

**Comment by mattmetlis** [comment]
So then the example is wrong and the proposal is out of date.

**Comment by dapengzhang0** [comment]
> So then the example is wrong and the proposal is out of date.

No, the example is using a Json file. It's a valid Json file. You can use "5" in Json file to represent a number. But in java api `defaultServiceConfig()`, you must use Double to represent a number.

**Comment by mattmetlis** [comment]
Isn't the whole point that we should be able to parse the JSON file into a Map and use it in Java? At best, it's misleading and confusing to specify that a number has to be an integer in one place and a double in another. Further, when I parse a JSON file that contains '5' into a Map, that value gets turned into an Integer - so I'm going to have to either add special logic to the parsing, or intentionally violate the spec, just to be able to use retries.

You can say that each piece is correct on its own because it's separate, and OK technically that's true, but do you not see that when you put them together (which is the whole point) this makes things confusing and difficult for users?

**Comment by mattmetlis** [comment]
Also, what is the purpose of forbidding Integers in the Java code, when an Integer is the type that makes the most sense for some of these values (which the spec agrees with)? Forbidding Integer and requiring Double gives the impression that there's some utility in using a Double, but what would it mean to say I want a max of 4.3 attempts?

**Comment by ejona86** [comment]
> Isn't the whole point that we should be able to parse the JSON file into a Map and use it in Java?

Are you saying the example doesn't execute for you? Can you provide the exception you get?

> Further, when I parse a JSON file that contains '5' into a Map, that value gets turned into an Integer

Which parser are you using? It would have been helpful to mention that earlier, as before you had not referenced anything other than the example which "works on my machine."

> At best, it's misleading and confusing to specify that a number has to be an integer in one place and a double in another.

The retry proposal is talking about JSON. JSON does not have a separate integer type. "5.0" and "5" are semantically equivalent in JSON. Saying it "must be an integer" is like saying something "must be greater than 3". The description here is the mathematical concept. It has nothing to do with _Java_ as the spec isn't talking about Java.

It is possible to store integers (the mathematical concept) in `double` that are impossible to store in `long` as well as integers in `long` that are impossible to store in `double`. I know some JSON parsers try to deal with that stuff, but we're trying to take a KISS approach.

**Comment by mattmetlis** [comment]
I have not tried the example directly. I'm using Jackson for parsing. I know it's not gson, but it seems like a popular and mature enough parser that I would expect it to be compatible with the way gRPC has specified service configuration.

My main issue is with the fact that the Java validation code prevents you from using an Integer type for a number that is conceptually an integer. Can anyone explain the reasoning for that? Allow it to be a double - sure. Recommend it be a double - ok, if you want. Force it to be a double - I would argue that is not keeping it simple.

I know that integer is not a type in JSON. I don't think it's unreasonable to look at a spec that says a value must be an integer and then be surprised when I get an IllegalArgumentException for trying to use an Integer in Java to represent that integer. I feel like this is a case of, is the goal here to do the minimum possible to be able to say that it's technically not incorrect, as long as you can find and figure out the gotchas, or is the goal to, within reason, make things clear and easy for users? I think I've already made it clear which option I think is better for a framework to do.

**Comment by voidzcy** [comment]
I'd also wish we could weaker the precondition of parsing numbers in [JsonUtil](https://github.com/grpc/grpc-java/blob/b1daad6f30f064d8b1fd423fc9051fc345cb310f/core/src/main/java/io/grpc/internal/JsonUtil.java#L108-L111) to allow Integer and Long values. It is true that converting a Long to Double may overflow, we could mitigate it in the parser (let it throw or cap to Double's max value as usually values that large aren't that useful). I had encountered a similar issue previously when implementing the XdsNameResolver to produce a service config with numbers (#7880). It's a bit cumbersome to ensure all numbers are casted to double when creating a service config map. Supporting Long and Integer natively can make this simpler as well as make the service config API more robust.

**Comment by ejona86** [comment]
> I'm using Jackson for parsing. I know it's not gson, but it seems like a popular and mature enough parser that I would expect it to be compatible with the way gRPC has specified service configuration.

Yeah, Jackson should be a fine JSON parser for this stuff. Although... does it seriously not let you configure this behavior? https://stackoverflow.com/a/51694642/4690866 It relies entirely on if you write `1.00` or `1` on the type it parses. That's just asking for runtime exceptions in _all_ consuming code, which is a strong argument to use its data mapping functionality which would coerce into a single type. Jackson can produce an Integer, Long, BigInt, Double, or BigDecimal.

Some other JSON implementations behave similarly; I question if they were mirroring each other. Given the wide range of types, I think we just get to rely on `Number.doubleValue()` and note the limited precision in the javadoc.

> My main issue is with the fact that the Java validation code prevents you from using an Integer type for a number that is conceptually an integer. Can anyone explain the reasoning for that? Allow it to be a double - sure. Recommend it be a double - ok, if you want. Force it to be a double - I would argue that is not keeping it simple.

Just because it opens the door to a lot of questions. The simplest would be to just support `Number.doubleValue()`, but that can cause silent data loss on conversions. That's not a problem today, but it could be for some future fields. If we don't just rely on Number, then it becomes a longer topic. Integer? Sure. Short? Uhh.. Byte? Long? We went for the most restrictive "just support Double" and it had served us well.

**Comment by ejona86** [comment]
API review notes:
 * Is seen as a problem, but nowhere near a consensus on solution. Spent too much time discussing this and only one user has been negatively impacted, so leave with the status quo
   * As more users impacted, can reopen discussion
 * Can add some notes to the doc and maybe provide a code snipped for the user to do the conversion themselves (less than 10 LOC?)

**Comment by ejona86** [comment]
Some things not discussed earlier that increased difficulty:
 * "users" are both producers (like this API) and consumers (like LBs) of these maps. That means adding a type as convenience requires consumers to be updated or for gRPC to make a copy
 * In ManagedChannelImplBuilder, grpc is making a copy _today_. However, we want to actually eagerly parse the config so we can throw validation errors at `defaultServiceConfig()` instead of `build()`. At that point, we'd no longer make a copy because the parsing process itself produces a copy of the data it cares about
 * I don't want to depend on BigInteger/BigDecimal

**Comment by ejona86** [comment]
Closing, since few users are impacted. We agree this could be easier, but few users have been impacted and it isn't trivial to resolve. If you are another user impacted and found this, please open another issue and reference this one, so we can more accurately understand the pain this is causing the community and prioritize appropriately.

**Comment by ejona86** [comment]
Oh, realized why I hadn't closed. I wanted to look at making a snippet to do the conversion yourself.
