### ISSUE TITLE
Ensuring resource cleanup before class loader is closed

### ISSUE THREAD

**Issue by asardaes** [grpc/grpc-java#8309]
Hello, I use `grpc-java` (version 1.32.1) inside a Flink application. AFAIK, Flink dynamically loads user jars with different class loaders and attempts to release them once the job finishes. My job only uses clients with a `ManagedChannel` built like this:

```java
NettyChannelBuilder.forAddress(host, port)
         .sslContext(sslContext)
         .build()
```

which is closed at the end:

```java
channel.shutdownNow().awaitTermination(5, TimeUnit.SECONDS)
```

Nevertheless, after my job finishes, I see warnings like this one:

```
2021-07-07T15:31:03,332Z WARN  io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop:414 [grpc-default-worker-ELG-1-3] Unexpected exception in the selector loop. java.lang.NoClassDefFoundError: io/grpc/netty/shaded/io/netty/util/collection/IntObjectHashMap$2
        at io.grpc.netty.shaded.io.netty.util.collection.IntObjectHashMap.values(IntObjectHashMap.java:221)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:428)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.grpc.netty.shaded.io.netty.util.collection.IntObjectHashMap$2
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
        at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 7 common frames omitted
```

Leaving resources running can cause problems with metaspace memory in Flink's JVM if the cluster is used multiple times, so I'd like to know if I should perform additional steps to ensure all netty resources are stopped.

**Comment by ericgribkoff** [comment]
No additional cleanup steps should be necessary, but I'm not at all familiar with Flink, so if there is a specific problem you're encountering caused by the Netty event loop here please reply with more details and we can try to help. You can specify your own `EventLoopGroup` when constructing the channel (https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyChannelBuilder.java#L330) which should give you more control over the resources versus the default (e.g., explicitly invoke its shutdown method) but in general that shouldn't be necessary.

**Comment by asardaes** [comment]
Thanks for the information. I didn't mean to make the question about interaction with Flink, the essence was rather that the grpc stack is started in a class loader that may be discarded without exiting the JVM.

The logs I posted made me think that the event loop kept running even after calling `shutdownNow`. If calling that method should be enough then I can leave it as it is. Do you think I should await termination for longer? I don't think I've seen exceptions indicating that the shutdown didn't complete.

**Comment by ejona86** [comment]
Does that error only happen after you call `server.shutdownNow()`? I'd normally expect ClassNotFoundExceptions _before_ shutting down, as most likely the JAR loading isn't quite right. Normally when unloading class loaders the classes continue operating as normal until fully garbage collected. That is to say I'd normally expect your current error is just a misconfiguration of some sort. However, the calling class and the missing class are in the same JAR, which is just weird. That probably means that Flink changes its ClassLoader behavior at runtime instead of creating/destroying new class loaders over time; I don't think there's much we can do to address that.

It looks like the error is when the Netty thread was shutting down. gRPC delays shutting down the default Netty threads for a second, to avoid cases where they are created+destroyed often. To avoid that, you have to specify all threads and shut them down yourself: eventLoopGroup(), executor(), offloadExecutor().

The cleaning of the ClassLoader should work fine, as long as you shut down any channels/servers... and cycle any user threads that used gRPC, since gRPC uses Netty and ThreadLocals can cause trouble: https://github.com/netty/netty/issues/6891 .

**Comment by asardaes** [comment]
I see. I don't have much control over the threads in this case, but that's a different topic.

I only see the warnings after the job has been completed, so it's not even right after calling `shutdownNow` (my class doesn't appear in the stacktrace). As far as I can tell, the shutdown and await complete successfully. Something I hadn't noticed though: I have a `ThreadLocal<MyServiceBlockingStub>` and each thread initializes the stub with the same `ManagedChannel`. Stubs don't need to be closed or something similar, do they?

**Comment by ejona86** [comment]
Stubs aren't a resource and don't need to be closed. Just make sure to clean up the ManagedChannels.

There's no way for your application to be in that stack trace, even if it triggered the action. I suspect that if you add a `Thread.sleep(1100)` after the await termination the error will go away, as it would work around:

https://github.com/grpc/grpc-java/blob/b9becb5c8e797f202ed0e566e752bd7a91e599e1/core/src/main/java/io/grpc/internal/SharedResourceHolder.java#L43

But my recommendation would still be to provide all the executors, which mostly avoids SharedResourceHolder.

It looks like that particular error is benign, but I'd other occurrences of it may not be (e.g., what if the crash is while we are trying to shutdown other threads; those threads wouldn't be terminated).

**Comment by asardaes** [comment]
All right, thanks, that certainly answers my question. I'll see what works best in my scenario.
