### ISSUE TITLE
Encounter io.grpc.StatusRuntimeException frequently

### ISSUE THREAD

**Issue by rantianhua** [grpc/grpc-java#8470]
### What version of gRPC-Java are you using?

1.37.0

### What is your environment?

Client:
MacOS 10.15.7 
OpenJDK Runtime Environment Corretto-8.292.10.1 (build 1.8.0_292-b10)

Server:
Linux
Use Golang to build the grpc server.

### What did you expect to see?

The grpc connection is stable.

### What did you see instead?

I encountered StatusRuntimeException frequently during the client receives data from the server, And the stacktrace is the following:

```

onError
io.grpc.StatusRuntimeException: INTERNAL: Internal error
Rst Stream
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:500)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:65)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:592)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:508)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:632)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:98)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
``` 

If I tried again after this error occurred, then there was anthor error:

```
onError
io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:500)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:65)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:592)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:508)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:632)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:98)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Steps to reproduce the bug

I encountered the error frequently, with no special reproduction steps.

Server configuration:

```
	server := grpc.NewServer(
		grpc.StreamInterceptor(
			grpc_middleware.ChainStreamServer(
				grpc_recovery.StreamServerInterceptor(grpc_recovery.WithRecoveryHandler(recoveryHandlerFunc)),
				grpc_zap.StreamServerInterceptor(log.Logger(ctx).Logger),
			),
		),
		grpc.ReadBufferSize(1024*1024),
		grpc.KeepaliveParams(keepalive.ServerParameters{
			Time:    time.Hour,
			Timeout: time.Minute,
		}),
		grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
			MinTime:             time.Second * 10,
			PermitWithoutStream: true,
		}),
	)
```

Client configuration:

```
            channel = ManagedChannelBuilder.forAddress("xxx", 8082)
                .keepAliveWithoutCalls(true)
                .usePlaintext()
                .enableRetry()
                .executor(Dispatchers.Default.asExecutor())
                .keepAliveTime(20, TimeUnit.SECONDS)
                .keepAliveTimeout(1, TimeUnit.MINUTES)
                .keepAliveWithoutCalls(true)
                .build()
```

**Comment by ejona86** [comment]
I do not believe the two errors have any relation. Two issues would really be best to discuss, but the first one might be quick so maybe we can manage them both here.

The first one is "the server sent `RST_STREAM(INTERNAL)`". The question is why. The only two places I see `ErrCodeInternal` are if the server's response headers/trailers are too large. Does the server end up logging anything? It seems the error should be exposed to the service by an error return value. The server either needs to use smaller values in the metadata or the client needs to increase the [`maxInboundMetadataSize()`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMetadataSize-int-).

The first error message looks generated from the okhttp transport. Is there a reason you are using okhttp on a desktop instead of Netty?

If keepalive repeatedly fails, then there's something killing TCP connections in your network. You will need to explain more about the networks connecting the client and server. But we can only provide rough guidance and you may need to do your own experimentation. It seems you already have a very aggressive keepalive policy and a very conservative keepalive timeout.

**Comment by rantianhua** [comment]
> Does the server end up logging anything? 

```
helpers/stream.go:52	send compile log	{"error": "rpc error: code = Canceled desc = context canceled", "compile_id": "1630636742746022547"}
2021-09-03T02:47:32.220Z	INFO	zap/server_interceptors.go:61	finished streaming call with code Canceled	{"grpc.start_time": "2021-09-03T02:32:55Z", "system": "grpc", "span.kind": "server", "grpc.service": "messaging.v1.CloudCompileService", "grpc.method": "Messaging", "error": "rpc error: code = Canceled desc = context canceled", "grpc.code": "Canceled", "grpc.time_ms": 876607.8125}
```

>  Is there a reason you are using okhttp on a desktop instead of Netty?

I use grpc in Android Studio Plugin, the Channel Provider is provided according to plugin environment.


> If keepalive repeatedly fails, then there's something killing TCP connections in your network. You will need to explain more about the networks connecting the client and server. 

What can I provide? The connection is the client connects to the grpc server directly through VPN.

**Comment by ejona86** [comment]
> helpers/stream.go:52	send compile log

Hmm.. okay. Those log statement seem unrelated.

> The connection is the client connects to the grpc server directly through VPN.

Ah, okay. The VPN provider may be killing the connection. Might the connection be killed because it is old? Depending on your usage pattern `channel.idleTimeout()` may help reduce the chances the connection from getting too old. But if the problem is actually the connection is too old, then you'll probably have to live with some level of errors.

**Comment by rantianhua** [comment]
The second error is caused by the `keepAliveTimeout` setting. I set the timeout as 1 minute, And I captured the network packages using Wireshark, it showed the delta is almost 1 minute, like the following picture:

<img width="274" alt="Screen Shot 2021-09-04 at 19 05 31" src="https://user-images.githubusercontent.com/7328707/132092301-a118f269-1893-4346-97ff-0376adcfb3f3.png">

So, the second error cause is clear.

The first error `io.grpc.StatusRuntimeException: INTERNAL: Internal error` always occurred during the client receiving stream from the server, and the client didn't send anything in the meaning time. I'm not sure whether this information can prove your conjecture that the connection been old and then been killed by the VPN.

**Comment by rantianhua** [comment]
Another question, if the connection is killed by the VPN, what kind of package(flag=reset or flag==fin) can prove that? I've checked my captured data, there was no package with flag equals to reset, and there was only one package with flag equals to fin which was after a timeout package.

**Comment by rantianhua** [comment]
What's the difference between `channel.idleTimeout()` and `keepAliveTimeout`? As you saw, I've enabled the `keepAlive` as the ping/pong mechanism to keep the connection available. So the connection still can be an IDLE connection event though the `keepAlive` is working?

**Comment by rantianhua** [comment]
I've set `.idleTimeout(5, TimeUnit.DAYS)`, but the first error still exists as before.

**Comment by ejona86** [comment]
> The second error is caused by the keepAliveTimeout setting.

Keepalive is "just the messenger." Keepalive notices the connection died. But it isn't the source of the connection breakage. Without keepalive, the RPC would just hang forever.

> The first error io.grpc.StatusRuntimeException: INTERNAL: Internal error

It seems you didn't read my very first comment where I talk about the first error. You need to either reduce the size of metadata the server is sending or increase the client-side allowed size via maxInboundMetadataSize(). The first error is unrelated to the rest.

> I'm not sure whether this information can prove your conjecture that the connection been old and then been killed by the VPN.

The best way to prove the conjecture is to check the age of the connection when the problem occurs. Since there will be communication at least every 20s (due to keepalive), you should have pretty strong resolution as to when the connection is killed. But I do understand that "connection age" can be a harder thing to track.

> Another question, if the connection is killed by the VPN, what kind of package(flag=reset or flag==fin) can prove that?

It is hard to. Ideally, when dropping one of these mappings (since it is probably using a NAT) the VPN would send a RST for the connection. That packet _could_ be lost, but most of the time would probably work. Additionally, after dropping the mapping it would send RST if a packet was received without a mapping.

Unfortunately, it isn't doing that (there may be some legitimate reasons for that). Instead, it is just dropping packets. So you are blind. You can either see if its behavior is documented by the VPN provider or you infer the behavior via experimentation.

> What's the difference between channel.idleTimeout() and keepAliveTimeout?

Idle timeout closes the connection when the timeout expires. `keepAliveTime` (not timeout) causes activity on the connection when the time expires. See also https://stackoverflow.com/questions/57930529/grpc-connection-use-keepalive-or-idletimeout/57930958#57930958

> .idleTimeout(5, TimeUnit.DAYS)

5 days is a very long time. I'd expect it not to do anything. From past experience, I'd expect the VPN to kill the connection somewhere between 1 minute and 1 hour, but it could be longer. Since idle timeout isn't monitoring the connection age, it will be an imprecise tool for your issue. But if you think there are periods where there may be 1 minute of inactivity, you could consider setting `idleTimeout(1, TimeUnit.MINUTES)` to have gRPC cycle the connection to keep the average connection age lower.

**Comment by rantianhua** [comment]
I increased metadata size to 1MB(default is 8K):
```
.maxInboundMetadataSize(1024 * 1024)
```
But the first error still occurred.

**Comment by ejona86** [comment]
I don't think there is any more we can do to diagnose the Rst Stream. The server knows why it reset and isn't able to inform the client. I suggest creating an issue on the grpc-go repo for the Rst Stream error, cross-linking to this one, and CCing me on it.
