### ISSUE TITLE
Log gRPC request payload as soon as the server receives it

### ISSUE THREAD

**Issue by billydh** [grpc/grpc-java#8481]
My objective is to log the gRPC request payload as soon as the server receives it before doing anything else.

This is how I write my `ServerInterceptor` implementation in an attempt to log the request payload.

```kotlin
import io.grpc.ForwardingServerCallListener
import io.grpc.Metadata
import io.grpc.ServerCall
import io.grpc.ServerCallHandler
import io.grpc.ServerInterceptor

class RequestLoggingInterceptor(private val shouldLogRequest: Boolean) : ServerInterceptor {
    override fun <ReqT : Any, RespT : Any> interceptCall(
        call: ServerCall<ReqT, RespT>,
        headers: Metadata,
        next: ServerCallHandler<ReqT, RespT>
    ): ServerCall.Listener<ReqT> {
        if (!shouldLogRequest) {
            return next.startCall(call, headers)
        }

        val logBuilder = logger.info()
            .event(EVENT)
            .add("method", call.methodDescriptor.fullMethodName)

        logBuilder.log("before forwarding")

        val serverCallListener = next.startCall(call, headers)

        return object : ForwardingServerCallListener.SimpleForwardingServerCallListener<ReqT>(serverCallListener) {
            override fun onMessage(message: ReqT) {
                logBuilder
                    .add("request", message.toString())
                    .log("after forwarding")
                super.onMessage(message)
            }
        }
    }

    companion object {
        private val logger by LoggerCreator
        private const val EVENT = "grpc_request_logging"
    }
}
```

In the normal occasion, when everything is good, both the logging in the body of `interceptCall` and the `onMessage` method gets triggered. However, in the unexpected circumstances, e.g. the DB that the gRPC server communicates to, is down, the `onMessage` method does not get triggered. The request goes into the `val serverCallListener = next.startCall(call, headers)` and results in an exception and finally, returns a response to the caller.

Now, you can see that I only have access to the request payload (or message) inside the `onMessage` method. How can I access the request payload before that, i.e. in the body of `interceptCall`?

Library versions
`com.linecorp.armeria:armeria-grpc:0.96.0`
`io.grpc:grpc-api:1.28.0`

**Comment by ejona86** [comment]
Cross-linking the SO question: https://stackoverflow.com/questions/69082423/grpc-java-log-the-request-payload-as-soon-as-the-server-receives-a-request

If `next.startCall()` throws, that means either an interceptor is throwing (which is bad practice) or the application is throwing. The application can only throw at that point for client-streaming and bidi-streaming RPCs. When `interceptCall`/`startCall` throws, then gRPC will kill the call. You don't get `onMessage()` because the call was killed before the message was processed.

In general, I suggest against throwing, even in the application. Instead, interceptors should call `call.close()` (although there are times) and the application should call `streamObserver.onError()`. However, that wouldn't change the issue: the server application isn't actually receiving the message, so there's nothing to log.

It seems everything is working as expected.

**Comment by dapengzhang0** [comment]
Seems the question is answered. Closing. Can be reopened on further questions.
