### ISSUE TITLE
It is hoped that the Java code generated by grpc can provide an ``interface``

### ISSUE THREAD

**Issue by brucelwl** [grpc/grpc-java#8708]
It is hoped that the Java code generated by grpc can provide an ``interface`` for developers to implement concrete logic rather than an ``abstract class``, because ide can help check whether developers have implemented the ``interface``, but can not check the ``abstract class``

https://www.grpc.io/docs/languages/java/quickstart/#update-the-server

![image](https://user-images.githubusercontent.com/13413715/142154268-7c79e820-33c3-4033-8300-8db2f5c73393.png)

**Comment by dapengzhang0** [comment]
We were supporting Java 7 (and 6) when the first code-generator was released, but interface in Java 7 does not support default method. Suppose we are using interface in generated code, if we add a new method to the proto, the generated interface will have a new method, and therefore the stub implementation will fail compile with the new generated interface because it does not implement the new method. So for backward compatibility, we could not generate interface but only abstract class.

**Comment by brucelwl** [comment]
@dapengzhang0 The purpose of using the interface is to find new methods that are not implemented in time

**Comment by ejona86** [comment]
> The purpose of using the interface is to find new methods that are not implemented in time

We explicitly cannot support that. Adding a new method to a service needs to be backward-compatible, which means it can't break any build. Once we drop Java 7 support we can use `default` methods in interfaces, but that still wouldn't provide you with what you are looking for.

See https://github.com/grpc/grpc-java/issues/1469. This restriction applies to all languages, so there are issues discussing it like https://github.com/grpc/grpc/issues/5371 as well.

**Comment by dapengzhang0** [comment]
Close as the requested feature would break backward-compatibility and we won't support that.

**Comment by ejona86** [comment]
@brucelwl, no. We can't have compilation fail if a method is unimplemented, because adding a new method to an existing service shouldn't cause any build breakages.
