### ISSUE TITLE
Round Robin Load Balancer Retry Logic

### ISSUE THREAD

**Issue by michaelli321** [grpc/grpc-java#8720]
Hello! 

I was playing around with the client side round robin load balancing in Kubernetes. I was making grpc calls to a headless service that had 2 backing pods and I noticed that
- if one pod goes down, ensuing requests are automatically routed to the surviving pod
- if a new pod comes back up, it won't be added to the pool and requests won't make it back to that pod
- if all existing pods go down, and new pods come up, requests are automatically routed to them

This leads me to believe that the round robin load balancer only issues a name resolution request for the ip addresses when it runs out of existing functioning ips. Is this expected behavior or is there something else I need to configure in order to get new pods automatically added to an existing pool?

We are using
```
ManagedChannelBuilder.forTarget(endpoint)
        .defaultLoadBalancingPolicy("round_robin")
        .usePlaintext()
        .build();
```

**Comment by dapengzhang0** [comment]
grpc would repeatedly try to reconnect to the backend address after an exponential backoff, and if gets connected, round robin would use that connection. So the case 

> if a new pod comes back up, it won't be added to the pool and requests won't make it back to that pod

might be caused by the name resolver removed the address of the pod that was down (so the grpc would no longer reconnect), but did not add the address of the new pod back. Would you please check the log for name resolution update?

**Comment by ejona86** [comment]
The problem is that the DnsNameResolver does not continuously poll. It only polls when a) when a connection is closed or b) there are no addresses. You want to use MAX_CONNECTION_AGE from [gRFC A9](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md). The Java API is `NettyServerBuilder.maxConnectionAge()`.

**Comment by michaelli321** [comment]
Ahh I see that makes sense, thanks!
