### ISSUE TITLE
Can we use gRPC to pass a file descriptor between server and client?

### ISSUE THREAD

**Issue by hfutatzhanghb** [grpc/grpc-java#8738]
As title says,  Can we use gRPC to pass a file descriptor between server and client?  I have known it can be done by using Netty EpollDomainSocketChannel, but i don't whether gRPC has implemented it or not.

**Comment by YifeiZhuang** [comment]
No, we do not do domain sockets, we choose epoll or nio for the netty transport depending on if the environments support it.
In addition to netty, we have in-process transport when a server is in the same process as the client.

**Comment by hfutatzhanghb** [comment]
thanks a lot.&nbsp; That means we haven't suppoted it yet ？ All right



---Original---
From: ***@***.***&gt;
Date: Sat, Dec 4, 2021 08:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [grpc/grpc-java] Can we use gRPC to pass a file descriptor between server and client? (Issue #8738)




 
No, we do not do domain sockets, we choose epoll or nio for the netty transport depending on if the environments support it.
 In addition to netty, we have in-process transport when a server is in the same process as the client.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ejona86** [comment]
Sending fds is tricky because you can't send them in-band with the rest of the HTTP/2 bytes. And looking at EpollDomainSocketChannel, we'd either need two connections (one to pass fds, one to pass bytes) or maybe have to figure out a way to mode switch (not easy). There is no planned support for FD passing.

We can do FD passing for on Android Binder, so we do know how to pass FDs in our API, but it looks like it'd take hackery to get it working with HTTP/2. Honestly, it is probably no different architecturally for you to implement it yourself using EpollDomainSocketChannel directly for the FD passing while letting gRPC handle the RPC management.

**Comment by ejona86** [comment]
Seems like this is resolved as best it can be. If not, comment, and it can be reopened.
