### ISSUE TITLE
Design Auth to combine normal credentials with TLS creds

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#874]
There is a want to guarantee that credentials are treated as a whole to guarantee invariants. For example, it is not appropriate to send a JWT over an unencrypted connection.

There may be other constraints that are missing, but it is not fully clear yet. I'll update the issue as more is known.

**Comment by louiscryan** [comment]
Given that (a) Channels are secure by default and that (b) we ultimately need the flexibility to support sending JWTs over an unencrypted connection because there are deployment scenarios where that is appropriate I think the existing low-level Channel & Server construction APIs are secure-enough by default. 

We do expect that there are vendor-specific requirements that may be more strict than what the raw GRPC library provides. To achieve this effect we expect vendors to provide their own initialization mechanisms which ensure that their requirements are met.

As a result I don't think we have a breaking API change here. We may at some point need to provide explicit indication on a Call that it is being sent on a secure transport so that interceptors can make appropriate decisions. That API should be additive however.

**Comment by ejona86** [comment]
This was fixed in #4486 (rolled forward in #4524). We have CallCredentials that are provided with the transport-specific security level.
