### ISSUE TITLE
java.lang.NoClassDefFoundError: io/grpc/BindableService

### ISSUE THREAD

**Issue by hy0619** [grpc/grpc-java#8741]
I used grpc for helloworld , but when I run grpc server  ,error occured : 
![image](https://user-images.githubusercontent.com/20480464/144876407-9102d184-afa4-420c-8be9-555c0c5a98b8.png)
1.server codes : 
![image](https://user-images.githubusercontent.com/20480464/144876557-ae03166c-dd1f-4b08-958a-bf36817a47fe.png)
2.pom files : 
![image](https://user-images.githubusercontent.com/20480464/144876626-ef42787c-76f4-4db3-a0f1-f04a114b0727.png)
![image](https://user-images.githubusercontent.com/20480464/144876665-9449bf09-06f0-4699-9ac0-411381bef0ad.png)
![image](https://user-images.githubusercontent.com/20480464/144876697-f27ea0f0-8b89-4f04-9b82-579a7d1bf9e7.png)
![image](https://user-images.githubusercontent.com/20480464/144876725-64debe63-7a2b-46ba-b1fd-bfc79f8a4656.png)
and how can i study grpc  , I first use this framework !

**Comment by ejona86** [comment]
BindableService is part of grpc-api. grpc-api is a transitive dependency of multiple of the dependencies you have, and BindableService has been present in grpc-api for a long time. So I'd be a bit more surprised if this is a dependency issue.

I expect the problem is how you are executing the application. It is probably missing grpc-api.jar in the classpath. Can you verify that grpc-api is part of the command line used when executing java?
