### ISSUE TITLE
Capability to configure both default `CallCredentials` and custom `SslContext` on netty `ManagedChannel`

### ISSUE THREAD

**Issue by pete-gillin-privitar** [grpc/grpc-java#8772]
### The problem

I would like to create a netty `ManagedChannel` which has both a default `CallCredentials` and a custom `SslContext`.

I can do the former with
```java
return NettyChannelBuilder.forTarget(
    target,
    CompositeChannelCredentials.create(TlsChannelCredentials.create(), callCredentials))
  .build();
```
and I can do the latter with
```java
return NettyChannelBuilder.forTarget(target)
  .sslContext(sslContext)
  .build();
```
but I can't see a way to do both at once.

### Solution ideas

I can see two possible API additions which would achieve this.
 1. Make it possible to configure an `SslContext` on a `ChannelCredentials` instance. I guess this couldn't be done on `TlsChannelCredentials` since that's in core and can't depend on the netty `SslContext`, so it would have to be a netty-specific `ChannelCredentials` implementation. Then I could do something like
 ```java
return NettyChannelBuilder.forTarget(
    target,
    CompositeChannelCredentials.create(NettyTlsChannelCredentials.create().withSslContext(sslContext), callCredentials))
  .build();
```
 2. Make it possible to configure a default `CallCredentials` on a `NettyChannelBuilder` without a `ChannelCredentials`. Then I could do something like
```java
return NettyChannelBuilder.forTarget(target)
  .defaultCallCredentials(callCredentials)
  .sslContext(sslContext)
  .build();
```

From what I've seen of the source code, 2. would probably be the easier change to make, but might fit in less well with the direction you want to take the API in.

### My current workaround

The workaround we're intending to use right now is to create a channel which has the correct `SslContext` but no default `CallCredentials`, and instead configure the `CallCredentials` directly on every stub I create. To make this easier, we'll wrap the `ManagedChannel` and the `CallCredentials` together into an object of our own so that we can pass them around together. Something like
```java
return GrpcChannelWithCallCredentials.create(
  NettyChannelBuilder.forTarget(target)
    .sslContext(sslContext)
    .build(),
  callCredentials);
```
where `GrpcChannelWithCallCredentials` is our wrapper class. This is a bit ugly, and involves a change in every bit of code where we create a stub, rather than being able to do it once where we create the channel.

**Comment by sergiitk** [comment]
Have you seen [`NettySslContextChannelCredentials`](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/NettySslContextChannelCredentials.html)? It's very similar to what you proposed in solution (1). 

```java
return NettyChannelBuilder.forTarget(
   target,
   NettySslContextChannelCredentials.create(sslContext), callCredentials))
 .build();
```

We also took a note to update the Java [Authentication docs](https://grpc.io/docs/guides/auth/#java).

**Comment by pete-gillin-privitar** [comment]
Thanks, that's exactly what I wanted!

I guess the only issue here is the lack of discoverability of this class. If you're tracking the docs update elsewhere, I'm happy to close this.

**Comment by sergiitk** [comment]
@ejona86 do you have a ticket to update Java docs, or would you like to keep this one as a reminder?

**Comment by ejona86** [comment]
I don't think we need _much_ discoverability for this class. TlsChannelCredentials should be a replacement for the vast majority of users, and is a stable API where this one is not. I guess we could put comments on methods like `NettyChannelBuilder.sslContext()` that the class is a replacement. But without being `@Deprecated` that seems a bit strange. I guess we could say "if you need CallCreds too..." and reference it or "this has been ported to the ChannelCredential API via ...". Today I think I'd just generally expect someone to [look through the netty package](https://grpc.github.io/grpc-java/javadoc/io/grpc/netty/package-summary.html) to find it.

Unfortunately it doesn't show up for `ChannelCredentials` "Direct Known Subclasses" because it isn't a credential itself. And that's semi-common for credentials. That just leaves the ["uses of" documentation](https://grpc.github.io/grpc-java/javadoc/io/grpc/class-use/ChannelCredentials.html), which I don't imagine many people think about (or are even aware exists).

There's really no documentation yet that encourages using the ChannelCredentials API over the earlier API. Once we start sprinkling that around this would also become more obvious.

**Comment by sergiitk** [comment]
Documentation update is merged, so closing. If more information is provided or there's a follow-up question, comment and we can reopen.
