### ISSUE TITLE
How to selectively require Client Certificate for a few services but not require it for other services?

### ISSUE THREAD

**Issue by umapriyadarsi** [grpc/grpc-java#8792]
In TLS mutual authentication, I am aware that ClientAuth has three modes:

1. None - Server does not request for any client certificate
2. Optional - Server requests for a client certificate but whether it is valid or not server will allow it pass through
3. Require - Client must provide a valid certificate

But say I have two grpc service definitions. For the first one I do not want any authentication and for the next one I do want to have the strict require authentication.How to do this? 

Should the server then be configured for 'Optional' mode and then an interceptor would be required to validate the client certificate based on the service being access by the client? If yes, then this does seem comparatively heavier, and also leaves more risk for error.

(Perhaps the previous paragraph make me sound like a lazy person and as outsourcing my security work to be done by someone else :p , but I am just trying to find out the best possible way to achieve this functionality and re-use existing frameworks instead of re-doing it)

**Comment by sanjaypujare** [comment]
> In TLS mutual authentication, I am aware that ClientAuth has three modes:
> 
> 1. None - Server does not request for any client certificate
> 2. Optional - Server requests for a client certificate but whether it is valid or not server will allow it pass through

The meaning of Optional is this: The client may or may not send its certificate. Client without a certificate is permitted but if the client does present a certificate then the server will/should check it.

> 3. Require - Client must provide a valid certificate
> 
> But say I have two grpc service definitions. For the first one I do not want any authentication and for the next one I do want to have the strict require authentication.How to do this?

The best thing to do is to bind these services to different ports so you can configure TLS/mTLS for each of those services as per your logic. Because TLS/mTLS auth happens once at connection setup and within that connection you can invoke different services and having different client auth logic based on a service doesn't make sense.

> 
> Should the server then be configured for 'Optional' mode and then an interceptor would be required to validate the client certificate based on the service being access by the client? If yes, then this does seem comparatively heavier, and also leaves more risk for error.

Yes, this is possible and in the interceptor you will have to then check the connection's SSL attributes to enforce client auth.

**Comment by umapriyadarsi** [comment]
> The best thing to do is to bind these services to different ports so you can configure TLS/mTLS for each of those services as per your logic. 

Thanks @sanjaypujare ... I wound up doing the same. Glad to get confirmation from you as well.

I will now close this question, as you have answered my question.
