### ISSUE TITLE
Revert API change in {ManageChannel, Server}Provider API

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#8887]
Although `ManageChannelProvider` and `ServerProvider` are `@Internal`, because they are not apparently internal with `Internal` prefix in name the API change in 881f747b7eaeffe2d9d0a2c461e1cd4ae636e717 and bd156f98d69d7dadf2991903b006cb762c4c18e1 may still impact existing users.

cc @sanjaypujare  @ejona86

**Comment by ejona86** [comment]
It's more: Let's not change these APIs for a known-temporary hack (even if it didn't cause breakage), especially since history has proven we'll likely forget to revert the changes. (Also, here we have to revert all the implementations as well, not just the abstract class.) These same needs can be met with an `Internal*` accessor which doesn't impact any other code and is much easier to learn when unused.
