### ISSUE TITLE
Dynamically apply metadata headers in dependency client calls

### ISSUE THREAD

**Issue by aphinier** [grpc/grpc-java#8911]
Hi team!

I'm working on authentication between multiple service, basically the logic is:
user A -> Service B -> Service C -> Service D
user A calls Service B
Service B calls Service C
Service C calls Service D

Both Service C and Service D are GRPC services.

I'm the owner of Service C. I got the auth Context of user A as input parameter from Service B, and I need to verify the permission of User A in service D and act correspondingly (we have a service D client in Service C). The strategy we want to use is to get the credential we want from the auth Context parameter and dynamically assign the credential as a header of request to Service D. For some reason we cannot get this auth Context from Metadata so we're not able to use ClientInterceptor to do this and dynamically apply this header in every client call to Service D is the only way.

Could you help on how we can make it work?

```java
public class ServiceCOrchestrator {
    @Inject
    public ServiceCOrchestrator() {
        ...
    }

    // this is API of service C
    public Item createItem(final AuthContect authContext,
                                           final Item input) {
            ...
            // Call to Service D, where we want to apply the auth header dynamically
            final Catalog catalog = serviceDClient.getCatalog();
            ...
            return item;
        }
    }
```

**Comment by ejona86** [comment]
I was following along until "For some reason we cannot get this auth Context from Metadata so we're not able to use ClientInterceptor to do this and dynamically apply this header in every client call to Service D is the only way."

You also pasted some class regarding Service C, but that has nothing gRPC in it. So I don't really know what to make of it.

If AuthContext is explicitly within the request message, then it is out of gRPC's hands; you'll need to wire something up yourself.

I'll mention how I've seen this sort of propagation happen in the past. The auth context is passed in Metadata (to both C and D). A ServerInterceptor validates the context and puts it in io.grpc.Context. A ClientInterceptor, with possible configuration passed via `stub.withOption()`, copies it from io.grpc.Context to the metadata.

**Comment by aphinier** [comment]
> You also pasted some class regarding Service C, but that has nothing gRPC in it. So I don't really know what to make of it. 
createItem() is the API of Service C and Service C is a GRPC service. 
For serviceDClient, Service D's Stub is wrapped in it.
Listed some detail of our code hope it's helpful.

Service D Client Module(in Service C's repo):
`
public class ServiceDModule extends AbstractModule {

    @Override
    protected void configure() {
        bind(ServiceDClient.class).asEagerSingleton();
    }

    @Inject
    @Provides
    @Singleton
    ServiceDGrpc.ServiceDBlockingStub getServiceDGrpcStub() {
         final Channel channel =
                    NettyChannelBuilder.forAddress()
                            .overrideAuthority()
                            .build();

            return ServiceDGrpc.newBlockingStub(channel)
                    .withInterceptors(...);
        }
    }
}
`

Service C Module:
`
public class ServiceDModule extends AbstractModule {

    @Override
    protected void configure() {
        install(new ServiceDModule());
    }
}
`

Service D client wrapper (within Service C repo):
`
public class DerviceClient {

    private final ServiceDGrpc.ServiceDBlockingStub stub;

    @Inject
    public ProductCatalogServiceClient(@NonNull final ProductCatalogServiceGrpc.ProductCatalogServiceBlockingStub stub) {
        this.stub = stub;
    }

    public Catalog getCatalog(final CatalogId catalogId) {
        final ReadCatalogRequest request = ReadCatalogRequest.newBuilder().setCatalogId(catalogId.getValue()).build();
        final ReadCatalogsResponse response = stub.readCatalog(request);
       ....
        return response.getCatalog();
}
`

**Comment by ejona86** [comment]
Given you have custom wrappers around your gRPC services, I don't know how you're hoping gRPC could help. I mentioned already you can use io.grpc.Context, which avoids needing to plumb a value into every API, but it does mean being semi-gRPC-aware to make sure to propagate the Context when offloading work to other threads. I don't know what you hope could happen other than a magic ThreadLocal like Context.

**Comment by aphinier** [comment]
Thanks! I think I misunderstood the thing you talked about, in this case we have couple of ways to do it:
1. use stub.withOption(AuthContextKey, value).readCatalog() to pass the authcontext, not sure if we need a ClientInterceptor in this case, refer to https://github.com/grpc/grpc-java/issues/1800
2. just before making the api call create a new interceptor and set it, like stub.withInterceptors(new AuthContextClientInterceptor(authContext)).readCatalog
3. Have a headerWriter to write the authContext key-value pair to Metadata, and have a ClientInterceptor to read the authContext from Metadata, like:
`@Override
                            public void onHeaders(Metadata headers) {
                                getInterceptorContext().processResponse(headers);
                                super.onHeaders(headers);
                            }`

Which one do you think is the best way?

**Comment by ejona86** [comment]
> use stub.withOption(AuthContextKey, value).readCatalog() to pass the authcontext, not sure if we need a ClientInterceptor in this case

Yes. You'd use an interceptor to copy the option to Metadata.

> Have a headerWriter to write the authContext key-value pair to Metadata, and have a ClientInterceptor to read the authContext from Metadata, like:

I'm not sure what a "headerWriter" is, but that code looks like it is _receiving_ a header from the server's response. That's quite a different use-case, so I doubt this approach applies.

You also have the option of using `CallCredentials`.

------

Most of these options are "okay" and just serve slightly different use cases better than others. An important difference is the scale this is needed; if small-scale you don't care as much how ugly but if used heavily you want easy to use and easy to detect when misused. All of them would use Metadata though; there are very few cases that would put this sort of information in the request.

There's three axes. First, the mechanism for attaching the metadata (don't dwell on this; it appears it doesn't matter much for you):
1. ClientInterceptor. Can see/modify all interactions between application and library. Frequently exists just to add some piece of metadata.
2. CallCredentials. More restrained than interceptor, but given some conveniences and extra power. Is easy to make asynchronous, where an asynchronous interceptor is involved. Also is told exactly which connection the RPC will be sent on, allowing it to verify its security requirements, like "the token must be encrypted using TLS."

Second, there's where it is installed:
1. Both can be applied per-call (`stub.withInterceptors()`/`withCallCredentials()`). This is ideal when you need per-RPC configuration, and you're okay with a noop if it isn't done.
2. Both can be applied when creating the channel (`builder.intercept()`/`CompositeChannelCredentials`). This is ideal when you want the processing for all calls, independent of what they are
3. Interceptors can wrap a Channel (`ClientInterceptors.intercept()`). This is ideal when you want the processing for a part of your application, but not all of it. If you want this for CallCredentials, though, you can use an interceptor to add the CallCredentials

Third, there is the mechanism for additional configuration:
1. None/just constructor. This works well for fixed values or if the interceptor/credential should do something _only_ if a value is provided
2. Explicit call option. This is great when the place doing the RPC knows what options to set. Without this option, the interceptor will fallback to some default behavior, which could even decide to fail the RPC. This happens to not be available for CallCredentials, but may be just because it hasn't been needed
3. Implicit Context. This is useful when you want to plumb information through APIs and do things automatically/implicitly. For example, tracing information is propagated through this. Context works best when need to modify the state one place, and then do the RPC someplace else

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
