### ISSUE TITLE
Netty Shaded high cpu utilization

### ISSUE THREAD

**Issue by anujbansal16** [grpc/grpc-java#8935]
Hello,

In one of the service while using the netty-shaded (ManagedChannel)  to build the channel we have observed a high cpu utilisation.
While running the jprofiler on the service we have found that epollEventLoop(epollWaitNoTimerChange) is consuming most of the cpu (in seconds).
The problem was resolved when we moved to netty library (NettyChannelBuilder) instead of netty-shaded (ManagedChannelBuilder).

Netty shaded version used that caused high cpu: 1.39.0
`def grpcVersion = '1.39.0'`
`implementation "io.grpc:grpc-netty-shaded:${grpcVersion}"`

netty (we use this to replace netty shaded)
`def grpcVersion = '1.41.0'`
`implementation "io.grpc:grpc-netty:${grpcVersion}"`

JVM version : `openjdk:8u141-jre`
OS version (e.g. uname -a): Linux 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/12298554/154951558-09cc1f24-a55d-4e0f-8537-331946fe6522.png)

Can anyone please help in clarifying this issue?

**Comment by ejona86** [comment]
I don't think that method would be consuming CPU often. That code calls into JNI code to park the thread on epoll, so I would assume the profiler just doesn't understand how to deal with that correctly. The code _is_ on the stack, but it isn't consuming CPU.

In general, when comparing shaded with non-shaded, you should really use the same version of gRPC. If you don't see a problem with grpc-netty, try grpc-netty-shaded with the same version. But what I really expect is happening is when using grpc-netty (non-shaded) you end up using NIO instead of Epoll because you don't depend the shared library in io.netty:netty-transport-native-epoll:linux-x86_64. I'd suggest reproducing with grpc-netty (non-shaded) by adding a dependency on native-epoll.

**Comment by ejona86** [comment]
I expect epollEventLoop is a red herring. I'd be interested to know how some of the tests I mentioned turned out, but there doesn't seem any more we can do on this issue with the current report. More information can be provided and then we can reopen.
