### ISSUE TITLE
Add an option to skip adding `@Generated` on the java stubs

### ISSUE THREAD

**Issue by michalszynkiewicz** [grpc/grpc-java#9153]
### Is your feature request related to a problem?
The `@Generated` annotation used in the generated java stubs comes from the `javax.annotation` package.
This annotation is moved to `jakarta.annotation` package with the Jakarta transition.

### Describe the solution you'd like
A parameter to disable adding the `@Generated` annotation for frameworks that have switched to Jakarta would help.

### Describe alternatives you've considered
Other options:
1. Remove the `@Generated` annotation completely, possibly replacing it with a comment
2. Add a switch to use the `@jakarta.annotation.Generated` instead

### Additional context
We encountered this issue while trying to switch Quarkus to Jakarta

**Comment by sergiitk** [comment]
At the moment, we're still targeting Java 8: https://github.com/grpc/grpc-java/blob/af56f1fc7dbca09cb919c45affc87a30ac485fe5/build.gradle#L257-L259

That said, could you please provide the details for the issue you encountered while trying to switch Quarkus to Jakarta?

**Comment by mkouba** [comment]
> That said, could you please provide the details for the issue you encountered while trying to switch Quarkus to Jakarta?

The annotation in question (`javax.annotation.Generated`) comes from the Common Annotations spec, primarily used within Java EE. Java EE was renamed to Jakarta EE after the transition to the Eclipse Foundation and so was the package `javax` renamed to `jakarta`. Common Annotations is now [Jakarta Annotations](https://jakarta.ee/specifications/annotations/) and the package name is now `jakarta.annotation`. The `javax` to `jakarta` happened in Jakarta EE 9. So basically any stack/platform that is built on Jakarta EE 9+ is not able to use the generated sources any more.

We'd like to introduce a config option to use the `@jakarta.annotation.Generated` instead of `@javax.annotation.Generated` in generated sources.

**Comment by ejona86** [comment]
> So basically any stack/platform that is built on Jakarta EE 9+ is not able to use the generated sources any more.

What? You can do what non-J2EE Java 9+ users have been doing: depend on a library that provides it. Our README recommends a compile-time dependency on `org.apache.tomcat:annotations-api:6.0.53`. How does that fail?

**Comment by mkouba** [comment]
> > So basically any stack/platform that is built on Jakarta EE 9+ is not able to use the generated sources any more.
> 
> What? You can do what non-J2EE Java 9+ users have been doing: depend on a library that provides it. Our README recommends a compile-time dependency on `org.apache.tomcat:annotations-api:6.0.53`. How does that fail?

Well, it's definitely not a good idea to depend on multiple versions of the same API...

**Comment by ejona86** [comment]
> Well, it's definitely not a good idea to depend on multiple versions of the same API...

But they are different APIs...

**Comment by mkouba** [comment]
> > Well, it's definitely not a good idea to depend on multiple versions of the same API...
> 
> But they are different APIs...

Not really. It's the same API but as explained in https://github.com/grpc/grpc-java/issues/9153#issuecomment-1123226082 the package was renamed from `javax.annotation` to `jakarta.annotation`.

**Comment by ejona86** [comment]
Different packages == different APIs. There's no conflict between the Java classes. I understand that one is a clone of the other and there's the new great thing. But because they are different packages they can coexist. And coexisting is the expectation when you rename the package like that. `Generated` is from 2006 and `javax.servlet` is from 1996; decades of code isn't suddenly invalid.

It can understand how it might "make you feel better" or "be cleaner." But I've not seen an actual _problem_ described yet.

**Comment by michalszynkiewicz** [comment]
Generally for Quarkus (and I bet not only) it hurts us if we have many dependencies.
This is specifically troublesome for us when we convert our upstream projects to products.

I'd be happy to create a pull request to add such an option but would like to hear first for maintainers which solution is preferred, the option to switch to jakarta or the option to remove the annotation. If you find it at all possible to get such a thing in :)

**Comment by mkouba** [comment]
> Different packages == different APIs. There's no conflict between the Java classes. I understand that one is a clone of the other and there's the new great thing. But because they are different packages they can coexist. 

Well, technically these are different classes but semantically it's a new version of the API of the same specification.

> And coexisting is the expectation when you rename the package like that. `Generated` is from 2006 and `javax.servlet` is from 1996; decades of code isn't suddenly invalid.

Of course, it's not invalid. But it cannot be used with both the old version and the new version of the implementation. New versions of the implementations usually switch to the new namespace and let the tooling do some magic (transform the sources automatically or rewrite the bytecode on the fly).

> It can understand how it might "make you feel better" or "be cleaner." But I've not seen an actual _problem_ described yet.

No, it's not only about being "cleaner". It would be very confusing for users too. Imagine you have two versions of `@Generated` annotation on the class path. Which one would you choose?

Anyway, as Michal suggested above it can be solved with a simple option ;-).

**Comment by mkouba** [comment]
> If you already have a dependency on both, then it doesn't matter which you choose. If it does matter, then we can't be willy-nilly replacing one with the other.

It does matter a lot because the libraries you use may support only one of them, i.e. you would need to use both `@javax.annotation.PostConstruct` and `@jakarta.annotation.PostConstruct` to make sure it all works. In other words, you don't want to have dependency on both and then randomly choose classes.

> `javax.annotation.Generated` was part of the JDK when gRPC started using it. The fact it is a separate dependency now is unfortunate. I have no want nor desire to depend on jakarta for something like this.

Yes, it's unfortunate and the whole jakarta package rename thing is even worse :-(

> I've been looking at replacing the Generated annotation for years, but it will take some work to understand how various tools (linters, static analyzers, IDEs) make use of it. I think many of them may just key off a "*.Generated" annotation because of the changes to the JDK, in which case we could add an annotation in io.grpc.stub. We'd need to figure out what retention is appropriate and confirm the current GrpcGenerated doesn't suffice.

+1
