### ISSUE TITLE
protoc-gen-grpc-java binary for ppc64le

### ISSUE THREAD

**Issue by sumitd2** [grpc/grpc-java#9274]
### Is your feature request related to a problem?

protoc-gen-grpc-java binary for ppc64le doesnt exist here: https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.47.0/

### Describe the solution you'd like

protoc-gen-grpc-java binary for ppc64le added here or in a subsequent release: https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.47.0/

### Describe alternatives you've considered

None

### Additional context

Hi team, 
We tried to build and test the _protoc-gen-grpc-java_ binary on ppc64le using the following commands, and were successful:
```
curl -LO https://github.com/grpc/grpc-java/archive/refs/tags/v1.47.0.tar.gz
tar xzf v1.47.0.tar.gz
cd grpc-java-1.47.0/compiler
../gradlew java_pluginExecutable -PskipAndroid=true
../gradlew test  -PskipAndroid=true

```
We noticed that it doesnt exist here:
https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.47.0/

Is it possible to include it in the maven repo in 1.47.0 or a subsequent release? Thank you.

**Comment by ejona86** [comment]
We don't have PPC machines and don't test on it. `compiler/build.gradle` was already updated to compile on the platform (a while back, in #2325), which allowed you to build from source without further changes.

We don't directly support ppcle, but would be willing to accept a community contribution for the platform using cross-compilation. It'd be similar to #6441, but easier because some of those changes were for general-purpose cross-compilation and not tied to aarch64. Looks like the debian package for ppc cross-compilation is g++-10-powerpc64-linux-gnu.

**Comment by sumitd2** [comment]
@ejona86 I have raised the PR. https://github.com/grpc/grpc-java/pull/9284
