### ISSUE TITLE
Provide a way to configure reconnection backoff parameters.

### ISSUE THREAD

**Issue by jcferretti** [grpc/grpc-java#9353]
### Is your feature request related to a problem?

There is no way to configure [reconnection backoff](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md) parameters (eg, INITIAL_BACKOFF, MULTIPLIER, MAX_BACKOFF) from Java.

### Describe the solution you'd like

A way to configure reconnection backoff parameters.

### Describe alternatives you've considered

I haven't found an alternative to create a policy with different parameters that applies to channel reconnection.

### Additional context

Service configuration settings can be provided for a channel builder via calling `defaultServiceConfig`; the service configuration may include a retryPolicy definition.  This policy does not apply on subchannel reconnection; as far as I can tell, it would only apply for UNAVAILABLE status coming from the server itself, and not for UNAVAILABLE coming from when the server is down.  

It is possible (necessary) to set "waitForReady" in the service configuration setting to prevent an RPC from failing right away if the channel is not READY, and instead wait for it to be reconnected [EDIT: this is not strictly accurate, I should have said "if the channel is in TRANSIENT_FAILURE"; RPCs will not fail right away for IDLE and CONNECTING states; thanks to Eric for pointing that out in a comment below].

That, together with a deadline (either specific to the RPC call point in the code or given as a timeout in the service config for the method) can be used, but overall the exponential backoff parameters for the retry policy for reconnections can't be configured, while the retry policy for `UNAVAILABLE` answers from the server can be configured in the service config itself.  My understanding of that being the case comes from:

* The code in `ManagedChannelImplBuilder` creates a new instance of an `ExponentialBackoffPolicy.Provider`
https://github.com/grpc/grpc-java/blob/3500243f4320fcde1d567184b822c98de017498e/core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java#L627
* `ExponentialBackoffPolicy` has default values matching the values documented in `connection-backoff.md`.
* While the `ExponentialBackoffPolicy` has setter methods, they are package private and they are not used from anywhere in the code.

**Comment by ejona86** [comment]
Can you please describe why you need to configure the connection exponential backoff (how is it triggering and what harm is it causing) and what values you'd like to use (what do you wish the constants were)?

> as far as I can tell, it would only apply for UNAVAILABLE status coming from the server itself, and not for UNAVAILABLE coming from when the server is down

It applies to both, but it only applies to _RPCs_, not connections.

> It is possible (necessary) to set "waitForReady" in the service configuration setting to prevent an RPC from failing right away if the channel is not READY, and instead wait for it to be reconnected

This is imprecisely said. RPCs do not fail if the channel is IDLE or CONNECTING. waitForReady only changes the behavior if the channel is TRANSIENT_FAILURE. But yes, if you are having connection failures, the channel will be TRANSIENT_FAILURE and waitForReady tells gRPC that you are willing to wait for the connection to come online.

**Comment by jcferretti** [comment]
I am a bit confused.  The reconnection exponential backoff is triggering because the server went down, and the client triggered the mechanism intended for trying to reconnect.  These parameters can be set from C++ and python, but not from Java, presumably my use case is similar to whatever motivated the ability to use parameters other than the default ones in that case.  In any case, and to specifically answer  your question: not any combination of deadline/timeout and reconnection max backoff makes sense; many combination would be sub-optimal (eg, if the deadline allows for X more seconds of retrying, but the next retry according to the hardcoded exponential backoff parameters is in Y seconds with Y > X).

> It applies to both, but it only applies to RPCs, not connections.
I am confused again.  Can you please elaborate what you mean here?  That full sentence reads as a contradiction to me.  Do you mean it applies to both cases of server down (TRANSIENT_FAILURE I presume, in the channel?) and server rejecting the RPC?
If so, that was not the behavior I saw and the behavior that you seemed to confirm in the "this is imprecisely said" paragraph.  If the server is down and the channel is in TRANSIENT_FAILURE and the reconnection exponential backoff is running, there are two independent things working in mechanical non-sympathy, on one hand the RPC retry policy form the service configuration will decide when to try again, and that seemed to me to be completely independent of when the reconnection policy (hardcoded) will try again.    Is this the behavior?

In more general terms, I do not understand why we have a very detailed way to configure parameters for retry policies from RPCs and we have a hardcoded reconnection policy for channels.  Obviously there are assumptions here about use cases, but it seems this is a world where server rejecting the RPC is more common than server bouncing, so there is more interest in configuring that, while leaving reconnection policy hardcoded is fine?

**Comment by ejona86** [comment]
> These parameters can be set from C++ and python, but not from Java, presumably my use case is similar to whatever motivated the ability to use parameters other than the default ones in those cases.

You're assuming there was a situation that motivated that. I expect it was exposed for some "unit" test code to test the reconnect behavior and it was public because they made lots of their internals public back in the old days.

> not any combination of deadline/timeout and reconnection max backoff makes sense

Do you mean there's no default value that makes sense, or that even in C++ and Python you can't configure something that you're happy with?

> In particular, a max backoff of 2 minutes in our setting is too high, we would like this to be in the order of 10 seconds given our current environment restrictions

What is the situation such that it would actually expect the server to come online in 10 seconds if it has already been down for ~5 minutes (the amount of time it takes to reach 2 minutes) and this service is important enough to the client that the client _needs_ to reconnect within 10 seconds of it coming online yet there's only a single server?

Recognize that in some cases it may be a minute for each connection attempt to fail.

> Do you mean it applies to both cases of server down (TRANSIENT_FAILURE I presume, in the channel?) and server rejecting the RPC?

Yes. RPC retries is based on the status, independent of the source/cause.

> In more general terms, I do not understand why we have a very detailed way to configure parameters for retry policies from RPCs and we have a hardcoded reconnection policy for channels.

Because most people don't understand networks and how they respond to failure. This is the main reason I haven't just added it, because people don't know when they _shouldn't_ be touching these nobs.

If the RPCs exceed the capacity of the network then you get lost packets and packet resending with exponential backoff and slower send rate. If too many new connections are hammering a server such that the packets are lost, then you have exponential backoff while waiting for the connect(). TCP handles both of those cases. For connecting, the OS will do exponential backoff with approximately an initial backoff of 1s, a multiplier of 2x, and max attempts of 6.

It isn't clear that just changing gRPC actually gets you want you want, as those still (relatively high) delays would still be in the system via the OS. If someone is aware of that and the purpose for the high values and will be configuring their OS with different settings, then I can have a very concrete conversation about what to do to satisfy those needs.

2 minutes sounds like a long time. And it is. But it is actually necessary when some networks fall over. As the backoff increases it gives the connect() more time to complete. I expect at some point there will be a redesign that doesn't use connect() timeouts at all and relies more on the exponential backoff in the OS (e.g., if we begin doing Happy Eyeballs). But with the current design multiple things are combined together (for simplicity).

**Comment by jcferretti** [comment]
> Because most people don't understand networks and how they respond to failure. This is the main reason I haven't just added it, because people don't know when they shouldn't be touching these nobs.

Well, that pretty much shuts down the conversation for me.

I spent two days of my life searching documentation, browsing stack overflow answers and contradicting blog posts, reading source code and playing with a debugger and simple examples to reverse engineer the behavior that I described in the description of this issue (and that you helped specify more exactly regarding the actual channel status and when an RPC will fail without waitForReady, thanks).  Perhaps the issue description will help other people find this information in one place and avoid having to put it together like I had to, so having discussed up to this point is not all a waste your and my time.

**Comment by ejona86** [comment]
> Well, that pretty much shuts down the conversation for me.

It really doesn't have to be. You have a problem and you have a solution in mind. You asked why don't we have that solution. I'm responded to that. But that doesn't mean your problem is invalid. I do want to understand what your problem is, to provide solutions. (It might turn out that solution is appropriate for your case, but often there's another option.)

> playing with a debugger and simple examples to reverse engineer the behavior

So is your problem mainly the "random" interaction between RPC retries and reconnects?

The main thing I can say is that retries != reconnects. They are completely separate. I agree it would be very confusing to try hard to figure out how they are connected because they aren't. We use the words "retry" for RPCs and "reconnect" for connections, but it is common for people to use them differently.

The main thing I don't understand is why you are concerned with failed connections. It doesn't sound like you are on Android. What sort of events are causing failed connections such that you started wandering down this road to begin with? I feel like there is still missing context.
