### ISSUE TITLE
how ro restart a bi-directional stream after channel re-connection

### ISSUE THREAD

**Issue by XiaoWeiKIN** [grpc/grpc-java#9384]
hi, I am using a bi-directional stream, similar to the following architecture.
![image](https://user-images.githubusercontent.com/20626345/179357042-26daccd5-91eb-4556-b985-6b982710ee42.png)

`duplexer` is a  bi-directional stream. `control-plane` sends requests to `client` via  bi-directional stream,  and the client sends a response. but cleint does not initiative  send data to `control-plane`. 

when I expand/shrink the `control-plane` instance, This topic describes how to enable xx of the client to automatically recver. how does the client auto restart the bi-directional stream.

**Comment by ejona86** [comment]
The client code would need to re-create the RPC. Are you asking how to trigger the client to re-create the RPC or how a client would choose to re-create the RPC?

**Comment by XiaoWeiKIN** [comment]
@ejona86 yes，i want to know how to trigger the client to re-create the RPC. I looked through many issues, but didn't find relevant case.

**Comment by ejona86** [comment]
The normal graceful approach is to put a "lifetime" on the stream, where the server will close the stream after it is X minutes old (e.g., 30 minutes). The client will see the RPC closure and re-create it. Instead of doing a closure from server-side, you could alternatively have the server send a message on the stream telling the client to re-create the stream.

But this approach of "limit the RPC lifetime" is a common and simple approach. It is in the server's control, so it can be tuned to how quickly you need to scale up/down. 

If the clients are directly connected to the servers, then you need to use something like [MAX_CONNECTION_AGE](https://github.com/grpc/proposal/blob/master/A9-server-side-conn-mgt.md) to balance the _connections_ (not just the RPCs).

**Comment by XiaoWeiKIN** [comment]
@ejona86 Thank you very much for your answer, I think it would be nice if there were some documentation or examples.
