### ISSUE TITLE
Possible NameResolver refresh check bug

### ISSUE THREAD

**Issue by fdfzcq** [grpc/grpc-java#9409]
### What version of gRPC-Java are you using?
1.46.0

### What is your environment?
We have seen this issue in services on GKE but can't reproduce it locally.

### What did you expect to see?
We have some low traffic services that are seeing the following warning from time to time:

> `LoadBalancer should call Helper.refreshNameResolution() to refresh name resolution if subchannel state becomes TRANSIENT_FAILURE or IDLE. This will no longer happen automatically in the future releases`

This applies to both services using the OSS round_robin LB and services using our home-grown LB. We haven't yet found any obvious pattern of this behavior other than that it only shows up on services with relatively low traffic. Could this possibly be a bug in [the NS refresh check on IDLE state transition](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1982)? Happy to provide more details if needed!

### What did you see instead?
The warning won't show up when using OSS round_robin load balancer.

### Steps to reproduce the bug
We couldn't reproduce this issue locally.

**Comment by sergiitk** [comment]
Hey @fdfzcq. Thank you for reporting. Could you please provide more details so we can get a better idea of what's happening?

**Comment by ejona86** [comment]
I think I see [a hole in RR](https://github.com/grpc/grpc-java/blob/e3d586127397af6d24559fa08e649a91efcdbfa5/core/src/main/java/io/grpc/util/RoundRobinLoadBalancer.java#L142) which could trigger the warning. But that's not actually an issue.

I'm noticing now the emulation of that old behavior is broken because `nsRefreshedByLb` was reused to only log the warning once. But in doing so it also only triggered refresh once. So it essentially only provided the warning. That warning is over a year old (https://github.com/grpc/grpc-java/pull/8048) so instead of fixing it I think we could just remove it.
