### ISSUE TITLE
Specify the retry policy for each call

### ISSUE THREAD

**Issue by Smityz** [grpc/grpc-java#9659]
### Is your feature request related to a problem?

When using retry policies, we can only assign a fixed retry policy to a method. But in practice, the same method may have different semantics, leading us to use different strategies. So I want to have a feature to assign a retry policy for each call.

### Describe the solution you'd like

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L554
```
        MethodInfo methodInfo = callOptions.getOption(MethodInfo.KEY);

        // retryPolicy can be covered by callOptions here
        final RetryPolicy retryPolicy = methodInfo == null ? null : methodInfo.retryPolicy;

        final HedgingPolicy hedgingPolicy = methodInfo == null ? null : methodInfo.hedgingPolicy;
        final class RetryStream<ReqT> extends RetriableStream<ReqT> {
          @SuppressWarnings("unchecked")
          RetryStream() {
            super(
                (MethodDescriptor<ReqT, ?>) method,
                headers,
                channelBufferUsed,
                perRpcBufferLimit,
                channelBufferLimit,
                getCallExecutor(callOptions),
                transportFactory.getScheduledExecutorService(),
                retryPolicy,
                hedgingPolicy,
                throttle);
          }
```
I want to change the codes here to change retryPolicy. The related parameter can be reset by callOptions.
So that users can change their policies by `ClientInterceptor` in each call.

If the community accepts this proposal, I am willing to pull requests to finish this job.

**Comment by ejona86** [comment]
A core design approach for retries is for service owners to be in control of the configuration. That's why the feature uses service config. This approach is counter to that goal, so I don't think it'd get very far. We could keep the service owner in control if there was some further matching ability in the config, but it isn't clear why the configuration complexity would be superior to just having a different RPC method.

If you are happy with hard-coded client-side configuration, I think as a team we'd recommend you to disable the built-in retries on the channel (`managedChannelBuilder.disableRetry()`) and use a retrying client interceptor instead.  It is possible to make your own, but I think I've seen some premade ones in the wider community when searching around.

**Comment by Smityz** [comment]
@ejona86 Thank you for the very detailed explanation!
And I have implemented a retry method by the interceptor.
(ref:https://github.com/facebook/buck/tree/16dc4866c20e807451a1762eb98776814c545e6f/src/com/facebook/buck/remoteexecution/grpc/retry)

> but it isn't clear why the configuration complexity would be superior to just having a different RPC method.

I use [oneof](https://developers.google.com/protocol-buffers/docs/proto3#oneof) in proto3 to distinguish different commands in the same method(maybe it's not a good design, but it's hard to refactor them immediately), so I can't use service config to control them.
And another scenario is our users have different network environment, so we want to overwrite the retry policy in clients.

>  I think as a team we'd recommend you to disable the built-in retries on the channel (managedChannelBuilder.disableRetry()) and use a retrying client interceptor instead.

Yes, this is a viable approach and there are many clients implement their retry policy by interceptor, but I think use the official solution can be better, [retry RFC](https://github.com/grpc/proposal/blob/master/A6-client-retries.md) is very powerful.

> A core design approach for retries is for service owners to be in control of the configuration. That's why the feature uses service config. 

Of course you are right, what I want to do is provide a interface for client to overwrite the policy and don't change the original method used. This allows us to use existing code to retry rather than build a new wheel.

**Comment by ejona86** [comment]
> I use oneof in proto3 to distinguish different commands in the same method(maybe it's not a good design, but it's hard to refactor them immediately), so I can't use service config to control them.

I can see how that would happen, but for it to impact retries seems to imply they should be different methods. I understand the difficulty of refactoring, but adding this to gRPC is not a "quick fix" to avoid service-level refactoring.

> And another scenario is our users have different network environment, so we want to overwrite the retry policy in clients.

This is an easier case to resolve, and should be some form of "use different configs for different clients." For example, with DNS, this could be an extension of the "criteria" section of the DNS JSON, which has clientLanguage and other parts. https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md

We'd need to understand the use cases more. How are you distributing service config? Is it hard-coded on client-side and passed to the channel, or are you using a Name Resolver to load it?

**Comment by Smityz** [comment]
> I can see how that would happen, but for it to impact retries seems to imply they should be different methods. I understand the difficulty of refactoring, but adding this to gRPC is not a "quick fix" to avoid service-level refactoring.

There is also a case where we will use some `put` method that will send as much as possible within the requested time when this method cannot be retried. And other `put` methods must be sent successfully. They both use `put` method, but have different config.

> We'd need to understand the use cases more. How are you distributing service config? Is it hard-coded on client-side and passed to the channel, or are you using a Name Resolver to load it?

I don't use any service config, I use it like `thrift`, and implement service discovery and load balance by myself. But as the business becomes more complex, we have more requirements, such as retrying under an asynchronous interface, error rate checking, etc. So I started researching the official solution.
I found a problem: gRPC has many features that are all implemented very well. But if I want to use them, I must have xDS suite to control them(or use JSON file save locally, which is not convenient I think). 
So can gRPC provide a dynamic config for these features? They do not change the previous logic, but for some cases it is more convenient.

**Comment by ejona86** [comment]
Service config is plain JSON so it can be distributed to the various languages. We feel the service should be in control of the config, but we accept that sometimes you need to overwrite it on client-side or it is too hard to have the service be in control. The "define the config on client-side" is not the primary use-case, and we wouldn't want "call arbitrary code to make the retry policy decision," _especially_ one that required digging into the message. That's not really feasible. gRPC as a whole does not dig into message contents.

We discourage having "doIt()" methods that do many different things depending on what "command" is passed. And that is a source of the problem here. Even with xDS you can't do what you are asking.
