### ISSUE TITLE
HELP NEEDED - Channel ManagedChannelImpl{logId=142, target=localhost:50052} was not shutdown properly!!!

### ISSUE THREAD

**Issue by noamyogev84** [grpc/grpc-java#9662]
Hi,
I sporadically see this error:

![image](https://user-images.githubusercontent.com/7726629/198866207-42bc0df9-d8ef-40d2-bf2d-20f06ba6a4f9.png)

My scenario is this:
I have a C# gRPC server running and accepting rpc's from mulitple Java clients.
The flow is like this:
1. create a new unsecure channel with server ip/port
2. instantiate a client over that channel
3. start a server stream rpc (keep alive) (CONNECT)
4. send unary rpc to get some information
5. Disconnect - Cancel stream call shutDown and await termination on the channel. (DISCONNECT)

When I do stress test (150 parallel clients doing this flow) I start to see the exception above sporadically and the stack trace is pointing at the CONNECT method.
1. What am I doing wrong? it there anything obvious that I'm missing?
2. Is there any options like in C# where I explicitly tell gRPC to create new subchannel per instantiated channel? is it even related?? :)

**Comment by noamyogev84** [comment]
Hey @debedb, it would be a great help to understand how you solved your issue here: https://github.com/googleads/google-ads-java/issues/399

**Comment by noamyogev84** [comment]
Heya @ejona86 and thanks for your help.
Actually, I am doing what you're suggesting. see my `disconnect` method:

![image](https://user-images.githubusercontent.com/7726629/199340599-a1d0a82b-4354-4738-b253-6864c2bab02f.png)

As I posted above, it looks like I get the channel exception during **channel creation** rather than in `disconnect`. 
See my `connect` method:

![image](https://user-images.githubusercontent.com/7726629/199341050-65ab6643-b932-4915-8f5f-cd7e628663e8.png)

What I'm doing in my connect flow:
1. calling `subscribe` server stream RPC
2. peek on the first response to see if auth logic in the server was succesfull
3. if yes - start a background thread on this stream (keepalive) if no - return the error response

I feel kind of lost because I keep getting the exception regarding the channel not being properly shut down.
I Even tried to implement some kind of retry logic around the channel creation but weirdly it throws beyond my try/catch block 🤷‍♀️🤷‍♀️🤷‍♀️ 

![image](https://user-images.githubusercontent.com/7726629/199342367-9c05cc39-2c83-48be-a62f-4c1b595ffba7.png)

BTW - I'm not a seasoned Java developer, any assistance would be appreciated.

**Comment by ejona86** [comment]
Posting screenshots makes it harder to talk about, read, and modify. In the future, please post text unless it can only be presented as a screenshot.

> Actually, I am doing what you're suggesting. see my disconnect method:

Okay. That means `disconnect()` is not being called or unsubscribe() is failing and throwing an exception.

> As I posted above, it looks like I get the channel exception during channel creation rather than in disconnect.

The exception is a record of the allocation size of the channel. It is saved when the channel is created and displayed if the channel is not shut down properly.

If using a debugger, you may notice you get that message when creating a channel. We check for orphaned channels when new channels are created. So you'll see we display the message within the connect(), but the message is talking about a _previous_ channel construction. You'd only notice this if looking in a debugger though.

Note: Constructing a channel does not involve I/O. Channel construction can fail, but only because of environmental issues, like certain code dependencies not being available. So it isn't something that should be retried.

**Comment by noamyogev84** [comment]
Thanks @ejona86!
So, you mean that there is no exception thrown, the connect is successful and that I should check for exceptions on my `subscribe` call? (`connect` is called by the consumer for sure)

**Comment by ejona86** [comment]
There is no exception thrown at all. It is pure logging. That is just a stack trace to help identify which channel wasn't destroyed.

**Comment by noamyogev84** [comment]
Thanks @ejona86 !
