### ISSUE TITLE
Force get from mavenCentral()

### ISSUE THREAD

**Issue by TheCarpetMerchant** [grpc/grpc-java#9664]
Since yesterday I'm getting this error (not the full trace) :

```
Could not resolve io.grpc:grpc-api:[1.21.1].
     Required by:
         project :in_app_update > com.android.tools.build:gradle:7.1.1 > io.grpc:grpc-core:1.21.1
      > Failed to list versions for io.grpc:grpc-api.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/io/grpc/grpc-api/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/io/grpc/grpc-api/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/io/grpc/grpc-api/maven-metadata.xml'.
                  > Read timed out
```

I have removed `jcenter()` from my `build.gradle` and added `mavenCentral()` but I don't know how to force `grpc-api` to be looked up in Maven and not the deprecated jcenter.

**Comment by sanjaypujare** [comment]
Sorry, can't help with jcenter vs maven but why use 1.21.1,  it's more than3 years old?

**Comment by TheCarpetMerchant** [comment]
You'll have to ask the guys from Gradle, since apparently this is what com.android.tools.build:gradle:7.1.1 depends on if I'm reading [https://mvnrepository.com/artifact/com.android.tools.build/gradle/7.1.1](this) correctly. They probably have a good reason, I just don't know why it's getting resolved to jcenter. Maybe I can specify `jcenter()` with the maven url in my own build.gradle...

**Comment by ejona86** [comment]
@TheCarpetMerchant, you might have still have had a reference to jcenter in your build, but in the `settings.gradle`, since it looks like that's a plugin. I will note that Gradle's plugin repository does still use jcenter (via special agreement) and it was hit by the recent jcenter outage. But it isn't clear to me that's the cause, since I thought jcenter wouldn't show up on the client-side error like that. For the recent outage, see https://status.gradle.com/incidents/9740r6bzx438 and https://status.gradle.com/incidents/c65zmfw32lpm .

**Comment by TheCarpetMerchant** [comment]
It was the outage then. Weird that there isn't any fallback to maven though. Closing the issue, thanks !
