### ISSUE TITLE
Does grpc-netty-shaded involve vulnerabilities CVE-2017-12613, CVE-2021-35940?

### ISSUE THREAD

**Issue by five111** [grpc/grpc-java#9679]
grpc-netty-shaded version 1.44.1
We used some vulnerability scanning tools to find that the binaries contained in the META-INF directory in grpc-netty-shaded may involve vulnerabilities CVE-2017-12613, CVE-2021-35940。
Is it really involved?do you have any suggestions?

**Comment by ejona86** [comment]
I don't see any reference to `apr_time_*` or `apr_os_exp_*` in netty-tcnative, which is the component that uses APR. They could be used by other APR functions or such, but in general I wouldn't expect netty-tcnative to be using APR time functions.

It looks like netty-tcnative has been on 1.6.5+ since [at least 2019](https://github.com/netty/netty-tcnative/pull/517) (version 2.0.31.Final). So grpc-netty-shaded versions at least 1.32.0+ are not be impacted.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
