### ISSUE TITLE
How to set a timeout/deadline in Server

### ISSUE THREAD

**Issue by uditsharma19** [grpc/grpc-java#9684]
Is there a way to set the timeout/deadline from server side?  I want to implement a way in my server to set the timeouts for every incoming RPC and to kill the RPC when the deadline/timeout expires.

**Comment by sanjaypujare** [comment]
This is for you to do it in your server application code and not for the gRPC library to do. Let's say for each incoming RPC you do the work asynchronously in a separate thread and after a timeout kill the task and return some error to the client.

**Comment by ejona86** [comment]
gRPC does not provide this directly. You can do it via a server interceptor, but it is a bit annoying because `ServerCall` is not thread-safe. You'd create an interceptor that creates a Context with the deadline you want. You'd then add a listener for that Context on when it closes and call `ServerCall.close()`. However, ServerCall will need its methods to become synchronized and you'll want to ignore calls to sendMessage(), close(), and the like after the deadline expires.
