### ISSUE TITLE
Questions about transferring large data through grpc?

### ISSUE THREAD

**Issue by stone-98** [grpc/grpc-java#9793]
I want to transfer a 100MB file via Grpc, currently I know of two ways to do it.

- Adjust the message size limit by SetMaxReceiveMessageSize
- Streaming with Grpc

I would like to know the performance comparison of these two methods.

**Comment by ejona86** [comment]
Performance (throughput) would be pretty similar. The difference is the memory usage. `SetMaxReceiveMessageSize` is there to protect your application. It is trivial to OOM a process with a 100 MB message limit. If all communication is with trusted clients, that could be fine. I'd assume in that situation you are in a data center where there's no want to resume a partial transfer because the transfer is so quick.

If it were me, I'd use streaming. Streaming with 64 KB-1 MB chunks is pretty easy and is less brittle, even if both the sender and receiver keep the entire thing in memory (today... tomorrow they may want to stream).

You would probably be interested in https://stackoverflow.com/a/46106469/4690866 and the question it links to.

**Comment by stone-98** [comment]
> （（）将将相似。不同之处在于内存使用使用情况`SetMaxReceiveMessageSize`为了保护保护保护您您您您的的的的应用应用应用应用应用程序程序程序程序。。对于对于对于对于消息消息消息消息消息消息消息消息消息消息限制限制限制限制限制为为为为为为为为为为为为为为为为为为为为的，那可能没有问题。我假设你在一个数据中心的那种情况下，因为传输速度太快，所以不想修复部分传输。
> 
> 64 kb-1 mb的。我我我我是。。进行流式流式传输简单简单那么脆弱脆弱脆弱.明天他们可能想要流式传输）。
> 
> 您可能会对https://stackoverflow.com/a/46106469/4690866及其链接感兴趣的问题。

Thank you for your answer, so according to my current understanding, the performance of using the first method will indeed be higher, but it will decrease the stability of the program?

**Comment by stone-98** [comment]
> Performance (throughput) would be pretty similar. The difference is the memory usage. `SetMaxReceiveMessageSize` is there to protect your application. It is trivial to OOM a process with a 100 MB message limit. If all communication is with trusted clients, that could be fine. I'd assume in that situation you are in a data center where there's no want to resume a partial transfer because the transfer is so quick.
> 
> If it were me, I'd use streaming. Streaming with 64 KB-1 MB chunks is pretty easy and is less brittle, even if both the sender and receiver keep the entire thing in memory (today... tomorrow they may want to stream).
> 
> You would probably be interested in https://stackoverflow.com/a/46106469/4690866 and the question it links to.

Thank you for your answer, so according to my current understanding, the performance of using the first method will indeed be higher, but it will decrease the stability of the program?

**Comment by ejona86** [comment]
The performance will likely be similar (excluding GC behavior). The main differences are memory usage (lower with streaming) and complexity in your code (lower with single large message).

**Comment by stone-98** [comment]
I don't consider GC now, and I can't understand why the performance of the two methods is similar, because one method uses multiple transfers, and the other uses one transfer. According to my understanding, the performance of one transfer should be better.

**Comment by ejona86** [comment]
The difference between the two is similar to:

```java
// single large call:
outputStream.write(new byte[100*1024*1024]);
// streaming:
for (int i = 0; i < 100; i++)
  outputStream.write(new byte[1024*1024]);
```

If the batch size were small (like 1 byte), then the second could easily be slower, especially if you weren't using BufferedOutputStream. But as the batch size increases (like to 100 KiB or 1 MiB), the difference between them disappears.

In a stream, the second message can be sent without acknowledgement by the receiver. (There are limits to this to provide flow control and avoid overwhelming the receiver, but they apply per-byte instead of per-message. Thus they apply in both cases.) The stream is "pipelined" as you can send more messages before the previous ones have been fully processed.

**Comment by stone-98** [comment]
@ejona86 I see, thanks for your reply.
