### ISSUE TITLE
VC++ building info seems out of date

### ISSUE THREAD

**Issue by depend** [grpc/grpc-java#981]
The Visual C++ Protobuf link in ./COMPILING.md seems broken. The following Visual C++ section also needs some update with the default include and lib paths.

**Comment by ejona86** [comment]
Yeah... You are referring to how protobuf is now using cmake on Windows, right? That would need to be updated.

**Comment by ejona86** [comment]
@depend, were you able to figure it out? I just want to make sure you aren't blocked.

**Comment by depend** [comment]
@ejona86 yeah, I am good. just want to raise the issue so it's tracked.

**Comment by depend** [comment]
well, actually I am getting link errors now. It all started with playing around with examples. I suppose it belongs to a separate issue.

**Comment by ejona86** [comment]
@depend, also, just because I'm curious, why are you building the protoc plugin manually? Are you not using Maven/Gradle, or are you wanting to make modifications?

Binaries available for many platforms are available [on Maven Central](http://search.maven.org/#artifactdetails%7Cio.grpc%7Cprotoc-gen-grpc-java%7C0.7.2%7CN%2FA).

**Comment by depend** [comment]
@ejona86 , thanks for replying. I am not trying to modify grpc. I was following http://www.grpc.io/docs/ to play around with it. But I got stuck at "../gradlew build" inside the examples folder because it tried to build grpc-compliler project but missed protobuf header files. Then I pulled ProtoBuf code to fix that. Now there are 12 link errors. I am on Windows 7 x64, Java x64 1.8.0_51, gradle 2.3, cmake 3.2.2, Visual Studio 2010/2013.

**Comment by ejona86** [comment]
Oh, I see. Hmm... We need to simplify that for people. Having to deal protoc is a bit of a pain (as you may have experienced).

So I'd suggest running `../gradlew build -PskipCodegen=true` instead for the moment. The problem is that the example is integrated into our build and our build needs to build the protoc plugin because it may have changed since the last release. For your own project you shouldn't have a problem if you follow our README.md because it will download protoc from Maven Central automatically.

**Comment by ejona86** [comment]
@depend, thanks for pointing that out. I've filed a bug against the website to figure out a way to let you play with the example without having to build protoc, because with your own project's usage of gRPC you wouldn't need to build protoc.

**Comment by depend** [comment]
@ejona86 , the examples probably should be a standalone project with only binary dependencies. Thank you for the help. :)

**Comment by ejona86** [comment]
#1070 addresses this. The biggest detail is swapping from /MD to /MT to match protobuf. There is also now a script that builds protobuf in case that helps you (it requires 7zip for extracting zips).
