### ISSUE TITLE
Can bazel run ShadedTest or any binary using netty.shaded?

### ISSUE THREAD

**Issue by lambdai** [grpc/grpc-java#9818]
I am quick prototype clients and transport using modified io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder and other shaded classes. Currently I have to publish alls maven packages and then build examples.

`grpc-java $  ./gradlew PublishToMavenLocal && cd examples && ./gradlew :helloWorldClient`

My questions are, 
1. Is it possible to run a bazel cmd to build the least dependencies? 
It's failing with the below error message
```
examples %  bazel run //:hello-world-client
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:hello-world-client (86 packages loaded, 1699 targets configured).
INFO: Found 1 target...
ERROR: /Users/lambdai/workspace/grpc-java/examples/BUILD.bazel:54:13: Building libexamples-class.jar (31 source files) failed: (Exit 1): java failed: error executing command (from target //:examples) external/remotejdk11_macos_aarch64/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 16 arguments skipped)
src/main/java/io/grpc/examples/helloworld/HelloWorldClient.java:28: error: package io.grpc.netty.shaded.io.grpc.netty does not exist
import io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder;
```

2. If 1) is not possible, what can be done faster than the naive `./gradlew PublishToMavenLocal` ?

**Comment by ejona86** [comment]
The bazel build doesn't shade anything. See for a little bit of reference:
https://github.com/grpc/grpc-java/blob/a2bbe8419891891fcfdb1b7215574f96db8057c5/netty/BUILD.bazel#L36

Essentially, there are two situations:
1. You are an application author that uses Bazel to build. In this case, you essentially have to use grpc-netty (not grpc-netty-shaded) make sure the Netty version you use is compatible across your entire binary. That's just because that's "the Bazel way" and doing shading would be troublesome for dependency resolution (since then you'd need to trick maven_install to depend on two different versions of Netty)
2. You are a library author that uses Bazel to build and you plan to publish to Maven Central somehow. In this case, you are free to use grpc-netty or grpc-netty-shaded, but in both cases you shouldn't really be referencing grpc-netty APIs because you can't dictate the version of gRPC used by your users. So it shouldn't matter whether grpc-netty or grpc-netty-shaded is used, because you aren't referencing classes from either

**Comment by lambdai** [comment]
Thank you @ejona86 for explaining the contexts and use cases.
My work currently does not import netty through another dependency, I will choose the first and switch to netty-shaded as the last round. 

I also find `./gradlew :grpc-netty-shaded:publishTOMavenLocal` is what I need to stay on shaded model. The flaw is that  examples build won't magically detect the necessary dependencies to rebuild. 
Is the above one of the reasons that examples is not indexed by the root grpc-java project?

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by lambdai** [comment]
Thank Eric for the resourceful approaches!
