### ISSUE TITLE
Using gRPC generated code with a different runtime version then the grpc-java-protoc-plugin version

### ISSUE THREAD

**Issue by beatrausch** [grpc/grpc-java#9867]
Hi,

is it possible, compatible in general to use java generated gRPC code with other gRPC-runtime versions compared to the version of the grpc-java-protoc-plugin?

**Example**:
grpc-protoc-plugin: version 1.52.1
grpc-java-runtime:  version 1.48.0

Regards

**Comment by ejona86** [comment]
grpc-java-protoc-plugin only uses stable APIs of grpc-java runtime, so it can be used with any later grpc-java 1.x version. grpc-java-protoc-plugin might use a new API, so it could have a minimum required version of grpc-java runtime, but there's generally no need to downgrade.

The generated code has a slow rate of change these days, so many versions produce the same code.

**Comment by beatrausch** [comment]
Great! I guess the same applies for protobuf itself?

**Comment by ejona86** [comment]
It _should_ be the case, as that's the only thing that can work in the ecosystem. It is simply impossible to generate code for all transitive dependencies using a single codegen version, in the Java ecosystem[1]. If matching the version was necessary, it would require every protobuf-using library to have a shaded private copy of protobuf, which isn't the case today. That would require you to also shade grpc-protobuf, grpc-services, and grpc-xds.

The [docs](https://github.com/protocolbuffers/protobuf/tree/main/java#compatibility-notice) don't say explicitly and have language that could be read to imply they could break older generated code. But it also doesn't say that libraries using protobuf must repackage it, like it does for `@ExperimentalApi`. To my knowledge, breaking generated code happened to date for 3.x; I think 3.x still supports 2.5/2.6 generated code. But that's all really a discussion to have with the protobuf folks. If they do break support, I would expect the ecosystem to stop upgrading protobuf without shading, like happened with Guava (because of bad libraries using `@Beta` APIs).

1.  That does happen in C++ though, and Javalite. The Java codegen was originally created in the Blaze/Bazel/monorepo world where that also holds. So the protobuf generated code is poorly suited to the task of long-term runtime stability. For gRPC, we knew up-front we'd need to support old codegen.

**Comment by ejona86** [comment]
This reminded me to add some docs for grpc maintainers in https://github.com/grpc/grpc-java/pull/9878 .
